### ISSUE TITLE
CRUD api (write access)

### ISSUE THREAD

**Issue by friimaind** [pi-hole/pi-hole#1002]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [X] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST]:**

I'm considering developing an application that uses the API and I'd like to know whether it is planned the integration of writing (insert/update). For example methods to insert/update/delete whitelist entries and so on.

There is this project https://github.com/packtloss/pihole-extension which seems a workaround for my needs but I am not convinced about security.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
We currently don't allow modifying the whitelist/blacklist via web api besides through the web interface (using CSRF), mainly because we don't want an ad to whitelist themselves by simply calling the API. [This](https://github.com/pi-hole/AdminLTE/blob/master/php/auth.php) authorization proceedure is the current way that we protect the lists. In the future we might remove the CSRF restriction and replace it with the password protection that is coming in the next update, but currently it still requires CSRF.

If you want to modify the lists remotely without going through the web interface, you'll have to use SSH to run the commands.

**Comment by friimaind** [comment]
Thank you @Mcat12 !

**Comment by Mcat12** [comment]
BTW, just released the next update

**Comment by friimaind** [comment]
Wuhuu great! ;)
