### ISSUE TITLE
[ISSUE] cannot add whitelist items via GUI

### ISSUE THREAD

**Issue by Mukrosz** [pi-hole/pi-hole#1007]
Pi-Hole v2.10
CentOS 7.3.1611

Good day,

I've noticed that I cannot seem to add entries to whitelist using the GUI.
After adding a new entry, I receive "Success..." but nothing is added. I confirmed by inspecting /etc/pihole/whitelist.txt.
/var/log/pihole.log doesnt list anything during above process. Perhaps that's not the right log file to be checking?

This behavior was observed prior to v2.10 also.

On the other hand, CLI command `pihole -w` domain works well! That or editing whitelist.txt manually.

Thank you for your time!

**Comment by Mukrosz** [comment]
A quick follow up.

As it turns out, I cannot change anything in the GUI at all. In the "Settings", I tried changing DNS servers as well changing from C to F temperatures, and upon Saving, the settings revert back to what they were.

I am checking if this is some kind of permission issue?

**Comment by DL6ER** [comment]
Okay, we can do some sort of live debugging here, as I'll be available for a few hours now. I'll put in PRs for all fixes we find here!

First, try fixing the sudoers file: `/etc/sudoers.d/pihole`

Replace
```
www-data ALL=NOPASSWD: /usr/local/bin/pihole
```
by
```
lighttpd ALL=NOPASSWD: /usr/local/bin/pihole
```

since the Fedora user is not `www-data` but `lighttpd`

**Comment by derekslenk** [comment]
I had this too. Doing it via the command line once creates the files, and then the Web GUI works

**Comment by Mukrosz** [comment]
hey @DL6ER, sorry, i called it a night yesterday, sorry I missed you.
I will do this later today once I get back home.
Thanks!

**Comment by Mukrosz** [comment]
Alright, change made.
Now the journal shows the following message each time I navigate pi-hole's GUI options or refresh pi-hole in general:

`lighttpd[29662]: sudo: no tty present and no askpass program specified`

What command is it attempting to run? perhaps it can be added to pihole sudoer file

**Comment by Mukrosz** [comment]
Setting SElinux in permissive mode resolves the problem. Obviously, this is a bad work around. I will have to dig through SElinux audit logs to what its having issues with.

**Comment by DL6ER** [comment]
> I will have to dig through SElinux audit logs to see what its having issues with.

We are highly interested in what you may find. In our team we have very only limited knowledge about SELinux, so out previous attempts failed. As most of us are on the Debian/Ubuntu/Raspberry side of things.

**Comment by bcambl** [comment]
We were previously deploying a custom policy for Pi-Hole; however, we recently removed it.
This decision was not due to a lack of SELinux knowledge, but more-so due to the type of permissions and policy required for Pi-Hole to operate. 
I have no problem creating a policy that will allow Pi-Hole to operate with SELinux enforcing, but I do have a problem with how said policy may affect other applications on your system security-wise.

SELinux exists for a reason. It stops things from happening that are unusual. A few examples are:
 - lighttpd/php writing dnsmasq files
 - lighttpd/php running privledged system commands

Personally, I would rather not force an SELinux policy on fellow SELinux users and let them make their own security decisions. Everyone else is likely running Debian and don't know any better ;)

You can find more information on creating custom policy here:
http://selinuxproject.org/page/Building_a_Basic_Policy

**Comment by Mukrosz** [comment]
thanks!
So I am assuming it's not worthwhile, tim-wise, to have it as an optional script?
I am very notice with SElinux and it would be invaluable to have with Pi-Hole. I do see where you are coming from though.

**Comment by Mcat12** [comment]
The `www-data` user can only use the `pihole` command with sudo, as specified in the sudoers file. So that executable would be the one which can be given the privileges.

**Comment by K-Ko** [comment]
Had same problem before. Check your AJAX calls.

I had to change the hostname to `pi.hole`, then it worked.

**Comment by dschaper** [comment]
Should be resolved, re-open issue if your still seeing the issue.
