### ISSUE TITLE
Pi-hole on Ubuntu 16.04 VM

### ISSUE THREAD

**Issue by mcblum** [pi-hole/pi-hole#1043]
So I've set up PiHole on 3 or 4 networks now and want to say thank you for your work on this.

I installed it on a VM at work, and even though it is not broken, it's also not working. I ran `scutil --dns | grep 'nameserver\[[0-9]*\]'` and have the IP as the PiHole but no matter what I do it never shows any DNS queries. There's actually 1 single query from my computer, but there are a ton of devices on this network and no matter what I do it's not incrementing or blocking ads.

Any ideas on what might be the issue?

**Comment by DL6ER** [comment]
Two questions:

1. Which OSs are the devices you use on?
2. If you go to the VM and try to resolve ordinary domains and ad domains, does this increase your counter?

```
dig google.com
dig doubleclick.net
```

Also you can investigate if your devices may still use another DNS server by trying
```
dig doubleclick.net
```
to whether the IP of your VM is given as a result.

3. Can you access the web UI using `http://pi.hole/admin` ?

**Comment by mikemihaylov** [comment]
I have a similar issue. I am running PiHole in a Ubuntu 16.04 VM

1. I have windows, mac, android and ios devices
2. running dig did not increase the query count
3. going to pi.hole/admin did not work (but going to the IP I assigned it does work)

I ran pihole -g and here's the output:

`root@pihole:/etc/pihole# pihole -g
:::
::: Neutrino emissions detected...
:::
::: No custom adlist file detected, reading from default file... done!
:::
::: Getting raw.githubusercontent.com list... List updated, transport successful!
::: Getting mirror1.malwaredomains.com list... No changes detected, transport skipped!
::: Getting sysctl.org list... No changes detected, transport skipped!
::: Getting zeustracker.abuse.ch list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting s3.amazonaws.com list... No changes detected, transport skipped!
::: Getting hosts-file.net list... No changes detected, transport skipped!
::: Getting raw.githubusercontent.com list... List updated, transport successful!
:::
::: Aggregating list of domains... done!
::: Formatting list of domains to remove comments.... done!
::: 128617 domains being pulled in by gravity...
::: Removing duplicate domains.... done!
::: 104575 unique domains trapped in the event horizon.
:::
::: Adding adlist sources to the whitelist... done!
::: Whitelisting 6 domains... done!
::: Nothing to blacklist!
::: Formatting domains into a HOSTS file... done!
:::
::: Cleaning up un-needed files... done!
:::
::: Refresh lists in dnsmasq... done!
::: Pi-hole blocking is Enabled
root@pihole:/etc/pihole#

`
Here is the output  pihole -d 

`root@pihole:/var/log# cat pihole_debug.log

Detecting Installed Package Versions:

Pi-hole: v2.10
WebUI: v2.0
lighttpd/1.4.35
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

Detecting existence of /etc/pihole/setupVars.conf:

PIHOLE_INTERFACE=ens32
IPV4_ADDRESS=192.168.1.222/24
IPV6_ADDRESS=fe80::20c:29ff:fe6a:2ba1
QUERY_LOGGING=true
WEBPASSWORD=4b20c060f40545f80ab87081c3c91842b8c30a2ea7c9b2f4ee9094b70c96fd61
PIHOLE_DNS_1=208.67.222.222
PIHOLE_DNS_2=8.8.4.4
DNS_FQDN_REQUIRED=true
DNS_BOGUS_PRIV=true


Detecting installed OS Distribution

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Checking processor variety

x86_64

IP Address Information

::1/128
fe80::20c:29ff:fe6a:2ba1/64
127.0.0.1/8
192.168.1.222/24
--- 192.168.1.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1999ms
rtt min/avg/max/mdev = 0.373/0.388/0.409/0.022 ms
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 14.483/15.395/16.751/0.977 ms

Daemon Process Information

Found user www-data with process lighttpd
Found user www-data with process lighttpd

Daemon Process Information

Found user bind with process named
Found user bind with process named

Processes Check


lighttpd
 processes status:
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2016-12-21 21:43:46 EST; 5 days ago
 Main PID: 2734 (lighttpd)
    Tasks: 6
   Memory: 44.1M
      CPU: 25.144s
   CGroup: /system.slice/lighttpd.service
           ├─2734 /usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf
           ├─2752 /usr/bin/php-cgi
           ├─2766 /usr/bin/php-cgi
           ├─2767 /usr/bin/php-cgi
           ├─2768 /usr/bin/php-cgi
           └─2769 /usr/bin/php-cgi

Dec 26 22:18:36 pihole sudo[11384]: pam_unix(sudo:session): session closed for user root
Dec 26 22:18:45 pihole sudo[11399]: www-data : TTY=unknown ; PWD=/var/www/html/admin ; USER=root ; COMMAND=/usr/local/bin/pihole status web
Dec 26 22:18:45 pihole sudo[11399]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 26 22:18:45 pihole sudo[11399]: pam_unix(sudo:session): session closed for user root
Dec 26 22:49:22 pihole sudo[12236]: www-data : TTY=unknown ; PWD=/var/www/html/admin ; USER=root ; COMMAND=/usr/local/bin/pihole status web
Dec 26 22:49:22 pihole sudo[12236]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 26 22:49:22 pihole sudo[12236]: pam_unix(sudo:session): session closed for user root
Dec 26 22:53:25 pihole sudo[12530]: www-data : TTY=unknown ; PWD=/var/www/html/admin ; USER=root ; COMMAND=/usr/local/bin/pihole status web
Dec 26 22:53:25 pihole sudo[12530]: pam_unix(sudo:session): session opened for user root by (uid=0)
Dec 26 22:53:25 pihole sudo[12530]: pam_unix(sudo:session): session closed for user root

dnsmasq
 processes status:
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: active (running) since Mon 2016-12-26 22:30:01 EST; 24min ago
  Process: 11910 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 11963 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 11952 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 11949 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 11962 (dnsmasq)
    Tasks: 1
   Memory: 21.7M
      CPU: 318ms
   CGroup: /system.slice/dnsmasq.service
           └─11962 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49AAC11D7B6F6446702E54A1607371607A1A41855200FD2CE1CDDE32F24E8FB5

Dec 26 22:30:00 pihole systemd[1]: Stopped dnsmasq - A lightweight DHCP and caching DNS server.
Dec 26 22:30:00 pihole systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Dec 26 22:30:00 pihole dnsmasq[11949]: dnsmasq: syntax check OK.
Dec 26 22:30:01 pihole systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.


Resolver Functions Check

Resolution of doubleclick.com from Pi-hole:

; <<>> DiG 9.10.3-P4-Ubuntu <<>> doubleclick.com @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17169
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	300	IN	A	216.58.218.238

;; AUTHORITY SECTION:
doubleclick.com.	170762	IN	NS	ns2.google.com.
doubleclick.com.	170762	IN	NS	ns1.google.com.
doubleclick.com.	170762	IN	NS	ns3.google.com.
doubleclick.com.	170762	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.		86110	IN	A	216.239.32.10
ns2.google.com.		86110	IN	A	216.239.34.10
ns3.google.com.		86110	IN	A	216.239.36.10
ns4.google.com.		86110	IN	A	216.239.38.10

;; Query time: 29 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Dec 26 22:54:13 EST 2016
;; MSG SIZE  rcvd: 203

Resolution of doubleclick.com from 8.8.8.8:

; <<>> DiG 9.10.3-P4-Ubuntu <<>> doubleclick.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42901
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;doubleclick.com.		IN	A

;; ANSWER SECTION:
doubleclick.com.	299	IN	A	216.58.217.174

;; Query time: 16 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon Dec 26 22:54:13 EST 2016
;; MSG SIZE  rcvd: 60

Pi-hole dnsmasq specific records lookups
Cache Size:
Upstream Servers:


Detecting existence of /etc/lighttpd/lighttpd.conf:

server.modules = (
"mod_access",
"mod_accesslog",
"mod_auth",
"mod_expire",
"mod_compress",
"mod_redirect",
"mod_setenv",
"mod_rewrite"
)
server.document-root        = "/var/www/html"
server.error-handler-404	= "pihole/index.html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80
accesslog.filename			= "/var/log/lighttpd/access.log"
accesslog.format			= "%{%s}t|%V|%r|%s|%b"
index-file.names            = ( "index.php", "index.html", "index.lighttpd.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )
compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.assign.pl"
include_shell "/usr/share/lighttpd/include-conf-enabled.pl"
$HTTP["url"] =~ "^/admin/" {
setenv.add-response-header = (
"X-Pi-hole" => "The Pi-hole Web interface is working!",
"X-Frame-Options" => "DENY"
)
}
url.rewrite = ( "^(?!/admin/).*\.js$"  => "pihole/index.js"   )
$HTTP["url"] =~ "^(?!/admin)/.*" {
setenv.add-response-header = ( "X-Pi-hole" => "A black hole for Internet advertisements." )
}
include_shell "cat external.conf 2>/dev/null"


Detecting existence of /var/log/lighttpd/error.log:

2016-12-25 06:25:00: (server.c.1242) logfiles cycled UID = 0 PID = 6500
2016-12-26 22:16:22: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: auth in /var/www/html/admin/header.php on line 209
2016-12-26 22:16:22: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: auth in /var/www/html/admin/header.php on line 325
2016-12-26 22:16:22: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: auth in /var/www/html/admin/header.php on line 384
2016-12-26 22:16:22: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: auth in /var/www/html/admin/header.php on line 397
2016-12-26 22:16:22: (mod_fastcgi.c.2695) FastCGI-stderr: PHP Notice:  Undefined variable: auth in /var/www/html/admin/header.php on line 423


Detecting existence of /etc/dnsmasq.conf:

conf-dir=/etc/dnsmasq.d


Detecting existence of /etc/dnsmasq.d/01-pihole.conf:

addn-hosts=/etc/pihole/gravity.list
addn-hosts=/etc/pihole/local.list
no-resolv
interface=ens32
cache-size=10000
log-queries
log-facility=/var/log/pihole.log
local-ttl=300
log-async
server=208.67.222.222
server=8.8.4.4
domain-needed
bogus-priv


Detecting existence of /etc/pihole/whitelist.txt:

raw.githubusercontent.com
mirror1.malwaredomains.com
sysctl.org
zeustracker.abuse.ch
s3.amazonaws.com
hosts-file.net


Detecting existence of /etc/pihole/blacklist.txt:

/etc/pihole/blacklist.txt not found!

Detecting existence of /etc/pihole/adlists.list:

/etc/pihole/adlists.list not found!

Analyzing gravity.list

/etc/pihole/gravity.list is 209150 /etc/pihole/gravity.list lines long.

pihole.log`

I am not sure why adlists.list and blacklist.list

**Comment by dschaper** [comment]
Try running `pihole -up` to get the latest version and see if that resolves the issue.

**Comment by mikemihaylov** [comment]
I just tried `pihole -up` and it seems like it's still not quite working. I did `dig doubleclick.net | grep SERVER` on the pihole VM and it shows 127.0.0.1

I did the same thing on my mac and it shows 192.168.1.222 (which is the IP assigned to the pihole)

However going to slickdeals.net I still see their ads.

**Comment by dschaper** [comment]
You may have their ads cached in your browser or client OS. Either wait out the 5 minutes for the cache to clear out, or manually clear out the cache on the client machines and try again. The `dig` responses are correct, so you may just need to wait a little bit.

**Comment by MartijnDevNull** [comment]
Same problem on a Ubuntu server 16 VM

**Comment by mikemihaylov** [comment]
I flushed DNS and i waited 12 hours and I am still getting ads :( I do see a few more requests actually going to the pihole but not in any meaningful number. 
<img width="1352" alt="screen shot 2016-12-27 at 11 46 45 am" src="https://cloud.githubusercontent.com/assets/12874409/21504117/3ab607ec-cc2a-11e6-80e7-d7fc8b0ff828.png">

**Comment by DL6ER** [comment]
Do you see your under Top Clients (even below the two tables in your screenshot) the IP addresses of the computers which still see ads?

**Comment by mcblum** [comment]
@DL6ER Sorry for the radio silence!

> Which OSs are the devices you use on?

Mac, iOS and Windows 10.

> If you go to the VM and try to resolve ordinary domains and ad domains, does this increase your counter?

No it didn't.

> Can you access the web UI using http://pi.hole/admin ?

Yes, it appeared to be working and if I suspended that VM DNS would then fail, but it never did actually process anything.

I did find a solution to this, and that was to go back to 14.04. I installed it and it immediately worked the first time.

**Comment by DL6ER** [comment]
Issue seems to be OS related, the original poster has solved it by going back to an older version of Ubuntu. Closing this issue for now, but I'll keep it in mind...

**Comment by stinkyjak** [comment]
This doesn't explain why Ununtu16.04 isn't working with PiHole.

**Comment by DL6ER** [comment]
Most likely it is due to `NetworkManager` messing around with your configuration.

@stinkyjak If you have this issue as well, please open a new issue, because this one is already quite chaotic

**Comment by dschaper** [comment]
@stinkyjak If you are having this issue, please open a new issues ticket with a new debug token and we can look into it. We've tested with Ubuntu16.04 on a few different VM providers and are unable to duplicate. We are willing to take a further look into the issue if you can provide the details of how you installed Ubunutu and what virtual environment it is running in.

**Comment by stinkyjak** [comment]
This wasn't working.... Works just fine for me now. 
PiHole on Ubuntu Server 16.04 KVM guest on Ubuntu Server 16.04 host. 
Thanks
