### ISSUE TITLE
DHCPv6

### ISSUE THREAD

**Issue by Tntdruid** [pi-hole/pi-hole#1079]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_{1}_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Did the DHCPv6 server not make it into this release?

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
It should be there

**Comment by Tntdruid** [comment]
Only ipv4 works now, the ipv6 is broken, turned off ipv6 dhcp in router.

**Comment by DL6ER** [comment]
What do you mean by broken?

**Comment by Tntdruid** [comment]
None of my iOS/windows pc's get ipv6 only my old printer get a ipv6 adresse.

**Comment by DL6ER** [comment]
Maybe @darkrain-nl and @dschaper can assist here, because I'm no expert for neither Win nor MacOS.

**Comment by darkrain-nl** [comment]
Let's try and see if I can assist.

Few questions first:

- Is the file 02-pihole-dhcp.conf there in /etc/dnsmasq.d and populated with corect values? especially those lines?
`dhcp-option=option6:dns-server,[::]
dhcp-range=::100,::1ff,constructor:eth0,ra-names,slaac,12h
ra-param=*,0,0`

- If you restart dnsmasq is something like:
`DHCPv6, IP range ::100 -- ::1ff, lease time 12h, template for eth0` there in your logfile? It should be followed by a line that looks similar but now with your complete prefix. Dnsmasq tries to guess this prefix from it's network adapter, in my case eth0...
It may very well be possible that by switching off DHCP in your router, IPv6 connectivity in the machine hosting dnsmasq is broken and no prefix can be found.

The best way to configure the router is SLAAC, this way devices can get an IPv6 address from your router and also get the default gateway from the router (without default gateway you have no internet). They will also get an IPv6 address from Dnsmasq together with the DNS server address.

Hope to help.

**Comment by Tntdruid** [comment]
Only get the Ipv6's from router and none from pi hole

02-pihole-dhcp.conf

dhcp-authoritative
dhcp-range=10.10.1.2,10.10.1.254,infinite
dhcp-option=option:router,10.10.1.1
dhcp-leasefile=/etc/pihole/dhcp.leases
domain=moo.com
#quiet-dhcp
#quiet-dhcp6
#enable-ra
dhcp-option=option6:dns-server,[::]
dhcp-range=::100,::1ff,constructor:eth0,ra-names,slaac,infinite
ra-param=*,0,0

**Comment by darkrain-nl** [comment]
Ok, and is the line `DHCPv6, IP range ::100 -- ::1ff, lease time 12h, template for eth0` in your logfile at /var/log/pihole.log?

DHCP logging is on, so there should be something in your pihole.log, maybe it helps identifying the problem.

**Comment by Tntdruid** [comment]
Jan  3 10:12:48 dnsmasq-dhcp[14080]: DHCPv6, IP range ::100 -- ::1ff, lease time infinite, template for eth0
Jan  3 10:12:48 dnsmasq-dhcp[14080]: DHCPv4-derived IPv6 names on eth0
Jan  3 10:12:48 dnsmasq-dhcp[14080]: router advertisement on eth0
Jan  3 10:12:48 dnsmasq-dhcp[14080]: DHCPv6, IP range 2a11:7660:d07::100 -- 2a11:7660:d07::1ff, lease time infinite, constructed for eth0
Jan  3 10:12:48 dnsmasq-dhcp[14080]: DHCPv4-derived IPv6 names on 2a11:7660:d07::, constructed for eth0
Jan  3 10:12:48 dnsmasq-dhcp[14080]: router advertisement on 2a11:7660:d07::, constructed for eth0

**Comment by darkrain-nl** [comment]
That looks promising, Are there any log entries about  IPv6 addresses being handout?
The lines look something like `SLAAC-CONFIRM(eth0) ::1` or `DHCPREPLY(eth0) ::1`

Also it would be nice to know what exact OS you use on the Windows machines and what happens if you do ipconfig /renew6 in an elevated command prompt...

**Comment by Tntdruid** [comment]
Jan  3 20:14:29 dnsmasq-dhcp[1557]: DHCPREPLY(eth0) 2a11:7660:d07::1f5 00:01:00:01:1d:1a:d6:64:ac:22:0b:2a:53:98 <- win 10 pc

Works on win 10 now after i added a startup script whit ipconfig /renew6

iPads and iPhones still not getting the ipv6 from pi hole, looks like the lease is only 1h on the ipv6 

![2017-01-03_20-45-10](https://cloud.githubusercontent.com/assets/72948/21620633/980df1fe-d1f5-11e6-9789-75607b1818a1.png)

**Comment by darkrain-nl** [comment]
On Windows 10 we have this: https://social.technet.microsoft.com/Forums/windows/en-US/b16e7d78-e390-4ada-a24b-3ccba60fa571/no-ipv6-dns-statelessdhcp-since-windows-10-anniversary-update?forum=win10itpronetworking&prof=required

Microsoft is working on a solution..

Unfortunately I don't have ios devices in my possession, so I cannot test this myself.

**Comment by martijnb92** [comment]
I'm experiencing the same problem, IPv6 is not working.
DHCP config:
```
dhcp-authoritative
dhcp-range=192.168.1.10,192.168.1.110,24h
dhcp-option=option:router,192.168.1.254
dhcp-leasefile=/etc/pihole/dhcp.leases
domain=homenetwork
#quiet-dhcp
#quiet-dhcp6
#enable-ra
dhcp-option=option6:dns-server,[::]
dhcp-range=::100,::1ff,constructor:eth0,ra-names,slaac,24h
ra-param=*,0,0
```

Log file:
`Jan 22 14:05:11 dnsmasq[14257]: started, version 2.72 cachesize 10000
Jan 22 14:05:11 dnsmasq[14257]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect
Jan 22 14:05:11 dnsmasq[14257]: warning: ignoring resolv-file flag because no-resolv is set
Jan 22 14:05:11 dnsmasq-dhcp[14257]: DHCP, IP range 192.168.1.10 -- 192.168.1.110, lease time 1d
Jan 22 14:05:11 dnsmasq-dhcp[14257]: DHCPv6, IP range ::100 -- ::1ff, lease time 1d, template for eth0
Jan 22 14:05:11 dnsmasq-dhcp[14257]: DHCPv4-derived IPv6 names on eth0
Jan 22 14:05:11 dnsmasq-dhcp[14257]: router advertisement on eth0
Jan 22 14:05:11 dnsmasq[14257]: using nameserver 8.8.4.4#53
Jan 22 14:05:11 dnsmasq[14257]: using nameserver 8.8.8.8#53`

Multiple errors like this:
`Jan 22 13:30:10 dnsmasq-dhcp[8218]: no address range available for DHCPv6 request via eth0`

**Comment by DL6ER** [comment]
Do you have a valid IPv6 address range? It won't work with e.g. link-local only.

**Comment by DL6ER** [comment]
Closed due to non-responsiveness. Feel free to re-open if the problem still persists.

**Comment by yann1420** [comment]
Can I reopen?

I have the same problem, every about 2 minutes an entry in the pihole log file 
**Jun 17 14:50:52 dnsmasq-dhcp[27079]: no address range available for DHCPv6 request via eth0**
$ grep 'IPV6\|INTERFACE' /etc/pihole/setupVars.conf
PIHOLE_INTERFACE=eth0
IPV6_ADDRESS=
$ ip -6 a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 state UNKNOWN qlen 1
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 3333::3333:3333:50a2:2904/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by dschaper** [comment]
Considering the last post was from over 3 years ago you may want to open a new issue.
