### ISSUE TITLE
An error occured while loading the data. Presumably your log is too large to be processed

### ISSUE THREAD

**Issue by aleph-1** [pi-hole/pi-hole#1243]
Hi Guys...

Had this for the first time ever.

"An error occured while loading the data. Presumably your log is too large to be processed" 

it came up when I was looking to review the query log.

a quick look at /var/log/ shows:

-rw-r--r--  1 dnsmasq  root     5.2M Feb 12 20:46 pihole.log

is this too big?  What is the max size? 

BTW the Queries over time graph on the main page shows all the data.

Any thoughts?

Thanks

**Comment by Mcat12** [comment]
The query log takes longer to parse the log than some of the other stats, so it all depends on how fast your Pi-hole's hardware is. We're working on drastically improving the performance of the web interface, which would be able to load even 100,000 queries without giving up (FTL and the Python/DB rewrite). Usually over 7,000-15,000 queries is too much for a B+ or Zero to handle. The 2B and 3B can handle those sizes though because they're faster.

**Comment by aleph-1** [comment]
that makes sense... 

I've had a VOIP  problem on the network today so I'm currently sitting at  17,912 dns queries. 

In fact it was a quick scan of the of pi-holes main page that first  alerted me that something had gone titsup
