### ISSUE TITLE
Qwertee.com broken when using pihole

### ISSUE THREAD

**Issue by SteveW25561** [pi-hole/pi-hole#1285]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1 

---

**[BUG | ISSUE] Expected Behaviour:**

qwertee.com should have a countdown clock when looking at the daily tees (clock at top of page) and clicking a shirt's Buy now should trigger another button to pick shirt size etc

**[BUG | ISSUE] Actual Behaviour:**

With pihole enabled, countdown clock doesn't work, Buy Now button also nonresponsive

**[BUG | ISSUE] Steps to reproduce:**

-enable pihole
-go to qwertee.com and look for countdown clock and buy now buttons = not working
- change DNS to another server (eg opendns)
- retry qwertee.com : above works

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Is the issue gone when you disable blocking via the Pi-hole web interface or CLI (`pihole disable`)?

I cannot confirm your issue here with Pi-hole running on defaults. Tested both Chrome on Android and Linux.
![screenshot_20170303-075947](https://cloud.githubusercontent.com/assets/16748619/23541850/3a104f7a-ffea-11e6-8eb6-e5c4c04a2ee5.png)
![screenshot_20170303-080014](https://cloud.githubusercontent.com/assets/16748619/23541852/3d16fd2c-ffea-11e6-8d7f-65abcd7a4d4b.png)
![screenshot_20170303-080133](https://cloud.githubusercontent.com/assets/16748619/23541856/405c458c-ffea-11e6-8c17-9779769ab8ba.png)

**Comment by dschaper** [comment]
This appears to be an issue with the block list, and not with the Pi-hole installation. Are you running with just the stock lists, or have you customized the Pi-hole and added additional blocklists?
