### ISSUE TITLE
[Debugging help] Pi-hole not blocking ads (running alongside apache2)

### ISSUE THREAD

**Issue by DarkMatterMatt** [pi-hole/pi-hole#1288]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**ISSUE: Expected Behaviour:**
Pi-hole to block ads

**ISSUE: Actual Behaviour:**
Pi-hole only responds to DNS queries from localhost, and doesn't block ads.

**ISSUE: Steps to reproduce:**
For the log generated by `pihole -d`, I did the following things:

- Set my desktop computer's DNS to my RPi's address
![DNS setting image](https://cloud.githubusercontent.com/assets/15150339/23566960/03e29cda-00b9-11e7-8263-fc23af73fbcc.png)
- Ran `pihole -d` over SSH
- On the desktop: attemped to browse to `a-ads.com`, then `google.com`. Both failed their DNS lookups.
- On the Pi: ran `curl -I a-ads.com`, then `curl -I google.com`. Both succeeded, neither were blocked.

**Debug token generated by `pihole -d`:**
`uxaebaw4gq`

To me this looks like 2 problems; the DNS lookups failing, and the ads not being blocked. I have modified the installation by changing the port in `/etc/lighttpd/lighttpd.conf` to `server.port = 6283`
![cat /etc/lighttpd/lighttpd.conf](https://cloud.githubusercontent.com/assets/15150339/23567028/4998ecb6-00b9-11e7-87cd-ed249eb1bacd.PNG)

`curl -I 127.0.0.1:6283` returns the correct pi-hole blocked page. 
![curl -I 127.0.0.1:6283](https://cloud.githubusercontent.com/assets/15150339/23567095/8b5ba4ea-00b9-11e7-95b1-f4bcea581f93.PNG)

I can access the pi-hole admin page from my desktop computer at 192.168.1.107:6283/admin
`cat /etc/resolv.conf` has a value of `nameserver 127.0.0.1`
![cat /etc/resolv.conf](https://cloud.githubusercontent.com/assets/15150339/23567197/0b19115e-00ba-11e7-93e0-7a49defdd2a7.PNG)

I have read through several "pihole not working" issues, and have installed `sudo apt install resolvconf` (it was not previously installed).

Thanks, DMM

**Comment by dschaper** [comment]
A couple of basic questions to get them out of the way:

Do you have any firewalls set up, and are you running any Anti-Virus software on the Windows box? (Some anti-virus have security features that disable local DNS servers.) Also, what model router and does it have `dns-rebind` blocking features?

**Comment by DarkMatterMatt** [comment]
On the Windows 10 Pro x64 desktop computer I have Kaspersky Internet Security. I have tried with it both enabled and disabled; the results do not change.

On the RPi 3 I have UFW. I have tried with it both enabled and disabled; the results do not change.

I have also tried from an android tablet, with the same results as the Windows box.

Thanks for your help 😄

**Comment by Mcat12** [comment]
We recently pushed out a few small fixes, so try `pihole -up`. Check the interface listening behavior under advanced DNS settings in the Pi-hole web interface's settings page. If it's still not working, run `pihole -d` for a fresh debug token.

**Comment by DarkMatterMatt** [comment]
So I updated pihole (please let us choose the default root directory and port), and nothing has changed.
My new debug token is `6a0t2dmf2s`. I think my Pi was running a different script at the same time as the debug was running so there may be some randomish web requests logged.
- On the desktop: attempted to browse to a-ads.com, then google.com. Both failed their DNS lookups.
- On the Pi: ran curl -I a-ads.com, then curl -I google.com. Both succeeded, neither were blocked.

**Comment by Mcat12** [comment]
I don't see any requests made except by the local device in your log. Is the pi connected via eth0?

**Comment by DL6ER** [comment]
Some more thoughts:

- Do you have any other devices available for testing if this issue is limited to the particular desktop computer?
- I see that you can ssh from your desktop to the Pi using the host name `raspberrypi`. Can you also ping the host name `raspberrypi` **and** the IP address `192.168.1.107` from the desktop?
- Does the Internet work as expected when you manually configure the DNS server to be `8.8.8.8`?

**Comment by DarkMatterMatt** [comment]
I just tried from an Android phone: when I set the DNS to 192.168.1.107 it connects and says `connected, no internet` and turns on my data. I turned my data off and I could not browse the internet (`you are offline`)

I tried from an iOS device: it connects fine but cannot browse to any webpages (`err_connection_timed_out`)

From my desktop I SSH into my Raspberry Pi using putty and the IP address `192.168.1.107`. I cannot use the host name `raspberrypi` ![could not find host](https://cloud.githubusercontent.com/assets/15150339/23719047/a174b396-049e-11e7-9125-662aaa0f7434.PNG). I have never been able to use host names before.

I can ping `192.168.1.107`, but not `raspberrypi` ![ping results](https://cloud.githubusercontent.com/assets/15150339/23719115/eb53434c-049e-11e7-985c-464909e66fab.PNG)

`8.8.8.8` is my standard DNS, and `8.8.4.4` is my normal secondary DNS. They work properly. I also tried Level3's DNS (`209.244.0.3`) and it works as it should.

**Comment by Mcat12** [comment]
What's the output of these commands on Windows?
```
nslookup google.com
nslookup google.com 192.168.1.107
```

**Comment by DarkMatterMatt** [comment]
![nslookup results](https://cloud.githubusercontent.com/assets/15150339/23766258/e88d5510-0568-11e7-9c85-5a3c60aa91c1.png)

**Comment by DarkMatterMatt** [comment]
UPDATE: I've successfully installed it on a clean Raspbian install on a RPi B+.

Now my only question is: Can I set a secondary/backup DNS address on the computer or the router? I tend to 'break' my RPi's pretty quickly, and I'd like the devices using pi-hole to automatically switch to Google's DNS servers if the RPi goes down. At the moment if I set the secondary DNS to `8.8.8.8` on the computer it stops the ad-blocking.

**Comment by DL6ER** [comment]
> Can I set a secondary/backup DNS address on the computer or the router?

> At the moment if I set the secondary DNS to 8.8.8.8 on the computer it stops the ad-blocking.

Yes, you misunderstand the concept (which is not surprising, since Windows makes it especially hard to understand it through the chosen wording).

See [here](https://discourse.pi-hole.net/t/primary-vs-secondary-dns/1536) for more information. A backup solution is (like what I have in an enterprise environment) to run actually *two* Pi-holes on two distinct devices. Considering that e.g. the NanoPi NEO is as powerful as the Raspberry Pi 3 but only costs $8 (the 256 MB version should be sufficient), the extra costs for a backup server is almost negligible.

**Comment by DarkMatterMatt** [comment]
That's really interesting, and weird. Thanks for clearing that up.

My latest question is: how can I *properly* change the port of the web interface?
I've already broken my B+ pi-hole installation (so I fresh installed again and started debugging).
I found that when I changed the port in the `lighttpd` config files, the `X-Pi-hole: A black hole for Internet advertisements.` header did not show up in `curl -I a-ads.com`.

I changed the port in:
`/etc/lighttpd/lighttpd.conf` and `/usr/share/lighttpd/use-ipv6.pl` from port 80 to port 6283
I restarted lighttpd: `service lighttpd restart`
I tested the web interface at `192.168.1.101:6283/admin`, it worked.
When I `curl -I a-ads.com`, I got the error `curl: (7) Failed to connect to a-ads.com port 80: Connection refused`
Debug token with the changed port is `83i8mkv7nw`.

I then changed the port back in both files and restarted lighttpd again.
`curl -I a-ads.com` then gave me the correct `X-Pi-hole` header response.
Debug token with the original port 80 is `qgmy62dlt1`

Sorry to keep bothering you guys, I *do* look through the FAQs, and Google before I post here, and I really appreciate the effort you spend answering my questions.

**Comment by DL6ER** [comment]
That can quickly be answered:

`lighttpd` gives you the expected response on querying the ad webpage. If you now change its port to something else than `80`, this will lead to problems, because there is nothing that can serve the ad content the webpages are requesting (expect time outs on a number of pages you visit from any browser).

> When I `curl -I a-ads.com`, I got the error `curl: (7) Failed to connect to a-ads.com port 80: Connection refused`

Sure, there is nothing on port 80 anymore that would be listing to your query. With the changed port, the correct call would now be `curl -I a-ads.com:6283` and you immediately see the problem - this is not what the web browsers will do - they expect the providing server to run on port 80.

Hence, we generally don't support running on a port that is *not* 80, because it can (and will) create unnecessary confusion and delays. There have been a number of users that wanted to use port 80 *no-matter-what-happens* to use it for something like Seafile or their own blog page, but be prepared that your blog or Seafile login page pops up in various places on websites zu visit, since the Pi-hole (correctly) just redirects the requests to itself. If `lighttpd` is not there anymore to control what is handed out, we are out of control what happens.

**Comment by dschaper** [comment]
Any further information or comments on this?

**Comment by DarkMatterMatt** [comment]
No, forgot to close sorry. I didn't solve my first problem, of my RPi 3 not receiving DNS requests from others on the network, but I installed Pi-hole on my RPi B+ and it is working happily.

What I learnt from this 'issue'.
 - Pi-hole redirects blocked websites to localhost:80. This means that Pi-hole cannot function ideally if another process is using port 80 (e.g. Apache2, Nginx, etc.) If another process _is_ using port 80, Pi-hole may occasionally show snippets of your website in place of blocked ads.
 - DNS primary and secondary addresses are the same. DNS requests are (almost) equally split among them. This means that Pi-hole must be the only DNS server listed (otherwise ads will get through the alternate DNS server.)

Thanks for all the help and support @dschaper @dan019 @Mcat12
