### ISSUE TITLE
Install dnsmasq manually

### ISSUE THREAD

**Issue by paulkramme** [pi-hole/pi-hole#1315]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_2_

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Open websites with cloudflare as backend

**[BUG | ISSUE] Actual Behaviour:**
Pihole returns bogus when trying to reach site with cloudflare backend/ddos protection when dnssec is enabled. It turnes out that dnsmasq 2.72 (which is the latest debian package) has a bug, which doesnt allow [dnsmasq to verify ECDSA signatures](http://serverfault.com/a/740529). This bug has been fixed in 2.73. The problem would be solved, if pi-hole downloads and compiles its own version of dnsmasq at install time, and checks for updates at pihole's update time. Otherswise, a manual install has to be done.

**[BUG | ISSUE] Steps to reproduce:**
- Activate dnssec
- Open cloudflare.com

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by paulkramme** [comment]
A manual install didn't fix it. Deactivating DNSSEC did. I don't know what to do, as i want to use DNSSEC.

**Comment by DL6ER** [comment]
> The problem would be solved, if pi-hole downloads and compiles its own version of dnsmasq at install time.

We won't do that. Full stop. We invested a lot of time to ensure that we can ship our own `FTL` engine to the end users w/o having to compile on their systems.

The reasons are manifold:
- Installing the build dependencies is > 100MB. While this might be fine for some, it would make the installation *considerably* slower (because of having to download and install *a lot of* packages)
- Not only the time, but also the space required by the Pi-hole installation would be going through the roof! Imagine only docker installs. The size would more than double (the image is 147 MB in size, the build dependencies for `dnsmasq` would add impressive `158 MiB in 27 packages`).
- Compiling on an end user's system is not reliable - there are way too many moving gears. He could have all kinds of issues with installed libraries and such. We cannot afford to support those situations where the compilation fails
- the list could go on

However, that does not mean that I'd like to stop you when you want to do it for yourself. I guess you already have done it? If not we can assist you with it as far as giving you the instructions how to do it (if you need it). However, if you encounter a compilation problem, I cannot promise that we will have the resources to deeply debug that with you.

**Comment by paulkramme** [comment]
Yea, dnsmasq project compilation is way more complicated than i thought. I try to design my application so that i could run it with as little dependencies as possible and make compilation as simple as possible. Unfortunately they don't. Hopefully the Debian developer will bring out Debian 9 fast, so that there will be a patched version of dnsmasq.

**Comment by paulkramme** [comment]
I will install pihole on my primary nas, which runs ubuntu.

**Comment by DL6ER** [comment]
A lot of expertise concerning DNSSEC has been collected on Discourse. I'd suggest you look that up and post there if you want more help or want to contribute to the discussion there.
