### ISSUE TITLE
Upgrade feature does not respect non-default port

### ISSUE THREAD

**Issue by rogierlommers** [pi-hole/pi-hole#1328]
I have a pi-hole installed on Ubuntu LTS 16.x. I have setup `server.port` to a port != 80 in the `/etc/lighttpd/lighttpd.conf` file. This works, but a few minutes ago, I ran `pihole up` which updates to the latest version.

Unfortunately now my pi-hole is listening on port 80 again. So for some reason, the `up`-feature does not respect a non-default port.

**Comment by Mcat12** [comment]
Yes, currently we don't support changing the port. This is because when an ad request is blocked and re-routed to the Pi-hole, it connects to port 80. We can't change that via DNS.

**Comment by rogierlommers** [comment]
I'm not sure if I understand well. I'm talking to the /admin interface. What exactly do you mean? In my information I'm perfectly able to run the admin interface on a non-80 port. Are you talking about the urls which pi-hole output which can be used to whitelist a host?

**Comment by Mcat12** [comment]
The web server used to host the web interface also handles blocked queries. When we block ads, we redirect them to the Pi-hole's IP address. So when the ad is requested, we can return a blank response. If you change the server to a port besides port 80, then there wouldn't be anyone to answer the queries and might lead to them timing out (if you don't reject packets on that port) and causing pages to appear to load slower. If you moved the web server to a different port and replaced it with another, then the 404 page on that web server would be the thing that replaces ads, which can be unwanted behavior.

**Comment by rogierlommers** [comment]
Check; clear. And it's not possible to redirect to the port mentioned in the configuration setting?

**Comment by Mcat12** [comment]
What do you mean? You might be able to set up a reverse-proxy to send all traffic to X domain to one port, and all the rest to Pi-hole.

**Comment by rogierlommers** [comment]
Sorry for my questions, but I would like to understand better. You say this:

- When a webpage servers an add which is being blocked
- pi-hole redirects to the webserver on port 80
- so the client requesting the ad quickly receives a blank html thingy

Right?

Then I don't understand why pi-hole can't redirect to the port lighttpd is running on, instead of port 80.

**Comment by dschaper** [comment]
When you visit http://www.github.com you are using the http protocol. That is, but convention, port 80. Your browser sends a request on port 80 expecting to get a result back. If you try to visit http://advert.domain, your browser sends a request on the http port again. We instead tell the browser that it should use the http port on the Pi-hole device instead of on the advert.domain server, but still on port 80. It would take a change on the broswer to try to view http traffic over a port besides the http port (port 80.)

**Comment by rogierlommers** [comment]
Ok, so in my situation I have pihole running on port 9005 in my server. However, pihole is available on a c-name domain, for example: `pihole.mydomain.com` (which is pointing to my server). There I have haproxy running and forward-proxying all traffic to pihole (on port 9005).

Is this situation right/correct?

**Comment by dschaper** [comment]
The Pi-hole returns an IP address for a DNS query, so the CNAME wouldn't come in to play.

**Comment by afxgit** [comment]
Sounds a little like my setup: I currently use nginx for OMV and installed pihole, which bundled lighttpd  (didnt get round to looking into using nginx with pihole). I had changed the lighttpd port to 8181 to prevent conflicts and this worked fine. Last update from pihole reset lighttpd port to 80, causing conflict which needed lighttpd.conf changing again.
Blacklisted domains to re-direct to my OMV page but I'm ok with that.

**Comment by diginc** [comment]
> Ubuntu LTS 16.x.

My docker project supports custom ports pretty easily.

**Comment by fortysixandtwo** [comment]
Hello, I have a question after having read this discussion.
I too am using a non-standard port (because on port 80 there is already an apache server listening which is accessible from the Internet).

The way I understood it I should always have the pi-hole web interface listening on port 80
because blocked ads will be rerouted to the pi-holes' IP (and standard port).
So far i haven't seen any timeouts (in a few months of usage) or other slow browsing.

But still I'm wondering if it would be smarter to let the webinterface listen on 80 and setup
my apache server on another port and have my router forward port 80 to the new apache port.
Any ideas/suggestions?

I've also posted a related post in the [feature-request page](https://discourse.pi-hole.net/t/support-for-choice-of-resolver-and-or-web-server/222/7)

**Comment by Mcat12** [comment]
@fortysixandtwo The main issues with not using lighttpd on port 80 are:
1. You may see the 404 page or whatever is running on port 80 in the place of a blocked ad. This can include login prompts, and can be a source of annoyance to those who want to have a tight control over the service running on port 80. (getting requests for random urls whenever an ad is blocked, wasting resources sending a login/404 page to replace an ad, etc)
2. The Pi-hole block page will not be active. Normally, if you go to a blocked domain, it will pop up and show some info about the domain, and let you whitelist it. If lighttpd is not on port 80, then this will not be shown. (only works on http by the way)

So if these issues are not issues to you, then it's fine to use lighttpd on a different port.

**Comment by Mcat12** [comment]
For now, this is not something that we are going to implement.
