### ISSUE TITLE
An error occured while loading the data. Presumably your log is too large to be processed.

### ISSUE THREAD

**Issue by ManuCart** [pi-hole/pi-hole#1336]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
_{4}_

---
**[BUG]:**
An error occured while loading the data. Presumably your log is too large to be processed.

**[BUG] Steps to reproduce:**
- click on Query Log
-Pi-hole Version v2.13.2 Web Interface Version v2.5.2 

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
It's not really a bug, it's telling you the log file is too large to be processed. We're working on a new back end that will be able to parse files, but what size is your `/var/log/pihole.log` file?

**Comment by ManuCart** [comment]
Can I delete this file ?
it's 12Mb

**Comment by PromoFaux** [comment]
You could try the `FTL` branch to see if it loads any quicker/at all.

`pihole checkout dev` will get you onto the beta branch for `FTL`

**Comment by Mcat12** [comment]
That file is the log for Pi-hole, so if you delete it then you are deleting record of all queries today.

**Comment by Tntdruid** [comment]
The FTL is fast! Load so fast whit 100k+ queries.

**Comment by dschaper** [comment]
@ManuCart Were you able to resolve this?

**Comment by ManuCart** [comment]
Yes working, thanks!

**Comment by PromoFaux** [comment]
@ManuCart What did you do to resolve this? For future reference...

**Comment by ManuCart** [comment]
Delete ```/var/log/pihole.log``` and reboot

**Comment by PromoFaux** [comment]
And you have not seen the issue since?

That tells me two things, either the log was not correctly flushing at midnight when it supposed to (Do rotated copies of the log exist? (`ls -lh /var/log/pihole*`)

Or for some strange reason one of your devices on that day decided to spam DNS lookups, causing the log to grow to that size!

Anyway, hopefully once we get `FTL` out there, logs being too large will be a thing of the past. (Until we find it's limit, of course! :wink:)

**Comment by audrummer15** [comment]
Sorry to reopen this issue, but I noticed that @PromoFaux mentioned a worry might be that logs were not being flushed/rotated at midnight. It looks like I've run into this snag. Any known reasons/ways to fix? I'm up to date and my logs haven't rotated in 34 days

**Comment by TylonHH** [comment]
What can I do if a client is running crazy? I know wich one because I see in the dashboard 26k request.

pi@raspberrypi:~ $ ls -lh /var/log/pihole*
-rw-r--r-- 1 root    pihole 9,9K Feb 16 22:27 /var/log/pihole_debug.log
-rw-r--r-- 1 dnsmasq root    14M Apr 20 15:07 /var/log/pihole.log
-rw-r--r-- 1 dnsmasq root    18M Apr 20 00:00 /var/log/pihole.log.1
-rw-r--r-- 1 dnsmasq root   1,3M Apr 19 00:00 /var/log/pihole.log.2.gz
-rw-r--r-- 1 dnsmasq root   1,2M Apr 18 00:00 /var/log/pihole.log.3.gz
-rw-r--r-- 1 dnsmasq root   983K Apr 17 00:00 /var/log/pihole.log.4.gz
-rw-r--r-- 1 dnsmasq root   1,2M Apr 16 00:00 /var/log/pihole.log.5.gz

**Comment by dschaper** [comment]
If the client is getting the DNS IP address via DHCP, then you pretty much need to take that client offline and diagnose why it's spamming. There's nothing server side that can easily handle things, other than just firewalling off the clients IP address and blocking it from being able to contact the Pi-hole completely.

**Comment by TylonHH** [comment]
My intention was to see the queries so I can find out which service on the client (NAS) is "spamming". As I see all that request aren't blocked, so the client is just very communicative.

**Comment by dschaper** [comment]
Would tailing the log live be of any help? You could do that from the web interface, or if you knew the IP of the client, just go to the Pi-hole and `tail -f /var/log/pihole.log |grep <IP>` and watch to see what the domain names the client is trying to resolve.

**Comment by TylonHH** [comment]
Awesome, that helped allot. The Synology Diskstation NAS couldn't complete a cloud synchronisation. Since I paused that, the client is quite.
Thank you very much.
