### ISSUE TITLE
Utilising graphs without logging queries

### ISSUE THREAD

**Issue by libeclipse** [pi-hole/pi-hole#1371]
When installing PiHole, you get the option of installing the admin interface and also of disabling logging. But you also get a warning saying that if you disable logging, it pretty much makes the graphs useless. 

Isn't there a way to just increment some kind of counter for requests instead of logging the actual domains? That way you can have the best of both worlds.

**Comment by technicalpyro** [comment]
please use the discourse forum for feature requests as was stated in the template you deleted in order to make this post

**Comment by libeclipse** [comment]
It's not a feature request, but I'd be happy to. No need to be passive-aggressive.

**Comment by Mcat12** [comment]
Dnsmasq logs the queries, domains and all, and so currently it's all or nothing. We are looking into better privacy methods in the future, possibly with the upcoming FTL backend.

**Comment by libeclipse** [comment]
@Mcat12 Ah, figured it would be dnsmasq handling the logging.

Well, tbh the privacy features only need to be for the control panel. We don't actually care if there's logs on the Pi do we, since the Pi's internal storage is (ideally) not accessible to anyone.

The control panel could parse the log file and display things on the control panel as pure statistics without the actual domains, even with dnsmasq.

What do you think? I guess with the FTL backend it could be re-implemented the other way, but I think this would work for now.

**Comment by PromoFaux** [comment]
> Edit: The page linked in the template doesn't exist.

[Sure about that](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)? 😜 

>[FEATURE REQUEST | QUESTION | OTHER]:

>Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community. It's also easier for us to track.


It does also say " Failure to fill the template will close your issue:" But we'll let it slide.. this time.

---

I discussed briefly with @DL6ER yesterday, and we came to the conclusion that it would be best to have a flag in `/etc/pihole/setupVars.conf`, but not as an accesssible switch on the dashboard (to prevent any user with access from changing it!), that toggles between full display of logs and numbers only.

**Comment by Mcat12** [comment]
We do have a privacy mode through the web interface settings, but anyone with the password can disable it...

**Comment by libeclipse** [comment]
@PromoFaux Oh, it gave me a 404 yesterday. I probably copied it wrong, oops.

Yeah, a flag would be nice for the privacy options. But the main part of this issue is graphs and statistics without logs, which could work even while using dnsmasq. Logs on pi, admin panel only exposes raw numbers.

**Comment by DL6ER** [comment]
If I get this right you are asking for a specific mode that shows statistics on dashboard, but **hides** the following altogether:
- Top Domains
- Top Advertisers
- Top Clients (?)
- Query Log
- Tail pihole.log (otherwise this could be used by users that have access to the dashboard to get the full data)

**Comment by libeclipse** [comment]
@DL6ER Hmm, yeah I guess I am. All I'm saying is that when presented with the option to disable logging, users are presented with "this makes everything in the dashboard essentially useless" (paraphrasing). It doesn't have to be like that. Users can have the best of both worlds.

Of course when you start using the new backend you're working on, you could have a more finely controlled system of only logging the number of requests on the backend too, but for now it's possible to allow logging and have the dashboard parse the log file and only display numbers.

**Comment by DL6ER** [comment]
Most likely `FTL` is the next release we are targeting at. There is nothing that speaks against this, currently.

The main reason for
> "this makes everything in the dashboard essentially useless" (paraphrasing)
is, I think, that users wanted to see the log going once and for all, because also the users that have full SSH access to the Pi-hole didn't wanted to be able to see the queries of the connected clients at all. If you leave the `pihole.log` file there and tell `FTL` to not return them via the API, you do not meet this requirement - instead, we get a new level in between.

**Comment by libeclipse** [comment]
@DL6ER Ah, didn't know that was a use-case. I was mainly concerned about anyone else on the network having access, and having this option in addition to the admin password as a precaution.

I mean I like the pretty graphs and some basic statistics so I don't want logging completely gone: which administrator would?

I do get your point of view though. I wonder if you have any other ideas about how to implement statistics without detailed logs. For the use-case you mentioned, an ugly solution would be to monitor dnsmasq's logs, incrementing some counters or some other data, and wiping that file periodically. But I don't think that's particularly clean.

**Comment by DL6ER** [comment]
> For the use-case you mentioned, an ugly solution would be to monitor dnsmasq's logs, incrementing some counters or some other data, and wiping that file periodically. But I don't think that's particularly clean.

I agree that this solution is quite dirty and there are several drawbacks to this:
1. `FTL` runs as unprivileged user which does not even have his own `/home` directory. Hence, it cannot delete *a single* file on your system - neither by intention nor by accident. So, `FTL` could also not flush the `pihole.log` file.
2. Say you restart the system or run out of memory or whatever happens that kills `FTL` while it is running - you would not be able to get the recent statistics after a restart, since the file has been periodically wiped out.

I think what we can so best is adding an option to `pihole-FTL.conf` which is read in on the start of `FTL`. According to its setting, it will just skip the entire processing of the mentioned data when asked for it by the API. The implementation will be very straightforward (just skip the returning functions altogether) and won't require that much of testing that would be required if I'd have to modify the routines more severely.

**Comment by jacobsalmela** [comment]
Looks like this is [implemented as of FTL v1.11](https://discourse.pi-hole.net/t/graphs-and-statistics-without-logging/2512/4?u=jacob.salmela).  Please re-open if I am mistaken.
