### ISSUE TITLE
More info on IP address?Ability to show more info on IP address

### ISSUE THREAD

**Issue by Toontje** [pi-hole/pi-hole#1398]
Is it possible to make the client IP address a link or hover which provides the hostname of the client? If hostname is not available show the vendor of the MAC address so i can find out who has that IP address at the moment and which device is accessing which domains?
I came up with this because i get a flood of DNS requests for nlsk.neulion.com from one of the hosts on my network and i want to know who is owning that IP address at the moment.
<img width="472" alt="screen shot 2017-04-22 at 09 45 00" src="https://cloud.githubusercontent.com/assets/4884243/25302609/e8e57e0c-2741-11e7-8d4a-d1f3b03c21d9.png">

**Comment by DL6ER** [comment]
The hostname is shown instead of the IP whenever it is available. Try playing around with the Pi-hole DHCP server and set static leases for the devices that do not tell the server their host name (or which doesn't have one).

We have no information about the  MAC address of a client. How do you think we should get it without causing much more network traffic?

**Comment by Toontje** [comment]
Arp cache?

**Comment by dschaper** [comment]
Getting the vendor from the OUI would either require a lookup to an external database, or one that is included with the install. That information changes as well and really isn't that reliable to identify a client. Unless there are very specific OUI's that you'd like to know about, like any Raspberry Pi. But other SBC's and VPN's can't be reliably identified via MAC, and quite a few of the cheaper SBC's don't even factory burn a MAC but generate on the fly, which is quite fun when you have two of the boards in the same collision domain and they use the same full MAC.
