### ISSUE TITLE
Admin interface over HTTPS

### ISSUE THREAD

**Issue by mauvehed** [pi-hole/pi-hole#1442]
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

1

---
**QUESTION**

Can I enable HTTPS for the admin web console at /admin ? I do not see a way to do this.

**Comment by WaLLy3K** [comment]
I know that from experience, it's possible with Let's Encrypt on a Raspberry Pi.

However, without the correct `lighttpd` config changes (which get blown away upon a Pi-hole update), you're going to cause pages to slow down and get configuration errors due to your Pi-hole pretending to be `blockedsite.com`. In the case of macOS and iOS, you'll get a browser popup on every page asking you to verify the identity of a blocked server because of the certificate mismatch, and that isn't fun for anyone.

We have changes in the pipeline for this issue, and if it all pans out as expected, it'll make this an easier process for all.

If you're the tinkering sort, you can possibly make a temporarily solution work based on #1420. It hasn't been tested outside of my own setup though, so your milage may vary.

**Comment by jacobsalmela** [comment]
We also have a [votable feature request](https://discourse.pi-hole.net/t/admin-web-interface-over-https/562) on this.

**Comment by dschaper** [comment]
Closing, refer to the Feature Request on Discourse at the above address.
