### ISSUE TITLE
Prefer ULA over GUA IPv6

### ISSUE THREAD

**Issue by dschaper** [pi-hole/pi-hole#1473]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

## 10

---
**[ISSUE] Expected Behaviour:**
On installs with GUA and ULA's we should prefer ULA's as it's been demonstrated that GUA's can and often are rotated by ISPs.

**[ISSUE] Actual Behaviour:**
GUA's are used as they are detected to have an outside route to the Internet.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
I concur! I'd love to see ULAs being the preferred choice when they are available.

It seemed to have solved some issues of a number of our users (including myself at two distinct locations) and I haven't heard of new issues caused by using ULAs.

For a detection algorithm we should use:

| Type | Address | Source |
| --- | --- | --- |
| GUA | 2000::/3 | RFC 4291 |
| ULA | fc00::/7 | RFC 4193 |

An exemplary implementation (while in PHP) can be found here:
https://github.com/pi-hole/AdminLTE/blob/master/settings.php#L82

**Comment by dschaper** [comment]
Great! Thanks for the pointer to the `&`ing functions, that should make it a lot easier to write the detection, just need to brush up on binary comparitors in `bash` 😄

**Comment by DL6ER** [comment]
```
(((5&3)==1)) && echo YES || echo NO
```

**Comment by dschaper** [comment]
Oh sure, use shell mathematics 😉

**Comment by DL6ER** [comment]
We do I have a M.Sc. in the end? Let me try some math:
```
ULA="fda2:2001:5688:0:bd27:edff:fd37:4201/64"
first="$(cut -f1 -d":" <<< $ULA)"
value=$((0x$first))
(((($value/256)&254)==252)) && echo "ULA" || echo "no ULA"
```

**Comment by DL6ER** [comment]
```
pi@raspberrypi:~ $ testipv6 fe80
no ULA
no GUA
Link-local
pi@raspberrypi:~ $ testipv6 fe85
no ULA
no GUA
Link-local
pi@raspberrypi:~ $ testipv6 fd54
ULA
no GUA
no link-local
pi@raspberrypi:~ $ testipv6 2154
no ULA
GUA
no link-local
```
