### ISSUE TITLE
Compressed gzip blacklist URL

### ISSUE THREAD

**Issue by exwhyz** [pi-hole/pi-hole#1590]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_1_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Block domains from a gzip URL resource

**[BUG | ISSUE] Actual Behaviour:**
Domains populated with binary unzipped data

**[BUG | ISSUE] Steps to reproduce:**
1. Using the GUI add a URL to http://www.shallalist.de/Downloads/shallalist.tar.gz
2. "Save and Update" action reports successful import
3. Go to the query blacklist page and it does not identify the domains as the file it is referencing has not been decompressed as part of the Save and Update action
4. Looking at the /etc/pihole blocked file lists the uploaded file has uncompressed content hence the issue
-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by technicalpyro** [comment]
does running `pihole -g` manually resolve the issue ?

**Comment by exwhyz** [comment]
None of the 3 actions have any effect:

1. Save and Update from the Settings GUI
2. Update Lists from the Tools GUI
3. Running `pihole -g` manually from command line

Data is still uncompressed in the generated list file under /etc/pihole

Query adlists from GUI and `pihole -q` returns the following result for a specific blocked domain that is included in the Shalla blacklist
::: /etc/pihole/list.7.www.shallalist.de.domains (0 results)

**Comment by WaLLy3K** [comment]
Pi-hole can only accept domains in plain-text HOSTS format, or domains-only format. I already [parse its malicious list](https://v.firebog.net/hosts/Shalla-mal.txt), and I can add more if you're interested. Pi-hole itself has no error checking when adding a list, which *is* a bit of a usability issue if a user isn't aware of Pi-holes blocklist limitations (e.g: When adding an [Adblock Plus style formatted list](https://adblockplus.org/filter-cheatsheet))

Currently, we have no plans to make Pi-hole compatible with compressed formats, as it requires some work for the user to be able to specify what file from an archive Pi-hole would need to extract in order to work.

We're always accepting of PR's, however! :smile:

**Comment by exwhyz** [comment]
I am thinking of modifying the gravity_transport() function at line 150 and including a case statement to check for ${url} file extensions (and if they end with `.tar.gz`) appending `| tar xz` to the curl command should uncompress the files on the fly prior to assembling them into gravity.list

Will that be a sustainable solution?

**Comment by WaLLy3K** [comment]
> PS: This is a simplistic assumption in that the .tar.gz uncompresses to a txt file versus a folder structure in which case additional logic will be required.

Unfortunately, this is where the complexity comes in and which is why we haven't had the time to prioritise this over other features and bug fixes. If you add a feature like this, you *need* to have the associated features to allow for specific file(s) to be extracted, as well as being able to support the three most common archive formats served with HOSTS files: `zip`, `tar.gz` and `7z`.

Without it, it'd be reasonable to assume that this could induce user confusion when they say "Hey, this compressed file worked but this other one doesn't".

**Comment by exwhyz** [comment]
Makes perfect sense. The best way then maybe to have a custom script that runs in the background as scripted by the user for their specific need. So for my case I will schedule a script that will download, explode and append custom lists to the gravity master list. I have done that as a proof of concept and it seems to work well using the below commands:

`curl http://www.shallalist.de/Downloads/shallalist.tar.gz | tar xz`
`awk '$0="192.168.1.10 "$0' /BL/spyware/domains >> /etc/pihole/gravity.list`

**Comment by WaLLy3K** [comment]
This is still *definitely* something I'm keeping in mind, but is a bit further down on the todo list. For now, I'm closing this as ultimately it's not an issue, but a feature request. :smile:

**Comment by mglinux** [comment]
Saw this issue while searching something else 😀

You could try my script (will be further improved next days). I wrote it for ipfire but should easily work for pihole too.

https://github.com/mglinux/IPF_Tools

Direct link to shalla script:

https://raw.githubusercontent.com/mglinux/IPF_Tools/master/shalla_hosts.sh

Feedback highly appreciated
