### ISSUE TITLE
tmpfs FTL start order

### ISSUE THREAD

**Issue by runningman84** [pi-hole/pi-hole#1591]
My pihole rpi (first gen using rasbian lite image) uses a tmpfs for /var/log in order to limit writes to sd card and increase data privacy...:
```
# rc.local
mkdir /var/log/apt
mkdir /var/log/fscks
mkdir /var/log/ntpstats && chown ntp.ntp /var/log/ntpstats
mkdir /var/log/lighttpd && chown www-data.www-data /var/log/lighttpd

touch /var/log/pihole.log && chmod 664 /var/log/pihole.log && chown dnsmasq.root /var/log/pihole.log
```
It looks like the start order of FTL is wrong:
```
root@pihole:/var/log# grep dns /var/log/daemon.log 
Jul  9 14:05:15 pihole systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Jul  9 14:05:16 pihole dnsmasq[553]: dnsmasq: syntax check OK.
Jul  9 14:05:19 pihole systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.
root@pihole:/var/log# grep FTL /var/log/daemon.log 
Jul  9 14:05:12 pihole systemd[1]: Starting LSB: pihole-FTL daemon...
Jul  9 14:05:13 pihole pihole-FTL[368]: Not running
Jul  9 14:05:14 pihole systemd[1]: Started LSB: pihole-FTL daemon.
```
This causes an error in FTL
```
root@pihole:/var/log# tail pihole-FTL.log 
[2017-07-09 14:05:13.961] FATAL: Opening of /var/log/pihole.log failed!
[2017-07-09 14:05:13.961]        Make sure it exists and is readable by user pihole
```

I do not really understand the issue because my rc.local script creates an empty log which should be readable. The pihole installer should ensure that FTL is started after dnsmasq.

Futhermore it looks like FTL constantly writes its database file (pihole-FTL.db) in /etc/pihole. I have now linked it to a file in /tmp.

**Comment by dschaper** [comment]
If `pihole-FTL.db` is linked to a temporary file in your /tmp directory that is deleted upon restart/reboot you will lose all historical data and the Pi-hole will not function correctly.

**Comment by runningman84** [comment]
yes that's perfect from a privacy perspective...

**Comment by dschaper** [comment]
We have a feature that disables all logging and log records if the goal is to not have any logging recorded.

**Comment by runningman84** [comment]
In this case I want to have some short term logs but I do not want to write to my sdcard...

**Comment by dschaper** [comment]
Understood, this may not be a use-case that we can accommodate, but I'll ask @DL6ER if this is something that is feasible with our current design.

**Comment by DL6ER** [comment]
> I do not really understand the issue because my rc.local script creates an empty log which should be readable. The pihole installer should ensure that FTL is started after dnsmasq.

Okay, I'll look at the PR you opened. In general, it is not a usual thing to encounter an empty `/var/log` directory on startup. Hence, `FTL` wasn't able to deal with that for a long time.

Why did I say "wasn't"? Because in the current `development` version (which will be released soon) `FTL` will not fail immediately when it find/read from `pihole.log`, but it will wait some time and then try again to ensure that any non-standard file system configuration and `dnsmasq` had enough time to come up properly. However, we do not add a general initial delay as most users don't need that, i.e. it would slow down the startup of `FTL` on their systems without any need for that.

> Futhermore it looks like FTL constantly writes its database file (pihole-FTL.db) in /etc/pihole.

> yes that's perfect from a privacy perspective...

> In this case I want to have some short term logs but I do not want to write to my sdcard...

The statistics shown on the dashboard are *entirely* independent of the database. You can safely disable the database by setting `MAXDBDAYS=0` as described [here](https://github.com/pi-hole/FTL#ftls-config-file). That is a much cleaner solution as generating a database every time that you then don't use at all.

**Comment by runningman84** [comment]
ok I got that, but my init script dependency makes sense anyway...

**Comment by jacobsalmela** [comment]
@DL6ER where are we with this?  I know FTL has had a lot of changes since July...FWIW, I also added an [FAQ on how to disabled the database](https://discourse.pi-hole.net/t/how-do-i-disabled-ftls-database/5624).

**Comment by DL6ER** [comment]
All recent versions of `FTL` can deal with the files not being readable on startup. It the files aren't there, `FTL` [waits for 15 seconds](https://github.com/pi-hole/FTL/blob/master/parser.c#L59) and then tries again. If the files are present, everything will work as expected. If they are still missing, then `FTL` terminates with an error.

**Comment by Mcat12** [comment]
Sounds like the issue should be solved then, because FTL can now handle being started slightly before `/var/log` is fully initialized.
