### ISSUE TITLE
Install: ERROR - Unable to update package cache. Please try "apt-get update"

### ISSUE THREAD

**Issue by Ruined1** [pi-hole/pi-hole#1595]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

I did search issues with "is:issue ERROR - Unable to update package cache" and didn't return any results that seem to match mine.

**How familiar are you with the codebase?:**

_1_

---
**[BUG REPORT]:**

**[BUG | ISSUE] Expected Behaviour:**

Pi-Hole installs

**[BUG | ISSUE] Actual Behaviour:**

Pi-Hole errors out during beginning of process

**[BUG | ISSUE] Steps to reproduce:**

- curl -sSL https://install.pi-hole.net | bash

```
# curl -sSL https://install.pi-hole.net | bash

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

:::
::: You are root.
::: Verifying free disk space...
:::
::: Updating local cache of available packages...
!!! ERROR - Unable to update package cache. Please try "apt-get update"
```

Running apt-get update and the piping the install script to bash returns the same result again.

64-Bit
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

**Comment by dschaper** [comment]
What is the output from `sudo apt update` ?

**Comment by Ruined1** [comment]
```
# apt update
Hit:1 http://download.virtualbox.org/virtualbox/debian xenial InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:5 http://ppa.launchpad.net/fkrull/deadsnakes/ubuntu xenial InRelease
Ign:6 http://ppa.launchpad.net/happy-neko/ps3mediaserver/ubuntu xenial InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Hit:8 http://ppa.launchpad.net/mc3man/xerus-media/ubuntu xenial InRelease
Hit:9 http://ppa.launchpad.net/team-xbmc/ppa/ubuntu xenial InRelease
Hit:10 http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu xenial InRelease
Hit:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
Err:12 http://ppa.launchpad.net/happy-neko/ps3mediaserver/ubuntu xenial Release
  404  Not Found 
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/happy-neko/ps3mediaserver/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
Not being able to update from that last repository is inconsequential.

**Comment by dschaper** [comment]
Any errors that come up during `apt` process will prevent Pi-hole from installing as we can't be sure the packages have been updated. That 404 error on the PPA is causing a non-zero return value from `apt update` which causes the failure of installation of Pi-hole.

**Comment by Ruined1** [comment]
That seems like an overly-cautious approach. I'll correct the apt error and try again and report back with success or failure. Thank you.

**Comment by dschaper** [comment]
It's what we've decided on since there can be any myriad of `apt` failures and there are no specific return values other than pass/fail that we could test for the allow for certain failures to pass while blocking showstopper bugs and errors.

**Comment by Ruined1** [comment]
@dschaper it's no problem, the repository was dead anyways, so why keep it right? I probably never removed it only due to sheer laziness. I removed it, apt updated, and pihole is working as expected. 

Thank you for everything you and your team does!

**Comment by dschaper** [comment]
Thanks!

**Comment by unknown-guy-1610** [comment]
Hey I'm facing the same Issue. I guess the issue was not yet solved please have a look into it 


This is my Terminals Output :


sandeep@Ubuntu:~/Desktop/projects$ sudo apt-get update
Hit:1 http://in.archive.ubuntu.com/ubuntu disco InRelease
Ign:2 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 InRelease      
Get:3 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release [3,462 B]
Hit:4 http://in.archive.ubuntu.com/ubuntu disco-updates InRelease              
Get:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release.gpg [455 B]
Hit:6 http://in.archive.ubuntu.com/ubuntu disco-backports InRelease            
Ign:7 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:8 http://ppa.launchpad.net/umang/indicator-stickynotes/ubuntu disco InRelease
Hit:9 http://security.ubuntu.com/ubuntu disco-security InRelease               
Hit:10 http://packages.microsoft.com/repos/vscode stable InRelease  
Hit:11 http://dl.google.com/linux/chrome/deb stable Release  
Ign:5 http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release.gpg
Hit:12 http://linux.teamviewer.com/deb stable InRelease
Reading package lists... Done          
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9ECBEC467F0CEB10
E: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
sandeep@Ubuntu:~/Desktop/projects$ sudo bash basic-install.sh

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [✓] Disk space check
  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"
sandeep@Ubuntu:~/Desktop/projects$

**Comment by dschaper** [comment]
It's not a Pi-hole issue to be solved. You have a repository that is broken for mongodb. We don't install that package so there's not really anything we can do. You need to resolve the below error.

```sh
W: GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 9ECBEC467F0CEB10
E: The repository 'http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by leopheard** [comment]
Is this the same issue? I have no idea what that repository is and why it's not updating

```
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'https://s3-us-west-2.amazonaws.com/brave-apt stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://s3-us-west-2.amazonaws.com/brave-apt/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
pi@Pihole:~ $ pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:	up to date
  [i] Web Interface:	up to date
  [i] FTL:		update available
  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check
  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u7
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✗] Update local cache of available packages
  Error: Unable to update package cache. Please try "apt-get update"
  Unable to complete update, please contact Pi-hole Support
```

**Comment by dschaper** [comment]
It's not a Pi-hole issue. A quick web search of `https://s3-us-west-2.amazonaws.com/brave-apt` shows it belongs to the Brave webbrowser.

**Comment by Bluejanis** [comment]
I am experiencing the same error with docker-pi-hole since this week. It was working fine last week when I had used this computer.  Other than updates, nothing changed.

> What is the output from `sudo apt update` ?
Where would you run that? In Docker Desktop, there is a button to open the CLI, but it closes as soon as the container fails. Almost instantly.

**Comment by PromoFaux** [comment]
>I am experiencing the same error with docker-pi-hole 

There is no need to run `pihole -up` or any `apt` commands at all in the docker container. If you're trying to upgrade to a newer version of pi-hole in docker, see here : https://github.com/pi-hole/docker-pi-hole#upgrading-persistence-and-customizations

Else please open a new issue on the docker repo

**Comment by Bluejanis** [comment]
Thanks for your input. I have already solved my issue in the meantime.

I am not sure what caused the issue in the first case. I recreated the pi-hole docker container with my config, and now it is working again flawlessly.
