### ISSUE TITLE
line 391 of /advanced/Scripts/piholeDegub.sh. 'Teminate' should be 'Terminate'

### ISSUE THREAD

**Issue by award28** [pi-hole/pi-hole#1625]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**
Not very familiar, noticed typo on debugging. 

_1_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**

**[BUG | ISSUE] Actual Behaviour:**

**[BUG | ISSUE] Steps to reproduce:**

-
-
-
-

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by WaLLy3K** [comment]
Hey @award28, thanks for the report. I can see the [issue you mention here](https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/piholeDebug.sh#L391) and can confirm that it'll be fixed in the [next release](https://github.com/pi-hole/pi-hole/blob/7d56e2a9371e952b5ffea24a298615a73e098b11/advanced/Scripts/piholeDebug.sh), due to a complete re-write of the debug script.

**Comment by award28** [comment]
Glad I could help. Thank you @WaLLy3K.

**Comment by jacobsalmela** [comment]
Resolved in v3.2 (#1585)
