### ISSUE TITLE
How do I update to the latest version? 

### ISSUE THREAD

**Issue by FrozenBeard** [pi-hole/pi-hole#1715]
1. Theres no webUI button to update pihole
2. Theres no FAQ how you update
3. Theres no Wiki page how to update
4. Shouldn't it say on the releases page how to update at the very least?

Do I just curl and run the install script again? or sudo apt-get update && sudo apt-get upgrade?

**Comment by dschaper** [comment]
In the future we'd like you to fill out the template that we have provided so that we can track your issue. It helps us out with the large volume of issues that we have to process.

The answer to you question is to run `pihole up` to update the process and it's explained in a couple of places. 

Thanks for your issue submission.

**Comment by Mcat12** [comment]
2. https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249

**Comment by FrozenBeard** [comment]
That was not there before.

`pihole -up`

So thats it?

**Comment by jacobsalmela** [comment]
Yeah, I added that link in there after seeing several new users not knowing how to update.  And, yes, it's as easy as `pihole -up`.
