### ISSUE TITLE
Pi-Hole accepts weak passwords for users and it is easy to crack by unauthorized users

### ISSUE THREAD

**Issue by sri786** [pi-hole/pi-hole#1781]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [yes] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [yes] The issue I am reporting can be *replicated*
- [yes] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

_5_

---
**[BUG REPORT | OTHER]:**

Please [submit your feature request here](https://discourse.pi-hole.net/c/feature-requests), so it is votable by the community.  It's also easier for us to track.

**[BUG | ISSUE] Expected Behaviour:**
Password for Pi-Hole admin should follow standard password guidelines and it should not accept weak passwords.

**[BUG | ISSUE] Actual Behaviour:**
Pi-Hole accepts (through Pi-Hole command line interface) any kind of password at least having single character 

**[BUG | ISSUE] Steps to reproduce:**

- go to terminal and enter the command pihole -a
- once you enter pi-hole admin utility , view the option using pihole -a --help
- now choose -p to set password, enter the command pihole - a -p
- now try to enter any kind of password having atleast 1 character in it (even blank password for special case)
- it accepts the password and gives the acknowledgement message

**[BUG | ISSUE] Idea for implementation to achieve Expected Behavior:**
- Go to the program https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh
- go to line 94 
- add else condition to validate the entered password with a regular expression 
- use regular expression like [[ ${#s} -ge 6 && "$s" == *[A-Z]* && "$s" == *[a-z]* && "$s" == *[0-9]* ]]
   this regex make sure that input string meet following conditions:
       1. at least 6 characters long
       2. has at least one digit
       3. has at least one Upper case Alphabet
       4. has at least one Lower case Alphabet
Following is the code snippet of this issue :
![webpage](https://user-images.githubusercontent.com/21104237/33108951-7d7bda7e-cf04-11e7-9f07-c398e5cb89fe.jpg)

The main reason i have created this issue is, password option in any interface is provided to ensure minimum security for the application user. Since, pi-hole accepting any kind of password (like 1 character) password, i feel it is not suggestible and no way it becomes a secure and user friendly application.

I can create a pull request, if my suggestion or idea is approved by you !
Kindly go through the details and advise/approve accordingly.

Thanks

**(Optional) Debug token generated by `pihole -d`:**

`<token>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
> easy to crack by unauthorized users

Besides brute force, have you found a method to easily crack the password?

**Comment by ferdydek** [comment]
@Mcat12 password complexity requirement is solely used as brute force countermeasure. @sri786 is asking directly for password complexity.

@sri786 Since the standard installation will use predefined username, the brute-force only has to guess the password. AFAIK there is also no mechanism to block/prolong time between attempts/lockout/ban malicious attempts, so +1 for the PR.
I would vote for 8 characters, with mandatory at least letters and numbers, as minimum standard.
Additionally, **as option**, upper/lower case and special characters requirement.

**Comment by sri786** [comment]
@ferdydek & @Mcat12  Yeah I agree ! any login authentication should have such minimum standard requirements for password, irrespective of what kind of attacks are possible. That way we can at least minimize the vulnerability.  @Mcat12  I think it will be an add on to the pi-hole authentication mechanism. Once you and other authors of this repository, approve my request for the add-on, i will do required change and create a pull request for the same . (kindly review details i have mentioned in the issue regarding the code change)

Thanks !

**Comment by Mausy5043** [comment]
Adding special characters will not increase entropy a lot. 
Additional length of the password will be more effective. 

That is why I always prefer to use 16+ character strings of only lower case characters above mixing upper/lowercase and numbers. I especially hate it when this mixing is required by a website and they require me to use special characters. 
If you've ever tried to type a complex password like you are suggesting on your mobile device you'll understand why I would prefer a 20 chars lowercase password over an 8 chars mixed. 

https://stormpath.com/blog/5-myths-password-security

Why not let the admin select which sets [a-z][A-Z][0-9][!@#$%^&*()] are required and what the minimal length should be? You can then have a default for the first three sets with a length of 8, but leave it to the admin to change it at will. This will also move the responsibility of sufficiently strengthening the login from you to the end-user which might be nice.

https://security.stackexchange.com/questions/143917/does-it-really-improve-a-password-if-at-least-one-character-of-each-group-a-z-a

**Comment by sri786** [comment]
@Mausy5043 Thanks and I agree to your suggestions !

**Comment by Mcat12** [comment]
:+1: for creating a PR

**Comment by sri786** [comment]
@Mcat12  Thanks for the approval ! But, i have couple of following queries before proceeding to work on PR.
1. So, finally do i need to work on the password requirements mentioned by me or the one suggested by @Mausy5043 ?
2. And, do i also need to attach the test results of the added logic, in the PR ?

**Comment by Mcat12** [comment]
1. You can implement the configurable password requirements if you want, but it is definitely not required (and would be a bit much for a first contribution, I'd think). A 6 or 8 min password with/without the special character requirements is good for now (we'll see how it turns out in the PR)
2. It is always nice to have tests, but at least with our current automated testing infrastructure I don't expect you to add tests. That being said, you should definitely manually test it to make sure that it works!

**Comment by sri786** [comment]
@Mcat12 Sure, Thanks for your information !

**Comment by diginc** [comment]
I searched a little after cringing at the idea of bash doing password complexity enforcement:

- https://stackoverflow.com/questions/392928/how-do-you-compute-password-complexity/393062#393062
- https://www.cyberciti.biz/security/linux-password-strength-checker/

**Comment by sri786** [comment]
@Mcat12,, what does automatic testing infrastructure mean ? could you please explain ? i have tested the relevant changed logic manually and it is working fine ! now i would like to know whether im ok to create pull request on dev branch ? or any other unit/integration testing needs to be done? ( its delayed because i was busy with other school work )

**Comment by diginc** [comment]
> what does automatic testing infrastructure mean

[./test/test_automated_install.py](https://github.com/pi-hole/pi-hole/blob/master/test/test_automated_install.py) is the main test file which can be if you have the python `requirements.txt` files installed.

[Here you can see travis-ci running the tests](https://travis-ci.org/pi-hole/pi-hole/builds/308756688)

As Matt already said, this isn't required or for the faint of heart.  The tests are based off an earlier version of my docker image testing framework, [my short readme for testing](https://github.com/diginc/docker-pi-hole/blob/master/TESTING.md) partially applies - I just wouldn't run the `-n` pytest flag as it may mess with the docker image building after tests, which require the image build to come first.

Here's a short summary of the testing framework without going into too much detail:

Tests are orchestrated and outcomes asserted in python, docker, and bash (in the order roughly).  The python spins up two OS varients in docker, debian and centos.  Since the majority of pi-hole is bash that bash is fed into the docker image when it is built, then the python executes the required parts of bash and asserts the returned data looks correct.  rinse and repeat for different functions good or bad cases.

**Comment by sri786** [comment]
@diginc  Thanks for the information !
Following is the logic i have added and tested separately (attached the test results also). 
**Logic:**
![image](https://user-images.githubusercontent.com/21104237/33653274-30a9db04-da32-11e7-8ff9-af5ae1064838.png)
**test results:**
![image](https://user-images.githubusercontent.com/21104237/33653302-453fd06e-da32-11e7-8ece-7c7375627744.png)
@Mcat12  and @diginc 
Acc to my understanding, i need to create a pull request and follow the instructions mentioned https://travis-ci.org/pi-hole/pi-hole/builds/308756688  to test.  am i right ? Can i add the logic in the https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/webpage.sh and create a pull request so that i can test the dev source?

**Comment by Mcat12** [comment]
All you should need to do is follow the [contributer's guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).

**Comment by dschaper** [comment]
Pull Request for this issue went stale and is closed. Closing issue at this time.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-accepts-weak-passwords-for-users-and-it-is-easy-to-crack-by-unauthorized-users/5612/1
