### ISSUE TITLE
Pi-hole silently installs lighttpd and messes up the configuration of the existing web server

### ISSUE THREAD

**Issue by oakkitten** [pi-hole/pi-hole#1785]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?**: 1

---

This issue is different to #1711 and #751 in that I am primarily concerned with the lack of warning in the installer, and not the actual behavior of it. Also, the solution to #751 only addresses the overwriting of the lighttpd config and ignores other problems.

**Expected Behaviour:**

1. Pi-hole installer warns the user that it will:
 1.1. install lighttpd, overwriting current settings
 1.2. use `/var/www/html` instead of its own folder and put its file in there
 1.3. change folder ownership to `www-data` for certain files and folders
2. Pi-hole installer asks the user on which port to run the server
3. Pi-hole installer notifies the user that it is possible to easily employ other web servers and manually configure things

**Actual Behaviour:**

 Pi-hole only asks if the user wants to use a web interface, which is ambiguous. Then, without further questions or warnings, it proceeds to do its things, messes up `/var/www/html`, and—because I already had another web server running with some custom settings—displays a 403 on `pi.hole`.

**Steps to reproduce:**

Run `curl -sSL https://install.pi-hole.net | bash`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
We're fine with adding in a warning about installing lighttpd and the relevant configs, but we can't change the port because HTTP requests will come over port 80, which is out of our control. We also don't currently support other web servers, but we welcome PRs.

**Comment by oakkitten** [comment]
http requests come over the port that is specified in the browser. just go to `http://pi.hole:8080` and it will connect to port 8080. accordingly, web servers can listen on arbitrary ports.

and imo there's no need to officially support other web servers as the configuration for many of them is straightforward. for example, this is the code that i added to my configuration files to make Pi-hole work with nginx:

```
location ~ ^/admin/.+\.php$ {
    include snippets/fastcgi-php.conf;
    fastcgi_pass unix:/var/run/php5-fpm.sock;
}

location /admin {
    index index.php index.html index.htm;
}
```
it's just 5 lines of text. a wiki page with a bunch of these snippets for different web servers, and, of course, a mention in the installer, will suffice

**Comment by PromoFaux** [comment]
>http requests come over the port that is specified in the browser. 

Correct, However in order for the block page to function correctly, Pi-hole needs to be listening on port 80, due to how pi-hole works.

E.g: If the browser requests `http://blockeddomain.com/images/advert.jpg`, then pi-hole will return `http://<IP of Pi-hole>/images/advert.jpg`.

The browser will then request that content (on port 80), and as it doesn't exist on the webserver portion of pi-hole, the block page is returned as a `404` error page.

**Comment by Mcat12** [comment]
Your nginx config is missing some things, such as redirecting 404 to the block page.

**Comment by Rassilion** [comment]
> The browser will then request that content (on port 80), and as it doesn't exist on the webserver portion of pi-hole, the block page is returned as a 404 error page.

You can fix this by using a reverse proxy, on nginx with this config ad spaces looks blank not 404 and block page works.
```
server {
    listen 80 default_server;
    server_name  pi.hole <IP of Pi-hole>;
    charset utf-8;
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

and you can access other sites or apps by custom local domains like this

```
server {
    listen 80;
    server_name rpimonitor.server.local;
    charset utf-8;
    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

**Comment by oakkitten** [comment]
wait, are you saying that lighttpd will be installed regardless of whether user chooses to have a web interface or not? for the sole purpose of returning 404? 😰

or, are you saying that in case lighttpd is installed, it is used to return 404 as an additional feature? 🙄

i'm not sure if i am getting it right, but in both of these cases you can run an additional server thread on another port. 

(what is the benefit of 404 over using an invalid ip or something like that?)

**Comment by PromoFaux** [comment]
Both of these are valid points, but Pi-hole was originally designed to be run on it's own on a raspberry pi, and as such `lighttpd` was a choice made at the very beginning of the project.

Yes there are lots of things that _could_ be done, and we have looked at [solutions for offering support for multiple web servers](https://github.com/pi-hole/pi-hole/pull/353) in the past, but you have to understand that our time as devs on this project is limited, and we can't get everything integrated that everyone wants!

If you choose not to install the web interface, then `lighttpd` will not be installed. I believe the IP that is returned in this case is `0.0.0.0`, but it's been a while since I've looked at that section of the code.

The benefit of the 404 page is that it provides a visual cue to users as to why there the address they've attempted to visit is blocked, rather than just being a blank page, or "<web address> cannot be resolved, refresh, try again etc" type pages. If the web interface/404 page is not something you want, you can always turn it off.

If you want to help out by providing a more robust solution for users that may have alternative web servers installed, we gladly accept (tested) Pull Requests from community members, we don't bite that hard!

**Comment by imnotme** [comment]
FYI, working apache setup (as a reverse proxy). I don't care about the block page for the moment : 

1. Stop apache
2. Install pihole
3. Change lighttpd.conf accordingly : 
```
server.bind                 = "127.0.0.1"
server.port                 = 8880
```
4. restart lighttpd
5. Add this to one vhost (default one for me, bonus: authent) and enable required apache modules : 
```
<Location /pihole>
        AuthType Basic
        AuthName "Restricted Content"
        AuthUserFile /etc/apache2/.htpasswd
        Require valid-user
        ProxyPass  http://localhost:8880/admin
        ProxyPassReverse http://localhost:8880/admin
        ProxyHTMLURLMap https://mysite.mydomain.tld/ /
</Location>
```
6. restart apache

Should work, but be sure to lock down the default apache vhost since pi-hole install itself in /var/www/html on debian.

**Comment by dschaper** [comment]
Option for not installing a webserver is now implemented.

**Comment by cayenne3** [comment]
Are you sure? I just installed pi-hole and did not see any warning and now my server configuration is all messed up. Is there an uninstall script?

**Comment by PromoFaux** [comment]
Just checked on a fresh install, this is the warning:

![image](https://user-images.githubusercontent.com/1998970/80867627-12170f80-8c8d-11ea-9a7a-bc104eef9d58.png)

When you say your server configuration is messed up, I presume you mean because `lighttpd` being installed as well as your web server?

`sudo apt remove lighttpd`

and edit `/etc/pihole/setupVars.conf` and change the following line:

```
INSTALL_WEB_SERVER=true`
```

to:

```
INSTALL_WEB_SERVER=false
```

This will prevent `lighttpd` being installed on any future updates.

**Comment by cayenne3** [comment]
Sorry. I misunderstood. Yes, you are correct. I was expecting a message along the lines of "Configuration files for existing lighttpd installs will be modified". My bad. Thanks.

**Comment by TerryE** [comment]
This is a nice product but the fact that it stomps over an existing lighttpd service is a PITA.  In my case I want to install a second instance of PiHole to act as a DNS2 for resiliency on a gateway server that already uses lighttpd to host a couple of HTTPS blogs.  I can't implement this using your `external.conf` concept, because of the precedence issues.  It was simple for me to add an extra VHOST and the rules to support PiHole in my setup.   However, _I would really prefer to avoid having to restore my lighttpd configuration after every Pihole upgrade_.  I see that a very simple approach would be to accommodate 2 usecases that facilitate the use of the web interface:

1)  the user is a basic user and doesn't use lighttpd or other webserver on the server -- in which case the existing defaults apply, or
2) the user already uses lighttpd or other webserver on the server -- in which case the responsibility for the config merge should be left the user.  The install should prompt for a www root folder, create a `lighttpd.conf_pihole_sample` and not overwrite any other webserver config or resources.
