### ISSUE TITLE
Only Netherlands Resolver Seems to Work!

### ISSUE THREAD

**Issue by humdane** [pi-hole/pi-hole#1958]
Tried multiple times but only Netherlands resolver works. Denmark resolver does not even manage to get a name resolution and times out!I tried over 10 times with different configs.

DnsCrypt in use with Pi-hole

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by humdane** [comment]
Wait... Why was it closed mate? What did I do wrong?

**Comment by PromoFaux** [comment]
Did you read my reply?

**Comment by humdane** [comment]
Yes. Went to a template.

**Comment by humdane** [comment]
Yes. Went to a template. https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by PromoFaux** [comment]
....

Did you read the template?

**Comment by humdane** [comment]
Yes.

**Comment by PromoFaux** [comment]
Then you know why I closed the issue.

**Comment by humdane** [comment]
I don't actually. Never mind you seem not to be expected any help from. I will see myself out. Be polite to someone who takes the effort to come here and ask for help. Not everyone's gonna act as you want them to. Sometimes you need a direct approach that includes simplicity to understand. You are good champ!

**Comment by PromoFaux** [comment]
In case it's not already abundantly clear (it is), your issue was closed because you elected to delete the template and create a new issue.

The issue template (clearly) states that failure to follow it (the template) will result in your issue being closed. On replying to your OP, I was helpful enough to have even pointed that part out for you.  (Highlighted in the screenshot of my reply below, in case you somehow missed it)

![image](https://user-images.githubusercontent.com/1998970/36041945-18132f46-0dc2-11e8-8e28-c78c436e2cae.png)

If you would like to continue with this ticket, please edit your OP to include the **_required_** issue template, filled out in full.

Everyone has to fill out that template in order to open an issue, no matter how trivial. It is there to help us to help you. Without the required information, we cannot help, it really is as simple as that!

>I don't actually
It is clear that although you said you read the template, you did not. The template explains why your issue was closed. ;)

**Comment by humdane** [comment]
Never deleted anything. Had to edit! Cause DNSCrypt Git redirects here and I did not want to make a double post you see. Wish you had paid more attention to issue then a template. But hey, who am I to ask? Just another ignorant user I am. And... I did go through it and found it unnecessary to this case. 

"Don't make permanent decisions on temporary feelings."

**Comment by PromoFaux** [comment]
OK, well this conversation has gone on a lot longer than I thought it would. The relevant part pointed out to you was:

>### **You must follow the template instructions. Failure to do so will result in your issue being closed**

Whether or not you thought it unnecessary is irrelevant.

If you cannot be bothered to take the time to fill out a template that we ask you to fill out, why should I take the time to read the issue you have submitted? (I am aware of the irony here, I have spent longer than needed on this "discussion")

Take a look through nearly every other issue against this repository, our [Discourse forums](https://discourse.pi-hole.net), our various social media channels ([Reddit](https://reddit.com/r/pihole), [Twitter](https://twitter.com/the_pi_hole), [Facebook](https://www.facebook.com/ThePiHole/)), and you will see that we are in fact very helpful people. We are also all volunteers on this project, doing this in our spare time outside of working full time jobs. The template really is an important part of the process.

Your original post gives us nothing helpful to go on. What have you tried? What do you expect to be happening? What are the details of the 10 other configs that you tried. Had you followed the template, you could have provided us with all of the relevant information, and you may have received a response more in keeping with what you expect. We expect users to help us to help them. It's not a big ask.
