### ISSUE TITLE
YouTube ads

### ISSUE THREAD

**Issue by githubsaturn** [pi-hole/pi-hole#1988]
[Sorry, I'm not using the template as most items on it are not applicable]

Should I expect PiHole DB include all subdomains `RANDOMCHARS.googlevideo.com`? i.e. is this a known bug/limitation that PiHole is unable to block video ads on youtube?

**Comment by vaguerant** [comment]
Unfortunately for people wishing to block ads, legitimate YouTube videos are also served from those *.googlevideo.com domains; if you blocked those, you wouldn't be able to use YouTube at all. So it's not really a bug or issue with Pi-hole, but with the nature of blocking by domain, which is a fairly monolithic solution which is great for some purposes and not great for others.

A browser-based ad-blocker will be much better at blocking YouTube ads, but is obviously no help if you're browsing YouTube via a smart device app or similar where you can't just install an ad-blocking extension.

In that scenario, if you've got an Android device, I think you should be able to do something like install Opera (built-in ad blocking support) or Firefox with an ad-blocker extension (Firefox supports extensions on Android) and watch YouTube via those instead of in a dedicated app. On iOS, Opera's built-in ad-blocking might be your best bet, as extension support is not allowed by Apple, so Firefox won't help much.

I don't personally have any Android or iOS devices on-hand to check whether those solutions work, though, so don't take that advice as gospel.

**Comment by githubsaturn** [comment]
> Unfortunately for people wishing to block ads, legitimate YouTube videos are also served from those *.googlevideo.com domains; if you blocked those, you wouldn't be able to use YouTube at all. So it's not really a bug or issue with Pi-hole, but with the nature of blocking by domain, which is a fairly monolithic solution which is great for some purposes and not great for others.

That's what I thought, but I wasn't sure if this is a known limitation or I have misconfigured something.

**Comment by PromoFaux** [comment]
Closing and suggesting a more appropriate place for discussion, as this is not an issue with the source, per se.

https://discourse.pi-hole.net/t/how-do-i-block-ads-on-youtube/253
