### ISSUE TITLE
How to delete query log history

### ISSUE THREAD

**Issue by jwillmer** [pi-hole/pi-hole#1992]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:** `0`

---
**Expected behaviour:**

I blacklisted a query in the query log. If I go to `long term data -> top lists` I see the query in both lists since it was not blocked before. How can I clear the whole log history in order to get rid of seeing the query in both lists?
`Flush logs` does only delete the log of the current day.

**Comment by Mcat12** [comment]
You can move/delete the long term history database:
```
cd /etc/pihole
sudo service pihole-FTL stop
sudo mv pihole-FTL.db pihole-FTL.db.old
sudo service pihole-FTL start
```

**Comment by jwillmer** [comment]
Works as intended. Maybe a feature to implement in the GUI?

**Comment by andreskrey** [comment]
+1

For some reason my database was showing a whole month of history and the web interface was super slow.

**Comment by PromoFaux** [comment]
>Maybe a feature to implement in the GUI?

Possibly, though any work on new features on the current web interface has been put on hold while we prepare to get the [new web interface](https://github.com/pi-hole/web) up to scratch. Maybe worth opening a feature request on [Discourse](https://discourse.pi-hole.net/c/feature-requests) so that it is trackable, and easier for the community at large to vote upon.

**Comment by msholly** [comment]
Hey I wanted to update the Devs on the Dashboard issue that cropped up recently. I think the FTL database got corrupted or too large for the web interface to handle. This prevented any records since December from showing up in the "all records" area, and completely blanked the Dashboard stats. 

The steps from @Mcat12 did the trick and the dashboard and query log instantly started working again. A repair install and some other suggestions online didn't have an effect. Only remaking the FTL database. Thanks for everyone's work on this project.

**Comment by wulfihm** [comment]
@andreskrey 
There is an entry in the /etc/cron.d/pihole file that runs a job once a day at 0:00 that flushes the log (pihole -f). That command is not for the whole file but for the displayed log in the dashboard. Maybe there's an issue there for you.
