### ISSUE TITLE
Pihole -up causes dnsmasq to stop functioning (01-pihole.conf line 37)

### ISSUE THREAD

**Issue by 7oxicshadow** [pi-hole/pi-hole#1997]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide]
- [?] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Update should should complete normally and pi-hole operates as expected

**Actual behaviour:**

Update gets to the end but a message of "Unable to complete, contact Pi-hole" is displayed.
Running pihole -up again says that pihole is updated.
Restarting pi-hole results in the dns service (dnsmasq) not starting

**Steps to reproduce:**
Set pihole to use devel branch
run pihole -up

**Troubleshooting undertaken, and/or other relevant information:**

dnsmasq --test reports:
"extraneous parameter at line 37 of /etc/dnsmasq.d/01-pihole.conf"

line 37 is "log-queries=extra"
**Changing the line to "log-queries" and saving the changes allows dnsmasq (and pihole) to start normally.**

**Comment by dschaper** [comment]
Please search through the Open and Closed issues, looking for the word `extra`. There's 3 or 4 issues that already cover this exact situation.

**Comment by PromoFaux** [comment]
Hi there,

Thanks for the report, however this is a known issue, due to unforeseen issues with some distros not being able to run the latest version of `dnsmasq` (which includes the `log-queries=extra` switch)

Take a look at the release blog post in pi-hole.net for instructions on how to downgrade back to 3.2.1, or manually update `dnsmasq` untill we can get the next version out.

Cheers!

**Comment by COLABORATI** [comment]
This issue came up first searching with ddg - I do not see that this issue is solved - this just f* up the pi-hole dns resolver on my local net, so the issue obviously is not resolved and still should be open, so please change the status as there is no solution to this problem now - a pi-hole upgrade kills the dns resolver and breaks connectivity of all machines using that resolver - this is the worst outcome you could have produced with an upgrade. Also you are not handling that appropriately.

Also you should **put a big red warning on the pi-hole** website!

The demonstrated attitude "some distros do not manage to update software like we think it should be done" is absolutely inappropriate for anybody who develops infrastructure code - it is just a plain wrong view of the world. Of course you have to adapt to the distro developers and can not dictate what your project requires. Of course you have to check for these kind of changes **before** you do a release and of course you should be able to provide a basic **version check** before killing an active piece of infrastructure.

Also the kill you provide with this upgrade is extraordinary stupid as the rollback is not possible with a broken dns resolver. Totally annoying, immature and amateurish. Horrible. Break the dns resolver and then dissing on the distro not providing the right package version - can not get lower.

Please step back for a while and learn how to develop a mature feeling of responsibility that is a basic requirement for every maintainer of infrastructure code. This upgrade was a huge destroyer for your credibility.

**Comment by PromoFaux** [comment]
Hi @COLABORATI, 

Firstly, please accept our apologies, It was an oversight on our part as we did not realise at the time that Raspbian Jessie did not have the version of dnsmasq in it's repositories that was required. 

As far as we're aware, it's only Raspbian Jessie that is affected. 

>Take a look at the release blog post in pi-hole.net for instructions on how to downgrade back to 3.2.1, or manually update dnsmasq untill we can get the next version out.

In case you are unable to find those solutions, please see below:
1) [Revert to a previous version of Pi-hole](https://discourse.pi-hole.net/t/how-do-i-revert-to-a-previous-version-of-pi-hole/7168)

2) [Manually install a more recent version of dnsmasq on Raspbian Jessie](https://discourse.pi-hole.net/t/install-a-more-recent-dnsmasq-on-raspbian-jessie/7306)

>rollback is not possible with a broken dns resolver

A way around this is to open up `/etc/resolv.conf` and temporarily replace `namesever 127.0.0.1` with `nameserver 8.8.8.8` 

Again, apologies that this is even an issue in the first place, and I appreciate your frustration, but we have worked to find a solution to it (listed above) and have learned from this to ensure that our pre-release testing is more stringent in future.
