### ISSUE TITLE
Unable to update Pihole?

### ISSUE THREAD

**Issue by Tibet4690** [pi-hole/pi-hole#2001]
Web interface is showing an update available.

Current Pihole Version: 3.2.1 (verified via pihole -v)

when I run pihole -up everything comes back as up to date.

OS: Ubuntu Server 17.1 (x64)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
