### ISSUE TITLE
Deleting a duplicate entry in Block Lists deletes all matching entries.

### ISSUE THREAD

**Issue by mayesidevel** [pi-hole/pi-hole#2013]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

If duplicate entries are allowed in Block Lists (possibly not after #1954 is approved?), then deleting duplicate entries in Block Lists should only delete the single entry selected for deletion.

**Actual behaviour:**

Selecting a duplicate entry for deletion in Block Lists deletes ALL matching entries.
See [here](https://imgur.com/a/YNfpY) for screenshots.

**Steps to reproduce:**

(This is the procedure followed in the linked screenshots above.)
1. Add duplicate entries to Block List.
2. Delete one of the duplicate entries.
3. Save (only tested without Update).
4. All of the matching entries are gone.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`fhomlc82iy`

**Troubleshooting undertaken, and/or other relevant information:**

Reproduced the issue, and included screenshots linked above.

**Comment by DL6ER** [comment]
You are right. I also think tha #1954 should be the solution, see my comments therein.

**Comment by mayesidevel** [comment]
Unless I'm mistaken, that would only prevent duplicates from being added moving forward though. Anyone that has duplicates before the change is made would still encounter this issue when trying to remove them.

**Comment by DL6ER** [comment]
You're right. So we should also add something like `sort -u` somewhere to have duplicates stripped, automatically.

**Comment by DL6ER** [comment]
@dschaper This might be expected behavior. When a user deletes a domain, they want to have it unblocked. This is what happens when *all* exact matches to this domain are deleted.

**Comment by mayesidevel** [comment]
@DL6ER For what it's worth- this issue is about pruning duplicates on the page for manging Block Lists, not Black Lists. The user would be deleting a URL pointing to a list of domains, as opposed to a single domain that they want to unblock.

I haven't tested this again since reporting, but if #1954 is working as intended, this should be a fix for legacy lists that had duplicates before adding duplicates was no longer possible.

**Comment by PromoFaux** [comment]
@mayesidevel this will be mitigated when we release the next version with database support for storing the lists. When the user's `adlists.list` file is migrated into the database, any existing duplicates will be "thrown out"

```
$ cat testdata
1,abc.de
2,abc.com
3,abc.de
4,def.de
5,fgh.com

$ sqlite3 test.db 
SQLite version 3.26.0 2018-12-01 12:34:55
Enter ".help" for usage hints.

sqlite> .schema test
CREATE TABLE test ( id integer primary key autoincrement, addr text unique not null );

sqlite> .mode csv
sqlite> .import "testdata" "test"

testdata:3: INSERT failed: UNIQUE constraint failed: test.addr

sqlite> select * from test;
1,abc.de
2,abc.com
4,def.de
5,fgh.com
```

**Comment by joballo** [comment]
https://wikict.org/index.php/Remove_duplicate_domains_from_multiple_domain_lists
Check this link it helps with remove duplicates from lists when adding large number of block lists

**Comment by jfb-pihole** [comment]
There is a reason that Pi-hole (since V5) does not remove duplicates.  To allow for group management and assignment of individual blocklists to client groups, the integrity of each blocklist must be maintained.  If you remove duplicates, you break this functionality.

From the linked page you provided - "The "issue" with these types lists is that when importing a large number you are prone to having duplicates an increasing the size of your database substantially. "

I installed all the linked blocklists (and only those blocklists) in a Pi-hole and there were the following domain count reported in the gravity update output:

`Number of gravity domains: 4174210 (3542550 unique domains)`

The resuting gravity database size is hardly a deal breaker.

```
ls -lha /etc/pihole/gravity.db
-rw-rw-r-- 1 pihole pihole 283M Apr 12 10:13 /etc/pihole/gravity.db
```

If you reduced this size to the ratio of unique domains/total domains, that's 84.8% of the existing gravity database size, or a savings of 42 MB.  That's a trivially small amount, and in the exchange you lose all capability to do group management of adlists.
