### ISSUE TITLE
Bind9 and Pi-hole

### ISSUE THREAD

**Issue by gofret84** [pi-hole/pi-hole#2032]
Hello, i´m from Spain, i´ll try to explain in english my question.

I have the raspberry pi 3 with bind9 for DNS and to resolve my lan names, I installed the pi-hole, but i have problems with that. I have to uninstall bind9? I set in pi-hole the 127.0.0.1 for the forwarders, but isn´t resolve the problem. I hope that the problem was understood.

Thanks for all, and congratulations for the project, it´s amazing!

**Comment by PromoFaux** [comment]
Hi there, I appreciate there may be a language barrier, but we do ask that all issues use the provided template in order to help us understand the issue better.

As it happens, the best place for this question may be on our [Discourse user forums](https://discourse.pi-hole.net), or our [subreddit](https://reddit.com/r/pihole). The community are bound to have an answer for you!

> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by PromoFaux** [comment]
https://discourse.pi-hole.net/search?q=bind9
