### ISSUE TITLE
GLOBAL variables should be in caps

### ISSUE THREAD

**Issue by Gunni** [pi-hole/pi-hole#2062]
As commented here:
https://github.com/pi-hole/pi-hole/blob/1e87850952b6d886674b487f57e47fae1c20dc8a/automated%20install/basic-install.sh#L27

Look a few lines down, most of them are not...

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
