### ISSUE TITLE
PiHole not working with DNS Name

### ISSUE THREAD

**Issue by thomas41587** [pi-hole/pi-hole#2078]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Pi holoe should work regardless if the website is visited via IP-Address or DNS Name

**Actual behaviour:**

If I visit PiHole via my public IP-Address, everything works fine (see attached "expected" picture).
![expected](https://user-images.githubusercontent.com/15812394/38243594-4df728fc-3738-11e8-80a6-8d41d04587df.PNG)
But if I visit PiHole via my DNS Name I will get something different (see attached "issue" picture).
![issue](https://user-images.githubusercontent.com/15812394/38243604-536f6330-3738-11e8-846d-743314c2caf9.png)
It also looks like this affects the Adblocking itself. I cannot visit Amazon via the app as long as PiHole is active. The app will always show me a picture of a dog and tells me that something went wrong

The described behaviour affects only the 404 page. The Admin page works without any problems

**Comment by Mcat12** [comment]
Make sure you don't have port 53 open to the internet. The block page expects that if you see it, then you are also using Pi-hole as your DNS. Since it appears that you aren't, it can't find the CSS file (located under `http://pi.hole/`).

You probably can't use Amazon correctly because something it requires is blocked.

**Comment by thomas41587** [comment]
Thank you for your answer but I do not really understand your explenation.
Port 53 is not open to the internet. Only 80 and 443 are open.
Why does the block page work when trying to access it with either my public IP-Address (through port forwarding to the Raspberry Pi) or via the private IP-Address of the Pi? The only point where it does not work is when accessing it via the DNS name (that actually points to my public IP-Address). 
I struggled over this behaviour because this page will also be displayed if I try to access a page that does not exist on the webserver (in fact I serve several other services through lighttpd).
Does the malfordm page indicate that PiHole is not working properly or is this something totally different?

**Comment by Mcat12** [comment]
The block page expects that if you see it, then you are also using Pi-hole as your DNS. Since it appears that you aren't, it can't find the CSS file (located under `http://pi.hole/`). That is why it is malformed.
You are seeing two different block pages. One is shown when it detects you are accessing it over the IP address, the other when it thinks you are trying to access a blocked domain.
The block page is the 404 page.

**Comment by thomas41587** [comment]
Is there any way to make the 404 page work with DNS names?

**Comment by Mcat12** [comment]
It does work with domain names. You just are accessing it from an invalid location. Why do you want to see the block page when you're not using Pi-hole?

**Comment by thomas41587** [comment]
I think there is a little missudnerstanding here: I do use PiHole (as DNS and DHCP server). But I also have several other content hosted using lighttpd (owncloud, wordpress, filemanager, ....). And as the default PiHole configuration is to set a 404 page I would like to see a "nice" 404 page instead of this malformed thing when someone accesses a invalid path.

**Comment by Mcat12** [comment]
There should be a way to specify in the lighttpd config that certain domains have certain 404 pages (like a reverse proxy).

**Comment by nsteinmetz** [comment]
If it can help : my setup is  LAN <-> Router <-> 2 piholes (hosted on scaleway) as I need local dns resolution also.

Using ipfire as router, I set two hosts for pi.hole using my 2 public IPs of my scaleway server. From this time, the page appear as expected. Otherwise even if router is using pihole instances as dns, it failed to resolve pi.hole.

Using `dig @pihole1 pi.hole` works as expected but just `dig pi.hole` did not return any answer.

Blocked page now works as expected - just need to make it also available as https for manage HSTS sites that are now blocked.

**Comment by Mcat12** [comment]
The block page is not intended for use outside of your local network. If you do intend to use the webserver for external access, you can specify your own 404 page in `/etc/lighttpd/external.conf` or by making a custom block page at `/var/www/html/pihole/custom.php`.
