### ISSUE TITLE
Add Cloudflare DNS to options during install

### ISSUE THREAD

**Issue by ScottHelme** [pi-hole/pi-hole#2103]
Cloudflare announced their new, consumer DNS service:

https://blog.cloudflare.com/announcing-1111/
https://blog.cloudflare.com/dns-resolver-1-1-1-1/

It'd be great to see it as a choice during initial setup.

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by PromoFaux** [comment]
Also https://github.com/pi-hole/pi-hole/pull/2075

**Comment by dschaper** [comment]
Scott,

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

This is already in development: https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L827

**Comment by vmarks** [comment]
It's good to see that adding Cloudflare's IP to the options is in development, but it doesn't look as if DNS-over-HTTPS is in the section linked.

It appears as if this only adds 1.1.1.1 and 1.0.0.1 to the DNS options on the web gui. That doesn't take advantage of the real benefit cloudflare is providing here:

Full end-to-end Encrypted DNS queries via TLS/HTTPS, superior to the current options of DNSSEC or DNSCrypt, where DNSSEC doesn't encrypt DNS queries and DNS Crypt doesn't do it very well. 

more at: 
https://www.reddit.com/r/pihole/comments/89pi1j/how_to_implement_cloudflares_1111_dnsoverhttps_on/

**Comment by PromoFaux** [comment]
@vmarks indeed, but `dnsmasq` does not support DoH, so it's not something we're going to be able to add without a lot of work first.

There are already multiple places to discuss this, such as the thread you linked, and this feature request on discourse:
https://discourse.pi-hole.net/t/implement-dns-over-tls-capability-in-pi-hole/8722

Thank you
