### ISSUE TITLE
DietPI; every night, dnsmasq is enabled; pihole-FTL not running anymore.

### ISSUE THREAD

**Issue by mariusrugan** [pi-hole/pi-hole#2109]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**
pihole-FTL daemon is running flawlessly.

**Actual behaviour:**

Running on a Pi 2 B+; armv6l;
Pi-hole version is v3.3-75-g82d5afe (Latest: v3.3.1)
AdminLTE version is v3.2.1-123-g89090261 (Latest: v3.3)
FTL version is vDev-1ca6b58 (Latest: v3.0)
Running with dnscrypt-proxy
OS is DietPI

**Steps to reproduce:**
i have pihole-FTL enabled, everything runs smooth; around 1:30 AM webinterface reports loosing connection with API. 
I find out next morning dnsmasq service enabled (while i manually disabled it).
I have disabled all cron jobs except pihole updateGravity thinking this might be a update issue. No visible change.
I have disabled extensive logging with no visible change  ( ) 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**
[EDIT]

In order to have a functional service, i have to do manually:
`systemctl stop dnsmasq`
`systemctl disable dnsmasq`
`/etc/init.d/pihole-FTL start`

running manually `/usr/local/bin/pihole updateGravity` doesn't disable pihole-FTL;

**Comment by PromoFaux** [comment]
I wonder if this is something to do with how DietPi handles things, especially as you're manually disabling `dnsmasq`. You could possibly also try `mask`ing the service `systemctl mask dnsmasq` which should prevent it from being enabled again.

 @Fourdee , Do you have any thoughts on this? Have you've had a chance to do any testing with `FTLDNS` and DietPi?

**Comment by mariusrugan** [comment]
thanks for the very quick reply,
I am afraid `systemctl mask dnsmasq` would result into no dns service, at the end of all what is happening, but i will try of course.

**Comment by PromoFaux** [comment]
You're on the `FTLDNS` branch, right? If so, you _shouldn't_ lose the dns service...

**Comment by mariusrugan** [comment]
Yes, i am on `FTLDNS` branch, 
so, again, 
i'm looking at this in the morning, pihole-FTL is NOT running; dnsmasq is running, even disabled manually the previous day; to go back to pihole-FTL running and web interface running i have to execute manual steps: stop dnsmasq; disable dnsmasq; run init.d/pihole-ftl 

at first i thought it was some cron'd job from pi-hole involving pihole-FTL update so i disabled everything in `/etc/cron.d/pihole` but it seems no success;

**Comment by mariusrugan** [comment]
right, 
thanks, i've re-processed what you've wrote and makes sense to mask it;

> There is nothing in the Pi-hole code (that I can think of, and at least, not on the FTLDNS branch) that will ask for dnsmasq to be enabled and started
I will investigate the dietpi more thoroughly 'till we get to the bottom of this. 

> Do you have a nightly reboot cycle set or anything like that?
No. 
PI running DietPI is dedicated to pi-hole only and pretty much standard setup, didn't touch a lot.

**Comment by MichaIng** [comment]
Hey guys,

jep the issue with the new pi-hole FTLDNS and DietPi is the following:
- `pihole-FTL.service` is controlled by `dietpi-service` script instead of leaving it to systemd. `dnsmasq` is left to systemd, as it would break connection, when `dietpi-services` disables it prior to updates and other maintenance/installation jobs. But at least thus DietPi does not touch/start `dnsmasq` at all, which should therefore not be the issue.
- Since `dnsmasq` will be integrated into `pihole-FTL.service` (and is in this case), we need to leave it from now (at least after official FTLDNS release) to systemd as well. We are aware of this and are discussing the solution.
- To solve any potential issue @mariusrugan please uncomment the following line within your system: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-services#L160 Then do `systemctl enable pihole-FTL`.

But as you disabled all cron jobs, I am wondering, if `dietpi-services` really is the issue in your case. It does not run by itself, just on actual updates, backups or installations. You need to check your systemlog around the time, where pihole-FTL stops.
`journalctl` might help more than `/var/log/_`, as most logs are combined there, giving a better overview of what's going on.

We will further investigate as well.

**Comment by MattAKAFred** [comment]
@MichaIng 

> To solve any potential issue @mariusrugan please uncomment the following line within your system: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-services#L160 Then do systemctl enable pihole-FTL.

Just looking for some clarification here - that line is found in `/DietPi/dietpi/dietpi-services`, correct? In my system the line is already uncommented (there is no # before it, as in the source you linked). Do you want us to comment it out (add a #) or leave it as-is?

Either way, I have tried both approaches followed by `sudo systemctl enable pihole-FTL` and I still seem to be having nightly restarts. I need to also `sudo systemctl mask dnsmasq` for full effect.

Has further investigation found anything? Am I going about this all wrong?

**Comment by MichaIng** [comment]
@MattAKAFred 
Ah yeah sorry, I meant to comment the line. And for nighty restart, the following is the reason, thus also need to be commented: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-logclear#L171

Masking of course also works, but cleaner than all of that is to just `apt purge dnsmasq` so nothing can start it anymore ;).

**Comment by Mcat12** [comment]
It seems that v6.8 of DietPi may have solved this issue? @mariusrugan @MichaIng @MattAKAFred

**Comment by MichaIng** [comment]
@Mcat12 
Jep, we took `pihole-FTL` out of DietPi-Services control, like `dnsmasq` before, to assure FTLDNS compatibility.
As well on DietPi-Logclear (see above) we restart `dnsmasq` only, if it was enabled for systemd before. Otherwise FTLDNS is expected and `dnsmasq` will be ignored. Of course simply not installing/purging it, when using FTLDNS makes still sense to assure it cannot interact.
