### ISSUE TITLE
Remove Sentry

### ISSUE THREAD

**Issue by dcramer** [pi-hole/pi-hole#2121]
Sentry (``sentry.io``) is included in the following list:

https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

It seems the author of this list is misinformed, as they include it under

> ``# Block ads on Hotstar streaming app by @anudeepND``

Sentry is not an advertising or analytics service. Hotstar simply uses Sentry to log client-side issues.

This is problematic for software developers due to the sheer nature of JavaScript used these days. If you can't log errors in your client-side applications, you best case lose context for debugging issues and worst case any visibility that errors are even happening (and end up relying on twitter-ragefests).

References:

- https://sentry.io
- https://github.com/getsentry/sentry
- https://github.com/getsentry/raven-js

**Comment by PromoFaux** [comment]
> [You must follow the template instructions. Failure to do so will result in your issue being closed.](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md)

Also to note: We have no control over what is on the lists, you'll want to take it up with @StevenBlack as it is in his list.

Cheers

**Comment by StevenBlack** [comment]
@dcramer @PromoFaux sentry.io is like crashlytics, which we also block.  A pretty massive leak of workstation-specific information and other things.

Check docs.sentry.io under "Sensitive Data".  https://docs.sentry.io/learn/sensitive-data

This is opt-in.  Wide open to abuse.  I would say, anyone using our hosts file seeks protection against exactly this sort of thing.

**Comment by PromoFaux** [comment]
Something more related to Pi-hole itself...

The lists we provide as defaults are by no means the be all and end all of things, and we have always stressed that they are suggested only. Users are free to add/remove lists from their Pi-hole install as they please.

In an ideal world ,we would provide a bare bones blocker that the user has to configure completely themselves. However, the difficulty we have with not providing any lists at all is that it raises the barrier to entry, and inexperienced linux users may be scared off by having to source the blocklists for themselves, especially when they expect it to "just work" out of the box.

One way we have discussed to overcome this (and to avoid the politics that come along with "Pi-hole is blocking my domain! Fix this!" conversations), would be to disable all lists by default, and have users opt in to them on first install:
https://github.com/pi-hole/pi-hole/pull/2015

**Comment by StevenBlack** [comment]
Yeah, Adam @PromoFaux it's a tough call.  It's a constant concern for the hosts file, which is why we make variants for porn, social media etc, mixed in various ways.

I suppose we could do a 'Crash Reporting' variant.  But that would contain, what, a single-digit number of entries?

I'm always happy to talk about this and, regardless, it boils down to making choices that won't pease everyone.

**Comment by dcramer** [comment]
@StevenBlack IMO it would get bundled under "Application Monitoring" or "Developer Analytics" or something along those lines.

Here's a collection of things that may or may not fit there (though I'd probably pull Analytics into its own category).

- Crash Reporting (Sentry, Crashlytics)
- Analytics (this is a gray area obviously, Segment, Google)
- APM (New Relic, AppDynamics)
- Logging (not sure if anyones doing this as javascript-focused item)

**Comment by sadsfae** [comment]
Related: https://github.com/pi-hole/pi-hole/issues/2122 sentry.io really shoudn't be in here in my opinion @StevenBlack

**Comment by softwrx** [comment]
Coming into this late. As a developer I'd like the crash reporting to work. As someone concerned with privacy and the insane amount of tracking being done at this point, I'm all for blocking it. It's a massive scoop of information that can sucked up in the name of analytics and crash reporting. If someone really needs it to work on an ad hoc basis they can whitelist it manually in my opinion. It's very easy to see in the query log, complete with the whitelist button next to the entry.

I'm also ok, in general, with the idea of a separate list for this so it's easy to toggle as a set.  Though, I'm not sure a new category is a good idea because then the conversation becomes what should go in that category and some seem to collect more data and be more invasive than others, meaning not-so-bad actors might get mixed with more questionable ones. Tough call.

**Comment by dschaper** [comment]
We don't curate or control ad block lists. If there is a domain blocked that you feel should be accessible you are free to whitelist it or contact the list owner and ask for them to consider unblocking it.

**Comment by softwrx** [comment]
I agree. I like the lists as they are, and if something needs tweaked, it’s easy to whitelist as needed.
