### ISSUE TITLE
Cron error after reinstall 

### ISSUE THREAD

**Issue by fsantiago07044** [pi-hole/pi-hole#2135]
Source code familiarity = 1

On fedora 27, I had removed and then reinstalled pihole and ever since then my nightly Cron job for pihole:

Cron <root@localhost>    PATH="$PATH:/usr/local/bin/" pihole flush once quiet

Is throwing an error:

sed: can't read /etc/pihole/pihole-FTL.conf: No such file or directory

That file does not in fact exist. Should it? And if so, what happened to it? 

Thanks. My installation is up to date as is my os and all other package updates.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
