### ISSUE TITLE
Some pages are not shown in query log

### ISSUE THREAD

**Issue by cristimiha** [pi-hole/pi-hole#2170]
Hello,
I observed that on a specific page I can see ads that on other pages are not visible so I went to the query log and searched for the domain I was visiting. Some visits are visible, some visits are not visible. I blacklisted the domains that are opened in the same time when I visit the page, then i refresh the page, and the ads are visible. I go again in the query log page and i cannot see the recent visit to the page.

Any idea?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
