### ISSUE TITLE
Block page failure - queryads.php: Connection timeout

### ISSUE THREAD

**Issue by KnightTim** [pi-hole/pi-hole#2172]
**In raising this issue, I confirm the following:** 

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
3

---
**Expected behaviour:**

When going to a blocked site I expect to see the block page 
![image](https://user-images.githubusercontent.com/858797/39794521-6033812a-5310-11e8-8439-e43a805a9fde.png)

**Actual behaviour:**

When I go to a blocked site I see: 
"[ERROR]: Unable to parse results from queryads.php: Connection timeout (3s)" 
![image](https://user-images.githubusercontent.com/858797/39794732-78b3afb2-5311-11e8-825f-d08bd3a3a160.png)

**Steps to reproduce:**

Setup pi-hole on a RasPi model B gen 1 with a large number of blocked domains ~2.9mil or more. Then visit a blocked page. 

**Troubleshooting undertaken, and/or other relevant information:**

To fix the issue locally I have edited pi-hole/advanced/index.php 
(stored locally: /var/www/html/pihole/index.php) 
I changed line 127 
from: `ini_set("default_socket_timeout", 3);`
to: `ini_set("default_socket_timeout", 7);`

As I am unfamiliar with the code base this is a bandaid, and I don't know if my fix could cause other issues.

**Comment by Amunak** [comment]
In my case the same issue boils down [to this line](https://github.com/pi-hole/pi-hole/blob/v3.3.1/advanced/index.php#L133) in index.php:

`$queryAds = file("http://127.0.0.1/admin/scripts/pi-hole/php/queryads.php?domain=$serverName&bp", FILE_IGNORE_NEW_LINES);`

For whatever reason there's hardcoded IP address of the server even though there's almost no reason to do that, and it fucks with more complicated setups that don't pass *everything* to the pihole web interface. The fix, to me, was to just put `$serverName` there instead of the IP address.

Or, if I cared enough, it'd be better to find out how to get the proper pihole server address and put that there if possible.

**Comment by dmblack** [comment]
Confirmed. I'm also experiencing this issue on a raspberry pi 2 model b

```
Hardware	: BCM2835
Revision	: a01041
Serial		: 00000000bf736934
```

I, too, have a large list of domains blocked.

Suggestion by @Amunak did provide a workaround. >.< Perhaps I'll get time to contribute.

**Comment by Mcat12** [comment]
With v4.0, the 0.0.0.0 response is expected because the default blocking method was changed to NULL blocking:
https://pi-hole.net/2018/08/06/pi-hole-v4-0-released-with-ftldns-improved-blocking-modes-regex-docker-and-more/

**Comment by dmblack** [comment]
@Mcat12 Thanks for that. I had a feeling this was the case.

The only reason I continued to investigate was;
* Multiple errors on upgrade (from 3 > 4)
* Website Blocked page still exists

For all those in a similar position re null blocking; https://docs.pi-hole.net/ftldns/blockingmode/

**Comment by dschaper** [comment]
Appears resolved.
