### ISSUE TITLE
DNS resolution fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by RlndVt** [pi-hole/pi-hole#2179]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

Working pihole

**Actual behaviour:**

Install on (l)ubuntu 18.04 fails to activate DNS resolution. Installation fails on:

`[✗] DNS resolution is currently unavailable`

Need to manually change the nameserver in `/etc/resolv.conf` to 127.0.0.53 to regain DNS resolution. 

This allows for normal internet on the machine, but the pihole DNS resolution still doesn't work and cannot be started.

**Steps to reproduce:**

Standard/default installation options. 

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`62rwn2e69i`

**Troubleshooting undertaken, and/or other relevant information:**

**Comment by rrobgill** [comment]
A more complete solution is to stop resolved from binding to port 53 (dnsmasq/ftl and resolved can't share the same port).  #2180 

This allows pihole dns resolution to work correctly (both for host and also other machines on the network) and allows normal internet connectivity on the host machine.

**Comment by RlndVt** [comment]
Fwiw, with systemd-resolved stopped and/or with "DNSStubListener=no", dnsmasqd will not enable.

```
~ sudo systemctl stop systemd-resolved 
~ ping google.com
ping: google.com: Temporary failure in name resolution
~ sudo systemctl start dnsmasq.service   
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
```

With the same error, being unable to bind to port 53.

**Comment by DL6ER** [comment]
> `See "systemctl status dnsmasq.service" and "journalctl -xe" for details.`

What do these outputs say @RlndVt ?

**Comment by RlndVt** [comment]
It reported the same error as previous, that port 53 was bound.

In the mean time I've managed to screw things up further on my end while testing things. (127.0.0.53 in resolv.conf doesn't work anymore with or without DNSStubListener
 enabled, don't know what is going wrong...)

**Comment by rrobgill** [comment]
@RlndVt I suspect one or more of your configuration files have wound up with invalid settings as things have changed back and forth. Or for some reason resolved has not reloaded its configuration files after they have changed.

If you could please try the following steps:

- Restore /etc/resolve.conf to its initial default state - contains:
nameserver 127.0.0.1

- Check that /etc/systemd/resolved.conf contains
DNSStubHandler=no

- Force a reload of all of systemd's configuration files
sudo systemctl reload-or-restart systemd-resolved

- Repair Pi-hole (to ensure dnsmasq's config files are correct)
pihole -r

Then, if you could please report the output of
systemctl status dnsmasq.service systemd-resolved

Should they not both be running, if you could please try:
sudo systemctl daemon-reload

- then once again
pihole -r 

and once again, please report the output of 
systemctl status dnsmasq.service systemd-resolved


Systemd-resolved and dnsmasq.service can coexist quite happily so long as resolved lets go of port 53. Once your config files are correctly restored, your output should look something like this, taken from a working pi-hole install on bionic.

#systemctl status dnsmasq.service systemd-resolved
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-05-18 07:10:40 AEST; 5min ago
  Process: 860 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 825 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 801 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 854 (dnsmasq)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/dnsmasq.service
           └─854 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,19036,8,2,49aac11d7b6f6446702e54a1607371607a1a4

May 18 07:10:40 bionicbox systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
May 18 07:10:40 bionicbox dnsmasq[801]: dnsmasq: syntax check OK.
May 18 07:10:40 bionicbox systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

● systemd-resolved.service - Network Name Resolution
   Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-05-18 07:10:39 AEST; 5min ago
     Docs: man:systemd-resolved.service(8)
           https://www.freedesktop.org/wiki/Software/systemd/resolved
           https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
           https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
 Main PID: 382 (systemd-resolve)
   Status: "Processing requests..."
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/systemd-resolved.service
           └─382 /lib/systemd/systemd-resolved

May 18 07:10:37 bionicbox systemd[1]: Starting Network Name Resolution...
May 18 07:10:39 bionicbox systemd-resolved[382]: Positive Trust Anchors:
May 18 07:10:39 bionicbox systemd-resolved[382]: . IN DS 19036 8 2 49aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb5
May 18 07:10:39 bionicbox systemd-resolved[382]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
May 18 07:10:39 bionicbox systemd-resolved[382]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr
May 18 07:10:39 bionicbox systemd-resolved[382]: Using system hostname 'bionicbox'.
May 18 07:10:39 bionicbox systemd[1]: Started Network Name Resolution.
`

Debug:

**Comment by RlndVt** [comment]
To add, this is not a server ubuntu installation,  so network-manager is also used which, if I'm not mistaken, starts it's own version of dsmasq (on 127.0.1.1).

But I did try your advice. I included the last line of `pihole -r` failing.

```
  [i] Starting dnsmasq service...%
➜  ~ cat /etc/resolv.conf                             
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
# 127.0.0.53 is the systemd-resolved stub resolver.
# run "systemd-resolve --status" to see details about the actual nameservers.

nameserver 127.0.1.1
nameserver 127.0.0.1
search fritz.box
➜  ~ cat /etc/systemd/resolved.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#Cache=yes
DNSStubListener=no
➜  ~ sudo systemctl reload-or-restart systemd-resolved
➜  ~ sudo systemctl start dnsmasq                     
Job for dnsmasq.service failed because the control process exited with error code.
See "systemctl status dnsmasq.service" and "journalctl -xe" for details.
➜  ~ sudo systemctl status dnsmasq                   
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-05-18 10:24:53 CEST; 57s ago
  Process: 16977 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 16976 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 9738 (code=exited, status=0/SUCCESS)

mei 18 10:24:52 SPHJ-PC systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
mei 18 10:24:52 SPHJ-PC dnsmasq[16976]: dnsmasq: syntax check OK.
mei 18 10:24:53 SPHJ-PC dnsmasq[16977]: dnsmasq: failed to create listening socket for port 53: Address already in use
mei 18 10:24:53 SPHJ-PC dnsmasq[16977]: failed to create listening socket for port 53: Address already in use
mei 18 10:24:53 SPHJ-PC dnsmasq[16977]: FAILED to start up
mei 18 10:24:53 SPHJ-PC systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
mei 18 10:24:53 SPHJ-PC systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
mei 18 10:24:53 SPHJ-PC systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
➜  ~ sudo lsof -i :53                               
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 5890 nobody    4u  IPv4  52121      0t0  UDP SPHJ-PC:domain 
dnsmasq 5890 nobody    5u  IPv4  52122      0t0  TCP SPHJ-PC:domain (LISTEN)
➜  ~ sudo lsof -i @127.0.1.1:53                       
COMMAND  PID   USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
dnsmasq 5890 nobody    4u  IPv4  52121      0t0  UDP SPHJ-PC:domain 
dnsmasq 5890 nobody    5u  IPv4  52122      0t0  TCP SPHJ-PC:domain (LISTEN)
```

And another debug token fwiw: ig0kb151lz

**Comment by RlndVt** [comment]
Ok after killing the task running dnsmasq, the dnsmasq service started and this seems to persist after reboot.

So imo rrobgill's #2180 seems like the proper fix.

**Comment by rrobgill** [comment]
@RlndVt Glad to hear that got it all working.

I have two more questions to trouble you with, if I may, so that I can run a few more tests.

In your report you mentioned (l)ubuntu - can you please tell me are you running lubuntu or ubuntu?
Also, was your installation a completely new install from the 18.04 .iso, or an upgrade from a prior version (and if so which version)?

**Comment by RlndVt** [comment]
Lubuntu, upgraded from 17.10.

**Comment by rrobgill** [comment]
Just an update on the 17.10 -> 18.04 upgrade path that I've also investigated at since RIndVt's feedback.

From a dns perspective, these systems are in the same situation as a clean 18.04 install, or an update from prior LTS versions 14.04 -> 16.04 -> 18.04. 

Systemd-resolved's dns stub handler is enabled.
Dnsmasq is neither active nor installed.
Desktop systems in each case also have network-manager installed.

Of course, if other software has been installed along the way which changes the networking settings at some point along the way, then the situation could be quite different. This could conceivably include prior installations of pi-hole under the older ubuntu versions.

**Comment by Lewiscowles1986** [comment]
Just a note on this, if you turn off resolv daemon, you need to have dnsmasq or you can't reach out to named services. I'm sure this is a broken config from debian / ubuntu folks
