### ISSUE TITLE
Add Support for DNS Cookies

### ISSUE THREAD

**Issue by killamjr** [pi-hole/pi-hole#2197]
This is a feature request: Add support for DNS Cookies for more secure DNS requests.

A good article regard DNS cookies:
https://isc.sans.edu/diary/DNS+is+Changing.+Are+you+Ready%3F/23711

Benefits:
Makes DNS cache poisoning very difficult
Prevent Spoofed DNS

**Comment by PromoFaux** [comment]
From the issue template:

----
> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.

----
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.
