### ISSUE TITLE
Request to increase localization

### ISSUE THREAD

**Issue by yyingc** [pi-hole/pi-hole#2228]
I am using pi-hole
But I come from other countries and want to provide localization.
I can translate for my country language

**Comment by dschaper** [comment]
See https://poeditor.com/projects/view?id=66305

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by yyingc** [comment]
Chinese (simplified)

**Comment by yyingc** [comment]
https://crowdin.com/project/pi-hole/zh-CN
The Chinese language has been translated. I hope to add the next version. Thank you for your project. It's great.
