### ISSUE TITLE
Statistics on MAC address instead of IP address

### ISSUE THREAD

**Issue by chscherrer** [pi-hole/pi-hole#2241]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`In the Dash-Board and elsewhere, logs and statistics should be produced on basis of MAC addresses instead of IP addresses. 
Modern mesh Wi-Fi like Google Wi-Fi or Netgear Orbi or Unifi Mesh to name a few do not allow for Pi-Hole to use DHCP. Therefore, all Wi-Fi statistics are condensed in one IP address (the one of the Wi-Fi router).`

**Actual behaviour:**

`All traffic of all different Wi-Fi devices are condensed within one IP address`

**Steps to reproduce:**

`Use Pi-Hole with any modern mesh Wi-Fi system.`

Would be fantastic if I were allowed to label MAC addresses with names; so these names would pop up within the statistics.

Thanks for helping me with this.

**Comment by Mcat12** [comment]
The router that requests DNS resolution from the DNS server will still have the same MAC address even though there are many clients behind the router making the request. What differentiates the requests from client to client?

**Comment by rrobgill** [comment]
For this to be even somewhat achieved under these feature-limited networks, would be really really difficult.

You'd need to be monitoring all traffic on the network, in order to capture DNS query packets inbound to the router, store the mac making the request then somehow line it up with the matching DNS request once the router eventually forwards it to the pi-hole. Also dealing with duplicate packets in a wireless environment, and potentially queries for the same hostname arriving out of order from multiple network clients. This is even assuming that such capture (promiscuous mode on a mesh network, successfully capturing all packets for a specific destination) is even technically plausible with the sort of wireless hardware people will be using with the pi.

**Comment by rebroad** [comment]
@rrobgill Technically this could be done without monitoring all traffic on the network as dnsmasq is dealing with both DHCP and DNS it already knows the MAC addresses per IP address and so could easily log the MAC address instead of the IP address, and pi-hole would then easily use this instead. It would require some modification to dnsmasq though.  Given pihole-FTL functions without dnsmasq then I'm guessing that somehow dnsmasq has been incorporated into pihole-FTL, so the code changes should be minimal and part of the pihole source code, if my assumption is correct.
