### ISSUE TITLE
Flushing logs flushes /var/log/pihole.log but not /var/log/pihole.log.*

### ISSUE THREAD

**Issue by notDavid** [pi-hole/pi-hole#2272]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

Flushing the logs by issuing `pihole flush` should delete all pihole logs:
1. /var/log/pihole.log
2. /var/log/pihole.log.x
3. /var/log/pihole.log.x.gz

**Actual behaviour:**

Only 1. `/var/log/pihole.log` is deleted.

**Steps to reproduce:**
1. `ls -la /var/log/pihole*`
```
-rw-r--r-- 1 pihole           pihole     71635 Jul 10 20:47 pihole.log
-rw-r--r-- 1 pihole           pihole       766 Jul 10 20:47 pihole.log.1
-rw-r--r-- 1 pihole           pihole   1799297 Jul 10 20:46 pihole.log.2.gz
-rw-r--r-- 1 pihole           pihole       187 Jul 10 13:56 pihole.log.3.gz
-rw-r--r-- 1 pihole           pihole       293 Jul 10 13:56 pihole.log.4.gz
-rw-r--r-- 1 pihole           pihole     51675 Jul 10 13:56 pihole.log.5.gz
```
2. `pihole flush`
3. `ls -la /var/log/pihole*`
```
-rw-r--r-- 1 pihole           pihole         0 Jul 10 20:47 pihole.log
-rw-r--r-- 1 pihole           pihole       766 Jul 10 20:47 pihole.log.1
-rw-r--r-- 1 pihole           pihole   1799297 Jul 10 20:46 pihole.log.2.gz
-rw-r--r-- 1 pihole           pihole       187 Jul 10 13:56 pihole.log.3.gz
-rw-r--r-- 1 pihole           pihole       293 Jul 10 13:56 pihole.log.4.gz
-rw-r--r-- 1 pihole           pihole     51675 Jul 10 13:56 pihole.log.5.gz
```

As seen above, only pihole.log is empty / 0 size.

**Version info**

*** [ DIAGNOSING ]: Core version
[i] Core: v3.3.1 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: FTLDNS (https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout)
[i] Commit: v3.3.1-136-ga7e7680

*** [ DIAGNOSING ]: Web version
[i] Web: v3.3 (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)
[i] Branch: FTLDNS (https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#checkout)
[i] Commit: v3.3-130-g4355bde

*** [ DIAGNOSING ]: FTL version
[✓] FTL: vDev-5ecab0a (https://discourse.pi-hole.net/t/how-do-i-update-pi-hole/249)

*** [ DIAGNOSING ]: dnsmasq version
[i] 2.75

*** [ DIAGNOSING ]: lighttpd version
[i] 1.4.35

*** [ DIAGNOSING ]: php version
[i] 7.2.7

*** [ DIAGNOSING ]: Operating system
[✓] Ubuntu 16.04.4 LTS

**Comment by dschaper** [comment]
Flush was meant to clear out the working memory for the logs. I can see that both `pihole.log` and `pihole.log.1` should probably be cleared since those are the files that are read in to memory. But I don't think we would delete the *.gz files. This is all going to be changing soon as we modify the logging process so it may not be an issue in the future.

**Comment by sh2d** [comment]
I may be missing something, but I'm (mis-?)using the LAN-wide public dashboard available at http://pi.hole/admin as a proof to clients that logging DNS queries is indeed disabled in pihole.  Ideally, the dashboard looks like this

    Total queries (0 clients)  Queries blocked  Percent blocked  Domains on Blocklist
    0                          0                0.0%             132,285


However, the information presented there doesn't work as a reliable non-logging proof for me.  After running some tests with logging enabled, I disabled logging flushing logs, but dashboard still showed non-zero numbers.  Only after removing old logs manually, dashboard showed all-zero numbers here as expected.  If an administrator doesn't know/expect/notice that, this may degrade client's trust in the local administrator.

When are non-zero numbers shown in dashboard with logging disabled and logs flushed? _Complete guesswork:_ Computing dashboard information involves old logs in `/var/log/pihole.log.<n>.gz` that are not removed when flushing logs as discussed in this bug.

If this reasoning does make sense, this bug is not a purely technical issue, but has social implications (degradation of client's trust).

If this reasoning doesn't make any sense, what means are there to proof to clients logging is disabled in pihole?

**Comment by Mcat12** [comment]
You can not use the dashboard as proof that logging is disabled, because you could just turn off FTL or modify the PHP API code to return empty data instead of the logged data.

We do not use any of the zipped logs when getting stats. How long did you wait before deleting those other files? You could have just not waited long enough for everything to be flushed. Also, with FTLDNS this issue would be impossible as it does not use the logs anymore.

**Comment by sh2d** [comment]
Thanks for making clear dashboard won't work a non-logging proof!  I'm actually using pi-hole just since two weeks.  Back to reading the docs.

Can't say exactly how long I waited before deleting files.  Could have been anything between 15 min and 2 hours.  But I did wait a while and searched and found this bug before deleting files.

So, does pi-hole provide any such means as a non-logging proof?  (Assuming honest administrators.)

**Comment by technicalpyro** [comment]
based on the documentation here https://docs.pi-hole.net/ftldns/privacylevels/ setting level 4 in your `/etc/pihole/pihole-FTL.conf` file SHOULD accomplish what you are looking for

**Comment by dschaper** [comment]
@pi-hole/core-approvers Is this a bug that needs to be fixed or working as intended. I don't have a preference either way.

**Comment by Mcat12** [comment]
For such an easy action, I don't think it should clear everything that has been logged. Currently, we only flush the last 24 hours, so the effect is that the are no queries to be shown in the default views.

**Comment by dschaper** [comment]
Reading this over again, there's two issues here. The main issue to me is what flush should do. And I think it should do exactly what it does now and not delete history, only flush the working memory.

The second and unrelated issue is proof of non-logging. We'll never offer that nor should any user blindly accept anything other than direct knowledge of the backend.
