### ISSUE TITLE
Failure! Something went wrong. ".loan" is not a valid domain

### ISSUE THREAD

**Issue by yratof** [pi-hole/pi-hole#2293]
Just had a site redirect me to a spam site with a new TLD - `.loan`

```
Failure! Something went wrong.
http://*.loan is not a valid domain`
```
It might be worth loosening validation on TLDs if spam sites are using newer ones?

**Comment by Mcat12** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
