### ISSUE TITLE
Conditional Forwarding doesn't determine the names of all devices, pi-hole server occurs twice

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/pi-hole#2332]
Some devices have correct names some are just IPs
![image](https://user-images.githubusercontent.com/37550896/43784574-b75cbc28-9a64-11e8-8de5-ba8126a8bcbd.png)
![image](https://user-images.githubusercontent.com/37550896/43784621-d1a6919e-9a64-11e8-9e49-16eb7ced24be.png)

10.8.0.6 is correctly not determine because this is vpn client ip and router doesn't return its name.

**Also pi-hole server occurs twice in client table, as localhost and as hostname (raspberrypi)**

**Comment by DL6ER** [comment]
Please hover your mouse above the duplicated entries as well as `raspberrypi` and `localhost`.

What are the IP addresses you see?

If your clients request DNS using both, their IPv4 and IPv6 addresses, then they are technically two separated devices and hence are shown twice. The mere equality of host names is not a necessary criterion for them being the same physical device.

**Comment by guinhas** [comment]
Hi,
I believe before FTL was introduced that my Top Clients list showed hostnames instead of ip addresses. I think that hostnames disappeared around the time FTL was introduced but I was still able to reach my local machines through the hostnames, they just didn't appear in the lists (only ip shown). With 4.0 I wasn't able to reach my machines through hostname, but after configuring conditional forwarding it was working again, but still no hostnames in the Clients list. I never configured a host file because when everything was working, my pi-hole's ipv4 and ipv6 upstream dns servers were my router ip addresses and pi-hole, somehow, got the hostnames from my router. I tried many different configurations, like disabling "Never forward non-FQDNs" and "Never forward reverse lookups for private IP ranges", but since FTL I can't get it to work... My router is a turris omnia with knot-resolver as dns without forwarding to my isp dns servers and pi-hole is installed in an lxc container. I am using dnssec because I have it enabled in knot-resolver and my local domain name is lan. What am I doing wrong? Thank you very much for you work.

**Comment by Mcat12** [comment]
Have you tried restarting FTL (`sudo service pihole-FTL restart`)? Once you change those settings, it has to re-resolve the hostnames.

It looks like you already have client hostnames getting resolved (`.home` addresses). It looks like your issues are just due to your networking and not Pi-hole.

**Comment by Haxy89** [comment]
Problem is my router. It does not resolve all hostnames. I dont know why.

![image](https://user-images.githubusercontent.com/37550896/43989182-2dcc7352-9d45-11e8-960c-d8dbde4a9cc2.png)

**Comment by Mcat12** [comment]
Possibly the clients did not return a  hostname for the router to use, but either way it is an external issue.
