### ISSUE TITLE
CentOS Version Check Fails on ARM

### ISSUE THREAD

**Issue by Firehwk** [pi-hole/pi-hole#2365]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

Basic-install.sh properly detects CentOS version and installs Pi-Hole

**Actual behaviour:**

Basic-install.sh does not detect CentOS version and fails.

The following rpm command fails with the error "package centos-release is not installed"
https://github.com/pi-hole/pi-hole/blob/ddbdb51d209fa9eea2451a1bebfaeaef23a9b77b/automated%20install/basic-install.sh#L257

**Steps to reproduce:**

Attempt to install Pi-Hole on CentOS 7.5 Raspberry Pi 3 image.

**Troubleshooting undertaken, and/or other relevant information:**

Replacing "centos-release" with "centos-userland-release" correctly detects the version on the Raspberry Pi.

After testing, replacing the rpm -q check with `rpm -qa --queryformat '%{VERSION}' centos-\*release` returns "7" on both CentOS 7.5.1804 x86_64 and CentOS 7.5.1804 armhv.

**Comment by rrobgill** [comment]
I don't have any arm systems running centos, but can confirm that your patch still works as expected on x86_64.

Would you like to submit a pull request with your proposed patch?

**Comment by bcambl** [comment]
Your proposed change would break all non-userland CentOS distros.  
The repositories you linked are the test/development repositories. I would prefer to wait until CentOS releases the stable repos before officially supporting CentOS on ARM.  Do you know when the repositories will be marked stable?  
I will look at modifying the CentOS check mentioned in this issue so that it will pass for userland without affecting non-userland.  

We currently have an outdated [wiki article](https://github.com/pi-hole/pi-hole/wiki/CentOS-and-RPi3) for userland that could use an update.  
Would you be interested in helping me update this article?
