### ISSUE TITLE
Know if you can add the function of local.list!

### ISSUE THREAD

**Issue by ceozero** [pi-hole/pi-hole#2399]
![image](https://user-images.githubusercontent.com/22513657/44915199-f4313300-ad64-11e8-88ab-c0de8917592e.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
