### ISSUE TITLE
Using non-wildcard list

### ISSUE THREAD

**Issue by Esmala** [pi-hole/pi-hole#2403]
Hi, i just downloaded a list with over 2 million addresses on it. It's pretty much impossible to manually convert the list to fully cover all domain sub addresses. Is there anything i can do to make PiHole read the list as wildcard. Thank you!

**Comment by dschaper** [comment]
Please see https://discourse.pi-hole.net for discussions on how to use the Pi-hole software.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
