### ISSUE TITLE
Pi-hole blocks domain.com but does not block www.domain.com

### ISSUE THREAD

**Issue by Haxy89** [pi-hole/pi-hole#2412]
I am using this list https://raw.githubusercontent.com/chadmayfield/pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list to block porn site in my local network.

Pi-hole blocks site when using sitedomain.com but does not work when using www.sitedomain.com

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
