### ISSUE TITLE
Can't login via SSH

### ISSUE THREAD

**Issue by geeflaxx** [pi-hole/pi-hole#2414]
Hey,
long time i did nothing for pi hole, now i want to update it.
My issue is, that i forgot my login data, what can i do ?

i only know the login data for the webinterface.

greece

**Comment by Mcat12** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

You most likely have not changed your user/pass. The default for Raspbian is pi/raspberry
