### ISSUE TITLE
Installer does not verify OS requirements

### ISSUE THREAD

**Issue by dustball** [pi-hole/pi-hole#2423]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

When attempting an install on Debain 7 (not supported), the installer should either raise an error or warn about the unsupported OS.

**Actual behaviour:**

The installer seems to work, reaches 100% and quits without an error message.

It does in fact run into many fatal errors, the package dns-root-data doesn't even exist on deb 7 for example.

**Comment by dschaper** [comment]
Thanks for the report. I'd be okay with warnings displayed, but since we can't really cover all the various distributions and versions it's hard to have a hard list of supported distributions. I think the better option would be to have hard dependency requirements and if the dependencies can not be fulfilled then the installer will not continue. 

I've been wanting to work on the installer and do a major overhaul on how it works but I've just not had the time to begin work on it with my real day work taking some much of my time the last few months.

**Comment by dustball** [comment]
That makes sense.

Thank you for your hard work on the project.   I reimaged my CF card with a new release and things are working great.
