### ISSUE TITLE
Nginx configuration - Missing line to replace

### ISSUE THREAD

**Issue by Rumpick** [pi-hole/pi-hole#2457]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`I should be able to follow the instructions at https://github.com/pi-hole/pi-hole/wiki/Nginx-Configuration without issue.`

**Actual behaviour:**

`Step 12 (7) details to replace a line that isn't actually in the specified file.`

**Steps to reproduce:**

`Attempting to follow Step 13 (step 7 once the counting resets), it says to replace `$serverName = escapeshellcmd($_SERVER['SERVER_NAME']);` with something else but this line isn't actually present in https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`N/A`

**Troubleshooting undertaken, and/or other relevant information:**

`I tried to comment out the existing $serverName = htmlspecialchars($_SERVER["HTTP_HOST"]); line and replace it with the desired line, but this didn't seem to work. I also updated /etc/pihole/pihole-FTL.conf to BLOCKINGMODE=IP in order to confirm that the blocking page wasn't being displayed for a known blacklisted domain. I just got a 500 error instead, after passing the .htaccess, which shouldn't be occurring when not going to /admin anyways,`

**Comment by dschaper** [comment]
The wiki pages are community supplied and maintained, they are not produced or edited by the Pi-hole development team.

**Comment by Toakan** [comment]
The line to replace is Line 10 : https://github.com/pi-hole/pi-hole/blob/master/advanced/index.php

On your host machine it is found under `/var/www/html/pihole/index.php` (Unless specified otherwise).

Please note the last line of that guide, you appear to be trying to overwrite the line that is present by default with the same line.
`(HTTP_HOST is already used in current version of pi-hole)`

**Comment by dschaper** [comment]
Thank you, feel free to edit the Wiki page with the correct information if you'd like.

**Comment by Toakan** [comment]
Changed as recommended @dschaper.

**Comment by PromoFaux** [comment]
FWIW: I think we should probably look at porting these wiki pages over to https://github.com/pi-hole/docs

The wiki pages are a great source for community developed guides, but anyone can change them at any time, with no review process.  If we disable the wiki and keep them to the docs page (things like this can go under the `guides` subheading) then there is at least a review process, so that we can ensure nothing malicious gets updated.

Just my 2c!

**Comment by Toakan** [comment]
Is there a way to disable Wiki write access? 

Linking back to those documents in the https://github.com/pi-hole/docs from the wiki, rather than disabling the wiki, at least gives users easier access?

**Comment by Toakan** [comment]
Can you close this issue? Wiki doc has been submitted for PR - https://github.com/pi-hole/docs/pull/62
