### ISSUE TITLE
After whitelist PiHole stops blocking ads

### ISSUE THREAD

**Issue by 07stuntar1** [pi-hole/pi-hole#2461]
Hi, I recently realized all the photos posted on engadget.com are being blocked by pi hole. I couldn't figure out which Domain was hosting the photos. I tried to whitelist the last one and for some reason after hitting the whitelist button the pictures start to load like normal. But I started to realized no ads are being blocked anymore off any site. I remove it from the whitelist and still nothing gets blocked. Only way to fix the problem was to restore pi-hole. Any Ideas?

Pi-hole Version v4.0 Web Interface Version v4.0 FTL Version v4.0

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
