### ISSUE TITLE
Make redirect IP configurable

### ISSUE THREAD

**Issue by kuro68k** [pi-hole/pi-hole#2542]
BLOCKINGMODE offers a number of options to handle blocked domains, but none allow for redirection to a custom IP address. This would be helpful for blocking ads on certain services such as YouTube.

I suggest adding a new BLOCKINGMODE option that supports a configurable IP address. Although it is possible to redirect specific domains already, it is not possible to do a global redirect or to use FTLDNS regex matches with redirection.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
