### ISSUE TITLE
[Question] Are FTLDNS and Unbound the same thing ? 

### ISSUE THREAD

**Issue by prog-amateur** [pi-hole/pi-hole#2549]
Hello, first of all, sorry to post a question as an "issue" in this github. 

I would like to install Pi-hole, and reading the blog, something remains unclear to me : are unbound and FTLDNS the same thing? 

I read an article that refers to the [installation of Unbound in parallel with pi-hole](https://pi-hole.net/2018/06/09/ftldns-and-unbound-combined-for-your-own-all-around-dns-solution/) (the title says _"FTLDNS and Unbound Combined"_, then a few months later, there is this article saying that FTLDNS which is supposed to do exactly the same as Unbound (DSN resolver) [is directly integrated with pi-hole 4.0](https://pi-hole.net/2018/08/06/pi-hole-v4-0-released-with-ftldns-improved-blocking-modes-regex-docker-and-more/). 
And since that article, I can't see no more mention of Unbound anywhere. 

I probably misunderstood. 

Have you just renamed the Unbound function as "FTLDNS" or are the two complementary? 
How easy is to set-up both of them ? 

Thank you very much for your kind help !

**Comment by dschaper** [comment]
Hi, you'll probably get a better and quicker answer to your question on our Discourse forum rather than here with GitHub Issues. 

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by prog-amateur** [comment]
OK : I have posted a topic in discourse, which is pending approval by an admin (I was not aware about this site, sorry).

**Comment by dschaper** [comment]
Thanks!
