### ISSUE TITLE
Active DHCP leases list doesn't show proper MAC address

### ISSUE THREAD

**Issue by LGro** [pi-hole/pi-hole#2569]
Pi-hole Version v4.1.1  
Web Interface Version v4.1.1  
FTL Version v4.1.2  

After enabling the DHCP server on my pi-hole and pointing my fritz.box to the pi-hole as custom DHCP server, I get correct MAC address listings for the IPv4 leases but I'm doubtful about the MAC addresses for the IPv6 leases (9 digit integers).

![pihole_dhcp_ipv6_error](https://user-images.githubusercontent.com/4706479/50561985-70865380-0d10-11e9-861b-101a04d7b4d5.png)

**Comment by dschaper** [comment]
https://en.wikipedia.org/wiki/DHCPv6#DHCP_Unique_Identifier

**Comment by LGro** [comment]
Thanks for the pointer. Do I then understand correctly that there is no way for me to assign a name to an IPv6 device via the "Static DHCP leases configuration"?

**Comment by dschaper** [comment]
There are a number of potential issues with trying to assign a name to an IPv6 lease. The client may be using privacy extensions and the DUID can change rather frequently, or the client can send differing DUIDs depending on it's current and changing configuration. @DL6ER if the conditions are set on the network so that there is a predictable DUID would name > DUID mappings work?

**Comment by DL6ER** [comment]
The first name trumps. When you try to add two names for the same IP address, `dnsmasq` will simply discard the second PTR request.

I'm not exactly sure what your question is
> if the conditions are set on the network so that there is a predictable DUID would name > DUID mappings work?

if you could give some more information, I can give a more accurate answer.

**Comment by dschaper** [comment]
If a network has security extensions disabled and the DUID of each client is known and will not change, can you use the DUID as the identifier for the IPv6 lease? (DUID in place of MAC for IPv6 isntead of IPv4)

**Comment by DL6ER** [comment]
Quoting the `dnsmasq` man page:

> It is allowed to use client identifiers (called client DUID in IPv6-land) rather than hardware addresses to identify hosts by prefixing with 'id:'. Thus: `--dhcp-host=id:01:02:03:04,.....` refers to the host with client identifier `01:02:03:04`.

**Comment by DL6ER** [comment]
I should also mention that setting this though the web interface is not supported at the moment. My personal feeling is that we should not make it "easy" to set static leases for IPv6 because any central management of IPv6 is probably a bad idea and users only wants to do this because they do so with their IPv4 network. However, IPv6 networks are conceptually completely different and don't need a central managing unit like a DHCP server.

**Comment by dschaper** [comment]
I concur, DHCPv6 is typically not the best solution to a network management issue.

**Comment by truehomie** [comment]
wassup folks, 

how i can change/renew/refresh/reset/modify my DUID client DHCPv6 ??? 
after i changed my MAC address it consists of two parts : my new MAC address + my old MAC address...

apreciate your help

**Comment by dschaper** [comment]
That's something you'll have to find out for your particular distribution / operating system. Really has nothing to do with this issue.

**Comment by truehomie** [comment]
@dschaper I 'm using Windows 10 at the moment
i cleared values at PC\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
no matter what i do DUID client DHCPv6 stays the same

**Comment by truehomie** [comment]
Ok, i found em,  values sits in PC\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\Intefaces, requires manual correction

**Comment by MayeulC** [comment]
I am using Pi-hole's DNS to bypass a hairpinning issue I have with my ISP-provided router. Unfortunately, I cannot just change the DNS records, and I must disable its DHCP server as well, so I'm using pi-hole's for now :)

For some reason, static ipv6 assignment isn't working on my server right now, so I would have liked to assign it with pi-hole's DHCP server, but there is no easy way to do so in the interface. I admit it's more of an issue on my side, and I should statically assign one.

However, what about link-local addresses? I am not *extremely* familiar with all of the IPv6 specificities, can a DHCPv6 server provide a link-local address as well (as well as the autoconfigured one)? If so, that would be useful.

Regarding MAC addresses, shouldn't these be known from the ARP table anyway, since we are on the same LAN? That could easily be extracted, and a name mapped to the most recent IPv6 address assigned to that MAC address.

The only thing missing is a way to assign a name, not an IP address, to a given MAC address. And also allow to enter multiple times a given MAC, as users might want to also assign a static IPv4, and/or multiple domain names to a single network card.

**Comment by MayeulC** [comment]
@dschaper, why close this? Even if it's hard to solve, it is still a deficiency in my opinion. Closing will make the issue harder to find (at least, thank you for not closing it).

I've since learned much, much more about IPv6. There are multiple ways one could trace an IP to a hostname, which is what's being asked here. mDNS could be used, for instance.
