### ISSUE TITLE
Web Interface Question...

### ISSUE THREAD

**Issue by gh0stshell** [pi-hole/pi-hole#257]
Is the more under each section suppose to do something when I click on it?

**Comment by dschaper** [comment]
Do you mean the squares? Right now they don't do anything when you click on them. The backside code is being fleshed out and developed right now. I don't know if anything has made it to the repository as a branch yet though, it's still in pre-alpha stage.

**Comment by DonLexos** [comment]
You can follow the interrace developement here:
https://github.com/pi-hole/AdminLTE

**Comment by Mcat12** [comment]
There is currently a small table of frequent queries on the devel branch that's shown when you click one of the squares, but there's a new formatting plan in the works that will probably change that.

**Comment by gh0stshell** [comment]
OK, thanks all, i was just curious

**Comment by DonLexos** [comment]
You are not the only one ;-) There are a few different people all trying to get more information in the dashboard. I think that due to the very active development on the pi-hole itself the interface related development is "a bit behind" but I don't doubt this will be picked up soon. Right now squashing bugs has the priority, and if things are running smoothly enhancements will be added I guess.
