### ISSUE TITLE
Long term query fails

### ISSUE THREAD

**Issue by stan-qaz** [pi-hole/pi-hole#2576]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:1

---
**Expected behaviour:**

The query should complete and return data to populate the page. It used to do this, can't recall if I tried it since the 4.1 update or not though. Tested on two different Pi-hole installs.

**Actual behaviour:**

Errors out with a message "An unknown error occurred while loading data"

![q-crash-screenshot_20190102_154317](https://user-images.githubusercontent.com/1954153/50616894-b75a8180-0ea7-11e9-8a96-eb59c6cda375.png)

**Steps to reproduce:**

Click Long Term Data then Query Log. Select a date range, I used last month for these debug files.

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

Pi-hole #1: q0l6lxsmjx
Pi-hole #2: 1fidpflbqp

**Troubleshooting undertaken, and/or other relevant information:**

Updated Pi software, checked PI-hole for updates, rebooted both Pi-holes.

**Comment by Mcat12** [comment]
Are you able to load shorter time spans? Most likely, you just have a lot of queries in that time span, and the PHP API is unable to handle loading all of those queries in a reasonable time frame.

**Comment by stan-qaz** [comment]
I can load daily or weekly queries with no problem, trying custom ranges I can get to about 15 days, about 350,000 queries before seeing the error. This is on a pair of Pi 3Bs so I was expecting that I'd be able to pull up a month's worth of data before hitting the limits.

If this as expected then we should close this issue.

**Comment by T-W-S** [comment]
I see the same error when I try to query **"Last Month"**


![error_pihole-long-term-query](https://user-images.githubusercontent.com/10873474/50710192-30053d80-1062-11e9-994c-04d309a90e4d.png)


However when I shorten the time span, lets say to **16. - 31. of Dec** it pulls the data, then I change it to **06. - 31 of Dec** also successful, then I go back to my initial query for **"Last Month"** and voila it works.

![working_pihole-long-term-query](https://user-images.githubusercontent.com/10873474/50710382-c46fa000-1062-11e9-9e30-c616bf26541f.png)


Once I leave the **"Long term data"** area e.g. to **"Dashboard"** and go back, the query for **"Last Month"** fails again with same error, shorten and then expand the time span works again.

Hope this helps.

**Comment by DL6ER** [comment]
When the PHP API needs more than 30 seconds (may it be PHP's own inefficiency or a slow SD card to read the database from), it inevitably runs into a timeout. This triggers the error as the frontend, unfortunately, cannot do anything better as it only gets a error 500.

**Comment by Jhfelectric** [comment]
Hi, 
Commenting on this as the same error can be observed when the list of domains contains bad chars. In my case, I figured out some of the domain names recorded in the 'queries' table of the SQLite3 database had bad chars or possibly non-ascii chars. While this shouldn't be an issue in most cases, here it seems to break the returned list of domains. While browsing the pihole-FTL.db I found multiple occurences of domains b._dns-sd._udp.?? as well as same starting with db, r, dr and lb. Using only a terminal, I was unable to 'see' those bad chars, they only appeared with ??. 
This can easily be fixed by adding a GLOB clause in the relevant query used to retrieve the domains. I modified the line 115 of file AdminLTE/api_db.php (https://github.com/pi-hole/AdminLTE/blob/38d8e77f999ba5999c013b44f6e8fe808308de7a/api_db.php#L115) like this:

`		$dbquery = "SELECT timestamp, type, domain, client, status FROM queries WHERE  domain NOT GLOB ('*[^'||char(1,45,127)||']*') and timestamp >= :from AND timestamp <= :until ";`

The GLOB clause will reject any domain containing non-ascii chars using a regex.
This solution solved my problem but of course one will miss out those excluded records.

Thanks to these blog entries:
https://discourse.pi-hole.net/t/long-term-data-query-unknown-error-occured/20259/15
http://sqlite.1065341.n5.nabble.com/Finding-records-containing-non-ascii-characters-td86959.html

**Comment by dschaper** [comment]
Hello, thanks for the update. Can you open a PR with the changes based on the development branch or create a new issue so that we can look at adding your changes to the code? Thanks.

**Comment by expressrussian** [comment]
Hello,
I have installed Raspberry Pi 4B yesterday and installed pihole on it yesterday.  So, i have only 1 day old installation with only pihole running on it.
Every time i click on the left "query log", or try to do long term data / query log, i get immediately this error: "An unknown error occurred while loading data". There is no wait.  On the dashboard i have only 530 queries (5 clients), 12 queries blocked. 
root@raspberry4b:/var/log/lighttpd# free -h
               total        used        free      shared  buff/cache   available
Mem:          3.8Gi       283Mi       2.3Gi        57Mi       1.2Gi       3.3Gi

Your debug token is: https://tricorder.pi-hole.net/92wuzsmnse
No recent errors in lighthttpd logs.

Long term data / Top Lists : Top domains spins and does not show anything, only spinner.
This whole query mechanism is obviously NOT working.
