### ISSUE TITLE
IP specific blocking

### ISSUE THREAD

**Issue by gilbertobr** [pi-hole/pi-hole#2579]
Good afternoon,
I'm currently trying create a custom block list for some specific IPs.

Ex:
IP 192.168.0.20 can access "www.google.com"
IP 192.168.0.21 can not access "www.google.com"

How do I do that?
can you help me

**Comment by dschaper** [comment]
Please open a topic on our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
