### ISSUE TITLE
Unable to update (generic error message)

### ISSUE THREAD

**Issue by ErikThiart** [pi-hole/pi-hole#2592]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

2

---
**Expected behaviour:**

I expect the update to work.

**Actual behaviour:**

```
pi@raspberrypi:~ $ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    update available
  [i] FTL:              update available

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [i] Update repo in /var/www/html/admin...
  : Could not update local repository. Contact support.
```

**Steps to reproduce:**

`sudo pihole -up`

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by ErikThiart** [comment]
Uhm, I posted the full code, what else do you need?
(I don't mind getting more info, but do tell me what info? (is a debug token even applicable to this issue?)

**Comment by dschaper** [comment]
Yes, a debug token is applicable. 

What distribution are you running, what version, what it the output from `sudo git status` in that directory, are you running any 3rd party extensions to the web interface among other questions that will need to be answered, or the debug token can give all that and more.

**Comment by ErikThiart** [comment]
Understood,

My debug token is: **uu08ia1ofo**

```
pi@raspberrypi:~ $ pihole -g
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: No changes detected

  [i] Target: sysctl.org (hosts)
  [✓] Status: No changes detected

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: No changes detected

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: No changes detected

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: No changes detected

  [i] Target: buffalo.biodome.org (youtube-ads-list.txt)
  [✓] Status: No changes detected

  [i] Target: buffalo.biodome.org (youtube-hosts-list.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 136184
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 113021
  [i] Number of whitelisted domains: 266
  [i] Number of blacklisted domains: 8
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [✓] Pi-hole blocking is Enabled

```

**Comment by ErikThiart** [comment]
```
pi@raspberrypi:~ $ cd /var/www/html/admin
pi@raspberrypi:/var/www/html/admin $ sudo git status
On branch master
Your branch is behind 'origin/master' by 2772 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   scripts/pi-hole/php/footer.php
        modified:   scripts/pi-hole/php/header.php

no changes added to commit (use "git add" and/or "git commit -a")
pi@raspberrypi:/var/www/html/admin $
```
I do not think this is a DietPi installation, I used the following command to install it `curl -sSL https://install.pi-hole.net | bash`

I footer.php and heater.php files I did change when I initially installed it, I changed the name from Pin-hole to my server name.

**Comment by dschaper** [comment]
You'll have to either undo the changes, update and then redo the changes, or `git stash` the changes and reapply.

**Comment by ErikThiart** [comment]
I don't mind re-doing the changes, is there a command I can run that will overwrite it for me?

**Comment by dschaper** [comment]
Yes, `sudo git reset --hard HEAD` will bring the repo back to origin condition.

**Comment by ErikThiart** [comment]
I love you @dschaper - Thank you so much for helping me, a neophyte.

```
pi@raspberrypi:/var/www/html/admin $ sudo git reset --hard HEAD
HEAD is now at af8c926c Merge pull request #795 from pi-hole/release/v4.0
pi@raspberrypi:/var/www/html/admin $ sudo git status
On branch master
Your branch is behind 'origin/master' by 2772 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working tree clean
pi@raspberrypi:/var/www/html/admin $ cd ~
pi@raspberrypi:~ $ sudo pihole -up
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    update available
  [i] FTL:              update available

  [i] Pi-hole Web Admin files out of date, updating local repo.
  [✓] Check for existing repository in /var/www/html/admin
  [✓] Update repo in /var/www/html/admin

  [i] If you had made any changes in '/var/www/html/admin/', they have been stashed using 'git stash'

  [i] FTL out of date, it will be updated by the installer.

  [✓] Root user check

        .;;,.
        .ccccc:,.
         :cccclll:.      ..,,
          :ccccclll.   ;ooodc
           'ccll:;ll .oooodc
             .;cll.;;looo:.
                 .. ','.
                .',,,,,,'.
              .',,,,,,,,,,.
            .',,,,,,,,,,,,....
          ....''',,,,,,,'.......
        .........  ....  .........
        ..........      ..........
        ..........      ..........
        .........  ....  .........
          ........,,,,,,,'......
            ....',,,,,,,,,,,,.
               .',,,,,,,,,'.
                .',,,,,,'.
                  ..'''.

  [i] Existing PHP installation detected : PHP version 7.0.33-0+deb9u1
  [i] Performing unattended setup, no whiptail dialogs will be displayed
  [✓] Disk space check
  [✓] Update local cache of available packages

  [✓] Checking apt-get for upgraded packages... up to date!

  [i] Installer Dependency checks...
  [✓] Checking for apt-utils
  [✓] Checking for dialog
  [✓] Checking for debconf
  [✓] Checking for dhcpcd5
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for whiptail

  [i] Performing reconfiguration, skipping download of local repos
  [✓] Resetting repository within /etc/.pihole...
  [✓] Resetting repository within /var/www/html/admin...
  [i] Main Dependency checks...
  [✓] Checking for bc
  [✓] Checking for cron
  [✓] Checking for curl
  [✓] Checking for dnsutils
  [✓] Checking for iputils-ping
  [✓] Checking for lsof
  [✓] Checking for netcat
  [✓] Checking for psmisc
  [✓] Checking for sudo
  [✓] Checking for unzip
  [✓] Checking for wget
  [✓] Checking for idn2
  [✓] Checking for sqlite3
  [✓] Checking for libcap2-bin
  [✓] Checking for dns-root-data
  [✓] Checking for resolvconf
  [✓] Checking for lighttpd
  [✓] Checking for php7.0-common
  [✓] Checking for php7.0-cgi
  [✓] Checking for php7.0-sqlite3

  [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'
  [✓] Installing scripts from /etc/.pihole

  [i] Installing configs from /etc/.pihole...
  [i] Existing dnsmasq.conf found... it is not a Pi-hole file, leaving alone!
  [✓] Copying 01-pihole.conf to /etc/dnsmasq.d/01-pihole.conf

  [i] Installing blocking page...
  [✓] Creating directory for blocking page, and copying files
  [✗] Backing up index.lighttpd.html
      No default index.lighttpd.html file found... not backing up

  [✓] Installing sudoer file

  [✓] Installing latest Cron script

  [✓] Installing latest logrotate script

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [✓] Downloading and Installing FTL
  [i] Backing up /etc/dnsmasq.conf to /etc/dnsmasq.conf.old
  [✓] man pages installed and database updated
  [i] Testing if systemd-resolved is enabled
  [i] Systemd-resolved is not enabled
  [✓] Starting lighttpd service...
  [✓] Enabling lighttpd service to start on reboot...
  [i] Restarting services...
  [✓] Enabling pihole-FTL service to start on reboot...
  [✓] Starting pihole-FTL service...
  [✓] Deleting existing list cache
  [i] Pi-hole blocking is enabled
  [i] Neutrino emissions detected...
  [✓] Pulling blocklist source list into range

  [i] Target: raw.githubusercontent.com (hosts)
  [✓] Status: Retrieval successful

  [i] Target: mirror1.malwaredomains.com (justdomains)
  [✓] Status: Retrieval successful

  [i] Target: sysctl.org (hosts)
  [✓] Status: Retrieval successful

  [i] Target: zeustracker.abuse.ch (blocklist.php?download=domainblocklist)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_tracking.txt)
  [✓] Status: Retrieval successful

  [i] Target: s3.amazonaws.com (simple_ad.txt)
  [✓] Status: Retrieval successful

  [i] Target: hosts-file.net (ad_servers.txt)
  [✓] Status: Retrieval successful

  [i] Target: buffalo.biodome.org (youtube-ads-list.txt)
  [✓] Status: Retrieval successful

  [i] Target: buffalo.biodome.org (youtube-hosts-list.txt)
  [✓] Status: Retrieval successful

  [✓] Consolidating blocklists
  [✓] Extracting domains from blocklists
  [i] Number of domains being pulled in by gravity: 136183
  [✓] Removing duplicate domains
  [i] Number of unique domains trapped in the Event Horizon: 113020
  [i] Number of whitelisted domains: 266
  [i] Number of blacklisted domains: 8
  [i] Number of regex filters: 0
  [✓] Parsing domains into hosts format
  [✓] Cleaning up stray matter

  [✓] Force-reloading DNS service
  [✓] DNS service is running
  [i] Pi-hole blocking will be enabled
  [i] Enabling blocking
  [✓] Reloading DNS service
  [✓] Pi-hole Enabled

  [i] The install log is located at: /etc/pihole/install.log
Update Complete!

  Current Pi-hole version is v4.1.1
  Current AdminLTE version is v4.1.1
  Current FTL version is v4.1.2
pi@raspberrypi:~ $
```

**Comment by dschaper** [comment]
Glad you were able to get it working, thanks for using Pi-hole!

**Comment by MichaIng** [comment]
@dschaper 
We have one user running into the same issue: https://github.com/Fourdee/DietPi/issues/2516#issue-408053617
I made a test via checkout, as well complaining about changed files, right after a fresh Pi-hole install, so I guess the update fails for the same reason, matching the here reported issue.

The thing is that the DietPi installer does not touch those files:
- https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L4293-L4311
- https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-software#L9124-L9161

But what we do is `chown`/`chmod` the webroot and that indeed is the issue. To replicate:
```
root@VM-Stretch:/var/www/html/admin# chmod +x api_db.php
root@VM-Stretch:/var/www/html/admin# pihole checkout master
  Please note that changing branches severely alters your Pi-hole subsystems
  Features that work on the master branch, may not on a development branch
  This feature is NOT supported unless a Pi-hole developer explicitly asks!
  Have you read and understood this? [y/N] y

  [i] Shortcut "master" detected - checking out master branches...
  [i] Pi-hole core
  [✓] Switching to branch: 'master' from 'refs/heads/development'
  [i] Already up-to-date.
  [i] Web interface
  [i] Switching to branch: 'master' from 'refs/heads/devel'error: Your local changes to the following files would be overwritten by checkout:
        api_db.php
Please commit your changes or stash them before you switch branches.
Aborting
  [✗] Unable to pull Web master branch
```

Now I see you already mentioned that above. Is this new, either to Pi-hole or the Git client itself, checking file permissions? I can't remember this being an issue before.

However, it indeed does not make much sense to overwrite webroot permissions after every install, since for security reasons there are often various different owners/modes.
We will change this behaviour to only chown/chmod the individual unpacked web application archives, without those being pulled via Git client where modes are applied automatically.

**Comment by dschaper** [comment]
Can you open a new issue with this information as tagging on to the end of a closed issue will not track anything and this will be lost in the ether.

**Comment by MichaIng** [comment]
@dschaper 
> Can you open a new issue with this information

I think it's not required, as nothing needs to be changed Pi-hole side?
- Besides, if this is not Git client internal thing, the updater/checkout script could give a hint, if only file permissions are changed, since there might be other reasons for them being overwritten by user, as this was the case for the TO.

I have bug report opened on DietPi, providing the solution and we will fix that in code with the next version: https://github.com/Fourdee/DietPi/issues/2516

**Comment by dschaper** [comment]
Correct, there is nothing to be changed on the Pi-hole side. The failure to update is due to changes being made to a local git repository and the expectation that what we installed was not modified or changed. If we override changes that users make then we risk destroying work the user intended to be saved via a stash.

The error is direct from `git` and while there are workarounds and very dirty hacks for instructing git to ignore file permissions when pulling and cloning, the practice of applying execute permissions blindly to every file in the web repository is not advisable and not something that we would be willing to implement a workaround. The permissions are set to be the lowest priv's required for the web interface to do what it needs to do and nothing further. 

The solutions you reference in the PR are great, there really should be no need to change ownership or permissions on any file in that specific directory.

**Comment by MichaIng** [comment]
@dschaper 
> The error is direct from `git` and while there are workarounds and very dirty hacks for instructing git to ignore file permissions when pulling and cloning, the practice of applying execute permissions blindly to every file in the web repository is not advisable and not something that we would be willing to implement a workaround.

I totally agree. Until next DietPi release I hope we catch all affected users in our forums/GitHub repo to forward to the quite simply solution, otherwise you know where to forward them, in case some DietPi user reports the issue here 🙈.
