### ISSUE TITLE
This site is able to detect that I'm using a Pi-Hole

### ISSUE THREAD

**Issue by dylanmtaylor** [pi-hole/pi-hole#2608]
When I visit https://www.wral.com/ and click around on the articles, I get a "powered by Admiral" message that somehow knows an adblocker is in use. 

![image](https://user-images.githubusercontent.com/277927/52165966-78516300-26d5-11e9-9e2a-06bb29e6d028.png)

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
