### ISSUE TITLE
after upgrade to 4.2.1 instagram cannot be open !

### ISSUE THREAD

**Issue by ErfanDL** [pi-hole/pi-hole#2616]
Hi last night I update the Pihole from 4.1 to 4.2.1 but after update and reboot the raspberrypi the instagram cannot be open ! any way to fix ? thanks

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
