### ISSUE TITLE
How do I find out what's blocking a particular site to whitelist?

### ISSUE THREAD

**Issue by aram535** [pi-hole/pi-hole#2617]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

During "Pause" let the user view all requests so that you can "add to whitelist".

**Actual behaviour:**

Can't track what is the particular BLOCKED that is causing website not to render correctly

**Steps to reproduce:**

Use pi-hole.
Go to: http://longisland.news12.com/

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

n/a

**Troubleshooting undertaken, and/or other relevant information:**

If you pause pi-hole, the site works.

**Comment by dschaper** [comment]
Please open a troubleshooting issue on https://discourse.pi-hole.net. Thank You.

---
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
