### ISSUE TITLE
whitelist issue when adding then removing top level domain

### ISSUE THREAD

**Issue by sectoramen** [pi-hole/pi-hole#2633]
Pi-hole Version v4.2.1 Web Interface Version v4.2 FTL Version v4.2.1

added COM to the whitelist
removed COM to the whitelist

Result: all domains ending in .com are gone.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
