### ISSUE TITLE
DHCP leases not sorting by   MAC / IP / Hostname   heading when clicked

### ISSUE THREAD

**Issue by optio50** [pi-hole/pi-hole#2645]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
0
---
**Expected behaviour:**

Click on heading and see IP / Hostname / MAC sorted

**Steps to reproduce:**

Settings ---> DHCP ---> DHCP leases, click MAC / IP / Hostname heading

**Troubleshooting undertaken, and/or other relevant information:**

It appears this was addressed and implemented but fails to work.
https://github.com/pi-hole/pi-hole/issues/2059

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by optio50** [comment]
Ok, no biggie. It was a simple to understand issue. Sorry you cant grasp it. Just trying to help. :-)

**Comment by dschaper** [comment]
Sure, not a problem. And if you'd like to fill things out with a debug token so we can see what version you're running and some information about the platform then we'd be more than happy to investigate.
