### ISSUE TITLE
Occasionally very many queries for "lb._dns-sd._udp.0.1.168.192.in-addr.arpa" (99,9% of all)

### ISSUE THREAD

**Issue by HATEthePLOT** [pi-hole/pi-hole#2654]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1
---
**Expected behaviour:**

`Pi-Hole should querry domains etc in a sensible manner`

**Actual behaviour:**

`lb._dns-sd._udp.0.1.168.192.in-addr.arpa gets querried about 300.000 times within 2 hours; these querries are not blocked by pi-hole; dns querries to other domains are slow or fail entirely`

**Steps to reproduce:**

`Fresh install with added filter lists -- no further changes. This behaviour occurs rather randomly and stops when I reboot my pi running pi-hole.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`tp72qn4hvp`

**Comment by Mcat12** [comment]
What tells you that this is Pi-hole querying for that domain? FTL only retrieves the hostname of its clients once, so it is probably not caused by that.

**Comment by 4s7r0** [comment]
I am having this problem as well.

**Comment by PromoFaux** [comment]
@HATEthePLOT  Could you please do a fresh debug token, that one has expired!

@4s7r0 could you please do a debug token, too (`pihole -d`)

Both : When you look at these queries on the query log of the front page, what client is showing as making the queries?

**Comment by HATEthePLOT** [comment]
> @HATEthePLOT Could you please do a fresh debug token, that one has expired!
> 
> Both : When you look at these queries on the query log of the front page, what client is showing as making the queries?

e902au17yy!

the queries are done by my router (although Pi-hole only shows either my router or localhost as querying institution).

**Comment by PromoFaux** [comment]
Hmm, so do all of your clients first query your router, which in turn queries the Pi-hole?

Difficult to tell which client it is in that case :)

If your router is set to do DHCP, then you should set it so that the clients use Pi-hole for DNS lookups, failing that, you could disable DHCP on the router and enable the Pi-hole to do the DHCP part, too, which will give the added advantage of seeing client hostnames in the query log rather than IP.

Unable to look at the debug token at the moment, will try and get to it before it expires though :)

**Comment by PromoFaux** [comment]
@HATEthePLOT I note from you debug log that you have conditional forwarding activated. I wonder if you're experiencing a feedback loop of sorts. Can you try disabling conditional forwarding and monitoring for a period to see what happens?

**Comment by HATEthePLOT** [comment]
> 
> 
> Hmm, so do all of your clients first query your router, which in turn queries the Pi-hole?
> 
> Difficult to tell which client it is in that case :)
> 
> If your router is set to do DHCP, then you should set it so that the clients use Pi-hole for DNS lookups, failing that, you could disable DHCP on the router and enable the Pi-hole to do the DHCP part, too, which will give the added advantage of seeing client hostnames in the query log rather than IP.
> 
> Unable to look at the debug token at the moment, will try and get to it before it expires though :)

Thanks for your advice!
I read the following thread https://www.reddit.com/r/pihole/comments/a59hb2/lots_of_localhost_requests_after_v41_update/ which mentions a similar problem. It is solved by changing the WAN-DNS in the router to a different DNS than Pi-hole (i.e. 1.1.1.1 8.8.8.8 etc).

I have setup Lan-DHCP to use Pi-hole as DNS and (until I changed it) WAN DNS to use Pi-hole. 

Migrating to Pi-hole DHCP is something I would want to avoid (to many individual settings). But I'll check each of your suggestions individually and come back to you.

**Comment by 4s7r0** [comment]
I think it was coming from my router. It stopped after I unchecked and re-checked the "Never forward non-FQDNs" and the "Never forward reverse lookups for private IP ranges" and enabled DNSSEC, but I wasn't trying to solve this problem that way. I was just changing my settings.

**Comment by 4s7r0** [comment]
It is coming from my MacBook Air. I did the whole "pihole -d" thing.

**Comment by neutmute** [comment]
I've been playing with VLAN's and jailing my IOT devices - and using pihole.
fyi - this traffic happened when I installed avahi daemon on my OpenWRT and set enable_reflector=yes

In other words, this is mDNS/bonjour/zero-conf traffic

**Comment by daprice** [comment]
Having the same (or similar) problem. Rebooting the pi-hole server helps temporarily (reduces the number of queries being made every hour) but eventually the queries increase to ridiculous levels again. As of right now, with 30 days uptime, it’s performing ~1000 PTR queries per hour, almost all for IPv6 addresses.

I have conditional forwarding off and the DNS in the router is not set to the pi-hole, so I don’t think it’s creating a feedback loop that way. What I *think* is happening is that every hour, it tries to perform a reverse lookup for __every__ client address it’s ever seen since it was rebooted. Most of the clients on my network use IPv6 privacy extensions, so they query using a different temporary address frequently (plus none actually have a PTR record so every lookup comes back with NXDOMAIN), so over time the list of addresses it tries to look up every hour grows ridiculously long.

Here’s my debug token: https://tricorder.pi-hole.net/4l92jt2trs

Is there a way to either disable reverse lookups for clients entirely (I don’t care about seeing hostnames in the pi-hole interface, and the clients don’t have PTR records anyway) and/or make it only perform lookups on clients it’s seen in the past *x* amount of time (instead of all clients it’s seen since boot) so the queries don’t balloon over time? I already have “Never forward reverse lookups for private IP ranges” enabled, but that only seems to apply to IPv4, not IPv6.

**Comment by dschaper** [comment]
Pi-hole doesn't generate any queries on it's own. Anything that is causing a lookup would be triggered by a client requesting that address.

**Comment by dschaper** [comment]
Looking things over, the PTRs are for addresses in the `2600:0000::/12 | ARIN` range which makes them public IPv6 addresses. Something on the Pi-hole device itself is asking for the PTRs. Pi-hole is then sending those queries over to `cloudflare` for resolution. The addresses are not private range so there isn't a way to block them without blockin the `2600:0000::/12` public ip space.

**Comment by daprice** [comment]
@dschaper Thanks for looking over my debug log. @Mcat12 mentioned “FTL only retrieves the hostname of its clients and upstreams once every hour” – is that not what’s happening here? The addresses being looked up in `2600:0000::/12` do appear to be the temporary IPv6 addresses of the clients in the local network making DNS queries to pi-hole.

Choosing “Restart DNS resolver” in pi-hole settings also reduces the queries for a time. The only other process on the pi-hole device that I thought might be making the queries is avahi-daemon, but I tried disabling that and they still occur.

**Comment by silvether** [comment]
I had issues with this when the _Conditional Forwarding_ feature was enabled.

Disabled, and the flood of PTR lookups went away.

**Comment by ckaznocha** [comment]
I'm having the same issue when `Conditional Forwarding` is enabled. Based on the advice [here](https://discourse.pi-hole.net/t/after-update-to-4-1-my-logges-are-flooded-with-ptr-requests/15070/8) I enabled `ANALYZE_ONLY_A_AND_AAAA` which offers some relief but when there are a lot of clients triggering these recursive requests the rpi still gets bogged down. Ultimately I had to disable `Conditional Forwarding` which means my local host names don't resolve anymore.

Despite disabling `Forward local domain queries to upstream DNS` on my router it seems to still miss a few of these arpa domains which cause the recursion. I think the proper solution would be for the router to not forward these queries but that's probably unlikely to happen anytime soon.

I think the path of least resistance would be if the pi hole offered a `Conditional Forwarding` block list. In my case there are only 3 domains causing the recursion so entering them all manually wouldn't be much work at all. All 3 follow a simple pattern so being able to enter a regex rule would also be a fine solution.

**Comment by ckaznocha** [comment]
Some more info, like the OP my queries are also for `.*.0.1.168.192.in-addr.arpa`. Unlike the other PTR queries I see, there isn't a device on my network at `192.168.1.0` which I assume is why these ones are an issue?

I've also tried adding a blacklist wildcard rule and putting an entry in my routers `/etc/hosts` like mentioned [here](https://www.reddit.com/r/pihole/comments/acv9a0/load_of_ptr_requests/). Neither helped.

**Comment by dschaper** [comment]
Would be better to solve the problem and find the client blasting the queries than to patch the server to ignore requests.

**Comment by arcaven** [comment]
First let me apologize for the poorly written reply here. I'm answering too quickly, in an informal rapid reply.

There are a few solutions that do not involve disabling the conditional forwarding, or the other solutions presented thus far. I'm assuming that you 1) setup the non-default conditional forwarding to get reverse resolution on the hosts on that segment from the DHCP server, and 2) that you had a good reason for the DHCP server to be where it is, and not on your pi-hole, because it's a good bet that is the case. And 3) that you don't want to point your DHCP device to the upstream DNS server because you want it to know about local non-DHCP entries, or 4) because you want it to get pi-hole protection as well.

If all of those are the case, here are two additional options for you:

### Option A: configure your DHCP server to "know" how to reply for that query. It may be as simple as creating an entry in the /etc/hosts file so that it can give pi-hole an answer (or so that, if it is the originator of the query it never even asks). It's difficult to share exactly how (or even if it is possible) to do this because it depends on the DHCP server.... good luck.

### Option B: 
  _step 1_ - configure a blacklist regex entry, something like the following will probably work for everyone, and for all of the different service discovery and similar requests (tcp and udp) 

# add as a regex blacklist
`^.*p\.(([0-9]{1,3}\.){4})in-addr\.arpa$` 

_step 2_ - delete the huge number of entries from the FTL database as shown above with the sqlite3 command (use sudo if you are not root (and I hope you don't log as root) because otherwise you may not have permissions to delete
`sudo sqlite3 /etc/pihole/pihole-FTL.db "DELETE FROM queries WHERE domain LIKE '%in-addr%';"`

_step 3_ - check your pi-hole server disk space with "df -k" and if / (root) or another partition such as /var/ are showing high use, consider cleaning or deleting the very large files you'll find this way:
`ls -l /var/log/pihole*`

_step 4_ - reboot the pi-hole server and log in as soon as it comes up, and watch the services spool up
       ie, sudo shutdown -r now
       terminal drops.... ping pi-hole-addr (until it responds, and immediately) ssh pi@pi-hole-addr, "uptime", "top" etc
Here you are confirming that your pi-hole is returning to normal service and isn't choking on the .db file or from some bitrot due to high disk use, etc.

_step 5_ - watch the DNS query tally for a few minutes, make sure it is not showing 200+ qps to confirm that the regex is handling the specific query on your network.
 
For those of you who may be interested in what is happening, a device makes the service discovery request to the pi-hole DNS, which triggers a conditional forwarding for that subnet (because your pi-hole is configured to refer unknown reverse queries to the DHCP server.) The DHCP server probably runs dnsmasq, or similar, and seeks to answer the question. If it was for a single host, it would be answered and that would be the end of it. However, this is a question the DHCP does not know how to answer, so it asks it's DNS server(s) ... which naturally is the pi-hole server. Repeat into a feedback loop. Now, I don't know about these other networks, but on mine the speeds and systems are healthy, so very quickly (minutes) I'm getting 200 qps on the pi-hole, and shortly after that (minutes) it approaches 2000 qps. Load on the pi-server begins to peg out, if there are switch ports that do not limit unicast traffic then it's a race to see if 1) pi-hole FTL fails due to memory or 2) the disk fills up due to pi-hole.FTL.log files or 3) the disk fills up due to the FTL database size or 4) the system load becomes too much and the applications crawl to their death, or 5) your switch gives up the ghost or 6) the ethernet chip can't get a word in edgewise and you achieve a steady state and then 1, 2, 3, or 4 are inevitable or 7) something like a system crash on either side interrupts the feedback loop. In that case, if it's the DHCP server, then you might luck out for a while if it does not repeat within the next 24 hours. If at any time in the next 24 hours the pi-hole server is restarted (service or system) then it's likely that the db is too large and pi-hole services (FTL mainly) will choke while starting up, and load will begin to climb from 1 to 3 to ... and so on.

**Comment by techie2000** [comment]
> _step 2_ - delete the huge number of entries from the FTL database as shown above with the sqlite3 command (use sudo if you are not root (and I hope you don't log as root) because otherwise you may not have permissions to delete
> `sudo sqlite3 /etc/pihole/pihole-FTL.db "DELETE FROM queries WHERE domain LIKE '%in-addr%';"`

@arcaven when I run this i get `Error: cannot modify queries because it is a view`

**Comment by techie2000** [comment]
> You have replied to a thread that is out of date. The query database format was changed since then.
> 
> https://discourse.pi-hole.net/t/delete-queries-error/53761

Thank you.This will serve as a useful redirect for future Googler's who stumble on this thread.
