### ISSUE TITLE
Log fills disk space and then I can't log in to flash the logs

### ISSUE THREAD

**Issue by JJandJ** [pi-hole/pi-hole#2667]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

I should still be able to log in to flush the logs when the disk is full

**Actual behaviour:**

I go to admin login page, enter password, and click log in, the page then refreshes at the admin login page. 

**Steps to reproduce:**

Fill up disk space and try to log in to admin panel

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`{Alphanumeric token}`

**Troubleshooting undertaken, and/or other relevant information:**

I have set the log rotate to 1 as a temp workaround

> * Please [submit any feature requests here](https://discourse.pi-hole.net/c/feature-requests), so it is votable and trackable by the community.
> * Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.
> * Detail helps us understand and resolve an issue quicker, but please ensure it's relevant.
> * _This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
Run `pihole -d` for a debug token, as requested by the issue template.
How much disk space are the logs taking up when it's full? You may have too small of a log partition.

**Comment by graybush** [comment]
I too have encountered this problem. My Pi-hole installation is on a raspberry pi 3 with a 1.8 GB SD card. To fix this issue I ended up adding a network mount and then created a symbolic link for the log files. I do not have exact stats but when I was troubleshooting the issue I believe the log files consumed approximately 200 MB.

**Comment by DL6ER** [comment]
The embedded `dnsmasq` writes to the log whenever there is something to log without checking for remaining disk size. This is typical behavior (I doubt any application really checks for available space before writing to its logfile).

The issue here is that the disk (= SD card) of your Pi-hole is too small for the job you want this machine to do. There are two(/three) options which will both work:

1. Use a larger SD card. Cards up to 64 GB are available for less than ten bucks. I've bought two Intenso 64GB SD Micro (Class 10) for 7.90€ each in an ordinary supermarket last week.
2. Disable logging. Pi-hole does not depend on the log files. You can safely disable logging to them. Your history will still be available as it is also stored in the database. However, the database is much cleverer at storing the data so the same content uses up less space.
3. (Not officially supported) You could also decrease the log rotation interval. This will cause the log files to get rotated (and flushed) more frequently, i.e., when they are not yet that large. Note that the customized intervals will likely be reset on repairs (`pihole -r`) or upgrades as we always ensure that users have the "right" configuration that is meant to run a mainstream Pi-hole.
