### ISSUE TITLE
Feature Request: Aggregate reporting for clients

### ISSUE THREAD

**Issue by lgap** [pi-hole/pi-hole#2670]
When selecting clients or URLS; is it possible to have aggregate reporting/query log so that it does not show all the individual log entries; but instead only shows unique instances (combinations of Type, Domain, Client, Status) and a counter of occurance within a given time-interval (e.g. last hour, last day, etc). Thus removing the timestamps / reply?

This will make it easier to quickly 'manage' unique blocked hits to domains and/or client usage without having to scroll through 'duplicate' information.

Thanks.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

## All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
