### ISSUE TITLE
default block list item is accessed over http, allows for DoS

### ISSUE THREAD

**Issue by sneak** [pi-hole/pi-hole#2704]
https://github.com/pi-hole/pi-hole/blob/995ee41d6bc3a405a0402745b24140ca08c148f3/automated%20install/basic-install.sh#L1184

**Expected behaviour:**

All default block lists are fetched securely via TLS.

**Actual behaviour:**

One of the default block lists is fetched over HTTP.  This allows an attacker to MITM the connection and cause your pi-hole to block any domains the attacker wishes to cause you to block, potentially causing a DoS.

**Steps to reproduce:**

Install pi-hole with default settings.

**Comment by sneak** [comment]
Sadly `sysctl.org` does not support TLS connections, otherwise I would have just sent in a PR.

**Comment by dschaper** [comment]
If there is no TLS support for https://sysctl.org I'm not sure how you propose we access it that way?

**Comment by sneak** [comment]
I did not propose that. My suggestion is to *not* download block lists over unauthenticated connections, because otherwise anyone in between you and that host (in common parlance, “someone with a privileged network position”) can alter the contents in transit and cause you to automatically block anything they want, which is a denial of service.

**Comment by sneak** [comment]
Options:

- contact sysctl.org and get them to update their server to 2010 standards

- re-host it somewhere authenticated (with periodic updates) and use that re-hosted url in the pi-hole software (still somewhat vulnerable to the same problem)

- drop that blacklist source entirely

**Comment by Mcat12** [comment]
If you are suggesting to not download blocklists over HTTP, then you are suggesting to remove that block list. Please be clear about what you are trying to accomplish, and the effects of the change.

If you do not want that block list, then remove it. We do not intend on removing it, as it serves its purpose, the average user does not have such strict security requirements, and if they do have such security requirements, they would have just removed the list or never added it when installing.

**Comment by dschaper** [comment]
Feel free to contact them and ask them about TLS hosting.

It is up to the users to decide what blocklists they would like to use and what method the would like to access those lists by. Requiring that all blocklists must have https endpoints is not something I see as being an option.

**Comment by sneak** [comment]
I don’t use pi-hole. This is not a configuration issue. This is a security issue - you are shipping a default configuration that is vulnerable to a Denial of Service. 

Either the unauthenticated download should be removed, or your project should re-host it elsewhere securely. You are putting your users at risk through your vulnerable default configuration.

**Comment by sneak** [comment]
This is absolutely a security bug in your default configuration, btw.

**Comment by PromoFaux** [comment]
OK, revisiting this now that the dust has settled.

I'd appreciate the tone of this discussion be reasoned and measured going forward. I can appreciate that in some of the previous comments, people have been responding to the tone and not the content, that does not make for a very productive conversation.

### Where is the contention?
 - There exists the possibility that one of the lists in our _suggested_ defaults could be compromised by a MITM attack. 
 - We believe the quality of said blacklist to be good enough to include as a _suggested_ default.

### What are the possible solutions?
 - Remove the suggestion of this blacklist
 - Contact the maintainer of this blacklist and ask him for his input (middleground)
 - Do nothing

To be honest, the attack vector, whilst feasible, is low risk. The list could be manipulated by a bad actor in one of three ways:
 - Additional domains added to the list.
   - This one might provide the user with an annoyance more than anything, e.g blocking `google.com`, but that is not directly a security issue. The user can still whitelist the domain or remove the offending HOST list themselves.
 - A domain known for spreading malware is removed from the list
   - This would have the same affect a removing the list all together. 
   - If the domain still exists on even only one of the other lists, then it would still be blocked
 - The list is emptied, and a blank file is sent back
   - see above

From a pure security perspective, you cannot deny that it is insecure. But the risk is acceptable for our tolerances, i.e the _security_ of Pi-hole is not affected. Pi-hole has never been billed as a security product, it was designed as an adblocker. As an added bonus, the same method that is used to block ads can be used to mitigate potential issues with phishing and malware.

There is no attack vector that would end up in a user being redirected to a bad domain, or hijacked in any way. Sure, the list at it's source could be redirected/hijacked, but for the reasons mentioned above, the user is at no risk (other than the potential for some annoyance)

I have asked the maintainer of the list for his thoughts.

![image](https://user-images.githubusercontent.com/1998970/56154161-cfb26000-5faf-11e9-8817-02b59812d4d8.png)

As a final note, DNS is a powerful tool, and we make it easy for even those with little experience in networking. Maybe too easy. But we cannot hold everyone's hand the whole way. We have tried that before, but it is too difficult to try and predict all the ways in which an unassuming user could break things. /shrug

**Comment by sneak** [comment]
> Additional domains added to the list.

Anyone in the path between the pi-hole user and OVH hosting in France could potentially disable communication with emergency services (my mobile uses my IP network to make calls when I am at home).

This seems pretty serious to me.

**Comment by sneak** [comment]
> But we cannot hold everyone's hand the whole way. 

No, of course not. But you can ship secure defaults, so that without handholding, most users end up with a secure product.

> We have tried that before, but it is too difficult to try and predict all the ways in which an unassuming user could break things. 

One thing that is not too difficult is shipping a package that is not broken before the user touches it.

**Comment by PromoFaux** [comment]
>or a malicious list download can be mitigated after the fact with whitelisting, 

One could argue that domains that are system critical should be whitelisted _before_ the fact. If something as important as making emergency calls relies on DNS to even work, then the security-conscious user would (nay, _should_) already have something in place to mitigate any potential outages to this service.

 (Another conversation entirely, but I was under the impression that mobile phones could always make emergency calls, regardless of direct carrier connection.. but I have no personal experience with VOIP, so cannot speak to that)

>Trusting a list provider with that power is not the same as “trusting everyone in the path between me and that list provider”. That’s like two orders of magnitude more people who can make my 911 calls stop working.

I only _sort of_ agree with you here. How can I be sure that a list that is hosted behind a HTTPS connection does not have the same potential for malicious interference from someone other than the list owner? Not in transit, but there are a whole load of hypotheticals that could be the cause of the list that ends up at the Pi-hole installation not being the same as intended by the author. 

I'm torn, I really am. On the one hand I agree with what you're saying, even if it is on the edge of worst case scenario. On the other, I can't help but feel that the situation is not, in the grand scheme of things, as dire as it is being made out to be. 

Even if we removed the list from the install script now, it would not remove it when folk updated their Pi-holes to the newest version (as yet, there is no date set for the next release), as the update script does not touch the user's configured `adlists.list`. It would only be reflected in a fresh install.

I'm not sure we want to maintain the possibility of mirroring the list ourselves. That puts us in a position we certainly do not want to be in, lest we be accused of whitelisting/blacklisting certain services. (It happened with adblock plus, afterall!)

I would like to give the maintainer of this particular list a chance to chime in with his reason(s) for not having his list behind an HTTPS connection. And there is time for that. We don't have to make any rash decisions straight away. 

Please understand that I am not purposefully trying to butt heads with you here.  There is room for constructive discussion on this subject. But it is late, and I would do well to go to bed, rather than spend the night arguing with strangers on the internet. Maybe one of my more learned colleagues will entertain you whilst I am away.

**Comment by Mcat12** [comment]
> Anyone in the path between the pi-hole user and OVH hosting in France could potentially disable communication with emergency services (my mobile uses DNS and my IP network to make calls when I am at home).

> Trusting a list provider with that power is not the same as “trusting everyone in the path between me and that list provider”. That’s like two orders of magnitude more people who can make my 911 calls stop working.

Hopefully you are aware (you should be, it was already mentioned) that DNS is by default sent unencrypted. That means that even if we used only HTTPS lists, anyone in the traffic path of the DNS query can respond with their own IP address. Unless you use a process such as DNSSEC or DNSCrypt for securing/authenticating your DNS requests, your DNS requests are already insecure.

> Unless it is an undocumented design goal to let pi-hole be remotely and automatically reconfigured by people other than the list administrators, then this statement is not accurate.

Please refrain from using insults hidden behind innuendos to prove your points. I will refer you to what has already been said:
> I'd appreciate the tone of this discussion be reasoned and measured going forward.

**Comment by sneak** [comment]
> Please refrain from using insults hidden behind innuendos to prove your points.

Please constrain your accusations to my words and actions, and not things you erroneously believe I meany to imply.

**Comment by sneak** [comment]
> Hopefully you are aware (you should be, it was already mentioned) that DNS is by default sent unencrypted. That means that even if we used only HTTPS lists, anyone in the traffic path of the DNS query can respond with their own IP address. Unless you use a process such as DNSSEC or DNSCrypt for securing/authenticating your DNS requests, your DNS requests are already insecure.

This is irrelevant for the purpose of this discussion, and conflating it with the security issue reported here does a disservice to your users.

**Comment by dschaper** [comment]
Okay, we're done here.
