### ISSUE TITLE
Updated Fedora to 30 and Pihole stopped working

### ISSUE THREAD

**Issue by SgtBauerFR** [pi-hole/pi-hole#2731]
**In raising this issue, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Pihole running on Fedora 30`

**Actual behaviour:**

`DNS service not running & FTL offline`

**Steps to reproduce:**

`upgrade from Fedora 29 To 30 with a working pihole`

`$ sudo dnf --refresh upgrade`
`$ sudo dnf install dnf-plugin-system-upgrade`
`$ sudo dnf system-upgrade download --releasever=30`
`$ sudo dnf system-upgrade reboot`
`$ rpm --rebuilddb`
`$ dnf distro-sync --setopt=deltarpm=0`
`$ dnf install -y rpmconf`
`$ rpmconf -a`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`https://tricorder.pi-hole.net/i79icp8tz9`

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

**Comment by Mcat12** [comment]
Note that we do not currently support Fedora 30: https://docs.pi-hole.net/main/prerequesites/

**Comment by SgtBauerFR** [comment]
Is there any chance you support Fedora 30 for the next milestone?

**Comment by Mcat12** [comment]
We are working on compatibility, though it will probably happen in v5.0 (v4.3 is about to release).

**Comment by bcambl** [comment]
Hey @SgtBauerFR, Yes, we will definitely be supporting Fedora 30 in a future release after some additional testing. Were you able to get your installation/upgrade to complete successfully?

I recently downloaded and installed a fresh copy of _Fedora 30 Server_ from the official site (https://getfedora.org/en/server/) and I was able to install the project without any issues.

I am curious as to what your issue is but unfortunately your debug token/info has expired since we do not keep debug data very long for security purposes. If you are still having issues, perhaps you could provide another token. I may have some additional questions about your installation but a fresh debug token would be a good starting point.

**Comment by SgtBauerFR** [comment]
Not yet, I also use the Pihole host server for Samba sharing, so I don’t want to start from scratch with a new copy of fedora 30.

Pihole was up and running with the 29, and I just upgraded my system with the commands above, nothing else.

***********************************
[✓] Your debug token is: https://tricorder.pi-hole.net/3npnojip9i!
***********************************

I hope this new debug token can be useful, in any case thank you @bcambl

**Comment by SgtBauerFR** [comment]
Solved =)

`$ pihole -r`

**Comment by bcambl** [comment]
Thanks letting us know. I will close this issue :)
Cheers!

**Comment by q2dg** [comment]
> Hey @SgtBauerFR, Yes, we will definitely be supporting Fedora 30 in a future release after some additional testing. Were you able to get your installation/upgrade to complete successfully?
> 
> I recently downloaded and installed a fresh copy of _Fedora 30 Server_ from the official site (https://getfedora.org/en/server/) and I was able to install the project without any issues.
> 
> I am curious as to what your issue is but unfortunately your debug token/info has expired since we do not keep debug data very long for security purposes. If you are still having issues, perhaps you could provide another token. I may have some additional questions about your installation but a fresh debug token would be a good starting point.

It's strange because I've tried to do the same and I've had an error when trying to install "chkconfig" package. It seems a problem of internal dependencies on Fedora system, because the error message is "File Unpacking  has failed in /etc/init.d : cpio: File from package already exists as a directory in system" . Sadly, this prevents me from be able to use Pi-Hole
