### ISSUE TITLE
Whitelist/blacklist domain - allow pasting entire urls in web interface

### ISSUE THREAD

**Issue by tkafka** [pi-hole/pi-hole#2745]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

`I can paste the entire link to a content I don't want to block into the whitelist, and Pihole will extract the domain automatically.`

**Actual behaviour:**

`Pasting the entire url will produce this error:`

<img width="832" alt="Screenshot 2019-05-12 16 39 45" src="https://user-images.githubusercontent.com/876717/57583808-9567b000-74d4-11e9-99fc-af873f8668a1.png">

**Steps to reproduce:**

`Paste the entire url into a whitelist/blacklist form field`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`n/a`

**Troubleshooting undertaken, and/or other relevant information:**

`n/a`

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Thank you for your understanding.

My personal opinion is that we shouldn't allow this. Users may expect that only the path they added will be blocked if Pi-hole does not complain.
