### ISSUE TITLE
Add description to dhcp server

### ISSUE THREAD

**Issue by Net-Felix** [pi-hole/pi-hole#2794]
Would it be possible to add a description field to the dhcp server static leases?

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
