### ISSUE TITLE
Bug: Settings - Blocklist

### ISSUE THREAD

**Issue by ambiguu** [pi-hole/pi-hole#2795]
Hello, from an mistake I've just added in Blocklist that url: https://*.youtube.com and now it is impossible to delete that url.

**Comment by dschaper** [comment]
Please fill out the issue template with the requested information, we need to know a lot more to be able to assist you and the template is meant to help with that.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
