### ISSUE TITLE
pihole web feature request

### ISSUE THREAD

**Issue by rrrevin** [pi-hole/pi-hole#2804]
On both the whitelist and blacklist screens, it would be immensely beneficial to add a "date/time" added column to each entry.

I know I do this all the time when surfing. A a whitelist here and there to see if it works or not. If it doesn't fix what I want I go back in and remove the entry.

By adding a date/time column that can be sorted, it makes it VERY easy to quickly back out of changes  to remove recent additions.

Much easier then having to remember what you added and scroll through a list of possibly hundreds of entries to find it.

If not possible perhaps a new option of "last 25 entries added" for each to make removing them easy to find.

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

To address your point: This will be added by the new web interface which is currently under development. From Pi-hole v5.0 on, we store all domain data in a structured database. For each domain, we will not only store when it was added, but also allow to add arbitrary comments (e.g., why you added it) and when it was last modified (enabled/disabled, comment changed, ...).

Thank you for your understanding.
