### ISSUE TITLE
gpgconf error after install pi hole

### ISSUE THREAD

**Issue by Nastras** [pi-hole/pi-hole#2842]
Hello, I have pi hole installed today. I have a script on the run which reports errors. After the installation, I get this error after every restart:
 systemd[2340]: gpgconf: running /usr/bin/gpg-agent failed (exitcode=2): General error

Without Pi hole installation, the error does not occur. My OS is Rasbian Buster on a Pi4

Can you tell me where the problem is?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by Nastras** [comment]
Sorry, my English is not so good that I can fill out your form. Great project what you have. I was hoping that you can help because the error appears right after running the install script. Maybe it's a bug.

King Regards

**Comment by dschaper** [comment]
Start a thread over on https://discourse.pi-hole.net, we have a section for German speakers if that is your preferred language.

**Comment by Nastras** [comment]
That's a great tip. I will try it there thank you!
