### ISSUE TITLE
is it possible to add DNSCrypt-Proxy and ChinaDNS?

### ISSUE THREAD

**Issue by crystalsis** [pi-hole/pi-hole#2883]
I am sorry that my english is poor.
And I want to ask that is it possible to add the "DNSCrypt-Proxy" and "ChinaDNS" for the special china internet environment?

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Alternatively, you can open a pull request for your feature to get reviewed.

Thank you for your understanding.
