### ISSUE TITLE
Can't connect to other networks after installing pi hole.

### ISSUE THREAD

**Issue by skashish** [pi-hole/pi-hole#2923]
Operating system: Debian 10 Buster

I installed pi-hole on my system using `curl -sSL https://install.pi-hole.net | bash`

Now, pi-hole is successfully blocking ads on all the devices on my home network but now I am not able to connect to internet on other networks ( say, like mobile network)

 I think this is because pi-hole has set my static ip as 192.168.1.xxx but mobile network is not able to run on that. 

How can I configure to run internet on mobile network also along with home network?

**Comment by dschaper** [comment]
Since this isn't a bug but instead a user configuration question please visit https://discourse.pi-hole.net for support.

--
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
