### ISSUE TITLE
Question:  why am I seeing loads of queries made by the router to www.tp-link.com ?

### ISSUE THREAD

**Issue by marxenegls** [pi-hole/pi-hole#2982]
ntp server at 0.europe.ntp , there's no mail service set up nor remote access and i'm using noip.com as dyndns - router has a static ip .
has anyone else noticed a similar behavior ?
even if i would blacklist it, still is a lot of traffic . 
firmware upgrades won't query www.tp-link.com, i wouldn't think so and certainly not 4 x a minute
![Opera Snapshot_2019-10-28_235552_raspberrypi00b local](https://user-images.githubusercontent.com/6319093/67724547-b028d500-f9df-11e9-90ae-f7470e6eab2e.png)

**Comment by marxenegls** [comment]
thank yous for nothing , i've always took care of my own miseries .. pihole is over rated anyways too much husstle pi could be used for other project ublock is more than enough for me

**Comment by PromoFaux** [comment]
Hi there, apologies for not instantly answering your question, forcing you to have to denounce us so dramatically.

Admittedly I read it before, but was knee deep in some other stuff at the time.

Your router is asking what the address for www.tp-link.com is, because it would like to know. Why would it like to know? Honestly, I have no idea, because it's your router and I don't know what kind of things it is doing. But it is certainly not an issue with Pi-hole, rather Pi-hole is just revealing what your router is doing. Might not even be a problem, per se, with the router. It could just be something a tp-link does. Maybe it's lonely? Who knows.

PS. We are all volunteers on this project, we can't immediately respond to every question every time. Honestly, a couple of days ain't bad going! 

Life is far too short.

**Comment by diginc** [comment]
I believe TP Link's firmware detects if the internet is working with requests like this.  They could be doing more than that or connectivity checks maybe all.
