### ISSUE TITLE
Is the logfile written directly to the SD card?

### ISSUE THREAD

**Issue by ruda-almeida** [pi-hole/pi-hole#302]
I have a Raspberry Pi B running Raspbian Wheezy -- I just imaged an SD card and then installed pi-hole, nothing else. 

Looks like for *each DNS request*, a line gets written into `/var/log/pihole.log`. Depending on usage, it can happens hundreds of times per minute, all day long.

I wonder if it could wear out the lifetime of the SD card. I know log files are being truncated on a daily cron, but inbetween days, do each request is directly written to the SD card?

I know solutions like DietPi put the log files in ramfs or something similar. What's the approach here?

**Comment by PromoFaux** [comment]
We currently are not mitigating SD card writes, although it's certainly not impossible to look into setting up. 

I actually moved the filesystem to a USB stick today using [this script](https://learn.adafruit.com/external-drive-as-raspberry-pi-root/hooking-up-the-drive-and-copying-slash) to save my SD card from constant writes.

**Comment by fayetted** [comment]
If the user setup a USB Drive for /var or /var/log before installing pi-hole this would be mitigated without any change to the install process, provided I understand the intent here.

In order to automate this for the user you could check to see if there was a USB disk present and then prompt the user to a. Write the log file to this partition. b. Move /var/log to this partition.

Option a. is trivial, option b. is not hard, just a little more work than option a.

The biggest concern I see with either approach is that dnsmasq will not start if the log file can't be written too.  I just changed my log file from /var/log/pihole.log to /v/log/pihole.log and tried to restart.  The service stops, but then doesn't start.  Again I see 2 obvious options, a. Service fails and user is left to figure it out. b. Service startup script is modified to check for the log file to exist and be writable and if it's not then it reverts back to /var/log/pihole.log.  If the 2nd attempt doesn't work, you could try writing to /tmp/ or disable logging in order to ensure that the service starts.

Lots of options here, I think it just boils down to a design decision.  I'm willing to look into any/all of these options.

**Comment by PromoFaux** [comment]
I think the simplest approach from our end would be to utilise tmpfs/ramfs. Though, it would be hardly nessacery on a non-SDcard based installation. I've actually got my installation of pi-hole running on my debian media server instead of the RPi now, so the USB check would be pointless.

It really comes down to user preference, and rather than automating it, I think a well documented wiki page on how to mitigate SD-card corruption would suffice.

**Comment by dschaper** [comment]
In the startup days of the RPi, SDCard corruption was a big issue. It's really not that big a problem anymore, and the Foundation is already testing a new SDCard interface. Once the bugs are worked out it should be rolled out to the masses through apt-get updates. You're really not going to overwork your uSD to past it's useful life, but you do have to worry a bit about brownouts or unplanned power outages, and even then you have to be unlucky enough for the event to happen right during a write to the uSD. We had a request earlier about how to get Pi-hole working in a read-only boot/root configuration, but that's low on the list of things to do, as any user that want's to go to that extreme is likely capable of doing the configuration themselves without us automating the process...

**Comment by NeroTux** [comment]
I have moved my whole /var/log to tmpfs. AFAIK this runs pure in memory, so no more excessive writes to the sd card.

**Comment by jacobsalmela** [comment]
Closing.
