### ISSUE TITLE
teleport hardcoded path

### ISSUE THREAD

**Issue by dumaresq** [pi-hole/pi-hole#3042]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*.
- [] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

1

---
**Expected behaviour:**

# pihole -a teleporter
# tar -tvzf pi-hole-teleporter_2019-12-14_08-07-32.tar.gz
-rw-r--r-- 0/0               0 2019-12-14 08:07 whitelist.txt
-rw-r--r-- 0/0               0 2019-12-14 08:07 blacklist.txt
-rw-r--r-- 0/0             313 2019-12-14 08:07 adlists.list
-rw-r--r-- 0/0             402 2019-12-14 08:07 setupVars.conf
-rw-r--r-- 0/0              62 2019-12-14 08:07 auditlog.list
-rw-r--r-- 0/0               0 2019-12-14 08:07 regex.list
-rw-r--r-- 0/0             492 2019-12-14 08:07 dnsmasq.d/02-pihole-dhcp.conf
-rw-r--r-- 0/0            1744 2019-12-14 08:07 dnsmasq.d/01-pihole.conf
-rw-r--r-- 0/0            2735 2019-12-14 08:07 dnsmasq.d/04-pihole-static-dhcp.conf
-rw-r--r-- 0/0             210 2019-12-14 08:07 dnsmasq.d/10-pihole-dhcp-extra.conf

**Actual behaviour:**

#  pihole -a teleporter
#   tar -tvzf pi-hole-teleporter_2019-12-14_08-21-34.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
#  cat pi-hole-teleporter_2019-12-14_08-21-34.tar.gz
Could not open input file: /var/www/html/admin/scripts/pi-hole/php/teleporter.php

**Steps to reproduce:**
Run pi-hole -a teleporter  (but do not have your php scripts under /var/www/html

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**
This should not be needed :)

**Troubleshooting undertaken, and/or other relevant information:**

`{Steps of what you have done to fix this}`

Symlinked /srv/http/pihole/ to /var/www/html

This should probably be fixed by replacing the hard coded path on line on 542 of webpage.sh with a parameter that you can pass in  (ie pihole --path <somepath> -a teleporter)

**Comment by dschaper** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net). 

Thank you for your understanding.

**Comment by BlackLight** [comment]
I've bumped into this issue as well, and found the root cause too - in [`webpage.sh:653`](https://github.com/pi-hole/pi-hole/blob/853f6b7da2b5130e33d76840f463ab374eb77596/advanced/Scripts/webpage.sh#L653).

The `/var/www/html` prefix is basically hardcoded in the script. No wonder that teleporter fails unless the web server pages are deployed _exactly_ in that path - which is a quite big assumption, to say the list.

So I would reformulate the title of this issue as "_Teleporter doesn't work (at all) unless you are serving the PHP files from `/var/www/html`_".

This sounds much more like a bug to me rather than something that is supposed to be discussed on a forum. And it's also a relatively trivial one to solve (the process can probably access the webserver root location from the environment), so I'm surprised that it hasn't been tackled in ~3 years.

**Comment by dschaper** [comment]
The assumption was made because that is where we install the files. If you have made modifications to change that path then you may want to modify that script along with the other modifications needed to move the webroot. 

Bug? Not really. Trivial change, possibly, we'd welcome a PR to make those modifications.

**Comment by BlackLight** [comment]
> If you have made modifications to change that path

Not really. I have a vanilla installation on Arch made via AUR, and Arch (like several other systems) installs web files under `/srv/http` instead of `/var/www/html`. It sounds to me like a `WEBROOT` environment variable would solve any hardcoded paths issues.

**Comment by dschaper** [comment]
https://aur.archlinux.org/packages/pi-hole-server?O=10&PP=10#comment-633053
