### ISSUE TITLE
Feature Request: FQDN UI

### ISSUE THREAD

**Issue by cyrus104** [pi-hole/pi-hole#3064]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`1`

---
**Expected behaviour:**

`Would like a new page that shows and allows for the addition and modification of FQDNs. I am using Pi-Hole as my primary DNS in a couple of small home and lab environments and I would like to be able to make some changes to the internal FQDNs but have to SSH in everytime I want to make these changes or check to see if there is an issue.`

**Actual behaviour:**

`None`

**Comment by DL6ER** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net), as mentioned in our [Issue Templates](https://github.com/pi-hole/pi-hole/blob/master/.github/ISSUE_TEMPLATE.md).

Feel free to add details (what do your do exactly when sshing to your machine) so it gets exactly clear what you'd like to be added.

Thank you for your understanding.
