### ISSUE TITLE
Dev - DB - Gravity Table - Is there a better way for Gravity to store domains?

### ISSUE THREAD

**Issue by mmotti** [pi-hole/pi-hole#3084]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behaviour:**

Gravity gathers domains and stores efficiently in the sqlite3 database with no need for duplicate entries.

**Actual behaviour:**

Gravity gathers domains and stores duplicate domains as they are technically "unique" in terms of which adlist they appear in (`adlist_id`).

I understand that this would be potentially a lot more involved and may affect things like joins (my db knowledge isn't fantastic), but would it not make sense to try storing ids in `adlist_id` in the following format: `1,2,5,6`?

This may not be an issue so much for users with a small amount of blocklists (e.g. the default ones), but so many people seem to see "bigger is better" when it comes to this kind of thing and it's not uncommon to see people with millions of domains across many blocklists.

I have seen instances of 4M+ unique domains where the gravity table grows to be in excess of 8M+ entries because of how things are currently stored. This must have some form of performance impact somewhere, seeing as the processing is mostly done on small devices like Raspberry Pis.

**Steps to reproduce:**

1. Have an accumulation of blocklists that have many of the same domains between them
2. Run gravity update

**Comment by PromoFaux** [comment]
>  but would it not make sense to try storing ids in adlist_id in the following format: `1,2,5,6`

I think what you are suggesting here is that the `adlist_id` column should, instead of being an `integer` type, should be a string, so that we may point to multiple adlists for the same domain.

This would not be as performant, as far as I can see...

pseudo example `SELECT * FROM gravity WHERE adlist_id = 1` would be better than, say, `SELECT * FROM gravity WHERE adlist_id like '%1%'`

Now.. one thing that has just crossed my mind, is that we could store them slightly differently and add another table, something like a domains table (constraint on each domain being unique, each with a primary key) and then a linking table that tells us which domains are part of which adlists

With an example maybe being that `adlist1` contains two domains, `example.com` and `example2.com`, and `adlist2` contains just one domain, `example.com`, then we could store it as such:

|id|adlist|
|:--|:----|
|1|adlist1|
|2|adlist2|


|id|domain|
|:--|:-------|
|1|example.com|
|2|example2.com|


|adlistId|domainId|
|:--------|:---------|
|1|1|
|1|2|
|2|1|

With the actual characters for `example.com` only being stored once, but referenced by two lists.

This is all probably a bit rambly and would need further exploration, but I'm not sure it would provide us with _much_ of a performance gain, if any...

**Comment by DL6ER** [comment]
> This must have some form of performance impact somewhere, seeing as the processing is mostly done on small devices like Raspberry Pis.

Yes, but the impact is only storage (which is usually abundant). Gathering the unique domains in the form you suggest would make `gravity` **way** slower. Instead of mass-injections of the domains for each imported blocking list, we'd need to `SELECT` each domain individually and then decide whether we want to `UPDATE` (append to the `1,2,3` string) or `INSERT` a new domain into the list.

Note that there is an index on the pair `(domain, adlist_id)` in the `gravity` database. This has the enormous benefit of making searched **very efficient**. Comparing to @PromoFaux's suggestion, I chose the current implementation as this allows the usage of
```sql
SELECT EXISTS(SELECT domain from gravity WHERE domain = ? AND group_id IN ?);
```
The `SELECT EXISTS()` compiles down to very efficient byte-code merely working on the table index only, not even touching any of the stored domains **at all*.

I see two drawbacks of a linking table approach: First, we'd need to generate two entries for each unique domain instead of only one. And, secondly, we'd need to take a second step in order to check whether the current `adlist` is even enabled for the current client. All this is avoided with my current implementation utilizing the index containing both details at the same time.

**Comment by DL6ER** [comment]
And concerning the size, the utilized [B-tree}(https://en.wikipedia.org/wiki/B-tree) shortens the time needed to do lookups from roughly O(n) [full table search] to roughly O(log_2 n).

Given your number of 8M domains, this means that storing the information how we do it now (with a possible lot of duplicates) only increases the number of actually happening lookups by 1, 2 or (at worst) 3. And this is not "three times". It is "three additional lookups". This is negligible.
