### ISSUE TITLE
REQUEST: DNS Servers

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#309]
add level 3 DNS servers: 4.2.2.1, 4.2.2.2. also add the ability to key in your own dns servers during install

**Comment by PromoFaux** [comment]
Hey, thanks for the request. We're currently looking into adding in additional upstream DNS servers, and the ability to add your own, so this will definitely be looked at!

**Comment by fulljackz** [comment]
Hi,I was thinking about this solution. I personnaly use others dns than google or open dns. I thought to create a flat text file with many entries and give to user the choice during installation. If this can be a solution, I could give it a try and PR it.

**Comment by slamanna212** [comment]
I added 3 more to the basic install script here: https://github.com/pi-hole/pi-hole/pull/318

Personally, i used https://code.google.com/archive/p/namebench/ and am using Comcast servers close to me as they are the fasted for me

**Comment by slamanna212** [comment]
I added 3 more to the basic install script here: https://github.com/pi-hole/pi-hole/pull/319

Personally, i used https://code.google.com/archive/p/namebench/ and am using Comcast servers close to me as they are the fasted for me

**Comment by DonLexos** [comment]
This will be in the next release afaik.

**Comment by dschaper** [comment]
So how will this be implemented, remember we have limited space with Whiptail dialogs, so at some point we need to cull the herd or add a FAQ that lists the upstream DNS servers out there to be used, and let the user input the addresses in the Whiptail instead of selecting from a list?

(And depending on load, I may open up my DNSCrypt wrapped DNSSec primary server for use, I need to see what kind of traffic that would generate and make absolutely certain it can't be used for DDOS'ing, I don't keep logs...)

**Comment by DonLexos** [comment]
This is in 2.5.3 :-)
