### ISSUE TITLE
Feature Request: Only Cache Blocked Domains

### ISSUE THREAD

**Issue by dMopp** [pi-hole/pi-hole#3133]
Hi,

since iam using unbound as my root-DNS resolver in background, i would like to use dnsmasq cache only for blocked domains, is that possible? (Maybe as an Option for people using multiple cache layers)

Thx :)

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not fill out the Issue Template and do not provide debug tokens when possible. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

### All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
