### ISSUE TITLE
OpenDNS does NOT support DNSSEC

### ISSUE THREAD

**Issue by dmnc-net** [pi-hole/pi-hole#3143]
https://github.com/pi-hole/pi-hole/blob/e41c4b5bb691cea1f5b950d39518d8c404b5846e/automated%20install/basic-install.sh#L34

it should be labeled as `no DNSSEC`

background info: [OpenDNS DNSCrypt](https://www.opendns.com/about/innovations/dnscrypt/), my Reddit [post](https://www.reddit.com/r/pihole/comments/f5q0h2/bogus_domain_status/)

**Comment by dschaper** [comment]
Shouldn't be a problem to enable DNSSEC with an upstream resolver that does not support it. You'll just get back responses from the upstream without any of the DNSSEC flags set. 

Can you post a debug token and we can take a look?

**Comment by HalfBit-hacks** [comment]
OpenDNS does support DNSSEC now: https://support.umbrella.com/hc/en-us/articles/360039414411-DNSSEC-General-Availability

**Comment by yubiuser** [comment]
Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

The relevant feature request on discourse: https://discourse.pi-hole.net/t/in-gui-note-on-opendns-support-for-dnssec/36500
