### ISSUE TITLE
pihole -up: FTL update available, but is not

### ISSUE THREAD

**Issue by corbolais** [pi-hole/pi-hole#3176]
- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I am reporting isn't a duplicate
  - issue pi-hole/FTL#245 seems unrelated (no DNS error in the logs, nor any other error for that matter)

**How familiar are you with the codebase?:**
not applicable

---

**[BUG | ISSUE] Expected Behaviour:**
FTL new release available: do _really_ update.
No new FTL release available: do not tell there is an update.

**[BUG | ISSUE] Actual Behaviour:**
- pre-update FTL release: **v4.3.1**
- No new FTL release available (as per https://github.com/pi-hole/FTL/releases)
- though `pihole -up` states FTL update available
- after update: Current FTL version is **v4.3.1**

**[BUG | ISSUE] Steps to reproduce:**
- `pihole -up`

**Log file output [if available]**

>   [i] FTL:              update available
>   Update Complete! 
> 
>   Current Pi-hole version is v4.4
>   Current AdminLTE version is v4.3.3
>   Current FTL version is v4.3.1

/etc/pihole/install.log: Nothing related to FTL.

**Device specifics**

Hardware Type: rPI 3, x64
OS: raspbian, Debian

**Comment by PromoFaux** [comment]
Please can you run the following:

`bash -x /opt/pihole/update.sh` and paste in the output?

also a debug token using `pihole -d` would be handy, too. Thanks!

**Comment by corbolais** [comment]
update.sh: exec w/o -x as output is long and wants to be filtered first (but not now)
  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date

  [✓] Everything is up to date!

pihole -d: maye this weekend.

Please let me know whether you _really_ need more data. Or rather I'd prefer you tell me what to look out for (high level stuff, as indicators), for me as hints where to dig deeper (no worries, have a big scoop'n'gloves at hand) ;-)

**Comment by PromoFaux** [comment]
Well, I would have liked to have parsed over the `bash -x` output of `update.sh` as that would give me clues as to what was going wrong in the update script (it's the same script that `pihole -up` runs) 

However, from the output it seems as though your original issue is solved... can you run a `pihole -up` again please, to see what kind of output you get?

As you are on Core 4.4, you should already have the fixes in place that fixed the phantom "[i] FTL: update available" message, which is why I was curious to see what the -x gave.

**Comment by droleary** [comment]
Probably related, FTL just failed on me for a fresh install.  Debugging basic-install.sh, it appears that critical headers from GitHub.com have switched to lowercase, causing this line to fail:

    latesttag=$(curl -sI https://github.com/pi-hole/FTL/releases/latest | grep "Location" | awk -F '/' '{print $NF}')

my temp fix was to do:

    latesttag=$(curl -sI https://github.com/pi-hole/FTL/releases/latest | grep "[Ll]ocation" | awk -F '/' '{print $NF}')

Don't know if the change on the server is permanent and affects updates as well, and don't know the code base well enough to know if a better fix should be pushed.

**Comment by corbolais** [comment]
@PromoFaux Thanks for coming back to me that quick.

The issue arose while updating to v4.4. pihole -up tells me exactly the same now as bash /opt/pihole/update.sh in my previous msg. So far so good.

I'm sorry, I cannot provide you with any debug output pre-v4.4-update, when the issue was showing. I had a glance at the files in /var/log/pihole but nothing sparked my interest in those files.

I ignore whether the fix @droleary reported is already included somehow in v4.4 or whether it is something that remains todo on top of v4.4, yet.

@PromoFaux do you have an idea what it was that fixed the "phantom" message in v4.4? I'm curious as you asked for what made pre-v4.4 fail. What could have caused it in the first place, as you seem in the know that v4.4 contains a fix for the "phantom" message.

**Comment by PromoFaux** [comment]
My mistake, it was actually 4.3.5 that fixed it (we had a short run of releases whilst getting to the bottom of failed FTL installs)

https://github.com/pi-hole/pi-hole/commit/b4c2bf678f4715da45cd22dcf56ca68d1a877112#diff-689793e68cde6270d074695b71c969afR2387

And @droleary is along the right lines. The way we fixed it was to add `-i` to the `grep` command, to make it case insensitive.

@droleary, i'm not entirely sure how you had this issue on a fresh install... did you use the `curl` command to install? Because that should not have failed! `basic-install.sh` on the `master` branch has the fix included:

https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L2387

**Comment by corbolais** [comment]
Thank you.

Had a chuckle at the `grep -i` solution, which is of course fastest, easiest and best solution for this issue. :-D

**Comment by droleary** [comment]
@PromoFaux Sorry if I caused any confusion.  The "fresh" install was actually a reinstall from a repository clone I had locally, but failed to do a pull before I rushed to get my pi-hole working again.  I see it now, of course; I won't be making that mistake again!

**Comment by PromoFaux** [comment]
Happens to the best of us!

So, I think we are all resolved and can close this out now?
