### ISSUE TITLE
HOST resolution in progress | after PiHole update

### ISSUE THREAD

**Issue by CloudItaly** [pi-hole/pi-hole#3232]
Hello! Today i have update my PiHole [Pi-hole Version v4.4 Web Interface Version v4.3.3 FTL Version v4.3.1] on my Ubuntu 1804Vps. 
Since this event, my browser don't load correctly the page because i read the status "**host resolution in progress..."**

How can i resolve this?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
