### ISSUE TITLE
Default lighttpd page displayed

### ISSUE THREAD

**Issue by jradwan** [pi-hole/pi-hole#329]
Back when the web interface was first released, there was a url.rewrite in lighttpd.conf so that if you just hit the Pi-Hole's web address you would get a blank page (issue #31). It looks like at some point this was removed so now I get the default lighttpd web page if I go directly to my RasPi's IP address in a browser (without the admin/ stuff). Not a big deal but was just wondering why this had been changed.

**Comment by jradwan** [comment]
Looks like this was changed in a Jan 17 commit (not sure how to link to those).

**Comment by dschaper** [comment]
If you do a `tail -f /var/log/lighttpd/access.log` you'll see all the URL's that are handled by `lighttpd`. Since we can't predict what URL a website will be serving as an advertisement, we have to respond to all requests with the replacement webpage. (A blank webpage in the default installation.) We changed to using a 404 response since almost all of the URL's that the Pi-hole will be serving don't exist, so 404's are generated and the 404 page is the blank html file.

**Comment by dschaper** [comment]
And you should be able to link to a commit by just typing in the first 8 or so characters of the hash for the commit. GitHub will automatically substitute in the link to the commit with that hash.

**Comment by dschaper** [comment]
Just a quick test but this should link to a commit c4fc2e089d

**Comment by jradwan** [comment]
Thanks for the commit linking tip. Here's the commit that removed the url.rewrite, for example: ede8f47

But my point here is that a blank page does NOT seem to be the default anymore. I get the lighttpd placeholder page. Maybe I'm missing something obvious. The IP of my RasPi is 192.168.1.66. If I put that into a browser on the local network, I get that placeholder page, NOT a blank page as I would have expected.

**Comment by dschaper** [comment]
We did that so that people who are running other webserver services on their Pi's were able operate. If you visit `http://192.168.1.66` you will get the `index.html` that is the default one shipped with `lighttpd`. If you visit any other page like `http://192.168.1.66/advert.html` then you'll get the blank page. The only time you will get the default page is if you specifically look for `index.html` which is an edge case. Visiting `http://192.168.1.66` will give you that default `index.html` as you have seen. Any advert should trigger the 404 as they won't be for `index.html`. I do suggest running that `tail` command so you can see all the different URL's that are being requested in place of advertisements.

**Comment by jradwan** [comment]
Ok, that makes sense. I'm familiar with tail'ing the log and do see all the redirects happening, I was just confused by the appearance of the placeholder. Maybe I'll replace it with a redirect to the admin page or another customized page for the Pi-Hole. Thanks.

**Comment by dschaper** [comment]
No problem, that's kind of why we made that move, it allows the end user to configure it how they want, and not how we think it should be.
