### ISSUE TITLE
Cameleon link in `basic-install.sh` should be https

### ISSUE THREAD

**Issue by essandess** [pi-hole/pi-hole#3322]
This link should be TLS secured:
```
        Cameleon     )  echo "https://sysctl.org/cameleon/hosts" >> "${adlistFile}";;
```

https://github.com/pi-hole/pi-hole/blob/9e490775ff3b20f378acc9db7cec2ae6023fff7f/automated%20install/basic-install.sh#L1199

**Comment by PromoFaux** [comment]
Thanks for the pointer :)

This link has actually been removed in the upcoming v5.0, as the list is no longer maintained.

**Comment by essandess** [comment]
Thanks. Does this fall under the category of not-maintained-but-still-useful?

A quick sample shows that a ton of those domains are still active, and the overhead of keeping a domain hash is quite small.

**Comment by essandess** [comment]
I see from this comment that this unmaintained list nevertheless has over 8k active domain not found on other lists.

https://github.com/pi-hole/pi-hole/pull/3287#issuecomment-617710728

**Comment by dschaper** [comment]
You'll still be able to add any list you find useful to your Pi-hole install.

**Comment by PromoFaux** [comment]
The default lists are only ever meant as suggestions to get started, we don't want to tell users what to/what not to block, it's especially useful for people totally new to the idea of ad blocking - so that they don't install Pi-hole and wonder why they are still seeing ads.

As fan mentioned, users are free to add or remove any lists they feel suit them.
