### ISSUE TITLE
Link to original blog post in README is a dead link

### ISSUE THREAD

**Issue by adrienball** [pi-hole/pi-hole#3338]
**In raising this issue, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate

**Description**
In the Origin Of Pi-hole section of the README, the link https://jacobsalmela.com/2015/06/16/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/ is a dead link.
I would love to read this blog post, does it still exist somewhere?

Thanks !

**Comment by PromoFaux** [comment]
Huh, Looks like Jacob has removed it. It's a good read if you want to understand the original incarnation of Pi-hole, though as was noted at the top of the article, Pi-hole as it is now has come on so far since then that the guide is no longer accurate.

It still exists on the wayback machine if you want to take a read https://web.archive.org/web/20200413111320/https://jacobsalmela.com/2015/06/16/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/

**Comment by adrienball** [comment]
Thanks!
