### ISSUE TITLE
Codespell report for "Pi-hole" (on fossies.org)

### ISSUE THREAD

**Issue by jschleus** [pi-hole/pi-hole#3361]
Since you encourage to report also typos here a list of some few spelling errors and typos that the server "[fossies.org](https://fossies.org/features.html#codespell)" have found with the help of the tool "[codespell](https://github.com/codespell-project/codespell)":

 https://fossies.org/linux/misc/dns/pi-hole-5.0.tar.gz/codespell.html

If it would make sense I could also implement a "continuous" check of the current master version.
But that would be done within a restricted special test folder that isn't fully integrated into the standard Fossies services.

**Comment by PromoFaux** [comment]
I wonder if there is something we can implement using Github Actions, that checks Pull Requests and the `development` branch

**Comment by jschleus** [comment]
Not the optimal solution and probably not what you want but fossies.org can offer a report at

 https://fossies.org/linux/test/pi-hole-development-snap.tar.gz/codespell.html

That testwise realized URL should always redirect to a codespell report for the current `development` branch (currently with a delay of max. 30 mins). As an additional information that page contains also a spelling error history report.

**Comment by dschaper** [comment]
https://github.com/codespell-project/codespell/issues/1499

**Comment by jschleus** [comment]
Oh, nice information. That are very interesting and promising approaches.

**Comment by peternewman** [comment]
Hi @dschaper / @jschleus ,

Glad you found that, given it seems to work already, feel free to just go with it if you want.

You just need a workflow file like this:
https://github.com/peternewman/actions-codespell/blob/master/.github/workflows/testing.yml

But change `uses: ./` to `uses: peternewman/actions-codespell` and it should just work.

I'm going to add more options soon (or they're as simple as this https://github.com/TrueBrain/actions-flake8/pull/9/files ), and I expect move it to the codespell-project organisation/publish on Marketplace etc.

Are there particular codespell arguments you need to make it work for you?

**Comment by dschaper** [comment]
Thanks for the note, @PromoFaux if you want to investigate?

**Comment by peternewman** [comment]
Just to let you know, the repo is now transferred, so please use https://github.com/codespell-project/actions-codespell going forward.

**Comment by yubiuser** [comment]
Pinging @PromoFaux

**Comment by PromoFaux** [comment]
@peternewman Apologies for this taking me sooooo long to look into. Not really sure where time went there.

Would you mind taking a look over #4713, please, and letting me know if I've done something wrong with the `.codespellignore` file? It seems that it is working for one entry (`doubleclick`) but not the others. Any pointers apperciated!

**Comment by PromoFaux** [comment]
Same with this one: https://github.com/pi-hole/docs/pull/692

It is ignoring some words that are on the ignore list and complaining that they are spelled wrong 🤷

**Comment by PromoFaux** [comment]
Ignore both previous comments - turns out if you pass them in as lowercase then it will work (tried locally using `act` to confirm)

**Comment by peternewman** [comment]
> Ignore both previous comments - turns out if you pass them in as lowercase then it will work (tried locally using `act` to confirm)

It's not lower-case per-say, as per the readme:
> Important note: The list passed to -I is case-sensitive based on how it is listed in the codespell dictionaries.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/pi-hole/releases/tag/v5.11

**Comment by jschleus** [comment]
Great, but still here a somewhat nitpicking comment: Although codespell-action seems now in use Fossies founds still some few typos, see the reports for the current release

https://fossies.org/linux/misc/dns/pi-hole/codespell.html

or for the "continously" analysed development branch

https://fossies.org/linux/test/pi-hole-development.tar.gz/codespell.html

**Comment by yubiuser** [comment]
Thanks for the "nitpicking" report. Should be fixed by https://github.com/pi-hole/pi-hole/pull/4802
___

@peternewman 
Those undetected mistakes were all in comment lines (starting with #). Is there a way to signal the action to analyse those lines as well?

**Comment by jschleus** [comment]
Perfect, from codespell point of view!

**Comment by peternewman** [comment]
> @peternewman Those undetected mistakes were all in comment lines (starting with #). Is there a way to signal the action to analyse those lines as well?

It doesn't ignore any lines by default, however there's something a bit suspicious going on; it found:

(N) | Spell Error | Suggested Fix | T | Source File  (error line number)
-- | -- | -- | -- | --
(1) | Additinal | Additional | c | pi-hole-5.11.3/advanced/Scripts/piholeDebug.sh   (584)
(2) | Othwerise | Otherwise | c | pi-hole-5.11.3/advanced/Scripts/piholeDebug.sh   (993)
(1) | severs | servers, serves | c | pi-hole-5.11.3/advanced/Scripts/piholeDebug.sh   (1051)
(2) | Othwerise | Otherwise | c | pi-hole-5.11.3/advanced/Scripts/piholeDebug.sh   (1312)
(1) | instuctions | instructions | c | pi-hole-5.11.3/advanced/Scripts/setupLCD.sh   (52)
(1) | verifiy | verify | c | pi-hole-5.11.3/automated install/basic-install.sh   (398)

But e.g. instuctions isn't in our dictionary, I've just opened a PR to add it here:
https://github.com/codespell-project/codespell/pull/2398/files#diff-f9288231dfd0270e6201e016c65672fab2e4bd85656eaf65569fe947c53e0603R18050
othwerise and verifiy are also missing...

So I don't know if Fossies are running a custom dictionary or what?

severs should be a rare at most, maybe it got removed (e.g. "man severs arm").

However your tests do catch it when they run on a PR:
https://github.com/pi-hole/pi-hole/runs/7263954552?check_suite_focus=true#step:5:17
And annotate:
https://github.com/pi-hole/pi-hole/pull/4806/files

**Comment by jschleus** [comment]
Yes, after analyzing some test runs done  on some big FOSS projects supported by Fossies, the codespell  reports on Fossies uses also an extract of the [orbitcowboy codespell_dictionary](https://github.com/orbitcowboy/codespell_dictionary) and aditionally an "own" small dictionary. 

By the way, the mentioned currently used dictfionaries are available via  https://fossies.org/codespell_usage_hints.html
