### ISSUE TITLE
Network Overview is empty (It was working at the beginning)

### ISSUE THREAD

**Issue by Franklin89** [pi-hole/pi-hole#3367]
I have pi hole installed and running on a raspberry pi. The Network Overview was showing entries at the beginning, both with devices using PiHole and with the ones that were not. Suddenly it stopped showing these devices.

Running `arp` shows the devices on the pi. Also calling `sqlite3 /etc/pihole/pihole-FTL.db "SELECT * FROM network"` shows all the devices. 

The logs do not show any information.

Is there anything I can do here?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by Franklin89** [comment]
@dschaper Sure thing sorry about this...
