### ISSUE TITLE
PiHole DHCP running alongside a Pi Samba AD DC

### ISSUE THREAD

**Issue by lesthawk** [pi-hole/pi-hole#3422]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**
1

---
**Expected behaviour:**

Is it possible to allow PiHole to manage the dhcp but if working in a network with a Domain controller such as Samba to put forward a different DNS IP instead of the Pihole's IP.

This is because whilst it seems impossible to setup pihole on the same pi as a running Samba AD DC, it's also incredibly difficult to have a DC setup using samba-tool which requires it's own DNS in order to run. This can be configured so that the Upstream DNS it forwads onto is the PiHole, however the PiHole doesn't appear to take uploads of DNS entries from the pcs on the network.

This is further complicated by issues in PiHole which dont properly handle SRV requests from client pcs trying to add to the domain running on the DC.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that either do not fill out the Issue Template, do not provide debug tokens when possible, or relate to a configuration issue as opposed to an issue with the code. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
