### ISSUE TITLE
Client name unknown or wrong

### ISSUE THREAD

**Issue by mkriegl** [pi-hole/pi-hole#3471]
Hi guys,

great work. I am running PiHole in a Proxmox Container and quite fine with the functionality. 
My only issue is, that I got two clients showing up with a wrong client name:
- my Samsung TV is listed as "localhost" 
- another container is showing up as unknown client

Both clients are listed correctly in my router and other containers are also showing up correctly in PiHole. As far as I remember I did the same settings on the container naming for the unknown client like the others. Regarding my TV I am not sure about naming.
How can this be re-inizialized or edited manually, as right now the unknown client is showing up with his IP adress and localhost is listed two times

Thanks in advance for your help
Max

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
