### ISSUE TITLE
Rename whitelist/blacklist to redlist/greenlist

### ISSUE THREAD

**Issue by benjaminhowarth1** [pi-hole/pi-hole#3479]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`2`

---
**Expected behaviour:**

`Use of redlist/greenlist to describe lists.`

**Actual behaviour:**

`Lists are described as blacklist/whitelist`

**Steps to reproduce:**

`Install pi-hole and navigate to web UI.`

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

`pxwzgwlpv8`

**Troubleshooting undertaken, and/or other relevant information:**

`None as yet, will happily replace keywords in source and documentation accordingly and submit a PR.`

**Comment by yubiuser** [comment]
There is already an open issue about the topic https://github.com/pi-hole/AdminLTE/issues/1448
And a feature request at 
https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657

**Comment by benjaminhowarth1** [comment]
@yubiuser ah, thanks! I've upvoted the issue on Discourse & of course, all terminology (not just the web interface) would require changing - this would involve some upgrade scripts renaming the text files and database tables as well.

**Comment by yubiuser** [comment]
Yey, I can see this would require more than just changing it in one/two places.... also the docs would probably need an update.

I think if you **would** create a PR this would speed up things a lot... ;-)

**Comment by dschaper** [comment]
There's an open feature request and an open issue already for this. Please use those for discussion.

**Comment by Peterkal2112** [comment]
# Restoring "Whitelist" and "Blacklist" in Pi-hole: A Logical and Practical Perspective

## Introduction

The decision to rename "Whitelist" and "Blacklist" to "Allow List" and "Deny List" in Pi-hole has been controversial. This change, intended to promote inclusivity, lacks a technical or practical foundation and instead introduces unnecessary confusion. This article presents logical arguments for reverting the terminology while referencing key points made by **ailothaen** in the Pi-hole forum discussion.

### Related Links:
- Discussion on Pi-hole Discourse: [[Proposal to Rename Allow List and Deny List](https://discourse.pi-hole.net/t/proposal-rename-allow-list-white-list-and-deny-list-black-list/76987)](https://discourse.pi-hole.net/t/proposal-rename-allow-list-white-list-and-deny-list-black-list/76987)
- Original Pi-hole Discourse discussion: [[Change Blacklist and Whitelist Terminology](https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657/104)](https://discourse.pi-hole.net/t/change-blacklist-and-whitelist-terminology/31657/104)
- The Pull Request that implemented the change: [[GitHub PR #3481](https://github.com/pi-hole/pi-hole/pull/3481)](https://github.com/pi-hole/pi-hole/pull/3481)

---

## Logical Fallacies Behind the Justification for the Change

### 1. **Appeal to Authority Fallacy**

The justification for the renaming was based on an **appeal to authority fallacy**—claiming that because other projects made similar changes, Pi-hole should follow suit. As **ailothaen** argued:

- Just because some projects changed similar terms does **not** inherently mean the change is necessary or beneficial.
- This reasoning ignores an **objective evaluation** of whether the original terms were problematic.
- No evidence was provided that "Whitelist" and "Blacklist" caused real confusion, harm, or had racial connotations in the context of software development.

This ideological shift is **not rooted in logic or technical necessity** but in an attempt to conform to a trend.

---

## The Unnecessary Division Created by This Change

### 2. **Seeing Racism Where None Exists Introduces Conflict**

- "Whitelist" and "Blacklist" have **long-established technical meanings**, unrelated to race or discrimination.
- Attaching **social interpretations** to these terms forces a **political debate into a purely technical domain**.
- This change fosters **unnecessary division** rather than addressing real usability concerns.

### 3. **Prioritizing Ideology Over Practicality Harms Software Development**

- Software projects should focus on **usability, clarity, and efficiency** rather than social movements.
- Making politically motivated changes **disrupts user experience** and creates unnecessary learning curves.
- Developers should prioritize **technical improvements**, not engage in ideological shifts that confuse users.

---

## The Practical and Logical Inconsistencies in the Change

### 4. **These Terms Have Clear, Well-Defined Meanings**

- In **computing**, "whitelist" means **allowing access**, and "blacklist" means **blocking access**—these meanings are universal and clear.
- The origins of these terms stem from **contrast and visibility concepts in physics** (white reflecting all light, black absorbing all light), not racial associations.
- Claiming these words have racial implications **imposes an unrelated framework onto a neutral technical concept**.

### 5. **A Slippery Slope of Endless Renaming**

- If "Whitelist" and "Blacklist" are changed due to perceived social concerns, **where does it end?**
- Other essential technical terms like "Master/Slave" have already been targeted, despite their longstanding use in computing.
- This cycle of renaming risks **constant disruptions** with no clear stopping point, leading to further confusion and division.

---

## Conclusion: Reverting the Change is the Logical Decision

The renaming of "Whitelist" and "Blacklist" in Pi-hole serves **no practical purpose** and was implemented based on ideological reasoning rather than technical merit. **As ailothaen correctly argued, there was no valid justification for this change other than following a trend set by other projects.**

Restoring the original terminology is not about politics—it is about **preserving clarity, usability, and technical neutrality**.

Pi-hole should prioritize **efficiency, user experience, and functionality** over ideological trends. The focus should remain on **developing excellent software, not engaging in unnecessary political debates**.

The most logical course of action is to **revert the terminology back to "Whitelist" and "Blacklist"**, respecting their long-established, clear, and universally understood meanings.

---

### Call to Action

Developers must take **active steps** to revert this change. The pull request [[#3481](https://github.com/pi-hole/pi-hole/pull/3481)](https://github.com/pi-hole/pi-hole/pull/3481) should be rolled back to restore common sense and technical accuracy to Pi-hole.
