### ISSUE TITLE
Valid Domains listed as Invalid

### ISSUE THREAD

**Issue by p1r473** [pi-hole/pi-hole#3483]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

0

---
**Expected behaviour:**

Domains listed as invalid should be invalid

**Actual behaviour:**

Domains listed as invalid seem to be valid

**Steps to reproduce:**

Use a blacklist that blocks the following such as https://block.energized.pro/basic/formats/domains.txt
```
e-geräteundhaus.com
polenböller-deutschland.com
```

**Troubleshooting undertaken, and/or other relevant information:**

According to https://github.com/EnergizedProtection/block/issues/421
These domains are actually valid
I believe the code used to detect invalid domains may need slight tweaking.

**Comment by p1r473** [comment]
Sorry, I believe this may be an invalid issue, as I can't nslookup the domains.

**Comment by p1r473** [comment]
Note that you cannot nslookup these domains without your nslookup tool being compiled with IDN support 
See EnergizedProtection/block#421 for moren info

**Comment by TheNec** [comment]
Those (internationalized) domains seem to be valid from user/application side but indeed they are not as they contain invalid letters (ömlauts in this case) while only letters from the modern latin alphabet (a-z) are allowed. Internationalized domains are translated from the browser/client to valid domain names and after that the valid domain ist passed to the dns infrastructure.

For example "polenböller-deutschland.com" is coded with punycode to "xn--polenbller-deutschland-zhc.com".

You may cross check this when startpaging "polenböller-deutschland.com" or just search for "xn--".

Hope that helps!

Btw. Does anyone know why neither regexes "(^|\.)xn--.*$" nor "(^|\.)xn--" from "https://discourse.pi-hole.net/t/add-option-to-block-all-idn-domains/6884/11" work to block all of those domains? I also tried others but I didn't get it to work.

**Comment by DL6ER** [comment]
Two things here:

1. I agree with @TheNec's description. They are invalid. I see that the discussion is going on in the issue ticket you linked. As this is a list and not a Pi-hole problem, I will close this ticket again.

2. @TheNec Try the regex debug mode to see what happens with regex magic. See https://docs.pi-hole.net/ftldns/regex/overview/#pi-hole-regex-debugging-mode
If something doesn't work right, please be so kind to open a new bug for [FTL](https://github.com/pi-hole/FTL). This is where we're doing the heavy lifting for regex.

**Comment by dumprop** [comment]
> Two things here:
> 
> 1. I agree with @TheNec's description. They are invalid. I see that the discussion is going on in the issue ticket you linked. As this is a list and not a Pi-hole problem, I will close this ticket again.
> 2. @TheNec Try the regex debug mode to see what happens with regex magic. See https://docs.pi-hole.net/ftldns/regex/overview/#pi-hole-regex-debugging-mode
>    If something doesn't work right, please be so kind to open a new bug for [FTL](https://github.com/pi-hole/FTL). This is where we're doing the heavy lifting for regex.

That's sad
I think they should be converted to punycode and added to adlist
Because then is possible to create ad domain, which pihole will always pass (because it always will be rejected as invalid domain)


> Note that you cannot nslookup these domains without your nslookup tool being compiled with IDN support
> See [EnergizedProtection/block#421](https://github.com/EnergizedProtection/block/issues/421) for moren info

All modern browsers converts these domains to punycode format, which works well in nslookup

**Comment by DL6ER** [comment]
>  I think they should be converted to punycode and added to adlist

Yes, I agree. However, it has clearly to be done on the adlist provider's side (which I think they did looking at the references issue ticket?). Stemming millions of domains on a Raspberry Pi for Pi-hole is a very tricky task. Every little bit of performance penalty (and may it only be 0.1 milliseconds) will quickly escalate to very long waiting times:
```
6 mio. domain * job that takes 0.1 milliseconds = 100 seconds
```
(just saying that checking and, if necessary, converting domains to punycode may be even slower than this).

I think the way Pi-hole handles this is entirely correct:
1. Users see there is something fishy going on
2. At least one user reports it to the adlist maintainers
3. It gets fixed for everyone without any added delay in the adlist update process

**Comment by dumprop** [comment]
Unfortunately not all are providing in punycode and for example me using server for pihole(not RPI), meaning that some people have resources for that (IMHO last versions of RPI have idle time too if used for personal use)  :)
Im not sure in that numbers
In 6 mio domain I have ~600 IDN domains (and plus 100 really invalid*)
So, I think is possible to try convert only invalid domains (600+100 * 0.1 milliseconds = 0.07 second)
Something like converting only in exception handling, then you will spend only a second for that

*I delete adlists with invalid domains

**Comment by DL6ER** [comment]
Only in an exception handler may work, however, it'll be a lot of work to route some of them (the valid ones) directly into the database and have the others do a detour over some conversion tool. So, in the end, we'd have to put everything though the conversion tool of we want this to work reliably.

So we'd need to add a third-party conversion tool to our dependencies or write one embedded into FTL. I guess the latter would be the better/only choice as we need a tool being able to process an entire list to not create a ton of overhead by executing a single program (like `idn2`) millions of times individually. So writing our own in code with high performance is the way to go.

At this point, I'm just not sure *if* we should do this. It is fixing low(er)-quality lists at the costs of running this on each and every individual Pi-hole. I'm going back and forth about this and would like some more input from @dschaper and @PromoFaux 

The technical realization would look like creating a new command `pihole-FTL gravityIDN` which would go through all domains in the gravity table and replace IDN-convertible by their converted self. The process would be fairly efficient because the database contains the numbers of invalid domains for each adlists so healthy lists could be skipped altogether. Nevertheless, it'd be another step in the process. Another moving gear. If it's worth it, then I'll add this feature.

**Comment by dschaper** [comment]
> fixing low(er)-quality lists at the costs of running this on each and every individual Pi-hole.

Nope from me. Either get the list maintainer to improve the quality of their lists or find another list. 

This is akin to us adding back in adblock list parsing.
