### ISSUE TITLE
Missmatch of pihole -a options and decription in help and man pages

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#3496]
**In raising this issue, I confirm the following:**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

10

---
**Expected behaviour:**

`man pihole` and `pihole -a -h` should list and explain all possible options for `pihole -a`

**Actual behaviour:**

Only a subset of options is shown in help and man pages

**Steps to reproduce:**

Compare listed options from
`pihole -a -h` or `man pihole` and 
https://github.com/pi-hole/pi-hole/blob/4d25f695267590b61a4061f9bb43448005d99b85/advanced/Scripts/webpage.sh#L626

**Comment by HalfBit-hacks** [comment]
There's no explanation in the help menu of the new `pihole -a theme` option. What does it do exactly?

**Comment by DL6ER** [comment]
The reason for the lack of documentation is that `pihole -a` is used as a backend by the web interface. Whenever things have to change here (like it will happen now with v5.2 -> v5.3 because we will allow multiple conditional forwarding destinations), breaking changes would otherwise require us to bump the major version. We're not browser makers so we're not into the story of being at version, what, 65.0 ? That's just insane. ;-)

Another reason against opening these options to the wider public is that **`pihole -a` will go away with Pi-hole v6.0**. We're redesigning the entire API into a REST-style theme. It will be usable to control *everything* on your Pi-hole. In contrast to the current API, it will also allow you to change the theme, all the DNS settings and more.

**Comment by yubiuser** [comment]
> `pihole -a` will go away with Pi-hole v6.0

Good too know. Should I close the issue then?
