### ISSUE TITLE
Changing admin password for PiHole through console has broken my admin page

### ISSUE THREAD

**Issue by LiamPM5** [pi-hole/pi-hole#3501]
After updating my admin password for my PiHole, my admin page no longer works, I get either a php file like [this](https://drive.google.com/file/d/1C0FrhPCk5U0e3Y6lz5m20G5aV9K2p6fp/view?usp=sharing) or a version of the admin page where only text can display.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by LiamPM5** [comment]
@dschaper Where on the github is the Issue Template? I've been looking over the site for it and cannot find it. Also I already searched this issue and could not find anything, I really need my admin file fixed and I have no frame of reference on how to do that

**Comment by dschaper** [comment]
It's the text you deleted when you typed your post.

**Comment by dschaper** [comment]
If you need assistance then please open a help topic at https://discourse.pi-hole.net
