### ISSUE TITLE
Dashbord Clients / double entries

### ISSUE THREAD

**Issue by un99known99** [pi-hole/pi-hole#3509]
Hi,
IPv6 and IPv4 clients are showing up separatly, despite entered ips in /etc/hosts.
Before 5.0 clients entered in hosts with ipv4 and ipv6 showed up in top clients summed up for 4+6 (as single entry), now there are 2 entries for same hosts, one for v4 and one for v6

BR,
Michael.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by nicoh88** [comment]
Same here, but i have three and more ipv6 entries for the same host.

@un99known99: Could you solve it?
