### ISSUE TITLE
.lists removed?

### ISSUE THREAD

**Issue by Daedalus-code** [pi-hole/pi-hole#3523]
is this performance related or something? adding manually not functional anymore, that sucks.

**Comment by Daedalus-code** [comment]
"Add through web bases" I know, but still.

**Comment by Daedalus-code** [comment]
"Add through web based" I know, but still.

**Comment by jfb-pihole** [comment]
As described in the release notes - a new gravity database allows Per-client blocking. 

https://pi-hole.net/2020/05/10/pi-hole-v5-0-is-here/

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by yubiuser** [comment]
>adding manually not functional anymore, that sucks.
>"Add through web based" I know, but still.

You can add per CLI via sql commands too, scripting is possible as well.
