### ISSUE TITLE
Release tarballs don't install. Instead pulls and runs code directly off the internet; No offline install

### ISSUE THREAD

**Issue by beren12** [pi-hole/pi-hole#3541]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*.
- [x] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

3

---
**Expected behaviour:**

The installer should install the version that is downloaded, not whatever happens to be in github at the time. This also means you are unable to install pihole from the tarball without working internet. The entire installer goes against the warning in the install documents: "Piping to bash is a controversial topic, as it prevents you from reading code that is about to run on your system.

If you would prefer to review the code before installation, we provide these alternative installation methods."

If the code you look at isn't the code you install, why have a release at all, just have a 1 line bash script that downloads and runs the pihole code off the internet.

**Actual behaviour:**

The installer downloads code from the internet and runs it

**Steps to reproduce:**

Run the installer

**Troubleshooting undertaken, and/or other relevant information:**

I have to run every command manually it seems.

**Comment by PromoFaux** [comment]
I'm m not sure I follow re:running the version that is downloaded rather than whatever is in GitHub...

The `master` branch is the latest version, and we don't really have anything in place to install specific releases (not officially, anyway... There is a method but I've not documented or tested it fully yet)

If you're taking about downloading the tar of a particular tag from the releases page, that's just a side effect of tagging a release, the source code is attached automatically at the point of pressing the release button

Curious as to why you'd want to do an offline install of Pi-hole... If there was no internet connection, how would the installer grab the dependencies? The very nature of the project requires an internet connection to operate.

**Comment by beren12** [comment]
Hmm I thought releases were something that were made. It doesn't really matter, its bad form (as the installer page notes) to run code straight off the internet. I've spent far more time on getting 5.0 working than I did with v4. There should be release tarballs that let you install from them, like almost every other project ever made.

As for dependancies, the installer doesn't need to worry about them if they are already installed. Its a no-brainer to save deb files from /var/archive/apt or use an offline tool to pre-download them to a thumb drive.

An offline install lets you do things like setup backlists before every machine on your network goes online, it lets you install if github is down or has a security breach (these have already happened) and you can sign/hash the release so it is verifiable that it hasn't been modified. It would also make bugs like this one a moot point as people could install any past version clean without some secret undocumented hack that needs testing.

Sorry if this comes off as harsh. It's been a frustrating couple of days. My router's ssd died (try installing freebsd and a firewall package without any internet) and the microsd for my pi zero died 2 days before. There have been problems with 5.0 just getting installed and I just want what I had working.

**Comment by beren12** [comment]
Right now it seems the only way to install a previous release is to checkout the code, roll it back, then change the installer so it looks to a local server not github. A large pain.

**Comment by yubiuser** [comment]
I've got the feeling this is more a feature request than an "current" issue. Please submit FR to https://discourse.pi-hole.net/c/feature-requests/8

There are two that might be releated:
https://discourse.pi-hole.net/t/why-not-distribute-with-package-managers/22541
https://discourse.pi-hole.net/t/another-options-to-install-pihole/2519

But feel free to open a new one if this the open one doesn't cover your scope.

**Comment by PromoFaux** [comment]
> Its a no-brainer to save deb files from /var/archive/apt or use an offline tool to pre-download them to a thumb drive

For you, maybe. Pi-hole is designed to be as simple as possible for _all_ skill levels - a lot of people's first introduction to linux is on a Raspberry Pi, and there are a good number of people who's first introduction to a Raspberry Pi is from hearing about Pi-hole. 

We don't go against any warning. We put the notice there to say "hey, you can download the script (from the master branch) and review it before running it if you are not comfortable with piping to bash from curl". Nowhere do we state that you can download a previous version's tarball and install it that way.

I appreciate that you have had a frustrating couple of days with various issues on your network devices, but I would ask you to moderate your tone and not take out your frustration on us  by being short with us. Be constructive, kind, and polite and you will find folk more willing to engage. 

> microsd for my pi zero died 2 days before.

Then perhaps it is time to look into taking regular backups?

The "secret undocumented hack that needs testing" is not so much a secret, and uses tools already available within the Pi-hole package to do it. It was just never designed for that purpose, but it could be done. However, as I have not tested it in any real capacity, it is not documented anywhere other than in my head.. but it goes along the lines of:

The way we asked people to try the beta release of 5.0 was to do the following:

```
echo "release/v5.0" | sudo tee /etc/pihole/ftlbranch
pihole checkout web release/v5.0
pihole checkout core release/v4.3.3
```

While we did not design it this way, it turns out that you can also check out tags this way too, in effect pinning the version at an earlier version. For example, the last 4.x version would be:

```
echo "release/v4.3" | sudo tee /etc/pihole/ftlbranch
pihole checkout web v4.3.2
pihole checkout core v4.3.3
```

If you wanted to install 4.0 from scratch, you would do what I do for testing new installs before we release a new version:
(this method involves no pre-installed Pi-hole commands)

```
git clone https://github.com/pi-hole/pi-hole /etc/.pihole
git clone https://github.com/pi-hole/adminLTE /var/www/html/admin
mkdir /etc/pihole
echo [whatever version] | tee /etc/pihole/ftlbranch
cd /var/www/html/admin && git checkout [whatever branch/tag]
cd /etc/.pihole && git checkout [whatever branch/tag] && bash automated\ install\basic-install.sh
```

We have never intended for Pi-hole to be installable offline, or via the tarballs of the source code, but I'm sure somebody with the gumption could figure out how to do it. We appreciate contributions to the code, big and small alike.

The alternative methods of install mentioned on the readme instruct you to download the very same install script that the one liner does, except this method gives you an opportunity to _read_ the script before running it. 

As @yubiuser mentioned, this is more of a feature request than a bug with the code, so I'll close this out now as there is not a lot more to say here.

Peace out, hope you get your network devices back up and running

**Comment by beren12** [comment]
Thank you. As an aside there was no gravity db, and a couple of php packages were missing after installing v5 like -intl. Update-rc.d needs to be run for pihole-ftl if you don’t have systemd. I installed pihole right before 5 was released, and didn’t do an off-device backup just a local snapshot.
