### ISSUE TITLE
5.1  regex filter warning: Invalid preceding regular expression

### ISSUE THREAD

**Issue by roe1974** [pi-hole/pi-hole#3554]
after update to pihole 5.1 the following regex filters (whitelist) doesnt work anymore:

*.push.apple.com
*.itunes.apple.com
*.apps.apple.com
*.mzstatic.com
*.amazonaws.com
*.cdn-apple.com
*.digicert.com
*.symcb.com
*.symcd.com

they workes with pihole 5.0 ......
what is the right format now ?

thx, Richard

**Comment by yubiuser** [comment]
What you want is wildcard filtering of subdomains. Enter `push.apple.com` in the 'add domain field', check wildcard and press add. This will create the right regex for you. You can see the format being added as `(\.|^)push\.apple\.com$`

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
