### ISSUE TITLE
basic-install.sh ignores apache2 server choice, other install does not

### ISSUE THREAD

**Issue by mmd123** [pi-hole/pi-hole#3613]
I posted a feature request over on the r/pihole reddit, only to be informed this is actually a bug, and to post this issue here referencing that reddit post by one of the developers.

the issue is that, one of my two piholes, apparently installed with the basic-install.sh script, installed to use apache2 as the web server, and it works just fine using it, just like the other pihole, but apparently the script ignores that I chose to use apache2 on that pihole server when it updates, whereas the other one (apparently installed without the script) keeps apache2 and does NOT add lighttpd every update, whereas the pihole made WITH the script ignores apache2 and installs lighttpd every single time it updates.

https://www.reddit.com/r/pihole/comments/hx5kcz/featurerequest_check_for_either_apache_or_lighttpd/

**Comment by dschaper** [comment]
I think this is because https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L112-L119 allows you to override installing `lighttpd` but when you update we ignore that setupVars.conf config line, https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/update.sh#L198. We source the config in `main()` but as soon as `reconfigure` is called, the install script sets the variable back to `true` https://github.com/pi-hole/pi-hole/blob/master/automated%20install/basic-install.sh#L79. 

So I think the easy solution is to do something like `INSTALL_WEB_INTERFACE=${INSTALL_WEB_INTERFACE:=true}` in the installer.

**Comment by gstrauss** [comment]
Is this still an issue?  The solution suggested by @dschaper should work, unless the script is re-executed via sudo and the environment is cleared by sudo.

**Comment by mmd123** [comment]
to the best of my memory, no I do not think that this is still an issue, I have not had it happen since, though to be entirely honest I have since changed to using pihole in a ubuntu VM, but no, I have not had this issue happen since.  so I do believe this is no longer an issue.
