### ISSUE TITLE
CNAME resolution doesn't check local DNS records

### ISSUE THREAD

**Issue by iMartyn** [pi-hole/pi-hole#3619]
**In raising this issue, I confirm the following:** `{please fill the checkboxes, e.g: [X]}`

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*.
- [X] The issue I am reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the the source code relevant to this issue?:**

`0`

---
**Expected behavior:**

If a CNAME resolves to something in the `Local DNS Record`s, the `Local DNS Record` should be returned.  I have a record for `bounce.martyn.berlin` to `192.168.1.11` (as per ![screenshot](https://user-images.githubusercontent.com/962908/88519841-0cfaff80-cff3-11ea-9b6b-f29a9dbf2c10.png) ) so when I look up `keys.martyn.berlin` which is a `CNAME` to `ing.martyn.berlin` (which I also have a `Local DNS Record` for) which is a `CNAME` to `bounce.martyn.berlin`, so I should recieve `192.168.1.11`.  It would be nice if it simply short-circuited at `ing.martyn.berlin` tbh, but that's just an implementation detail.
```
> nslookup -type=A keys.martyn.berlin 192.168.1.201
Server:         192.168.1.201
Address:        192.168.1.201#53

Non-authoritative answer:
keys.martyn.berlin      canonical name = ing.martyn.berlin.
ing.martyn.berlin       canonical name = bounce.martyn.berlin.
Name:   bounce.martyn.berlin
Address: 192.168.1.11
```

**Actual behavior:**

If the first domain looked up is not in the `Local DNS Record`s, but a `CNAME`, the Local DNS records are never checked again.
```
> nslookup -type=A keys.martyn.berlin 192.168.1.201
Server:         192.168.1.201
Address:        192.168.1.201#53

Non-authoritative answer:
keys.martyn.berlin      canonical name = ing.martyn.berlin.
ing.martyn.berlin       canonical name = bounce.martyn.berlin.
Name:   bounce.martyn.berlin
Address: 31.7.180.171
```

**Steps to reproduce:**

* Create a DNS record that is a `CNAME`
* Create a `Local DNS Record` that covers the end-result of the `CNAME`
* Note that it does not get returned

**Debug token provided by [uploading `pihole -d` log](https://discourse.pi-hole.net/t/the-pihole-command-with-examples/738#debug):**

https://tricorder.pi-hole.net/rzb2l6xhaw

**Troubleshooting undertaken, and/or other relevant information:**

I attempted to add `Local DNS Record`s for each step along the way, but only first-requested works, this means I have to manage a LOT of records, defeating the point of using `CNAME`s

**Comment by yubiuser** [comment]
I tried to reproduce the issue with the following setup: Local DNS Record for test (1.2.3.4), CNAME test1 -> test, CNAME test2 -> test1. If I understood you concretely, I get the desired results.

```
hrko@ThinkPad-X230:~$ dig test

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> test
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 654
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.				IN	A

;; ANSWER SECTION:
test.			2	IN	A	1.2.3.4

;; Query time: 6 msec
;; SERVER: 10.0.1.5#53(10.0.1.5)
;; WHEN: Mon Jul 27 12:10:18 CEST 2020
;; MSG SIZE  rcvd: 49

chrko@ThinkPad-X230:~$ dig test1

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> test1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24841
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test1.				IN	A

;; ANSWER SECTION:
test1.			2	IN	CNAME	test.
test.			2	IN	A	1.2.3.4

;; Query time: 4 msec
;; SERVER: 10.0.1.5#53(10.0.1.5)
;; WHEN: Mon Jul 27 12:10:20 CEST 2020
;; MSG SIZE  rcvd: 68

chrko@ThinkPad-X230:~$ dig test2

; <<>> DiG 9.11.3-1ubuntu1.12-Ubuntu <<>> test2
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35931
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test2.				IN	A

;; ANSWER SECTION:
test2.			2	IN	CNAME	test1.
test1.			2	IN	CNAME	test.
test.			2	IN	A	1.2.3.4

;; Query time: 6 msec
;; SERVER: 10.0.1.5#53(10.0.1.5)
;; WHEN: Mon Jul 27 12:10:22 CEST 2020
;; MSG SIZE  rcvd: 87
```

**Comment by iMartyn** [comment]
How did you create those `CNAME`s?  There's no way to create `CNAME`s via the web interface and even if it could that would not cover my use case because the `CNAME` is set on the internet DNS servers.

**Comment by yubiuser** [comment]
Ah sorry. I assumed you created them in pihole by using the development branche. The next version of the web interface will likely contain the possibility to create CNAMEs (https://github.com/pi-hole/AdminLTE/pull/1278).

So what you want is: Pihole should drop the answer (IP) of the upstream DNS server, if the answer contained a CNAME that is also found in a Local DNS Record, and substitute it with the local IP?

I think that is more likely a feature request than an issue and should go to: https://discourse.pi-hole.net/c/feature-requests/8
This might need a bunch of changes in pihole-FTL analog to deep CNAME inspection. The reason is: the upstream DNS answer is served as a whole and not step-by-step (or CNAME by CNAME). Pihole must therefore intercept to get the desired behavior and not just continue to process the answer IP it got.

**Comment by iMartyn** [comment]
I see, so that would require something akin to changing requests to first query CNAME explicitly and then A record if not a valid response. ouch.  I didn't realise that the upstream DNS does the CNAME resolution directly.

**Comment by yubiuser** [comment]
> changing requests to first query CNAME explicitly and then A record if not a valid response

I think this is not they way it would work/would be implemented. The reason is, this must be done for every request, because pihole doesn't know if a CNAME will be returned. As the complete answer will be returned in one piece, pihole instead will walk through the answer step-by-step. This is how it is implemented in deep CNAME inspection
https://github.com/pi-hole/FTL/pull/642/commits/2e97d2e6cddce22e7b209872646be11fc3d7c7cc

The effort might be not extremely high, becaue CNAME analysis is done already since v5.0. It would "only" require another exit (next to CNAME on a adlist).

File the feature request, link the issue and see what the devs say.
