### ISSUE TITLE
Since installing Pihole my cellphone network drops, have to update network profile to enable it again, i leave and come back its gone again.

### ISSUE THREAD

**Issue by mazfarx7pi** [pi-hole/pi-hole#3674]
Installed Pihole on a PI2 Via ethernet.  Had to sandwich the Pis IP address on router admin page due to it now allowing me to set primary DNS.  Set up the dhcp on admin page of Pihole.  Now for some reason my network (no calls or text) went blank, after a few hours of troubleshooting I updated my profile -settings-updates-update profile and the network came back on my phone. If i restart my phone it goes blank again.  Turned off Pihole and still goes blank.  Any suggestions?  I believe it may have something to do with a google service that was somehow blacklisted, however I set it back to stock and still same issue.  Contacted sprint and networks not down and other household people are running fine, albeit they are on iPhones.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
