### ISSUE TITLE
Pi-hole v5.1.2 Missing Query type on dashboard

### ISSUE THREAD

**Issue by jhjatl** [pi-hole/pi-hole#3683]
I had to reinstall pihole and the new version does not have all the Query type in the dashboard.  The one missing are (**ANY, SRV, SOA, TXT**)  I tried to update, repair, and reconfigure multiple time.   Any thoughts?  See the pictures of my old and new dashboard. 

![New dash](https://user-images.githubusercontent.com/37995110/90043501-d0d1cb00-dc91-11ea-9975-7c9a677e69ab.png)

![old dash](https://user-images.githubusercontent.com/37995110/90043866-53f32100-dc92-11ea-8100-23a9fc5ac1b1.png)

**Comment by dschaper** [comment]
There hasn't been any queries of those types since you reinstalled.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by yubiuser** [comment]
https://github.com/pi-hole/AdminLTE/pull/1475
