### ISSUE TITLE
Create a option to adopt to change the web interface to dark theme when the browser/system is in dark theme

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [pi-hole/pi-hole#3714]
It is quite annoying when your whole system is in a dark theme but the website has a white theme. I have seen website adopt the global theme of your system, so I think this is possible and not quite difficult. Is that difficult? And are the dev team considering to implement it?

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that either do not fill out the Issue Template, do not provide debug tokens when possible, or relate to a configuration issue as opposed to an issue with the code. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)

**Comment by yubiuser** [comment]
Please vote for the existing feature request instead of opening a new one:

https://discourse.pi-hole.net/t/default-theme-use-prefers-color-scheme-to-detect-system-theme/35615
