### ISSUE TITLE
Redirection to https no longer working

### ISSUE THREAD

**Issue by simpassy** [pi-hole/pi-hole#3721]
![pi-hole error](https://user-images.githubusercontent.com/31965315/91865082-4ae1e800-ec71-11ea-924f-27df1246a987.png)
I am using pi-hole also as my local DNS Server.
With the old version of pi-hole I created /etc/dnsmasq.d/02-lan.conf path and file and inclouded  "xxx.ddns.net" "servername" in /etc/pihole/lan.list
Every time I opend xxx.ddns.net from my local network a connection to my local server was opened. Every think worked fine

Now with the new version of pi-hole I get am error message "Website Blocked"

Even whitelisting the page does not bring any  success

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the Community Help category.
