### ISSUE TITLE
Pi-Hole says it's blocking stuff, but nothing's actually getting blocked

### ISSUE THREAD

**Issue by ravenclaw900** [pi-hole/pi-hole#3734]
### Versions

- Pi-hole:  v5.1.2
- AdminLTE:  v5.1.1
- FTL:  v5.2

### Platform

- OS and version:  Raspberry Pi OS Buster

- Platform:  Raspberry Pi

### Expected behavior

For ads and trackers to actually get blocked.

### Actual behavior / bug

Shows ads and trackers are getting blocked on pi.hole, but everything's still there.

### Steps to reproduce

1. Go to an ad-block checker (I use canyoublockit.com and the extreme test) and try it.

## Debug Token

- URL:  https://tricorder.pi-hole.net/o0lq5egigq

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

Doing on my main computer (macOS 10.13.6) `nslookup doubleclick.net` returns
```bash
Server:		2600:6c56:4100:1317:e8c5:a276:301d:a282
Address:	2600:6c56:4100:1317:e8c5:a276:301d:a282#53

Name:	doubleclick.net
Address: 0.0.0.0
```

**Comment by dschaper** [comment]
The response for the `nslookup` is correct, 0.0.0.0. 

Pi-hole is functioning but you likely have another DNS server configured on the client along with Pi-hole. This will leak ads.

See https://discourse.pi-hole.net/t/why-should-pi-hole-be-my-only-dns-server/3376

Please use our support forum at https://discourse.pi-hole.net since this is a configuration issue and not a bug.

**Comment by ravenclaw900** [comment]
Oh, I just realized that my computer automatically hides other DNS servers after adding a new one.  Sorry for the trouble.
