### ISSUE TITLE
Windows phone 10 - wifi - attention required

### ISSUE THREAD

**Issue by shanemdoyle** [pi-hole/pi-hole#374]
##### Expected Behaviour:
until recently everything worked fine on windows phone 10 fast ring (build 10.0.10586.107) 

##### Actual Behaviour:
within the last week or two wifi stopped connecting successfully and presents an open browser message - as if connected to a wifi hotspot that requires accepting terms. If i change DNS to point to router instead of pi-hole this issue goes away. Guessing one of the blocklists are blocking something MS but I don't know where to look

I haven't had any phone updates so don't think this is the issue. Have cleared browser cache and deleted and rejoined wifi network. Have even created a new SSID and same issue

**Comment by dschaper** [comment]
Thanks for the trouble ticket report. Microsoft does have a number of telemetry domains that call back to home to ping MSoft's servers. Can you do a `sudo tail -f /var/log/pihole.log | grep gravity.list` on the Pi-hole and powercycle the Win Phone? You will probably see some entries that contain the microsoft.com domain (and either spy or telemetry in the name, the spynet is actually the cloud based antivirus upload...) 

We have had a list in the last week or two that has blacklisted some Microsoft domains that has lead to odd behavior, but this should help find the domains to whitelist.

**Comment by PromoFaux** [comment]
There is also an faq for this on the wiki page that may be worth trying out :)

**Comment by rotational467** [comment]
Yes, I noticed last night that someone has slipped in some non-advertising MS telemetry servers into multiple default pi-hole lists upstream (including the Steven Black and malwaredomains.com lists), such as settings-win.data.microsoft.com (which is used so your Windows profile can roam with you to other machines) as well as some MS/Akamai distribution hosts and endpoints.  I think this is the second time in two weeks that I've noticed it.

I really wish the list maintainers would declare a separate and optional "Windows 10 Telemetry" , because paranoids and jerks keep blocking non-ad/non-telemetry servers in the main lists.  For example I haven't been using Quidsup's Tracking List at all because blocks a bunch of legitimate MS domains (including support.microsoft.com), but at this point I think I'm just going to add the legit domains to the whitelist as they show up in gravity.list and be done with it.

**Comment by dschaper** [comment]
Might be the best way to handle the situation. There was one blocklist that was trying to block all `.com` domains for a bit...

**Comment by lamarios** [comment]
I've been facing the same issue, do you mind sharing the list of domains to whitelist ?  It affected my windows phone and my windows 10 installation...

**Comment by rotational467** [comment]
Hi there,

I'm happy to.  I can't promise that one or two of these isn't actually
tracking/telemetry, but most of these are definitely legit services.
akadns.net is Akamai.  I doubt this is everything legitimate being blocked,
while researching some of these lists have 80+ Microsoft domains blocked.
This covers everything legit showing up currently in my gravity.list

settings-win.data.microsoft.com
apprep.smartscreen.microsoft.com
fe2.update.microsoft.com.akadns.net
schemas.microsoft.akadns.net
microsoft.com (yes, this was in one of the lists!)
amer.hops.glbdns.microsoft.com
dmd.metaservices.microsoft.com
s.gateway.messenger.live.com (skype)

#possible (bad) telemetry servers, I'm not 100% sure about these.  I don't
consider normal Windows opt-in telemetry as "bad"
reports.wes.df.telemetry.microsoft.com
statsfe2.ws.microsoft.com
wes.df.telemetry.microsoft.com

**Comment by lamarios** [comment]
Thanks a lot.

**Comment by philippseith** [comment]
The problem is currently reappearing with the default pi-hole config.
BTW: Wouldn't it be nice to disable pi-hole for specific clients?

**Comment by PromoFaux** [comment]
@philippseith Did you try whitelisting the domains that @rotational467 mentioned [here](https://github.com/pi-hole/pi-hole/issues/374#issuecomment-194667018)

**Comment by philippseith** [comment]
No, I didn't. I was assuming that these domains have been removed from the default blocking lists. Isn't pi-hole "advertised" as an out of the box solution? Even if wp10 is a rare beast, pi-hole should work for it without fiddleing.

**Comment by PromoFaux** [comment]
It's totally an out of the box solution... but no matter what lists we include as default there are always going to be domains in there that don't work for someone.

That's what the whitelisting feature is for. If you have trouble with domains, whitelist them, and you will have no problems! 

We have no control over the domains that are actually in the default blocking lists, they are not ours. What we do is aggregate and deduplicate multiple lists from various sources and go from there. We will never whitelist any domains by default though, no matter how common an issue they cause. It's better for the user to whitelist it themselves, else it may come across that we are whitelisting domains for ulterior motives...

**Comment by DL6ER** [comment]
@philippseith 
> BTW: Wouldn't it be nice to disable pi-hole for specific clients? (wp10 does not allow to change the dns manually)

I looked through the man page of `dnsmasq` and don't think that this is (if at all) easily doable from the side of pi-hole. If you have a highly customizable DHCP Server like myself (running `isc-dhcp-server` on the very same Raspberry Pi), then you might be able to set there that specific clients should receive upstream DNS servers instead of the Pi-hole.

**Comment by philippseith** [comment]
@PromoFaux 

> Did you try whitelisting the domains that @rotational467 mentioned here?
I did now, but had to add www.msftncsi.com to succeed.  (No wonder, see [answers.microsoft.com](https://answers.microsoft.com/en-us/mobiledevices/forum/wp7-wpstart/what-is-ncsitxt/6bce0922-0614-45f9-b307-cf61cf43b337)

**Comment by Mcat12** [comment]
Yes, www.msftncsi.com is a very commonly whitelisted domain. So common in fact, that we have provided a [few places](https://github.com/pi-hole/pi-hole/wiki/FAQs#windows-thinks-there-is-no-internet-connection-but-there-is-one-315) which help our users [whitelist common problem domains](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212). ;)
