### ISSUE TITLE
Pi hole

### ISSUE THREAD

**Issue by YoloAlien64** [pi-hole/pi-hole#3764]
I noticed that my raspberry pi add blocker does not have an block list and instead has a adlist. How to I add a block list? I also noticed that it is not blocking any adds. How can I fix that? Is it because I don’t have a block list? Please see attachments below.
![image](https://user-images.githubusercontent.com/72054690/94501660-37199b00-01b7-11eb-98e1-5a741dd21eae.jpg)
![image](https://user-images.githubusercontent.com/72054690/94501684-413b9980-01b7-11eb-9986-2740c6b934ad.jpg)
![image](https://user-images.githubusercontent.com/72054690/94501710-557f9680-01b7-11eb-9de3-5db0c393fcf9.jpg)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
