### ISSUE TITLE
Cannot connect to pi-hole after a random amount of days (iptables issue)

### ISSUE THREAD

**Issue by ethaniel** [pi-hole/pi-hole#3791]
### Versions

- Pi-hole:  v5.1.2 (Latest: v5.1.2)
- AdminLTE:  v5.1.1 (Latest: v5.1.1)
- FTL:  v5.2 (Latest: v5.2)

### Platform

- OS and version:  Raspbian 10 (buster)

- Platform:  Raspberry PI

### Expected behavior

Normal operation.

### Actual behavior / bug

After a seemingly random amount of days raspberry starts blocking all incoming connections.
`sudo iptables --list -n` at the time of the problem shows (nothing out of the usual):

```
Chain INPUT (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     icmp --  0.0.0.0/0            0.0.0.0/0            icmptype 255
DROP       all  --  127.0.0.0/8          0.0.0.0/0

Chain FORWARD (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
```

However, this problem can be reversed by doing `iptables -P INPUT ACCEPT`

### Steps to reproduce

Just a regular installation according to https://github.com/pi-hole/pi-hole/#one-step-automated-install
And wait a few days.

## Debug Token

- URL:  https://tricorder.pi-hole.net/9dkipyc6mf

However, right now the problem is solved by the  `iptables -P INPUT ACCEPT` fix above.

**Comment by josteink** [comment]
I'm not sure if this is the same issue, or another one vaguely related. I've had my Pi-Hole (dedicated RPi 3b+ with 64-bit Ubuntu server) become unavailable for any DNS queries after a certain amount of time.

My solution so far has been to simply setup a cron-job to reboot it regularly (yay! there I fixed it!), although feels way beyond hackish. A proper solution to the root-cause of this issue would be great.

So... What would cause Pi-Hole to constantly/occasionally update/alter `iptables` rules so that they eventually end up in an inconsistent state?

I'd (naively) assume that these things are set and fixed on boot, and then ignored afterwards? Could it be network connect/disconnect events causing `itables` state to reset, and no longer match whatever Pi-hole expects?

**Comment by squio** [comment]
I got an occasional random "lock up" with my rpi 0 w setup (yes, wirelessly connected to my router) and I blamed it on the low specs and wireless connection but might well be this issue. A power cycle fixed everything (and didn't brek the SD card luckily)

**Comment by Feliix42** [comment]
My pi-hole also gets stuck after a few weeks and at around 1am at night stops replying to DNS queries. The web interface is still available and working however. I route my DNS queries through my router to the pi-hole installation.

The RaspberryPi's own `localhost` queries still resolve correctly, manual queries like `dig uberspace.de @192.168.178.44` also resolve without issue.

It seems a reboot fixes the issue temporarily.

Debug token: https://tricorder.pi-hole.net/i6lw9k8pp4

### Version info
  Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

**Comment by dschaper** [comment]
Please use https://discourse.pi-hole.net for configuration issues.
