### ISSUE TITLE
Lancache format change breaks pi-hole

### ISSUE THREAD

**Issue by quielb** [pi-hole/pi-hole#3792]
Because of a change in the way the files are structured for lancache cache-domains, dnsmasq can't properly load the config.  Changing the dnsmasq.conf conf-dir directive to `conf-dir=/etc/dnsmasq.d,*.conf` would solve this issue.  It probably also best practice to limit file extensions for configuration.  In this case limits configuration files placed in /etc/dnsmasq.d to files with a .conf extension.

This is probably specific to the docker container build.  I have never used the bare metal install of pihole so don't know what dnsmasq.conf is provided for that.

**Comment by PromoFaux** [comment]
Wait. What else is `lancache` storing in `/etc/dnsmasq.d/` that breaks Pi-hole?

**Comment by quielb** [comment]
Looks like my description was a little confusing, sorry about that.

Lancache has a sub-project called cache-domains.  That project contains a script to generate output that is compatible with dnsmasq.  It doesn't actually store anything in any of the pihole config tree. The output is a list of domains that you want to redirect DNS for local caching and are intended to be dropped in /etc/dnsmasq.d. In the previous version of that code, all the files that were generated were files with contents that were compatible dnsmasq configuration and had a `.conf` extension.  The newest version generates 1 file that is dnsmasq configuration and the rest of the files are host file formatted and an extension of `.hosts`.  The dnsmasq config file looks something like: `addn-hosts=/etc/dnsmasq.d/arenanet.hosts`

Problem is, the path in those files is expeted to be in the normal /etc/dnsmasq.d tree.  Since the docker container version of pihole has a dnsmasq configuration of `conf-dir=/etc/dnsmasq.d` it tries to include those host files which aren't valid dnsmasq config.  By changing the conf-dir to `conf-dir=/etc/dnsmasq.d,*.conf` it will correctly ignore anything without a .conf extension

**Comment by jfb-pihole** [comment]
"Since the docker container version of pihole has a dnsmasq configuration of conf-dir=/etc/dnsmasq.d"

This is the same configuration with non-docker Pi-hole. 

The better solution might be to change the lancache software to put the hosts files elsewhere.

**Comment by dschaper** [comment]
The default behavior of `dnsmasq` is to use anything in `/etc/dnsmasq.d/*`. The intent is that `/etc/dnsmasq.d/*` contains only configuration directives for `dnsmasq`.

We believe the same thing for `pihole-FTL`. Host files do not belong in `/etc/dnsmasq.d/*`. 

Technically this is a feature request so I'll close this as we do with all feature requests:

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
