### ISSUE TITLE
Default lists on download.

### ISSUE THREAD

**Issue by j-dogcoder** [pi-hole/pi-hole#3840]
Hi, when you download PiHole, there are 2 recommended lists. Is there any way to get your list on the recommended ones?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by dschaper** [comment]
We ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by PromoFaux** [comment]
> Is there any way to get your list on the recommended ones?

Though, to save you from getting your hopes up... The current recommended lists are not so much "recommended" as "suggested". They're totally optional to the user, and makes no difference to us whether or not they select them.

 In recent months, the number of lists on the defaults has gone down, as they become out of date/no longer maintained. The ones that remain are there purely because they've always been there, and I can't see us adding any more to this list. In an ideal world, we would have 0 suggested lists - but then that lowers the barrier to entry, and we would get an influx of "I've installed Pi-hole - but nothing is being blocked" issue tickets.

At the end of the day, what is or isn't blocked is down to the user. But the default lists on Pi-hole is not the place to advertise your list.
