### ISSUE TITLE
basic auth is not working

### ISSUE THREAD

**Issue by mdujava** [pi-hole/pi-hole#3911]
If I set up adlist address as: https://username:password@fqdn/dir/file.list, `pihole -g` or update on the web will always fail with `Invalid Target` for this adlist. On lines mentioned below `@` is not considered as usable character.

https://github.com/pi-hole/pi-hole/blob/0d8ece1be249fdc5993f01a45f8d0464257df819/gravity.sh#L397-L403

My local workaround was to add `@` to regex.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
