### ISSUE TITLE
pi-hole just cannot find an address

### ISSUE THREAD

**Issue by smcclosr** [pi-hole/pi-hole#3922]
Hello, there is a small issue that I am seeing.  Have latest 5.2 pi-hole installed, and seeing email links not resolving.  Here is an example.  My pi-hole server is 192.168.11.2, and unfiltered DNS is on 192.168.11.1:

Default Server:  VC-PIE01.localdomain
Address:  192.168.11.2

> mi.capitalone.com
Server:  VC-PIE01.localdomain
Address:  192.168.11.2

*** No internal type for both IPv4 and IPv6 Addresses (A+AAAA) records available for mi.capitalone.com
> server 192.168.11.1
Default Server:  [192.168.11.1]
Address:  192.168.11.1

> mi.capitalone.com
Server:  [192.168.11.1]
Address:  192.168.11.1

Non-authoritative answer:
Name:    ink1001.com
Address:  54.164.249.22
Aliases:  mi.capitalone.com
          www.ink1001.com

Using Cloudflare as uplink DNS for both 11.1 and 11.2

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
