### ISSUE TITLE
LDAP authentication ($100)

### ISSUE THREAD

**Issue by cyberb** [pi-hole/pi-hole#3975]
Hi,

I am the owner of Syncloud project which helps people to self host popular open source services.
Pi-Hole is one of the apps in our app store, but it is based on react/rust suspended branches.

Is it possible to implement LDAP authentication similar to this?

1. https://github.com/pi-hole/web/pull/400
2. https://github.com/pi-hole/api/pull/233

Syncloud is ready to pay for this about $100

**Comment by dschaper** [comment]
Are you selling Pi-hole?

**Comment by cyberb** [comment]
well, I sell hardware with this software installed: https://github.com/syncloud/platform

**Comment by dschaper** [comment]
Unfortunately that's against both our copyrights and our trademarks. https://pi-hole.net/trademark-rules-and-brand-guidelines/

Please remove our software from your commercial applications.

**Comment by cyberb** [comment]
Which commercial applications?
Can you clarify exactly what am I doing against Pi-Hole rules?
If I buy a System76 laptop with Ubuntu on it can I install Pi-Hole on it from their repo?
Or if I have a dynamic dns domain can I install pihole as a subdomain?

**Comment by dschaper** [comment]
From my understanding, you are selling hardware with our software pre-installed? 

System76 doesn't have a Pi-hole repository.

**Comment by cyberb** [comment]
> From my understanding, you are selling hardware with our software pre-installed?

Pi-Hole is not preinstalled, users can install it from our repository.

> System76 doesn't have a Pi-hole repository.

Ok, ubuntu snap store.

**Comment by dschaper** [comment]
There is no other way to install Pi-hole other than our official installer. Any other method is in violation.

If you are using our trademarks and copyrighted code and making modifications in any way then you are in violation of both our copyrights and our trademarks. 

Please do not do that, that is against the letter of the law and more importantly the spirit of Open Source. Do you have a public repository that contains our code and a copy of our LICENSE file?

**Comment by dschaper** [comment]
I do not see any requests from you or your company asking for our permission to use our trademarks or our copyrighted code in your product.

**Comment by cyberb** [comment]
> There is no other way to install Pi-hole other than our official installer. Any other method is in violation.

https://snapcraft.io/pihole-snap

> If you are using our trademarks and copyrighted code and making modifications in any way then you are in violation of both our copyrights and our trademarks.

EUPL (GPL compatible) license allows me to redistribute the code (an modify it) and executables as long as I can provide a source code. Do not see any problem here.
Is there any code which is not under this license?
Or do you want me to remove any trademarks from the code that would be strange?

> Do you have a public repository that contains our code and a copy of our LICENSE file?

Your code is obviously in your repo.
My change is here:
https://github.com/pi-hole/web/pull/400
https://github.com/pi-hole/api/pull/233

> I do not see any requests from you or your company asking for our permission to use our trademarks or our copyrighted code in your product.

I think I am following the License agreement in the code.

**Comment by dschaper** [comment]
> Do not see any problem here.

Great, link please to the source you are using to download and install on your commercially sold devices?

As the EUPL states, your modifications must be done under EUPL.

> Or do you want me to remove any trademarks from the code that would be strange?

That would be modification of the code and again, the requirements state that you must release that code.

> https://snapcraft.io/pihole-snap

That's not our installer, and I'll follow up with the maintainers on that, so thank you for the link.

> My change is here:

Those are changes to files that we do not use or ship, so you have obviously made modifications that you are hosting somewhere with our source code that you have modified. Please provide the link to those changes along with the copyright notice that includes our original copyrights.

https://joinup.ec.europa.eu/collection/eupl/how-use-eupl#section-21

For convenience: 

> 
> * if you modify it, keep intact all existing copyright mentions and identify your own modifications by prominent marks (who did it, when, for what purpose) with mention of your own copyright
> 
> * if you redistribute it, ensure that it is done under the EUPL licence, or under a compatible licence from the list attached to the EUPL (only if this is compulsory after merging or integrating the software with a component that is licensed under the compatible licence). 

In any case, you have not asked nor been provided any agreements that allow you to use our trademarks.

**Comment by dschaper** [comment]
https://github.com/kz6fittycent/pihole-snap/

I guess you didn't bother to check the repo.

**Comment by dschaper** [comment]
And for your next argument of not needing to show the files I've requested:

> Therefore, the deployment of the EUPL licensed software via Internet or via any similar public network is considered as a case of «distribution» according to the licence. This remains true even if the end-users perceive (for example through their Internet browser) only a selection of functionalities and not the whole software itself.
> 
> As soon such communication of EUPL software is done, the licence covers it (because – according to Article 10, the licence is accepted by exercising any rights granted by Article 2). However, this means also that, if you modify or improve some EUPL licensed software and use it to provide your services on line to the general public, you have to make your modified source code available on a repository, in order to allow the original author as well as other members of the «developers community » to benefit from your contributions, as the case could be.

**Comment by cyberb** [comment]
> Great, link please to the source you are using to download and install on your commercially sold devices?

https://github.com/syncloud/snapd

How is downloader related to the downloaded software?

> Those are changes to files that we do not use or ship, so you have obviously made modifications that you are hosting somewhere with our source code that you have modified. Please provide the link to those changes along with the copyright notice that includes our original copyrights.

Not sure what is wrong here, PRs are modifications that are done on the forks:
https://github.com/cyberb/api/tree/development
https://github.com/cyberb/web/tree/development

I have to keep the forks until LDAP feature is implemented in pihole.

> I guess you didn't bother to check the repo.

Well, I actually made it work:

https://github.com/syncloud/pihole

> In any case, you have not asked nor been provided any agreements that allow you to use our trademarks.

I have followed the license agreement, is this not enough?

Can we start discussing LDAP?

**Comment by dschaper** [comment]
So, you're being intentionally disingenuous, dodging my questions and using outdated source without proper attribution.

I can't say I'm surprised that someone who believes stealing others work and trying to turn a profit on it would behave in such a lecherous way. 

You may believe you've followed the license agreement, but you haven't. And you have no rights to our trademarks. I'll follow up with that at your posted contact information though.

As to your request:

Since we believe in open source and being proper members of that community you have two options. 

1. Write the code yourself, under our EUPL license terms, provide that code and allow others to use it per EUPL.
2. Open a Feature Request and see if anyone feels like it's worth the work. I honestly don't see it happening this year, so don't expect us to assist you with continuing your thievery. 

Either way, this repo is for bug reports so I'll close this out with what we tell others whom ignore the templates.

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by cyberb** [comment]
> So, you're being intentionally disingenuous, dodging my questions and using outdated source without proper attribution.

Is using outdated code is against the license?
What kind of attribution do you want me to make?

> You may believe you've followed the license agreement, but you haven't

In what way?

> I can't say I'm surprised that someone who believes stealing others work and trying to turn a profit on it would behave in such a lecherous way.

Is this not what pihole is doing, "stealing" AdminLTE and dnsmasq and trying to make a profit with donations and subscriptions?

> Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers

This is exactly why I am trying to pay.

> we ask that you open all Feature Requests at our Discourse Forum.

Sorry for that I thought it will be easier here as I already have some example code.
Will open a feature request on discourse.

**Comment by DL6ER** [comment]
As I see it, nobody here is "stealing" any code, we're all taking open source software and improving on it. We're hosting everything we code fully publicly online and frequently submit improvements back to `dnsmasq`. Admittedly, we never contributed back to `AdminLTE` but that's because we use it for mere displaying things and never have found it necessary to really actually change anything here.

I do see some difference in selling hardware with certain software on it and working on an entirely open software project that collects donations to keep up the various servers for deployment, discussion platforms, website, etc., but that's outside of the discussion for a feature addition IMHO.

It is unfortunate that you based your initial work for LDAP on an experimental project which was terminated mid-way. The decision was made because we only had one person maintaining/developing the code and, once this one person turned away, there was nobody left that would have been able to finish the work in any reasonable time. Unfortunately, the entire core developer team had a lot of changes in their life in the past few years (moved to different states, new jobs with more responsibilities, built up a family, etc.) so the focus of Pi-hole had to change focus from being very innovative and explore new languages and concepts to improving what we already have and know. Learning a new language is out of scope for us all at the moment which is another reason why the decision was made to shutdown the Rust/React experiments.

We're currently looking at moving away from `lighttpd` and PHP to an embedded webserver (civetweb) with embedded PHP-compatible scripting (PH7) in FTL. This is scheduled for Pi-hole v6.0 and hopefully something we can achieve this year. The largest change will be that we redesign the entire API to something better suited for the job (RESTful).
The next step after this one is then targeted to be a switch to a new, more modern, web framework but this is still experimental and has not even an approximate ETA on it.

I'm not sure how LDAP would fit into all this as of yet, but this may be also because I've never used it myself (I only heart rumors it'd be complex to setup but I have never felt the need to actually even consider doing it for me at home). You may know this better.

**Comment by cyberb** [comment]
LDAP is horrible on server side but bearable on client side and I think (maybe I am wromg) it is still the most common authentication/authorization protocol with a very wide language coverage.

What would be the best place to implement it right now php or c?
Also would you accept the implementation?
Obviously I can get some freelancer to do that.

**Comment by dschaper** [comment]
We enforce DCO and require all submissions to be compatible with EUPL 1.2.

https://docs.pi-hole.net/guides/github/contributing/

Hiring a Fiverr to write some code that is unsustainable or unsupportable probably isn't going to get merged in.
