### ISSUE TITLE
Not redirecting blocked https://

### ISSUE THREAD

**Issue by noipstream** [pi-hole/pi-hole#3979]
The blocked page is not working over HTTPS:// even if the pi-hole ip has a FQDN.

ERR_SSL_UNRECOGNIZED_NAME_ALERT

(mod_openssl.c.362) SSL: no certificate/private key for TLS server name filterlist.com

**Comment by technicalpyro** [comment]
1st You complete have ignored the issue template.  
2nd pi-hole will never work on Https as that would require a man in the middle attack which the project will not do

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.
