### ISSUE TITLE
PiHole blocking not works on Mi A2 Lite

### ISSUE THREAD

**Issue by LorisTecnology** [pi-hole/pi-hole#3984]
### Versions

Pi-hole version is v5.2.2 (Latest: v5.2.2)
AdminLTE version is v5.2.2 (Latest: v5.2.2)
FTL version is v5.3.4 (Latest: v5.3.4)

### Platform
- OS and version:  Raspberry Pi Os 
- Platform:  Raspberry Pi 3B

### Expected behavior

Pi hole should block queries from Mi A2 Lite running Android 10

### Actual behavior / bug

No query got blocked or even pass through the pi hole
See screenshoot for more details

### Steps to reproduce

1. Enable Pi hole
2. Enable DHPC
3. Connect a Mi A2 Lite running Android 10 to the network

### Screenshots
![image](https://user-images.githubusercontent.com/63395247/104346126-58508e00-54ff-11eb-88b4-b9deae35472d.png)

**Comment by hyperbaba** [comment]
It's not pi-hole issue. The real issue is that mi phone is completely ignores dns settings and uses it's own dns servers. Usefull for tracking, isn't it?

**Comment by ChurchOfNoise** [comment]
Blokada (an android app) has a functionality where it can 'force' DNS server settings IIRC, perhaps that could help... 


Van: "Vladimir Grujic" <notifications@github.com> 
Aan: "pi-hole/pi-hole" <pi-hole@noreply.github.com> 
Cc: "Subscribed" <subscribed@noreply.github.com> 
Verzonden: Vrijdag 5 februari 2021 12:13:31 
Onderwerp: Re: [pi-hole/pi-hole] PiHole blocking not works on Mi A2 Lite (#3984) 





It's not pi-hole issue. The real issue is that mi phone is completely ignores dns settings and uses it's own dns servers. Usefull for tracking, isn't it?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
