### ISSUE TITLE
local cnames not working

### ISSUE THREAD

**Issue by nebakanezzer** [pi-hole/pi-hole#3992]
hi there,

I use pihole with unbound primarily as a lightweight linux dns server. I am utilizing dnsmasq.d for local dns entries. I am sure I am missing something very simple or screwing up syntax, but my cnames have never really worked correctly.

an example of one of my cname entries:

cname=firewall.xyz.com,fw-01.xyz.com
address=/fw-01.xyz.com/192.168.1.1

I see this is supported in webui now, so I added an entry there and saw it created this file:

/etc/dnsmasq.d/05-pihole-custom-cname.conf

I added all of my cname entries there and removed them from

/etc/dnsmasq.d/05-custom.conf

restarted pihole dns and flushed dns on windows laptop. tried to lookup a cname, could not find host

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by nebakanezzer** [comment]
i left out the debug token, as i was copying and pasting from reddit: https://www.reddit.com/r/pihole/comments/k8d9mw/local_cnames_not_working/

where i was specifically told not to log it as a bug. if i'm not to follow the bug issue format, what instructions should i follow to post an issue?

token https://tricorder.pi-hole.net/km65721eqa

**Comment by dschaper** [comment]
>Github is for bug reports. You don't appear to have a bug. Open a new help topic on discourse.pi-hole.net.

**Comment by nebakanezzer** [comment]
cnames not working at all, and being able to reproduce that isnt a bug?

**Comment by dschaper** [comment]
https://discourse.pi-hole.net/t/local-cname-resolution-is-inconsistent/41842/4?
