### ISSUE TITLE
pihole failed to install FTL Engine when reinstall

### ISSUE THREAD

**Issue by laoshaw** [pi-hole/pi-hole#3998]
### Versions

```
  Pi-hole version is v5.1.2 (Latest: v5.2.3)
  AdminLTE version is v5.1.1 (Latest: v5.3)
  FTL version is v5.2 (Latest: v5.4)
```

### Platform

Linux Pi 4.19.62-sunxi pi-hole/FTL#5.92 SMP Wed Jul 31 22:07:23 CEST 2019 armv7l GNU/Linux

Debian 10.7

### Expected behavior

upgrade should complete

### Actual behavior / bug

upgrade failed with:

PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -r

```
 [✓] Enabling lighttpd service to start on reboot...
  [✓] Checking for user 'pihole'

  [i] FTL Checks...

  [✓] Detected ARM-hf architecture (armv7+)
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL https://github.com/pi-hole/ftl/releases/latest/download/pihole-FTL-arm-linux-gnueabihf not found
  [✗] FTL Engine not installed
```

NOTE, `pihole -up` worked fine though.

**Comment by dschaper** [comment]
`PIHOLE_SKIP_OS_CHECK=true`

If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.
