### ISSUE TITLE
PiHole not loading admin GUI and DNS problem

### ISSUE THREAD

**Issue by XeroHero** [pi-hole/pi-hole#4007]
Hi. 
I have had PiHole set up on my Raspberry Pi for about 6 months and it has worked perfectly fine until this evening. 
I decided to run `pihole -up` to update it (I do that every few months).
This time, however, it seems like something went wrong with the update. It is now showing a PHP script (in text form) whenever I try to access the admin console or any of the pages for PiHole on 192.168.0.11/admin where 192.168.0.11 is the Pi's static IP address.
I have tried uninstalling and reinstalling PiHole, but it is still not loading. Also, the DNS server seems to have gone down. I have rebooted the Pi several times already but to no avail.
Any help is greatly appreciated, as i would not like to have to reimage the Pi as i have a lot of other services running off it at the moment.
Thank you very much. 😊

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. 

Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
