### ISSUE TITLE
latest upgrade fails as it implicitly assumes DNS access.

### ISSUE THREAD

**Issue by nimbius** [pi-hole/pi-hole#4011]
the latest pihole update check fails if DNS is unilaterally restricted on the local network.  specifically, when determining if an OS is supported.

the bug indicates:
` - ns1.pi-hole.net being blocked (required to obtain TXT record from versions.pi-hole.net containing supported operating systems)
`

- pihole should never assume it has direct line-of-site to resolve DNS outside of its host network.  many private and/or hostile networks block port 53 outbound in order to prevent circumvention of pihole filtering or IPS/IDS systems.

- instead of a callout, pihole should perform this check once the new version is staged on the system.

- pihole developers should **never** assume the network is reliable.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by dschaper** [comment]
`curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash`
or
`PIHOLE_SKIP_OS_CHECK=true sudo -E pihole -up`
