### ISSUE TITLE
Dns Resolution Stops working after PiVpn - Wireguard installation

### ISSUE THREAD

**Issue by goldytech** [pi-hole/pi-hole#4027]
### Versions

- Pi-hole: 5.2.4  
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  

- Platform: Raspberry Pi 3  

### Expected behavior

After installation and configuration of Pihole , Everything seems to be working as expected. Then I installed PiVpn (Wireguard)
In the installation of PiVpn I had selected default option of using PiHole as DNS. Now my internet has stopped working after as dns queries are not being resolved. Can you please help if anything important that I've missed as a part of configuration.

### Actual behavior / bug

DNS resolution should work after Pivpn Wireguard installation

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
You'll need to open an issue on PiVPN's repo since that's the application that caused DNS to stop working.

And you've ignored the bulk of the template.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
