### ISSUE TITLE
Graphs broken by recent update

### ISSUE THREAD

**Issue by Synetech** [pi-hole/pi-hole#4035]
### Versions

- Pi-hole:  5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform
Armbian Buster

### Expected behavior
Dashboard should show graphs

### Actual behavior / bug
Graphs are empty (data exists in logs, but graphs are blank)

This started after a recent update.

### Steps to reproduce

1. Go to dashboard
2. Look at graphs
3. See graphs are empty

### Screenshots
![Pi-Hole Empty Graphs](https://user-images.githubusercontent.com/5210197/106767535-f5877980-6608-11eb-9748-fdc9751e9291.png)

**Comment by yubiuser** [comment]
Please provide a debug token as required in the template

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by Synetech** [comment]
Restarting Pi-Hole didn't fix it, but deleting the logs and the restarting did.

**Comment by dschaper** [comment]
Not sure why that did anything since the data is in the database and not in any logs. But glad you fixed it.
