### ISSUE TITLE
Pi-hole and google oauth weird problems

### ISSUE THREAD

**Issue by DurgNomis-drol** [pi-hole/pi-hole#4045]
### Versions

- Pi-hole:  v5.2.4
- AdminLTE:  5.3.2
- FTL:  5.6

### Platform

- OS and version:  OpenmediaVault 5.5.23-1

- Platform:  Raspberry Pi in a docker container

### Expected behavior

Normal behavior for all devices trying to connect to google like my android phone or android tv. Problem does not seems to exists on non android platforms, but im not sure

### Actual behavior / bug

On android devices it constantly ask you to sign in again and when you do it connects. But after about 5 minutes it ask you again and it does this again and again and again.

When im connected to LTE or if i remove Pi hole entirely the problem disappears. Disabling pi hole in the admin interface does not remove the problem.

### Steps to reproduce

No idea. It just started happening one day after i change my google password.

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

I dont have any, there isnt anything to take a screenshot of.

### Additional context

All logs are normal, every thing that should be allow are allowed in pi-hole.

I have removed pi hole from my installation and this bug is properly one of those bugs that only exists in very rare conditions. When i have time i will start a new installations and try to figure out what maybe be the problem.

I dont expected you to have a solution. I thought i would make this bug report so others who is maybe having the same experience.

Recently a bug in urllib3 where found related to google oauth python library, i dont know if that is any help to you. [Bug here](https://github.com/urllib3/urllib3/issues/2101)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
