### ISSUE TITLE
Local DNS : Using one domain with more one ip

### ISSUE THREAD

**Issue by muhanadali100** [pi-hole/pi-hole#4052]
In local DNS i can't using one domains with more one ip like
cndw2.shabakaty.com 46.151.64.49
cndw2.shabakaty.com 46.151.64.50
cndw2.shabakaty.com 46.151.64.51
cndw2.shabakaty.com 46.151.64.52

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
