### ISSUE TITLE
DNS cache size is lost when updating

### ISSUE THREAD

**Issue by cybernard** [pi-hole/pi-hole#4078]
Pi-hole version is v5.2.4 (Latest: v5.2.4)
  AdminLTE version is v5.4 (Latest: v5.4)
  FTL version is v5.7 (Latest: v5.7)

 I want my cache size to be larger, but every time I update it resets to 10k.  

### Versions

- Pi-hole:  
- AdminLTE:  
- FTL:  

### Platform

- OS and version:  Standard Pi 4   Pi OS

- Platform:  

### Expected behavior
I expect 100k cache size to stick and not get reset

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

The DNS cache size resets to 10,000

### Steps to reproduce

1.  Set cache size to 100,000
2.  wait for an update and install it
3.  Now your cache size is 10,000

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
