### ISSUE TITLE
cant resolve facebook services (messenger, instagram, etc...)

### ISSUE THREAD

**Issue by lalicsatlos** [pi-hole/pi-hole#4080]
### Versions
- Pi-hole:  v5.2.4
- AdminLTE:  v5.4
- FTL:  v5.7

### Platform
- OS and version:  Ubuntu 20.04.2 LTS
- Platform:  Truenas VM

### Expected behavior

Load facebook services

### Actual behavior / bug

When I trie to connect messenger.com in chrom or other browser it don't want to connect. If I switch my dns server from pihole to 1.1.1.1 it works (1.1.1.1 is also my pihole dns). And I also have a backup pihole on a raspberry but thats also broken. It worked before I upgraded from pihole (I don't remember the version). And also when I trie to nslookup messenger.com it gives a valid ip.

## Debug Token

- URL:  https://tricorder.pi-hole.net/luqreo7rwk

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
