### ISSUE TITLE
Pihole binary not supplying non-zero exit codes

### ISSUE THREAD

**Issue by shoddyguard** [pi-hole/pi-hole#4082]
### Versions
- Pi-hole:  5.2.4
- AdminLTE:  5.4
- FTL:  5.7

### Platform
- OS and version:  Ubuntu 20.04
- Platform:  Direct install

### Expected behavior

`pihole` should return non-zero exit codes when it fails to perform an operation

### Actual behavior / bug

`pihole` reports an exit code of `0` for some failed operations

### Steps to reproduce

```
root@linux-tests-ubuntu-2004:/home/vagrant# pihole -w '!12345Test'
  [✗] !12345test is not a valid argument or domain name!
root@linux-tests-ubuntu-2004:/home/vagrant# echo $?
0
```

## Debug Token

- URL:   https://tricorder.pi-hole.net/j1i5kikqqc

### Additional context

While this bug isn't a showstopper by any stretch of the imagination it does make doing things programatically somewhat of a challenge especially when it comes to trying to handle errors.

**Comment by jfb-pihole** [comment]
Is the plain text explanation of the error not sufficient?  The domain you are entering is not a valid domain, and Pi-hole won't add it to the domain list as a result.  Or, are you running a script that is looking for an exit code following the operations?

https://en.wikipedia.org/wiki/Hostname

**Comment by dschaper** [comment]
`pihole` is a bash script. I guess we could make sure all `exit` and `return` calls are 0 or 1. I guess we could get even fancier and output to `stdout` and `stderr` depending. Really this isn't a bug in my opinion and more of a feature request and should be addressed in that manner. 

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.

**Comment by shoddyguard** [comment]
To answer the above questions, yes I am running pihole as part of another operation. specifically I'm writing a Puppet module to be able to deploy Pi-Hole and due to Puppet's declarative nature it expects exit codes.

I would argue that this is more of a bug as standard practice is to have commands terminate properly, but I appreciate this isn't exactly a show-stopper and most users will probably never run up against this.

Given you're limited on resources then it makes sense for me to make these changes myself and submit a PR.
