### ISSUE TITLE
Pihole *DEV* will return HTTP ERROR 500 on 404 pages where the generic page is expected.

### ISSUE THREAD

**Issue by DenyDarko** [pi-hole/pi-hole#4098]
### Versions

 - Pi-hole version is development v5.2.4-24-gb51751e (Latest: v5.2.4)
 - AdminLTE version is devel v5.4-27-g6fd3a02 (Latest: v5.4)
 - FTL version is development vDev-cf2e3e5 (Latest: v5.7)

### Platform

- OS and version:  Linux raspberrypi 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux

- Platform:  Raspberry Pi

### Expected behavior

_See the "do you want to go to the admin panel" generic page when visiting a non-existing page on pihole server_

### Actual behavior / bug

_Lighttpd error 500. Something's wrong with pihole/index.php_ 

## Debug Token

- URL:  https://tricorder.pi-hole.net/7nsh8qjoou

**Comment by dschaper** [comment]
Can you give an example URL of where this happens please?

**Comment by DenyDarko** [comment]
hey @dschaper.
Commit https://github.com/pi-hole/pi-hole/pull/4095 by @jbaez is fixing the 500 error.

It just breaks the visual part:
![11av](https://user-images.githubusercontent.com/3320229/112869762-2db9ae80-90c6-11eb-87ee-b7e916d080df.png)

**Comment by PromoFaux** [comment]
Before anyone expends too much energy on this, I've proposed these changes for 6.0:

https://github.com/pi-hole/pi-hole/pull/3910

**Comment by jbaez** [comment]
> Hey @dschaper.
> It happens on root directory. Where the splash is shown.
> 
> Commit #4095 by @jbaez is fixing the 500 error.
> 
> It just breaks the visual part:
> ![11av](https://user-images.githubusercontent.com/3320229/112869762-2db9ae80-90c6-11eb-87ee-b7e916d080df.png)

I haven't checked running index.php in a development branch installation since my changes didn't change the HTML (apart from removing a duplicated viewport meta tag)

In the commit before mine 13cf0c12881447a4fc7cab5cedee6e2cd7514e0c the HTML and the CSS was changed. So by just copying the index.php into a running pi-hole from a branch that doesn't have that CSS updated, would probably show the screen like in that screenshot (it's showing like that when I emulate a mobile screen in mine since I just replaced the index.php in my running pi-hole install from master)

What I just did to confirm, and until this is merged and applied into the next release, is revert the previous commit 13cf0c12881447a4fc7cab5cedee6e2cd7514e0c changes to my running index.php so it looks as it used to in master branch

<img width="432" alt="Captura de pantalla 2021-03-29 a las 20 23 06" src="https://user-images.githubusercontent.com/1777543/112881942-9dcb3300-90cc-11eb-9408-c691e07bce7f.png">

**Comment by DenyDarko** [comment]
> Before anyone expends too much energy on this, I've proposed these changes for 6.0:
> 
> #3910

Well it seems it's a simple CSS matter as the abovementioned commit is fixing the php part, no much energy is involved I assume
