### ISSUE TITLE
Signing-in, but nothing happens

### ISSUE THREAD

**Issue by josemi73** [pi-hole/pi-hole#4124]
- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8

- Platform:  Windows 10 - Chrome, Firefox, Edge

I have just updated, and after signing-in, it works, but nothing happens. Options in Menu are shown, but if you click an option, the sign-in field is shown again. I have restarted httpd daemon, and tested with 3 different browsers (deleting caches), private tabs, but the same behaviour

Thank you

**Comment by bharathmsd7** [comment]
Try running pihole -r to run the repair script.
Then run pihole -up 
This may help you to fix this issue

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by josemi73** [comment]
@bharathmsd7 I repaired but it didn't work. It was my mistake, my microSD was full. I freed some space, and it is working fine now. Sorry for the inconvenience. I have spent much time looking for the problem, when I tried to install again pi-hole, it showed up that it was unable to write, and it gave my the right track.

@dschaper I am very sorry, I am not a native speaker, and my english knowledge is limited.

Thank you both
