### ISSUE TITLE
Feature request: whitelist domain from query list

### ISSUE THREAD

**Issue by eDavidT** [pi-hole/pi-hole#414]
Would be nice to whitelist domain straight from the query list GUI. Maybe add both whitelist and blacklist options?
##

**Comment by Mcat12** [comment]
We are working on this feature in a branch called whitelist, but we want to make sure it is secured so that ads can't whitelist themselves (addomain.com/admin/php/add.php?l=white&domain=addomain would whitelist itself, since we redirect queries to the pi itself).

**Comment by DonLexos** [comment]
Would a regular expression to check the referer of the whitelist request not fix this potential issue?

I mean if add.php would check it's own requested url and check if it is requested from a (local) ip address instead of a domain? Not sure if I explain it well but basicly that it's run from http://192.168.1.x/etc (maybe can even check it's own local IP from somewhere) and check if the requested url contains that string instead of a domain.com?

**Comment by Mcat12** [comment]
@Rahel-A O.o another?

**Comment by Mcat12** [comment]
When the whitelisting is added, you should be able to just copy the domain and whitelist it. A whitelist button would be convenient though.

**Comment by Mcat12** [comment]
Whitelisting/blacklisting will be available from the web interface in the next update!

**Comment by jacobsalmela** [comment]
Closing.  Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/whitelist-domain-from-query-list/558) so this feature is votable.
