### ISSUE TITLE
Query log displays incorrect client name

### ISSUE THREAD

**Issue by antamy** [pi-hole/pi-hole#4181]
### Versions
  Pi-hole version is v5.3.1 (Latest: v5.3.1)
  AdminLTE version is v5.5 (Latest: v5.5)
  FTL version is v5.8.1 (Latest: v5.8.1)

### Platform
Linux pihole 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64

### Expected behavior

Expect to see the query log display the correct name for the client

### Actual behavior / bug

For one particular client (my cell phone - 10.10.10.76), the query log shows the dns name for my work laptop (G417LLAX / 10.10.10.77).   

If I grep pihole.log for G417LLAX, I see:

```
May 25 14:05:52 dnsmasq[578]: reply 10.10.10.77 is G417LLAX.xxx.com
May 25 14:13:55 dnsmasq[578]: cached 10.10.10.77 is G417LLAX.xxx.com
May 25 14:29:03 dnsmasq[578]: reply 10.10.10.77 is G417LLAX.xxx.com
```

If I look at Query Log, I see queries associated with G417LLAX, but they are not queries that come from that device.  If I grep pihole.log for 10.10.10.76, these queries are correct in the pihole.log, but they do not display with that IP address or client name in the Query Log.  See the example in the attached screenshot.

I have tried rebooting the pihole, flushing DNS and the same errors occurs.

![image](https://user-images.githubusercontent.com/6841038/119558826-883e5680-bd67-11eb-9698-a00a05d6043a.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
