### ISSUE TITLE
Debian10, unsupported OS

### ISSUE THREAD

**Issue by enesinan** [pi-hole/pi-hole#4185]
### Platform
<!-- OS examples: Debian 10

### Expected behavior

can be set up to pi-hole

### Actual behavior / bug

when I type to,
 curl -sSL https://install.pi-hole.net | bash
 give an error to that using unsupported OS

### Screenshots

![issuee](https://user-images.githubusercontent.com/72499839/120100397-4d626700-c149-11eb-8b78-41aac8560b03.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
