### ISSUE TITLE
Blockingmode IP does not block

### ISSUE THREAD

**Issue by eglyn** [pi-hole/pi-hole#4198]
### Versions

- Pi-hole:  5.3
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform

- OS and version:  Debian 10

- Platform:  VM

Hello !
I try ro use the blocking webpage of Pihole instead the default dns error, so I follow the doc: 
- change in pihole-FTL.conf --> BLOCKINGMODE=IP
- restart service pihole-FTL

But when I test on a website that I have blocked, this site is not blocked... In log, the website is tagged blocked, but not blocked on the browser.
If I come back to BLOCKINGMODE=NULL, website is blocked with default browser dns error.

I checked the lighthttpd config and there is the: 
server.error-handler-404    = "/pihole/index.php" line 
Any idea why ?

**Comment by jfb-pihole** [comment]
"`server.error-handler-404 = "/pihole/index.php"`
Any idea why ?"

This is normal.  That is the error handler for lighttpd when configured for Pi-hole.

"In log, the website is tagged blocked, but not blocked on the browser."

This appears to be a browser issue.  If Pi-hole is blocking the domain but the browser still loads the domain, the browser has that domain in cache or is getting DNS resolution from somewhere other than Pi-hole.

Side note - the Pi-hole block page has limited usefulness, since it only works for http pages (and not https).  The block page will be discontinued in the future.

**Comment by eglyn** [comment]
> Side note - the Pi-hole block page has limited usefulness, since it only works for http pages (and not https). The block page will be discontinued in the future.

Oh, ok, i did my tests on a https website (http website are very rare :D nowaday :D)

So, i will switch definitively to NULL mode, It's too bad, because displaying a custom error page would be really good :)
