### ISSUE TITLE
Excessive queries from two specific Homebridge devices.

### ISSUE THREAD

**Issue by radeonx1800** [pi-hole/pi-hole#4204]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5
- FTL:  5.8.1

### Platform
 Raspbian
- OS and version:  10
 
- Platform: Pi 3b

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
Using Homebridge and Pi-Hole on the same Pi. Two domains are generating excessive amounts of queries "local cache" from "localhost." The queries are related to a Govee led strip and wyze smart plugs. 
This all began when I setup PiVPN and Unbound, after they were up and running the queries spiked. Before when I this setup without PiVPN&Unbound everything was totally normal. I don't think The devices themselves are phoning home this often since this began the second I installed those two. 
I have conditional forwarding and DNSSEC disabled. 
## Debug Token

- URL:  https://tricorder.pi-hole.net/1hyi677gnz

### Screenshots

_If ![image](https://user-images.githubusercontent.com/61127410/122486106-60c55d00-cfa6-11eb-9e8d-86ae1ca7e276.jpeg)applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by dschaper** [comment]
How can we help you?

**Comment by radeonx1800** [comment]
Trying to figure out why only these two domains are producing so many queries since setting PiVPN and Unbound up.

**Comment by dschaper** [comment]
Okay, can you show your query log that shows what clients are querying these domains? I'm not quite sure what you mean when you said "local cache". 

If PiVPN is set up on the same Pi as Pi-hole and the clients are set to use PiVPN then it may be difficult to decide where the queries are truly coming from. It sounds like the clients are indeed making these queries since you have Govee and Wyze devices on the network. 

I don't think this is a bug so you might be better served using our https://discourse.pi-hole.net for your questions. It's likely a configuration issue and there are a lot more people on Discourse that can provide hints or tips. We deal with bugs here on GitHub and very few of the support team is active here.
