### ISSUE TITLE
Deleted the server where i installed pi-hole but the ads still blocked with the ip of the client 

### ISSUE THREAD

**Issue by YAS01-M** [pi-hole/pi-hole#4210]
### Versions

- Pi-hole:  unknown
- AdminLTE:  unknown
- FTL:  unknown

### Platform

- OS and version:  Ubuntu Server 20.04 

- Platform:  VM 

### Expected behavior

Hi , i installed Pi-hole in my Ubuntu VM and i added the ip of my windows who is the client . After a while , i removed the Ubuntu VM and forgot to uninstall Pi-hole , now i can't access the web interface , in the same time the ads are blocked , this is even when i restarted my router so i can get a new ip address .  Now i installed Pi-hole in Debian wsl 2 with new a ip adress , i accessed the web interface but i found as i expected that the device does not use Pi-hole because of the old installation . I've been locking around   the web about this problem but i can't found anything like it , any solutions ?

**Comment by jfb-pihole** [comment]
Please open a ticket on our Discourse site:

https://discourse.pi-hole.net

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
