### ISSUE TITLE
When connecting to the DNS server on other device lose connection

### ISSUE THREAD

**Issue by bananastew** [pi-hole/pi-hole#4250]
Hi, when I try to configure my win10 pc (Or any other device on the network) to the pihole DNS server the pc connected loses connection and can't access the admin panel, I am able to access the panel fine on the Ubuntu VM (that it's hosted on) and blocking works as well on the VM but nothing works on other devices.

Debug token:
mdvsxp4lso

Thanks!

**Comment by bananastew** [comment]
*The ubuntu VM that it is hosted on.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
