### ISSUE TITLE
DNSSEC Issue - Time Sync and Name Resolution Problems For The Hole Network

### ISSUE THREAD

**Issue by userofgithub023897** [pi-hole/pi-hole#4283]
### Versions
pihole -v
  Current Pi-hole version is v5.3.1.
  Current AdminLTE version is v5.5.1.
  Current FTL version is v5.8.1.

### Platform
cat /etc/*release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

#### 1. Time Synchronization Issue
Raspberry Pi server on which Pi-hole runs was not in time sync.

`timedatectl` showed a complete different time as the current time.
Because of this issue
* the query logs 
* web interface 
were wrong too.

#### 2. Name Resolution Issue
Additional to that time issue a couple of devices within the network were not able to connect to the internet.
It showed the error *"Temporary failure in name resolution"*

### Steps to reproduce
1. I rebooted the hole Raspberry Pi system a couple of times, deactivated temporarily the firewall, etc. Nothing fixed the problem. 

2. Deactivated DNSSEC (Settings --> DNS --> Use DNSSEC) in Pi-hole settings and everything works as expected. All network devices are in time sync again and the name resolution issue is gone.
Now the query log shows the correct time and the Dashboard jumped to the correct one, too.
(The tip I found here [https://discourse.pi-hole.net/t/uhrzeit-ist-falsch-und-pihole-funktioniert-nicht-mehr/47790](https://discourse.pi-hole.net/t/uhrzeit-ist-falsch-und-pihole-funktioniert-nicht-mehr/47790))

3. Activated DNSSEC again and hopefully the issue will not come back.

**Comment by yubiuser** [comment]
This is not a Pi-hole issue. As you figured out, DNSSEC needs accurate time to work. Otherwise all queries will be rejected. The catch 22 is, that also the queries to the NTP servers will fail.

Fix the time issues of your OS and Pi-hole will work as expected.

**Comment by dschaper** [comment]
Raspberry Pi devices do not have a real time clock module on them so they can have problems with time. As yubiuser mentioned, DNSSEC is affected by time issues.

There's a couple of solutions to this. First would be to get an RTC module and connect it to the Pi device. They are inexpensive and there are many guides out there on how to connect them and set them up. The other option would be to use NTP and use an IP address instead of a domain name so there is no DNS involved. This can cause an issue if the time is adjusted after `pihole-FTL` is started however.
