### ISSUE TITLE
Running a Standard Update of the Gravity DB Yields Connection Refused

### ISSUE THREAD

**Issue by stevefxp1** [pi-hole/pi-hole#4285]
### Versions

- Pi-hole:  5.3.1
- AdminLTE:  5.5.1
- FTL:  5.8.1

### Platform
Ubuntu 20.4.02

### Expected behavior

Running a Standard Update of the Gravity DB Yields Connection Refused

In running a standard update of the Gravity DB and I am getting 3 connection refused results. Please see the attached screen shot. I can click on each list and get access, so why is this getting refused when I do an update?

![129499495-9557e249-c450-4cc7-aa75-d9b016a51075](https://user-images.githubusercontent.com/70986226/129631183-1bd9da79-4323-4148-a76f-1e93298af9d2.png)

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
