### ISSUE TITLE
Missing `mod-deflate` on Debian 11

### ISSUE THREAD

**Issue by CypressXt** [pi-hole/pi-hole#4310]
### Versions

- Pi-hole:  `v5.3.1`
- AdminLTE:  `v5.5.1`
- FTL:  `v5.8.1`

### Platform

- OS and version:  `Debian 11 (bullseye)`

- Platform:  `VM`

### Expected behavior

Automated install succeed to finish without error, bringing Pi-hole up and running.

### Actual behavior / bug

During the automated install `lighttpd` is unable to start because `mod-deflate` is not installed.
```
lighttpd[20035]: 2021-09-03 21:01:33: configfile.c.461) Warning: "mod_compress" is DEPRECATED and has been replaced with "mod_deflate".  A future release of lighttpd 1.4.x will not contain mod_compress and lighttpd may fail to start up
lighttpd[20035]: 2021-09-03 21:01:33: plugin.c.195) dlopen() failed for: /usr/lib/lighttpd/mod_deflate.so /usr/lib/lighttpd/mod_deflate.so: cannot open shared object file: No such file or directory
lighttpd[20035]: 2021-09-03 21:01:33: server.c.1238) loading plugins finally failed
```

### Steps to reproduce

1. Clean and default Debian 11 install
2. Trigger the automated install skipping the OS check:  `curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash`
3. See error

## Debug Token

- URL:  https://tricorder.pi-hole.net/l403n4bU/

### Additional context

Was able to solve the issue by installing  the missing `lighttpd-mod-deflate` package. Retarted the auto-install and everything is working perfectly since then. 
Not sure if it's actually a "bug report"  or a "feature request" due to the fact that Debian 11 is officially not supported yet.
Sorry if I categorized it wrongly.

**Comment by yubiuser** [comment]
Thanks for the report.

`mod_compress` will be removed from lighttpd config in the future. 
https://github.com/pi-hole/pi-hole/pull/4221

**Comment by abesnier** [comment]
Sorry to come back on a closed issue, but there are other adjustments to be made for Bullseye and Buster-backports (lighttpd 1.4.59).
As already mentioned, `lighttp-mod-deflate` is now a separate package.
The following need to be amended in `lighttpd.conf` to prevent warnings:
replace `compress.filetype` with `deflate.mimetypes`
replace `compress.cache-dir` with `deflate.cache-dir`

I also got a warning ("`WARNING: unknown config-key: alias.url (ignored)`), because of `/etc/lighttpd/conf-enabled/90-javascript-alias.conf` that contains the following line:
`alias.url += ("/javascript" => "/usr/share/javascript")`
I don't know if this configuration is enabled by pihole or by default though. To remove the warning, it requires `mod_alias` to be added in the `server.modules` section.
