### ISSUE TITLE
Catchpoint blog migraiton

### ISSUE THREAD

**Issue by doffymingozzz** [pi-hole/pi-hole#4337]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages:
https://archive.org/details/github.com-pi-hole-pi-hole_-_2019-09-24_08-46-08
I wonder if you’d be able to replace it with the new one:
https://www.catchpoint.com/blog/ad-block-ios-impact
Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by yubiuser** [comment]
Thanks for letting us know.

This should be fixed with: https://github.com/pi-hole/docs/pull/570
You can see the preview here: https://deploy-preview-570--pihole-docs.netlify.app/main/coverage/?utm_source=github&utm_campaign=bot_dp

In turn, please change the broken link in your blog post (http://jacobsalmela.com/block-millions-ads-network-wide-with-a-raspberry-pi-hole-2-0/) to https://pi-hole.net/

Thanks you.

**Comment by yubiuser** [comment]
Pinging @doffymingozzz 
Can you please change the broken link in return?

Thanks

**Comment by doffymingozzz** [comment]
Sure, will be fixed ;) I'll write to devs
