### ISSUE TITLE
Unable to add , remove URLs on adlist or block / white lists

### ISSUE THREAD

**Issue by Diaclone** [pi-hole/pi-hole#4340]
Error, something went wrong!
While executing adlist_by_group statement: attempt to write a readonly database

Above is the error I am getting. HELP  

I did try to reboot FTL and did a ( -r  ) and ( -up  )... I even tried ( -a ) in hopes it may list something.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
