### ISSUE TITLE
pi-hole status ok / interface ok / blocking not working

### ISSUE THREAD

**Issue by botea14** [pi-hole/pi-hole#4344]
### Versions
  Pi-hole version is v5.4 (Latest: v5.4)
  AdminLTE version is v5.6 (Latest: v5.6)
  FTL version is v5.9 (Latest: v5.9)

### Platform
- OS and version:  CentOS 8 fresh install, CentOS 7 fresh install ( on both of them tried also minimal / server install.
- Platform:  VM - Dedicated IP, 8x3.5GHz core, 4GB ram.

### Other platforms
- Debian 11, Ubuntu 20, Ubuntu 21, teste from a Container (VPS) with Dedicated IP, 8x3.5GHz core, 4GB ram.
- 
### Expected behavior

_After installing pi-hole on Debian 11, Ubuntu 20,21 and CentOS 7 and 8 many times, i am still not able to understand why i can't get blocking to work. Everything works well, /admin/ interface works, i can edit anything, all system is up and running but not blocking anything, even if i add domain on Blocklist.,_

_Please i am trying to make it work for last 2 days :( _

**Comment by yubiuser** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search open and closed issues for others that may have your same question. Also, visit our[ Discourse site ](https://discourse.pi-hole.net/)for additional assistance.
