### ISSUE TITLE
Can not access domain name when DHCP domain name set

### ISSUE THREAD

**Issue by amohsen01** [pi-hole/pi-hole#4390]
### Versions

- Pi-hole:   v5.5
- AdminLTE:   v5.7
- FTL:  v5.10.2

### Platform

- OS and version:  Ubuntu 20.10

- Platform:  Proxmox VM

### Expected behavior
When setting up the domain name on the DHCP Settings, the user must be able to access the domain normally.

_A clear and concise description of what you expected to happen._

### Actual behavior / bug
NXDOMAIN error returns when accessing the same domain as the DHCP Domain name.
_A clear and concise description of what the bug is._

### Steps to reproduce

1. Go to 'Settings and click on DHCP tab'
2. Edit the domain name for the DHCP to any domain you want to 
3. Try accessing the domain name, and you will get a NXDOMAIN

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._
![Screenshot 2021-10-16 174401](https://user-images.githubusercontent.com/58693279/137589833-cf93aacb-65e7-45e0-b4ee-1e16805b5b2c.png)
![Screenshot 2021-10-16 174422](https://user-images.githubusercontent.com/58693279/137589835-b0bd8656-3c1e-420a-8cb6-b6ce628a03a4.png)

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Do you habe any host named `www`?

**Comment by yubiuser** [comment]
Please provide a debug token.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
