### ISSUE TITLE
IP4 address not provided for googlemail.l.google.com

### ISSUE THREAD

**Issue by VioletGiraffe** [pi-hole/pi-hole#4402]
```
  Pi-hole version is v5.5 (Latest: v5.5)
  AdminLTE version is v5.7 (Latest: v5.7)
  FTL version is v5.10.2 (Latest: v5.10.2)
```

Platform: Raspberry Pi Zero W running Raspbian
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

I have configured a complete recursive DNS using `unbound` according to this guide: https://docs.pi-hole.net/core/pihole-command/

Problem: I occasionally find that I can't access Gmail and some other Google services:
```
nslookup mail.google.com
Server:  pi.hole
Address:  192.168.1.220

Non-authoritative answer:
Name:    googlemail.l.google.com
Address:  2a00:1450:400d:80a::2005
Aliases:  mail.google.com
```

The IP6 address is provided, but no IP4 address. As a result, I can't access these Google services from my browser. How can I debug this? It doesn't happen often, but it does keep happening from time to time. I have not noticed this problem with other DNS names.

`pihole restartdns` fixes the problem.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
