### ISSUE TITLE
Bug? Feature? Support uBlock/adBlock style blocklists

### ISSUE THREAD

**Issue by tibers** [pi-hole/pi-hole#4437]
### Versions

- Pi-hole: 5.6 
- AdminLTE:  5.8
- FTL:  5.11

### Platform

- OS and version:  Ubuntu

- Platform:  Raspberry Pi

### Expected behavior

It looks like adding ublock/adblock style blocklists isn't supported. The primary differences are the use of regex inline to the URLs and using `!` as a comment. I understand that filter lists related specifically to filtering based on inline elements won't work as pihole is a DNS based blocker, but it should be able to work on the nonelement filters. The difference is usually `##` being included in the string to indicate some level of content munging.

### Actual behavior / bug

URLs are simply thrown out as invalid.

### Steps to reproduce

Under your adlists - add https://github.com/uBlockOrigin/uAssets/blob/master/filters/filters.txt (the main ublock adlist) and then refresh the DB. You should see something like "7100 URLs added. 7000 invalid URLs not added. Example URLs..." with a list of comments and regexes in the preview.

**Comment by yubiuser** [comment]
Adblock style blocklists are not supported. They have been once but it turned out that filtering out domains from those lists let to overblocking.

See the feature request here
https://discourse.pi-hole.net/t/limited-parsing-of-adblock-style-lists/25784/1

and here: https://github.com/pi-hole/pi-hole/pull/2912

**Comment by jfb-pihole** [comment]
Taking an example line from the URL adlist you provided (which is not in HOSTS format), how would you propose to parse something like this line to any domain that Pi-hole can work with?

google.*###center_col > #resultStats + div[style="border:1px solid #dedede;margin-bottom:11px;padding:5px 7px 5px 6px"]

We deliberately removed support for adBlock and uBlock style lists over two years ago because there is no reliable way to parse these lists, and the outcome was typically a number of false positives.  Even with our latest Pi-hole version which does limited parsing of these lists, there are still a lot of false positives generated.  Users end up with domains such as Netflix.com, github.com, etc on their blocklist.

As an example, enter the following adlist only into your adlists (disable all others).  Rebuild gravity with pihole -g.

```
  [i] Target: https://easylist.to/easylist/easylist.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 23519 domains, 20426 domains invalid!
      Sample of invalid domains:
      - 2.0]
      - (easylist@protonmail.com).
      - -ad.jpg?
      - -ad.php?
      - -ad1.$domain=~oraclecloudapps.com
```
Run the following SQL command to output the contents of your gravity list:

`sudo sqlite3 /etc/pihole/gravity.db "SELECT domain FROM gravity WHERE rowid IN (SELECT rowid FROM gravity GROUP BY domain);"`

Your gravity list now contains the following (just a small sample provided) - this will likely not lead to a good experience:

woot.com
nasdaq.com
buzzfeed.com
buzzfeednews.com
cnbc.com
cnn.com.
...

Rather than push a square peg into a round hole, use round pegs (blocklists that are formatted for and intended to work properly with Pi-hole).
