### ISSUE TITLE
pihole updateGravity doesn't handle comments in /etc/pihole/pihole-FTL.conf prefixed with semi-colon

### ISSUE THREAD

**Issue by Tuxdude** [pi-hole/pi-hole#4444]
### Versions
- Pi-hole:  v5.6
- AdminLTE:  v5.8
- FTL:  v5.11

### Platform
- OS and version:  Raspbian 10 (buster)
- Platform:  Raspberry Pi 4B

### Expected behavior

Ability to add comments in `/etc/pihole/pihole-FTL.conf` file with no warnings when invoking the `pihole updateGravity` command and also no warnings/errors in the Web Settings UI (under System tab).

### Actual behavior / bug

See the following warnings, even though the command completes successfully without a zero return code.

```
$ PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updateGravity >/var/log/pihole_updateGravity.log                                                                                            
/etc/pihole/pihole-FTL.conf: line 2: syntax error near unexpected token `;'                                                                                                                                        
/etc/pihole/pihole-FTL.conf: line 2: `; Make FTL only analyze A and AAAA queries (true or false)'                                                                                                                  

$ echo $?                                                                                                                                                                                   
0
```

Also, since these commands are run as part of a cronjob, any text output (warnings like these) gets sent automatically as an email to the root user even if the command exits with `0` status.

### Steps to reproduce

1. Add one or more lines in `/etc/pihole/pihole-FTL.con` that start with a `;`.

The contents of my file that I used to reproduce this issue for example:

```
PRIVACYLEVEL=0
# Make FTL only analyze A and AAAA queries (true or false)
ANALYZE_ONLY_A_AND_AAAA=true

; TTL (90-days) entries for FTL database (saves on space)
MAXDBDAYS=90
```

2. Run the `pihole updateGravity` command that was added in `/etc/cron.d/pihole`.

```
PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updateGravity >/var/log/pihole_updateGravity.log
```

## Debug Token

N/A

### Screenshots

N/A

### Additional context

- Using `;` for comments in `/etc/pihole/pihole-FTL.conf` doesn't work with the `pihole updateGravity` command. However, there are no warnings or errors in the web Settings UI (under the System tab).
- Replacing these comment lines to begin with `#` instead fixes this issue with the `pihole updateGravity` command. However, the web Settings UI (under the System tab) shows the following error.

```
Error
There was a problem applying your settings.
Debugging information:
PHP error (2): syntax error, unexpected '(' in /etc/pihole/pihole-FTL.conf on line 2 in /var/www/html/admin/scripts/pi-hole/php/FTL.php:23
```

**Comment by yubiuser** [comment]
Thanks for your report. 

The reason for the gravity update issue here

https://github.com/pi-hole/pi-hole/blob/b5e0f142ccefe9b1b59b94d7e82d3052efbfdcd0/gravity.sh#L55-L57

`pihole-FTL.conf` is used for three different things: FTL (`C`) the web interface (`PHP`) and gravity (bash). While C accepts `#` and `;` PHP only allows `;` but bash only `#`.

See this PR for more discussion:
https://github.com/pi-hole/pi-hole/pull/4081

**Comment by jgrisham** [comment]
**If you’re willing to experiment, please try prefixing a comment with `#;`**

The `php` errors you posted look like they were hanging up on the first parenthesis (`(`), not on the hash mark (`#`):

1. The `#` should placate `bash` and cause the remainder of the line to be ignored
2. If the `#` is indeed ignored by `php` here, then _(if the particular `parse_ini` function in use allows mid-line comments)_ the rest of the line after `;` should be ignored by the web interface

_(By extension of the above, the reverse `;#` will **not** work.)_

- - - -

If `#;` does appears to work, then we should test it followed by otherwise illegal characters _(i.e. those likely to be used in a comment; e.g. `@$&()%-+//!{}<>~_|…§€£^`)_ in the following circumstances:

1. indented by spaces
2. indented by tabs
3. indented by spaces followed by tabs, and the opposite
4. following a valid configuration string _(e.g. `MAXDBDAYS=90 #; five fortnights is too long for us!`

- - - -

If a combination of comment delimiters _is_ found that does work in all three instances _(the `bash` scripts, `FTL` itself upon reboot/cold-start, and the web interface)_ than the `man` page for `pihole-FTL.conf` _(#4081)_ and online documentation can be updated to reflect that.

**Comment by Tuxdude** [comment]
Using `#;` as suggested in https://github.com/pi-hole/pi-hole/pull/4081#issuecomment-988089252

**Comment by yubiuser** [comment]
On new installations a template `pihole-FTL.conf` will be installed containing the right comments syntax:
https://github.com/pi-hole/pi-hole/pull/4496
