### ISSUE TITLE
"broken trust chain resolving" on bind9 behind pi-hole

### ISSUE THREAD

**Issue by SourceDoctor** [pi-hole/pi-hole#4463]
OS : Debian 11
Pi-hole v5.6 FTL v5.11 Web Interface v5.8

i use pi-Hole as DNS forwarder on another system for bind9

System/DNS Query Structure:
network -> bind9 -> pi-hole -> public DNS Server

internal IP of pi-Hole System: 192.168.250.3

i'm slightly confused about this Log Entries in bind9.
especially about the "DNS format error"

does someone have some ideas about?
DNSSEC not enabled on both sides.

```
Dez 11 23:45:08 wotan named[1880917]: validating ad.doubleclick.net/A: bad cache hit (doubleclick.net/DS)
Dez 11 23:45:08 wotan named[1880917]: broken trust chain resolving 'ad.doubleclick.net/A/IN': 192.168.250.3#5335
Dez 11 23:45:08 wotan named[1880917]: validating www.google-analytics.com/A: bad cache hit (google-analytics.com/DS)
Dez 11 23:45:08 wotan named[1880917]: broken trust chain resolving 'www.google-analytics.com/A/IN': 192.168.250.3#5335

```
and sometimes i see this:
```
Dez 11 23:49:06 wotan named[1880917]: DNS format error from 192.168.250.3#5335 resolving githubapp.com/DS for <unknown>: invalid response
Dez 11 23:49:06 wotan named[1880917]: FORMERR resolving 'githubapp.com/DS/IN': 192.168.250.3#5335
Dez 11 23:49:06 wotan named[1880917]: broken trust chain resolving 'collector.githubapp.com/A/IN': 192.168.250.3#5335
Dez 11 23:50:51 wotan named[1880917]: DNS format error from 192.168.250.3#5335 resolving githubapp.com/DS for <unknown>: invalid response
Dez 11 23:50:51 wotan named[1880917]: FORMERR resolving 'githubapp.com/DS/IN': 192.168.250.3#5335
Dez 11 23:50:51 wotan named[1880917]: broken trust chain resolving 'collector.githubapp.com/A/IN': 192.168.250.3#5335

```

**Comment by yubiuser** [comment]
It looks like a DNSSEC issue.

My guess is: a client requests `DS` records (part of DNSSEC), bind forwards them to Pi-hole. But Pi-hole blocks them and does not return any DS record. All those domains are on the adlist shipped by default with Pi-hole.

**Comment by DL6ER** [comment]
> i'm slightly confused about this Log Entries in bind9.
> especially about the "DNS format error"

Pi-hole is generating query-aware responses. In the default blocking mode, this means we generate either `A 0.0.0.0` or `AAAA ::` or a valid `NODATA` (`NOERROR` with no answer records) for all other types. To me, it looks a bit like a `bind` issue, especially because of this `<unknown>` which does not come from Pi-hole (only `bind` could be aware of it as it is the querying party here):
> ```
> Dez 11 23:49:06 wotan named[1880917]:
>    DNS format error from 192.168.250.3#5335 resolving githubapp.com/DS for <unknown>: invalid response
> ```

Breaking the chain of trust is 100% expected when blocking traffic as Pi-hole does. There is no way of blocking domains *ans* adhering with DNSSEC. In the end, this is exactly what DNSSEC has been made for: Detecting *any* manipulation of DNS.
