### ISSUE TITLE
Wireguard on pi hole (help )

### ISSUE THREAD

**Issue by Decapitater** [pi-hole/pi-hole#4464]
### Versions

- Pi-hole:  latest
- AdminLTE:  latest
- FTL:  latest

### Platform

- OS and version:  Debian 10

- Platform:  rpi 3b+

### Problem 
My router does not support dynamic dns natively I want to use pi hole with wireguard , I am ready to enable dns providing on pi hole and disable on my router , what are the possibilities. 
Got my hostname from no-ip 

Tldr: router does not support dynamic dns natively , got hostname from no-ip.anyway I would be able to use it online away from the source 

@yubiuser

**Comment by yubiuser** [comment]
Pi-hole is a DNS forwarder and as has a build-in DHCP server. It is not a router and has no dyn dns capability. Best idea I have is to exchange the router to some model that can deal with dyn dns.

**Comment by Decapitater** [comment]
Any other ways I can do something , without changing router it's fibercated I can't use openwrt on this thing , Dydns ? Or no-ip would that help ?

**Comment by Decapitater** [comment]
Any dedicated piece of software ?

**Comment by yubiuser** [comment]
You would need a piece of software that requests the WAN IP from your router, a router that would understand that request and concretely answer this, and the software needs to send end the IP to your dny dns provider. I'm not aware of such software (but of course, it might exist). 

This is far out of Pi-hole's scope, so I'm closing this issue.

**Comment by yubiuser** [comment]
You could use a dyndns client on your Pi device.

**Comment by Decapitater** [comment]
While using dns of rpi ?

**Comment by DL6ER** [comment]
Dyndns has nothing to do with DNS despite the similar names. Dyndns clients do exactly what yubiuser said above, it updates some record on the web with your outside IP address.

I've been using [ddclient](https://github.com/ddclient/ddclient) in the past and was very happy with it. I stopped using it because I switched from using a dyndns provider to using my own domains by updating my own DNS server records directly. It is still a very good choice.

Please note that we cannot provide a walk-through for the configuration but you should be able to find a ton of good tutorials online. Especially if you want to use it with the popular no-ip service.

**Comment by Decapitater** [comment]
Thanks @DL6ER (cute doggo)
