### ISSUE TITLE
conditional forwarding not working with uppercase domains

### ISSUE THREAD

**Issue by WiredLife** [pi-hole/pi-hole#4465]
i can confirm this minor bug
https://discourse.pi-hole.net/t/latest-update-ftl-v5-9-web-v5-6-and-core-v5-4-breakes-some-conditional-forwarding-fixed/49615

please fix it

my old ticket:
https://github.com/pi-hole/pi-hole/issues/4462

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
