### ISSUE TITLE
Pause button please? [$40]

### ISSUE THREAD

**Issue by richardhughes260** [pi-hole/pi-hole#449]
##### Feature Request:

Can you install a pause button?

Some sites I go to sense the ad blocker and do not render the content.

**Comment by PromoFaux** [comment]
Check out [this answer](https://github.com/pi-hole/pi-hole/wiki/FAQs#some-sites-are-detecting-ad-blocker-348) in the FAQ for a workaround!

We are looking at adding functionality like a disable button/ability to control scripts from web UI, but in the mean time, that work around should fix things....

**Comment by rappo** [comment]
@PromoFaux I know that you guys will be looking into adding a toggle to the UI, so I put a [$40 bounty on this issue](https://www.bountysource.com/issues/32758981-pause-button-please) to show my gratitude / add encouragement :)

**Comment by richardhughes260** [comment]
cool

**Comment by dschaper** [comment]
Thank you very much for you contribution!

**Comment by jacobsalmela** [comment]
@rappo take a look at [this](https://github.com/pi-hole/pi-hole/blob/pause-resume-pihole/advanced/Scripts/pauseResume.sh), which I plan to put in the next release if it works well for everyone.

**Comment by tuplink** [comment]
[SHELL](https://github.com/pi-hole/pi-hole/pull/823) PR
[WEB](https://github.com/pi-hole/AdminLTE/pull/173) PR

**Comment by dschaper** [comment]
We need to be extremely careful with out code reviews, we've gotten a little lax and some bad bugs have gotten through. When we get time all PR's will be reviewed and we'll go from there. I don't know how Bounty works but if the bug is solved we'll work out something. This is FOSS code, anything else is just a great thing to be rewarded beyond regular recognition. 

We have processes we follow and we will get to things as we can. I hope you understand that. Code changes this big are going to take a week or so to fully review. (We tend to have smaller PR's that have fewer changes in them just so we can go step by step and do our due dilligence.) 

The PR's/commits and effort are greatly appreciated and will be forever in our hearts! So Thanks!

**Comment by rappo** [comment]
@dschaper as the backer of the bounty, I didn't intent for the bounty to suggest it was higher priority or in any way should compromise what you guys do. From my point of view, I just wanted to see that feature built for all of us (but mostly for myself :D) and had neither the time nor the means to do it myself.

The bounty can be claimed automatically whenever this GH issue is closed.

And thank you all for the PR for this issue specifically, and for pi-hole in general 🎉

**Comment by PromoFaux** [comment]
Implemented in 2.9.5/ web frontend 1.4.4

@tuplink, claim your bounty!

**Comment by tuplink** [comment]
@PromoFaux please claim this. I have no intention of claming it.

**Comment by PromoFaux** [comment]
@rappo Any idea why Bountysource is no longer updating our issue? Can't seem to uninstall/reinstall integration from the tools menu on your site...
