### ISSUE TITLE
PiHole Consistently Requires 2-3 times to load a website

### ISSUE THREAD

**Issue by fazzitron** [pi-hole/pi-hole#4492]
Ever since installing PiHole on my system, websites will consistently need 2-3 times to properly load a website. When trying to connect to a server, it will often fail the first time. When loading a website it hasn't seen in a while, it will often not load at first, then load the page without CSS requiring a 3rd load. If this is on a site where I have to input credentials, it will mean I sometimes have to put them in again as the reload will occasionally make the site forget who I am. It honestly sometimes doesn't even feel worth it to have this set up.

Here's a video of it happening (which I should note, failed to load when I double checked the url)
https://youtu.be/vXNxlinyD-A

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
