### ISSUE TITLE
no ipv6 internet access when pi-hole is the router caused by ra-param=*,0,0

### ISSUE THREAD

**Issue by Omoeba** [pi-hole/pi-hole#4504]
### Versions

- Pi-hole:  v5.7
- AdminLTE:  v5.9
- FTL:  v5.12.1

### Platform

- OS and version:  Raspbian Buster

- Platform:  Raspberry Pi 4

### Expected behavior

clients have access to the internet over ipv6

### Actual behavior / bug

clients do not have internet access

### Steps to reproduce

1. Check `Enable IPv6 support (SLAAC + RA)`

### Additional context

The problem is caused by `ra-param=*,0,0` in `/etc/dnsmasq.d/02-pihole-dhcp.conf`, which prevents the router from advertising a route. Due to not advertising a route, clients on the subnet have no internet access.

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
