### ISSUE TITLE
Still stuggling with update gravity

### ISSUE THREAD

**Issue by wanttoreportabug** [pi-hole/pi-hole#4531]
### Versions
  Pi-hole version is v5.8.1 (Latest: v5.8.1)
  AdminLTE version is v5.10.1 (Latest: v5.10.1)
  FTL version is v5.13 (Latest: v5.13) 

### Platform
Linux Mint 20.3 / Mac-OS Monterey
- OS and version:  

- Platform:  Raspberry Pi

### Expected behavior
**REMARK:** I did post this problem before but there is new information:

When i, either using ssh (pihole - g) or using the normal GUI update gravity i expect the lists are updated and the domaincount
in the shown result is correct. This count is my "check" to see if the lists are updated correctly or if there are errors in them.

### Actual behavior / bug

Somehow the number of blocked domains is not shown properly?

### Steps to reproduce

1. Make a list with, say 5 - 10 block entry's
2. Upload this list to your website using FTP (i use Filezilla and a domain i own)
3. Update gravity either using ssh or the Pi-hole GUI
4. Remove 1 or 2 items from the blocklist you made in step 1
5. repeat step 2

Now in this case there where 8 initial entry's in the list. I then removed 2 and re-uploaded the list, updated gravity. The result should
be "analyzed 6 domains, list updated" but it still shows 8 domains. I did check if the list was changed on the server, i did a
reboot of the pi-hole and then update gravity again. Still same result. BUT, when i check if i could visit the sites i removed from
the list i notice they are no longer blocked so the representation of the results (see screendump) must be off?

Hoever, if i wait a several hours and then do a gravity update the correct number of domains in the list is shown and "list updated"
is displayed.

## Debug Token

- URL:  

### Screenshots
![ScreenShot-DeList](https://user-images.githubusercontent.com/45028553/148530538-6615ea73-5a96-4065-acbd-0c141e86c94c.png)
![ScreenShot-2update](https://user-images.githubusercontent.com/45028553/148530603-84c56c06-d04b-464b-84aa-7fd050184a5a.png)

### Additional context

_Add any other context about the problem here._

**Comment by PromoFaux** [comment]
Hi there, interesting situation.

When the list is checked, it's based on the http return code, in this case the server is returning http code 304 (not modified)

https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L651

I'm not sure the issue is with gravity here. Silly question, is your domain (specifically the domain you're hosting your list at) behind Cloudflare, or some other caching CDN?

**Comment by jfb-pihole** [comment]
Likely unrelated to this problem, but Linux Mint is not a supported OS.

**Comment by wanttoreportabug** [comment]
Uhh Linux Mint has nothing to do with Pi-hole, a question you need to answer when you make a bug-report is the OS you are using. I assumed it was the OS on your desktop/laptop. The Pihoile runs on a Raspberry-Pi 4 with Raspian (latest/up-to-date) should this be the answer expected.

**Comment by PromoFaux** [comment]
Yeah, we are expecting the OS of the device Pi-hole is installed on :) not to worry!

Regards your issue: is your blocklist hosted behind cloudfare or some other caching CDN?

**Comment by kebugcheckex** [comment]
I'm having a similar issue. Symptoms:
* Domains on Blocklist is -2  #4519 
* Nothing is blocked
* Normal DNS resolution seems fine
* Unable to update gravity from the Web UI, no response after clicking "Update"

I'm running Pi Hole in Docker on Ubuntu 20.04 x86_64. Even fresh install has the same issue. I don't have any custom block list or customization.
```
$ docker exec pihole pihole -g
  [✗] DNS resolution is currently unavailable
  [i] Time until retry: 11
```

**Comment by kebugcheckex** [comment]
After some debugging, I solve the issue on my system. May or may not be the same as yours.

I configured my router's DHCP to offer the Pi-Hole host as the DNS server, unlike the typical configuration where the router forwards DNS request to Pi-Hole. This causes an issue on Pi-Hole startup because Pi-Hole needs to download the blocklist from GitHub, which needs to resolve domain names. But at this time Pi-Hole itself is not ready yet, so it fails to download the blocklist.

I'm running Pi-Hole in Docker so the solution is to set the container's DNS sever to a public one so that Pi-Hole doesn't depend on itself to start up.

**Comment by fotingo** [comment]
I have to update gravity more than once in order for adlists to get updated. This doesn't happen all the time, but I notice it fails to update from time to time. To fix this, I have to keep updating gravity over and over until it updates.
