### ISSUE TITLE
UnBound + PiHole v5.8

### ISSUE THREAD

**Issue by itsavius** [pi-hole/pi-hole#4564]
### Versions

- Pi-hole:  v5.8
- AdminLTE:  v5.10.1
- FTL:  v5.13

### Platform

- OS and version:  Rasbian v5.10

- Platform:  Raspberry Pi 4

### Expected behavior

_PiHole is not resolving DNS queries._

### Steps to reproduce

1. sudo apt install unbound
2. wget https://www.internic.net/domain/named.root -qO- | sudo tee /var/lib/unbound/root.hints
3. nano /etc/unbound/unbound.conf.d/pi-hole.conf
4. Copy config server: [Config Unbound](https://docs.pi-hole.net/guides/dns/unbound/?h=unbound)
5. sudo service unbound restart
6. configure Pi-hole to use your recursive DNS server by specifying 127.0.0.1#5335 as the Custom DNS (IPv4)
7. Save
8. dig pi-hole.net @127.0.0.1 -p 5335 this status report  see "**SERVFAIL**"
 

### Screenshots
[Screen Ibb.co](https://ibb.co/94BxHVJ)
_And PiHole not resolution DNS Queries._

**Comment by dschaper** [comment]
If you are Experiencing issues with a Pi-hole install that has non-standard elements (e.g you are using nginx instead of lighttpd, or there is some other aspect of your install that is customised) - please use the [Community Help](https://discourse.pi-hole.net/c/bugs-problems-issues/community-help/36) category.
