### ISSUE TITLE
Add group by domain field (checkbox) on the query results list

### ISSUE THREAD

**Issue by myset** [pi-hole/pi-hole#4618]
### Improvement on query results list 
Add group by domain field (checkbox) on the query results list for:
- /admin/queries.php?client=some_ip&type=blocked
- /admin/db_queries.php

### Expected behavior
Filtered list grouped by domain with additional column count.

**Comment by PromoFaux** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that either do not fill out the Issue Template, do not provide debug tokens when possible, or relate to a configuration issue as opposed to an issue with the code. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

## All Feature requests should be opened on [Discourse](https://discourse.pi-hole.net/c/feature-requests)
