### ISSUE TITLE
Installer stops at first whiptail on Ubuntu 22.04 and Debian Bookworm

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/pi-hole#4693]
Keeping it here to track the issue. Reported
https://discourse.pi-hole.net/t/unable-to-install-pi-hole-on-ubuntu-22-04/54130
and
https://discourse.pi-hole.net/t/os-release-debian-11/54779

**Comment by MichaIng** [comment]
This should be reported to the Debian whiptail/newt maintainer(s), as it doesn't look intended. There is no explicit changelog about this in whiptail/newt, so likely it is caused by other library changes on Bookworm unexpectedly: https://bugs.debian.org/cgi-bin/pkgreport.cgi?src=newt

Otherwise, the following can be used to call the installer without detaching the shells STDIN from terminal (via pipe):
```sh
bash -c "$(curl -sSfL https://install.pi-hole.net)"
```
_The added `-f` assures that no error document can be passed via STDOUT as script to the shell, but a shortened error message is instead printed to STDERR. The same would harden the current installer call as well._

**Comment by m4k5ym** [comment]
I recommend following version for jammy:

```
PIHOLE_SKIP_OS_CHECK=true bash -c "$(curl -sSfL https://install.pi-hole.net)"
```

**Comment by MichaIng** [comment]
Reported to Debian bug tracker, along with further tests and findings: https://bugs.debian.org/1010059

**Comment by Rychveldir** [comment]
i managed to install it with the above mentioned commandline, but DNS won't run:

root@kserv:~# sudo systemctl status --full --no-pager pihole-FTL.service
● pihole-FTL.service - LSB: pihole-FTL daemon
     Loaded: loaded (/etc/init.d/pihole-FTL; generated)
     Active: active (exited) since Sun 2022-04-24 18:03:17 UTC; 8min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 20503 ExecStart=/etc/init.d/pihole-FTL start (code=exited, status=0/SUCCESS)
        CPU: 49ms

Apr 24 18:03:17 kserv systemd[1]: Starting LSB: pihole-FTL daemon...
Apr 24 18:03:17 kserv pihole-FTL[20503]: Not running
Apr 24 18:03:17 kserv su[20513]: (to pihole) root on none
Apr 24 18:03:17 kserv su[20513]: pam_unix(su:session): session opened for user pihole(uid=998) by (uid=0)
Apr 24 18:03:17 kserv su[20513]: pam_unix(su:session): session closed for user pihole
Apr 24 18:03:17 kserv systemd[1]: Started LSB: pihole-FTL daemon.

What to check here?

**Comment by Rychveldir** [comment]
root@kserv:~# ls -lah /etc/dnsmasq.d/
total 16K
drwxr-xr-x   2 root root 4.0K Apr 24 18:03 .
drwxr-xr-x 115 root root 4.0K Apr 24 18:03 ..
-rw-r--r--   1 root root 1.4K Apr 24 18:03 01-pihole.conf
-rw-r--r--   1 root root 2.2K Apr 24 18:03 06-rfc6761.conf

**Comment by MichaIng** [comment]
I suggest to open a new issue about this here on GitHub or via Pi-hole forum. This is not related to the installer issue, also your Pi-hole service runs fine, so when doing the dedicated report, append a tricorder token to allow team members checking other logs and details. As own preparation you should check `/var/log/pihole.log` and `/var/log/pihole-FTL.log` for possibly related/suspicious entries.

**Comment by HeAuDa** [comment]
Not sure how many people are still facing this issue, but I found that if I cloned the repository and used the command 
PIHOLE_SKIP_OS_CHECK=true flag (as described by the installer) when starting the installation it worked. When it gets to the screen asking to continue (where it froze up on my first machine) I simply waited a few minutes (because I got interrupted and had to leave my computer the first time) and it worked on two machines with this method.

**Comment by MichaIng** [comment]
The issue is that keyboard inputs are not recognised anymore by the whiptail dialogs when the script is piped `|` into the shell, like it is done with the official one-line install command:
```sh
curl -sSL https://install.pi-hole.net | bash
```
So when you clone the repo and execute the installer directly, it is not an issue, similarly the above solution works where the script is given as argument to the shell, instead of being piped.

**Comment by HeAuDa** [comment]
Good to know why. Thanks.

**Comment by terrysimons** [comment]
If you sudo bash and then install pihole without "sudo" in the installer line, the whiptail issue is not encountered and dialogs work as expected.  This allowed me to install on Ubuntu 22.04.

```
sudo bash
curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash
```

**Comment by MichaIng** [comment]
Ah right, correction to my above post: Not the pipe itself causes the issue, but piping into a sudo shell `| sudo bash`.

**Comment by shyce** [comment]
Where would I place the --unattended flag?

**Comment by MichaIng** [comment]
The `--unattended` flag is not really supported for manual usage. See the two open pull requests about validating setupVars and providing an example (both is outdated). But of course it world work around the issue given a correct `setupVars.conf`, while there is another workaround I posted above.
