### ISSUE TITLE
CPU Usage with Web Interface.

### ISSUE THREAD

**Issue by Interknet** [pi-hole/pi-hole#473]
While the web interface is closed, my Pi's CPU runs at 2.9%.
Now when the interface is open in a browser, it jumps to 100% while loading stats, and I noticed there's 4 PHP scripts running (which may or may not contribute to it loading slowly?)

When everything has loaded, it settles, but some part of the site refreshes stats maybe every minute or so, and CPU usage jumps back to 100% which seems a little high just to load some stats (I'm assuming it's just the queries, ads blocked, %)

Not sure if you already know about it or not. Hope it helps.

**Comment by manuelgu** [comment]
Are you running the latest versions of bot pi-hole and the web interface? I remember them doing huge performance improvements lately.

**Comment by Interknet** [comment]
Bot Pi-hole? 

Pi-hole Version v2.6.2 Web Interface Version v1.2. Think that's up to date. Could be wrong.

**Comment by Mcat12** [comment]
The CPU usage jumps to 100% so that it loads the stats as quick as it can. This is just a normal function of PHP. Also, since we're reading and manually parsing stats from the log, it takes longer than if we were reading from a database (which we want to switch to when we get the time). If you run Pi-hole on a beefier machine than a little Pi, it'll have no problem loading stats quickly. I mean, this is just a little credit card sized (and in the zero's case, even smaller) computer. It's pretty amazing in itself. :)

**Comment by Interknet** [comment]
Yeah the Pi is pretty amazing. Hope using a database doesn't take too much work to change to. Hoping to get a Zero to replace my Model B+ and sell it. If ever.

Can't wait to see where Pihole goes. I love it. Customized little things that don't really 'help' me, such as  chronometer with CPU temperature and usage. PiHole has actually helped me learn bash a little more. So thanks for that.

**Comment by Mcat12** [comment]
:) Right now there's some stuff in the making that will lead to more features ( #444 leads to #469 which leads to more control from the web interface)
