### ISSUE TITLE
Issue adding blocklist domains

### ISSUE THREAD

**Issue by tehmessiah75** [pi-hole/pi-hole#4739]
### Versions

 - Pi-hole version is v5.10 (Latest: v5.10)
 - AdminLTE version is v5.12-1-g495df8b9 (Latest: v5.12)
 - FTL version is v5.15 (Latest: v5.15)  

### Platform

- OS and version:  Raspbian Lite 32bit 5.15.32-v7+

### Expected behavior

expected that when I add a domain to the block list that it is displayed like "domain.com" and that the sites its trying to block are actually being blocked.

### Actual behavior / bug

Instead after I add a domain either through the web interface or adding the .list or .txt files to the /etc/pihole/ folder and runing `pihole -g` the domians in the list read as `(\.|^)domain\.com$` and the sites dont get blocked.

## Debug Token

- URL:  https://tricorder.pi-hole.net/XGKLlklE/

### Screenshots

Attached

**Comment by dschaper** [comment]
Pi-hole doesn't use the `.list` or `.txt` files anymore. This was changed a few releases ago.

Even if they still did use those files, they wouldn't import regex entries like you have shown.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we ask that all configuration questions be addressed at our  [Discourse](https://discourse.pi-hole.net) forum.

Thank you for your understanding.
