### ISSUE TITLE
js rewrite rule in lighttpd.conf breaks admin page 

### ISSUE THREAD

**Issue by berdan** [pi-hole/pi-hole#477]
##### Expected Behaviour:
Seeing some data in the admin web page.

##### Actual Behaviour:
Page loads, but no data.

##### Steps to reproduce this issue:
Used the guide on https://pi-hole.net/install-the-web-interface-on-an-existing-pi-hole/ to install the admin page, but skipped the part about editing lighttp.conf as it already had adjustments that looked good. 

Admin page loads, but no data shows up. The web console returns "`Can't find variable: $`" in index.php:372. Trying to manually load one of the js files such as /pihole/admin/js/app.min.js, returns a pi-hole filtered page. Reverting the change in https://github.com/pi-hole/pi-hole/commit/a44a201f0088a48a4240f380dded8c815ed4411e and commenting away the js rewrite rule in lighttpd.conf makes everything work again.

Raspbian Jessie Light, lighttpd/1.4.35

**Comment by PromoFaux** [comment]
Hmm, this is interesting. 

I take it, by the fact that you're following that guide, that you installed everything manually? (We should probably update those pages and/or put a disclaimer right at the top saying they're outdated!!)

I've only ever used the automated install (which also includes the web admin these days) and haven't seen this issue...

Thinking about it, the JS rewrite rule is for 404 errors. So you should not be seeing this, unless the file does not exist. For example, the page makes a request for `http://pihole.ip.address/admin/path/to/goodfile.js`, and it will return it because it exists (or should) under `/var/www/html/admin/path/to/goodfile.js`, whereas an adhost will make a request for `http://addomain.com/path/to/badfile.js` which does not exist under `/var/www/html/path/to/badfile.js`, so `lighttpd` redirects to the blank pihole page.

What version numbers does the admin page display at the bottom? Could you please run `pihole -d` and pastbin the output file? thanks¬

**Comment by berdan** [comment]
Yes, I did a manual install. I couldn't easily find information on where to locate the admin interface, so I googled for a guide and found that outdated one. Can't the install script point you to the admin interface URL after a successful install?

Revisited my install today and I realized my self installed admin pages were in /var/www/html/**pihole/**admin and not in /var/www/html/admin. 

Did a reinstall and everything works when using the correct URL. Chalk this one down as problematic user and maybe add the part about what URL to find the admin page on to the install script?

**Comment by bitterypaul** [comment]
I installed lighttpd with the configuration you gave on the website. The lighttpd service did not start at all. But when starting with the default config the lighttpd works

**Comment by dschaper** [comment]
@bitterypaul Can you open a new issue and provide us with some more info like the exact config that doesn't work and the errors that you are getting? Thanks.

**Comment by PromoFaux** [comment]
@berdan Apologies for the lack of reply, got a bit bogged down!

Glad to see it's sorted, and will certainly look into adding that line to the end of the install script.

@bitterypaul If you can, try the automated install method over doing it manually, you're likely to run into less problems!

**Comment by bitterypaul** [comment]
I actually tried out the automated script but didn't work out with the configuration I have. I use my pi connected to an ADSL modem, used as a wifi hotspot. I have troubles  setting up the interface. Without pi-hole everything is normal. but when i run the script, dnsmasq service stops working, things go awry.
