### ISSUE TITLE
Top list exclusions are not not working as they should 

### ISSUE THREAD

**Issue by HyperCriSiS** [pi-hole/pi-hole#4829]
Hi, 
- Pi-hole:  v5.11.4
- AdminLTE:  v5.13
- FTL:  v5.16.1

### Platform
Dietpi, Raspberry Pi 4

### Expected behavior
Excluded top domains should be completely dropped. 

### Actual behavior / bug

Excluded top domains still show up in the query log. 

This totally kills the query log, which makes it kind of unusable, because even one single device can produce many hundreds of the same request per minute.
These request should also not be saved on disk. 

I have two of such devices which create HUGE amounts of requests and no possibility to disable them at the device directly.

Thanks and regards, 
Hyper

**Comment by jfb-pihole** [comment]
"Excluded top domains should be completely dropped."

This is not the expected behavior.  As noted in the API/Web Interface settings tab, "Exclude the following domains from being shown in"  "Top Domains / Top Advertisers"  and/or "Top Clients".

Adding domains to either list removes them from that "Top" list on the home page of the dashboard.  The domains are not removed from the query log or the overall stats.

"This totally kills the query log, which makes it kind of unusable, because even one single device can produce many hundreds of the same request per minute."

The query log is accurately showing the received DNS queries.  You can filter the query log with multiple active filters to show just the information you want to see.

"These request should also not be saved on disk."

Logging to your disk or uSD card is controlled by the following:

1.  For the query database, your privacy settings.
2. For the dnsmasq log, by the setting "disable query logging" on the System main page.

These settings affect all queries equally.

Note that you do have two additional options on the API/Web Interface page regarding the query log.  You can choose not to show permitted domains, or not to show blocked domains. But, the queries will still be logged per your logging settings.

**Comment by yubiuser** [comment]
> Excluded top domains should be completely dropped.

This is a feature request. Please vote here:
https://discourse.pi-hole.net/t/option-to-ignore-domains-from-appearing-in-the-query-log/6319
