### ISSUE TITLE
Windows machines open default browser with MSN on startup on Pi-holed networks.

### ISSUE THREAD

**Issue by Debonnys** [pi-hole/pi-hole#486]
##### Expected Behaviour:
On startup of a windows machine, everything should still be the same as on a none pi-holed network.

##### Actual Behaviour:
On startup the default browser opens with the MSN start page.

##### Problem:
The problem is that www.msftncsi.com is Pi-holed

##### Solution:
Whitelisting www.msftncsi.com solves the problem
This should be whitelisted by default instead of manually added.

(or a regsitry edit: see [stackexchange question](http://serverfault.com/questions/695874/default-browser-opens-to-msn-com-when-logging-into-windows-server) (comments also mention pi-hole as reason))

**Comment by Mcat12** [comment]
While it would be nice to automatically whitelist certain domains, we do not believe that we should be the ones doing so. If we whitelist sites like msftnscd.com then we could also be whitelisting sites that are not so safe. To prove to our users that we are not whitelisting ads because they paid us to (like some ad blockers nowadays are doing) we are not automatically whitelisting domains. We do think that a community list might be useful for these things, but it would be an optional list that the community would have say over.
