### ISSUE TITLE
Not working for the "list of configured clients" in Group Management

### ISSUE THREAD

**Issue by rothapheng** [pi-hole/pi-hole#4866]
When I added a new client, it showed a successful message but the list keeps loading since the initial page load.

<img width="1243" alt="Screen Shot 2022-08-09 at 4 48 25 PM" src="https://user-images.githubusercontent.com/14921816/183619197-ba92cccb-d85e-444f-a4a6-dae044bff48c.png">

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by LukeOwlclaw** [comment]
The same problem was reported here:
https://www.reddit.com/r/pihole/comments/10v2egr/pihole_showing_top_clients_but_client_group/?rdt=42389

Cause:
DB is missing a table. (Same happened to me right after installing)

Solution:
Stop pihole service, remove DB file, restart pihole, e.g. like this:
```
sudo service pihole-FTL stop
sudo mv /etc/pihole/pihole-FTL.db /etc/pihole/pihole-FTL.db_bkp
sudo service pihole-FTL start
```
