### ISSUE TITLE
Variable CACHE_SIZE configured in setupVars.conf does not update cache-size in 01-pihole.conf on restart

### ISSUE THREAD

**Issue by Sassafras76** [pi-hole/pi-hole#4888]
Hello 

When using unbound with pihole, I wanted to disable pihole cache and when i modify the variable CACHE_SIZE in /etc/pihole/setupVars.conf, it does not update cache-size in /etc/dnsmasq.d/01-pihole.conf 

is this an issue with the variable case-sensitive and therefore does not match or possibly the difference with "-" and "_" as a separator?

i noticed my change in /etc/dnsmasq.d/01-pihole.conf when set to zero (0) was reverted when I updated pihole (pihole -up) back to 10000

cache-size=0

after update

cache-size=10000

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
