### ISSUE TITLE
Variable CACHE_SIZE configured in setupVars.conf does not update cache-size in 01-pihole.conf on restart

### ISSUE THREAD

**Issue by Sassafras76** [pi-hole/pi-hole#4890]
### Versions
  Pi-hole version is v5.12 (Latest: v5.12)
  AdminLTE version is v5.14 (Latest: v5.14)
  FTL version is v5.17 (Latest: v5.17)

### Platform
	PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
	NAME="Debian GNU/Linux"
	VERSION_ID="11"
	VERSION="11 (bullseye)"
	VERSION_CODENAME=bullseye
	ID=debian
	HOME_URL="https://www.debian.org/"
	SUPPORT_URL="https://www.debian.org/support"
	BUG_REPORT_URL="https://bugs.debian.org/"

### Expected behavior

	when i modify the variable CACHE_SIZE in /etc/pihole/setupVars.conf, i woudl like to see the update to cache-size in /etc/dnsmasq.d/01-pihole.conf

### Actual behavior / bug

	change to variable CACHE_SIZE in /etc/pihole/setupVars.conf should update cache-size in /etc/dnsmasq.d/01-pihole.conf

### Steps to reproduce

1. modify the variable CACHE_SIZE in /etc/pihole/setupVars.conf from 10000 to 0
2. execute pihole restartdns
3. verify cache-size in /etc/dnsmasq.d/01-pihole.conf
4. it is not updated

## Debug Token

- URL:  https://tricorder.pi-hole.net/ToCtdU2C/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

is this an issue with the variable case-sensitive and therefore does not match or possibly the difference with "-" and "_" as a separator?

**Comment by jfb-pihole** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net/) site for additional assistance.

**Comment by dschaper** [comment]
Please see the documentation for the full process on making that change.

https://docs.pi-hole.net/ftldns/dns-cache/?h=cache_size#dns-cache-size

**Comment by Sassafras76** [comment]
> Please see the documentation for the full process on making that change.
> 
> https://docs.pi-hole.net/ftldns/dns-cache/?h=cache_size#dns-cache-size

I will try this, and get back to you with a comment.  

My initial reason for opening this was to be dynamic on restartdns instead of executing pinhole -r

**Comment by dschaper** [comment]
> My initial reason for opening this was to be dynamic on restartdns instead of executing pinhole -r

Ah, that would be a feature request then thus:

Because of the number of requests and the very limited resources we have as a free open-source project run by volunteers, we ask that you open all Feature Requests at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8). 

Thank you for your understanding.
