### ISSUE TITLE
conditional forwarder issue with Pi-hole v5.12  FTL v5.17

### ISSUE THREAD

**Issue by j0np** [pi-hole/pi-hole#4891]
ran update today, and after conditional forwarder no longer works. Currently have my internal domain forwarding to my dhcp server, was working perfectly until upgrading today. 

also tried instead using dnsmasq custom conf and still doesn't work.

Having really odd issues now with internal dns record resolutions. For example since the upgrade, i can't resolve any internal dns records, however I tried adding A records into the Local DNS\DNS Records using short name and FQDN, only short name resolved and FQDN failed still.

**Comment by rdwebdesign** [comment]
As a free open-source project run by volunteers we have very limited resources and time.
Because of the number of support requests, we will be closing all issues that do not follow all instructions in the **Issue Template** and/or do not provide **debug tokens**, if applicable.

Please search [open and closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue) issues for others that may have your same question.
Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

Thank you for your understanding.
