### ISSUE TITLE
Does Pi-Hole download the ad networks' ads?

### ISSUE THREAD

**Issue by marclar** [pi-hole/pi-hole#493]
I'm wondering if Pi-Hole _only_ intercepts requests from the local network, or if it does that AND downloads assets from the remote server, thus suggesting to advertisers that there's no ad-blocking taking place.

**Comment by PromoFaux** [comment]
Hi there,

I'll try and explain this clearly... but do ask questions if you need to!

Website requests ad from `adcompany.org/images/ad.png`, your computer does a DNS lookup to the pi-hole, which tells your computer that the IP address of  `adcompany.org` is `<yourpiholeIPhere>`, so your computer tries to find `<yourpiholeIPhere>/images/ad.png`, which it can't, so a blank html (404) page sent to your computer (from the pi-hole). The ad-company isn't aware that the request was redirected, because they never knew they were expecting a request in the first place.

**Comment by marclar** [comment]
Got it. 

So when I visit Forbes.com without any ad-blocking extensions running (e.g. from Chrome on Android), they're still able to detect that _some_ ad-blocking is happening.

I assume they know because something isn't being requested. 

*If* that assumption is correct, this makes me wonder if it would be helpful for the Pi-Hole to still request various ad scripts & assets, but just drop them when they arrive.

**Comment by PromoFaux** [comment]
The Anti-ad-blocker-blocker stuff starts to get a bit recursive, and difficult to keep up with! As we're blocking ads at a DNS level, it makes it pretty much impossible to catch everything.

There is a section in the [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs#some-sites-are-detecting-ad-blocker-348) about getting around ad-blocker-blockers on your PC/Mac, at least.

**Comment by DonLexos** [comment]
.. which will only work until the introduction of the (trick ad-blocker-blockers)-blockers.

**Comment by marclar** [comment]
I suppose, but it seems to me that, if all devices on your network are hiding behind the same public IP -- and barring communication between legit scripts and ad scripts (to confirm they're being loaded by the same device) -- remote servers wouldn't be able to determine that a given request was being split across multiple devices.

**Comment by DonLexos** [comment]
Well they can bypass that by trying to do something in your browser using code in a file running at http://their.adnetwork.domain.com/script.js . Even if a device in your network downloaded it, if it is not in your browser/cache that is impossible to trick.

Only pi-hole does is DNS lookups, if it's an ad domain a client will get nothing.
