### ISSUE TITLE
Install script claims SELinux active, but is disabled

### ISSUE THREAD

**Issue by coogor** [pi-hole/pi-hole#4944]
I'm trying to install pihole 5.12.2 on a Raspi with MicoOS ( https://microos.opensuse.org/ )

The installation script claims that 'SELinux Enforcing detected' , although sestatus reports that SELinux is disabled.
After setting the PIHOLE_SELINUX variable the installation script dies silently.

What can I do?

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
