### ISSUE TITLE
Reply error is 1

### ISSUE THREAD

**Issue by NeutralGround** [pi-hole/pi-hole#5021]
Hey,

after updating to latest pihole version today and enabling use-stale-cache, I noticed ’reply error is 1’ in Pihole logs for most cached-stale records. 

Everything still seem to be working fine. Is there any issue here? Does anyone else also experiencing this?

**Comment by jfb-pihole** [comment]
Please generate a debug log, upload it when prompted and post the token URL here.

**Comment by NeutralGround** [comment]
I’m not comfortable with sharing the contents of the debug logs. Since it is working fine I’ll leave it for now.

**Comment by dschaper** [comment]
The debug log is only accessible by Pi-hole staff.

Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
