### ISSUE TITLE
Cronjob fails on reboot

### ISSUE THREAD

**Issue by RobThree** [pi-hole/pi-hole#5029]
### Versions
    Pi-hole version is v5.14.1 (Latest: N/A)
    AdminLTE version is v5.17 (Latest: N/A)
    FTL version is v5.19.2 (Latest: N/A)

### Platform
Raspberry Pi 4 / Raspberry Pi OS Lite / 64 bit

### Expected behavior

No error

### Actual behavior / bug

When I reboot the system I receive an email:

    ...
    From: Cron Daemon <myname@mydomain.tld>
    ...
    Subject: Cron <root@dns1>
        PATH="$PATH:/usr/sbin:/usr/local/bin/" pihole updatechecker reboot
    ...
    
    fatal: unable to access 'https://github.com/pi-hole/pi-hole/': Could not resolve host: github.com
    fatal: unable to access 'https://github.com/pi-hole/AdminLTE/': Could not resolve host: github.com
    fatal: unable to access 'https://github.com/pi-hole/FTL/': Could not resolve host: github.com

### Steps to reproduce

1. Set up email correctly
2. Just reboot the system (type `reboot`)

## Debug Token

N/A

### Screenshots

N/A

### Additional context

I assume most people don't set up email at all so most people won't even notice this (but, hey, something about assumptions being the mother of...). Anyway, I set up email and so status emails from cronjobs (backups for example) get sent out to an actual email server. And so every time (or _maaaaybe_ not _every_ time but certainly _most_ of the time) the pihole is rebooted I get the above email. And having been on [FTL 5.19.1](https://github.com/pi-hole/FTL/issues/1478) for a day or two, scratching my head what was going on, I rebooted quite a few times.

My guess what happens is that the DNS has already shut down before [the cronjob](https://github.com/pi-hole/pi-hole/blob/21026d941428bfcb4f405479db470a90bae6aec1/advanced/Templates/pihole.cron#L33) is started, resulting in the `Could not resolve host: github.com` messages.

**Comment by dschaper** [comment]
`@reboot` cron jobs happen at the start of the system, the error you are seeing is that DNS is not available when the system starts. 

The cronjob calls for an updatecheck with the `reboot` argument which delays the process by 30 seconds in order to let DNS come up first. https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/updatecheck.sh#L64

**Comment by RobThree** [comment]
Hmm, today I learned... That makes much more sense...But then it would mean DNS isn't up within those 30 seconds. I'll investigate a little further.Thanks so far!Op 19 nov. 2022 om 21:35 heeft Dan Schaper ***@***.***> het volgende geschreven:﻿
@reboot cron jobs happen at the start of the system, the error you are seeing is that DNS is not available when the system starts.
The cronjob calls for an updatecheck with the reboot argument which delays the process by 30 seconds in order to let DNS come up first. https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/updatecheck.sh#L64

**Comment by RobThree** [comment]
Wouldn't it be a better idea, instead of a hardcoded sleep of 30 seconds, to do something like

    while not service_started(FTL)
        sleep(5)

**Comment by dschaper** [comment]
Then you have to add a counter and determine a number of times to loop and hope that the script doesn't break and loop infinitely. 

I think the better solution would be to dig around and find out why DNS is up 30 seconds after boot, or do what we suggest and not have the Pi-hole server use itself as the DNS.

**Comment by RobThree** [comment]
> Then you have to add a counter and determine a number of times to loop and hope that the script doesn't break and loop infinitely.

You could easily add a timeout or counter or something to break out of the loop. I don't see how that would loop infinitely. But I'm just spitballing ideas here. To me, waiting for some arbitrary time and assuming then something will be (or should be) up is kind of weird.

> I think the better solution would be to dig around and find out why DNS is up 30 seconds after boot

I will investigate, it _should_ be up, I agree on that.

> or do what we suggest and not have the Pi-hole server use itself as the DNS

I use itself because I have a lot of local hosts set up; and some of them are used for monitoring (like collectd) or as backup targets (my nas). I don't see how else I would do that (aside from putting them in my hosts file which kinda defeats the purpose of a DNS server).

**Comment by dschaper** [comment]
I'm not inclined to add complexity and points of failure for a single reported instance of an issue. I also wouldn't go past 30 seconds anyways so we'd be back in this situation. You received an email that the crojob failed because your DNS server was offline longer that 30 seconds after boot, I consider that a good thing to be notified about. 

We really do not suggest using the Pi-hole server as it's own DNS because of this kind of situation. 

I'm closing this as it's not a Pi-hole issue, you need to find out why your server is misbehaving.

**Comment by dschaper** [comment]
@RobThree I don't think you'll find your DNS server is malfunctioning, the `reboot` code is indeed broken.

See #5034

**Comment by RobThree** [comment]
> @RobThree I don't think you'll find your DNS server is malfunctioning, the `reboot` code is indeed broken.
> 
> See #5034

Thanks for the heads-up and thanks for reopening. That has saved me a weekend of investigating 👍 I'll follow the #5035 and contribute where I can. As far as I'm concerned, this issue can be closed as duplicate.

**Comment by gelsbern** [comment]
I use unbound, so if I follow this:

"We really do not suggest using the Pi-hole server as it's own DNS because of this kind of situation."

by setting say, 1.1.1.1 as the nameserver.  Will pihole itself still use the unbound server?   Seems to me that it would be better to just wait until everything is up before trying to do this update check.
