### ISSUE TITLE
teleport backup file .tar.gz can not have a space in it, or it breaks

### ISSUE THREAD

**Issue by dkerlee** [pi-hole/pi-hole#5030]
I changed the name of the backup file.tar.gz  It had a space in it, and broke the importer on the other pihole

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
