### ISSUE TITLE
Admin page 503 Service Not Availalable

### ISSUE THREAD

**Issue by linucksrox** [pi-hole/pi-hole#5131]
### Versions

- Pi-hole:  v5.15
- AdminLTE:  v5.18.1
- FTL:  v5.20.1

### Platform

- OS and version:  Ubuntu 20.04.5

- Platform:  VM

### Expected behavior

Admin page should consistently work and return HTTP 200 OK

### Actual behavior / bug

I added a monitor to my Uptime Kuma instance which does a GET request every 60 seconds to http://[pihole-ip-address]/admin/login.php and expects an HTTP response from 200-299. This works for about a day, but then eventually the pi-hole admin page starts returning HTTP 503

The only changes I have made recently were upgrading pi-hole to the latest version, and adding the Uptime Kuma monitor right after that.

### Steps to reproduce

1. Use a monitoring tool to send a GET request to http://[pihole-ip-address]/admin/login.php every 60 seconds
2. Wait
3. Eventually the lighttpd server crashes, or something and begins to return HTTP 503 instead of 200 OK

## Error Logs

/var/log/lighttpd/error-pihole.log shows this repeatedly
```
2023-01-18 18:35:26: (gw_backend.c.939) all handlers for /admin/login.php? on .php are down. 
2023-01-18 18:35:28: (gw_backend.c.315) gw-server re-enabled: unix:/tmp/pihole-php-fastcgi.socket-0  0 /tmp/pihole-php-fastcgi.socket
```

**Comment by linucksrox** [comment]
https://tricorder.pi-hole.net/bktEF98B/

**Comment by rdwebdesign** [comment]
This seems to be a problem with the socket used by PHP and the web server.

What is the output of `ls -la /tmp/pihole-php-fastcgi.socket-0`?

**Comment by linucksrox** [comment]
```
ls -la /tmp/pihole-php-fastcgi.socket-0
srwxr-xr-x 1 www-data www-data 0 Jan 18 16:10 /tmp/pihole-php-fastcgi.socket-0
```

**Comment by rdwebdesign** [comment]
That's the expected result.

What is the output of `curl -I http://<pihole-ip-address>/admin/`?

**Comment by linucksrox** [comment]
```
HTTP/1.1 503 Service Not Available
Content-Type: text/html
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline';
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: same-origin
Content-Length: 365
Date: Thu, 19 Jan 2023 11:54:20 GMT
Server: lighttpd/1.4.55
```

**Comment by hoveeman** [comment]
I am experiencing the same issue. 
Raspbian GNU/Linux 10 (buster)
Pi-hole: v5.15
AdminLTE: v5.18.1
FTL: v5.20.1

I have UptimeKuma checking it every 60 seconds doing a GET request to http://raspberryip/admin. I have had this set up for over 6 months with no issue. After updating pihole the page shows 503 Service Not Availble after a few hours of the pihole running. The Pihole DNS Services are still working correctly.

This is what I see after running the curl command above while the admin page works correctly.
```
HTTP/1.1 302 Found
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: PHPSESSID=1dnt804q9a8b1duscmalnu1a9v; path=/; HttpOnly; SameSite=Strict
Location: login.php
Content-type: text/html; charset=UTF-8
X-Pi-hole: The Pi-hole Web interface is working!
X-Frame-Options: DENY
X-XSS-Protection: 0
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'self' 'unsafe-inline';
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: same-origin
Date: Thu, 19 Jan 2023 14:21:50 GMT
Server: lighttpd/1.4.53
```

Once the page goes down, I'll paste that as well, but I imagine it's the same as @linucksrox.

I also have another Pihole instance running in a docker container on an Unraid Server with the same pihole version being checked by Uptime Kuma with no issues. `Docker Tag [2023.01.3]`

**Comment by afxefx** [comment]
Experiencing the same symptoms as the above individuals.  Started after the most recent update.  Restarting lighttpd resolved the issue via: 

`sudo systemctl restart lighttpd.service`

**Comment by rdwebdesign** [comment]
Could you please try to delete the socket file manually and restart `lighttpd`:

```
rm /tmp/pihole-php-fastcgi.socket-0
```

and 

```
sudo systemctl restart lighttpd.service
```

Does this work?

**Comment by PromoFaux** [comment]
> Another interesting issue is that visiting the root which used to show a page that asked if you meant to visit the admin page with a link, now goes to a 403 Forbidden page. e.g. http://192.168.1.123/

Expected. https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

**Comment by hoveeman** [comment]
> rm /tmp/pihole-php-fastcgi.socket-0

After doing this, I haven't had any issues yet. Been about 20 hours.

**Comment by j0np** [comment]
having the same 503 error on both of my nodes since the most recent upgrade. 

Did the rm /tmp/pihole-php-fastcgi.socket-0 and restarted my lighttpd service on both, let see if this fixes the issue. Should know by tomorrow.

Quick question, notice in another thread the dev recommend to delete the following also:
rm /run/lighttpd/php.socket

Should we be doing the above also along with the socket-0 file removal?

**Comment by rdwebdesign** [comment]
The previous config (before the update) uses `/run/lighttpd/php.socket` and the new one uses `/tmp/pihole-php-fastcgi.socket-0`.

On the other thread, I just suggested to remove the old file in case this file is causing some issues too. The file is recreated when needed.

**Comment by j0np** [comment]
so to confirm we shouldn't have to worry about "/run/lighttpd/php.socket" if we are using new version correct? or should we delete that too?

**Comment by rdwebdesign** [comment]
The new config doesn't use `/run/lighttpd/php.socket`. You can remove this file if you find it.

**Comment by j0np** [comment]
Quick update, one of my node just errored out again with 503

**Comment by linucksrox** [comment]
Same, mine went back to a 503 again around 2PM today.

**Comment by rdwebdesign** [comment]
Was there any cron job running at that time?

**Comment by j0np** [comment]
No cron jobs on my end running during that time

**Comment by rdwebdesign** [comment]
Do you have another PHP website running on the same system?

**Comment by j0np** [comment]
Nope, 2 VM's dedicated to pi-hole only. Been running solid for couple years without any issue until the last update

**Comment by PromoFaux** [comment]
Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` to `/run/lighttpd/php.socket`

This is not a permanent change - any update or repair will revert this, but I would be interested to see if you still see the same issue.

My reasoning: there was some contention about changing the file of this path to live in `/tmp/`, but everything I read in the lighttpd docs used `/tmp` in the examples - so it seemed like a safe choice.

The default path when enabling fastcgi-php is `/run/lighttpd/php.socket`

Paging @gstrauss for any hints

**Comment by linucksrox** [comment]
Ok, I made the change and restarted lighttpd, waiting to see if it goes down again. So far the pattern has been less than 24 hours uptime before it goes back to a 503, so we'll see by tomorrow what happens.

**Comment by gstrauss** [comment]
Is something on the system (cron job) is removing files from `/tmp`, then that could cause the problem you are seeing, since the old PHP backend might still be running but listening on a socket file that no longer exists in the filesystem.

> Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in /etc/lighttpd/conf-enabled/15-pihole-admin.conf to /run/lighttpd/php.socket

Having `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` use `/run/lighttpd/pihole-php-fastcgi.socket` is better than `/tmp/pihole-php-fastcgi.socket` since `/run/lighttpd` should be limited to writing by lighttpd, whereas someone else could create the file in /tmp if the file did not previously exist, or as mentioned above, a `/tmp` cleanup script might remove the socket file.

Aside: The reason lighttpd uses `/tmp` in examples is that `/tmp` exists on all Linux systems, whereas `/run/)lighttpd` has to be created as part of the lighttpd package installation, and different packagers on different distros might not do so.  On much, much older systems, the typical path was `/var/run/lighttpd`, but `/var/run` has been migrated to `/run` on modern Linux distros.  (There is often a symlink `/var/run` -> `/run` for compatibility.)

**Comment by gstrauss** [comment]
BTW, it pains me to see that people are running lighttpd 1.4.53 (released 4 years ago) and lighttpd 1.4.55 (released 3 years ago).  Has anyone checked if a later version of lighttpd is available on your platform?  Debian buster-backports has lighttpd 1.4.59.  Latest lighttpd release is currently lighttpd 1.4.68, and lighttpd 1.4.69 is expected to be released soon.

**Comment by PromoFaux** [comment]
> Having /etc/lighttpd/conf-enabled/15-pihole-admin.conf use /run/lighttpd/pihole-php-fastcgi.socket is better than /tmp/pihole-php-fastcgi.socket since /run/lighttpd should be limited to writing by lighttpd

I think this is probably worth a try. The concern that the file could get deleted if it was in `/tmp` was brought up when we first looked at making some further tweaks to the config you kindly helped us with, but we ended up keeping it there. I think my main stipulation is that the socket filename be different from the one that is defined by default in `15-fastcgi-php.conf` - but that is only based on a hunch.

**Comment by linucksrox** [comment]
I think we established that nothing was deleting or changing the socket file in /tmp, since after it went to a 503, the file was still there with the correct ownership and permissions.

Regarding the version of lighttpd, I'm running Ubuntu 20.04 LTS with the latest apt patches, so this should still work in theory. I don't mind upgrading to a newer version of lighttpd, but I'd be more interested in why, if we could identify what's not working in an older version.

For clarification, I changed the socket to `/run/lighttpd/php.socket` as requested by PromoFaux, but should I try with `/run/lighttpd/pihole-php-fastcgi.socket` instead?

I still want to wait a day to see if this change resolved the issue before trying anything else, otherwise we won't know which change really had any effect.

**Comment by PromoFaux** [comment]
> I changed the socket to /run/lighttpd/php.socket as requested by PromoFaux,

Keep it like that for now , see if it makes a difference. I've just tried a change with `/run/lighttpd/pihole-php-fastcgi.socket` in my config but that is now giving me something else entirely:

```console
2023-01-21 17:50:22: server.c.1513) server started (lighttpd/1.4.59)
2023-01-21 17:50:26: gw_backend.c.503) bind failed for: unix:/run/lighttpd/pihole-php-fastcgi.socket-0: No such file or directory
2023-01-21 17:50:26: gw_backend.c.670) ERROR: spawning backend failed.
2023-01-21 17:50:26: gw_backend.c.970) all handlers for /admin/index.php? on .php are down.
```

(This problem might exist between my chair and my keyboard, however)

**Comment by PromoFaux** [comment]
> (This problem might exist between my chair and my keyboard, however)

Actually it is because I'm using our docker container (because I was being lazy)  that has a `service` shim that doesn't fully restart this service.

Switching the file on a bare metal install works fine.  I imagine spinning up a fresh container that _always_ had this configuration would also be fine - if I can find the time to build one, I will try

**Comment by gstrauss** [comment]
`2023-01-21 17:50:26: gw_backend.c.503) bind failed for: unix:/run/lighttpd/pihole-php-fastcgi.socket-0: No such file or directory`

Sounds like /run/lighttpd does not exist on your system @PromoFaux 

@linucksrox:
> I still want to wait a day to see if this change resolved the issue before trying anything else, otherwise we won't know which change really had any effect.

Yes, please keep your current config for another day to continue your test.

> I think we established that nothing was deleting or changing the socket file in /tmp, since after it went to a 503, the file was still there with the correct ownership and permissions.

Please check the file timestamp of `/run/lighttpd/php.socket-0` (which you are using now).  For others, please mark the current timestamp of `/tmp/pihole-php-fastcgi.socket-0`.  If the problem occurs again, please check the timestamp of the socket file again to see if it has been changed.

> Regarding the version of lighttpd, I'm running Ubuntu 20.04 LTS with the latest apt patches, so this should still work in theory.

I have ranted about this elsewhere, but can you not see that your "LTS" is poorly maintained if it is running 3-year-old software (lighttpd 1.4.55) and there have been *13 releases* of lighttpd since then to get to lighttpd 1.4.68?  "not updated" != "maintained".  lighttpd 1.4.56 (released over two years ago) added support for HTTP/2.

Currently, we do not think this a problem with lighttpd code because this used to work.  Am I mistaken?  Did something else change on the system other than the pihole upgrade between the last time it worked and now?  Instead, I think the current hypothesis is that a configuration change has exposed an issue.  Let's go with that for another day.  If we do end up thinking that there is an issue in lighttpd, I ask that someone test with lighttpd 1.4.68 to see if the issue has already been fixed.  I am not going to waste me time *looking* to see if I fixed something *3 years ago*.

**Comment by PromoFaux** [comment]
>Sounds like /run/lighttpd does not exist on your system

Yeah, `1D10T`/`PEBCAK` error on my part :)

And before we get too off-topic, can we keep the conversation about the versions of `lighttpd` available or not available to a minimum please? I know you're passionate about it, and I get that, but it is outside of the scope of this issue. Try tying your message to a brick and chucking it at Ubuntu HQ (or using their forums 😅)

**Comment by PromoFaux** [comment]
@ghtesting2020 - that is off-topic for this tread and is explained in the release notes (which we always recommend you read before updating)

https://pi-hole.net/blog/2023/01/15/pi-hole-ftl-v5-20-1-web-v5-18-1-and-core-v5-15-released/#page-content

**Comment by PromoFaux** [comment]
Quoting from the release notes:

> Automatic redirection to /admin will only happen if you browse via http://pi.hole. If you wish to browse via http://[IP Address], then you will need to ensure that you add /admin manually. In the past, a splash screen has been shown with a link to /admin, however this is now removed along with the now-defunct blockpage

The splash page was removed - it serves no purpose other than to say "click here to go to /admin". The solution is to type /admin after the IP address, update your bookmark, or use the address `pi.hole` instead of the IP address, which will automatically redirect to /admin.

**Comment by PromoFaux** [comment]
@linucksrox - everything still ticking along nicely? I note we're coming up to about 24 hrs... 🙈

**Comment by linucksrox** [comment]
Yep I'm trying to stay out of the back and forth 🙂 but it's still up, no problems getting to the admin page since moving the socket file to /run/lighttpd

**Comment by PromoFaux** [comment]
This is promising. I think it is probably the answer. We've included the change in `development` already for the next update

**Comment by jauderho** [comment]
Just tried running pihole/pihole:2023.01.7 as container image, I get a 503 error. Reverting to pihole/pihole:2023.01.6 makes things run again.

**Comment by rdwebdesign** [comment]
Try `2023.01.8`. 
The previous image `.7` had a problem and was replaced after a few minutes.

**Comment by jauderho** [comment]
Yup. Looks like that did the trick.

**Comment by linucksrox** [comment]
Thanks everyone for getting this solved! I'm closing out this issue since it appears to be resolved on my end.

**Comment by j0np** [comment]
> Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` to `/run/lighttpd/php.socket`
> 
> This is not a permanent change - any update or repair will revert this, but I would be interested to see if you still see the same issue.
> 
> My reasoning: there was some contention about changing the file of this path to live in `/tmp/`, but everything I read in the lighttpd docs used `/tmp` in the examples - so it seemed like a safe choice.
> 
> The default path when enabling fastcgi-php is `/run/lighttpd/php.socket`
> 
> Paging @gstrauss for any hints

updated one of my pi-hole nodes to use /run/lighttpd/php.socket, s

> Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` to `/run/lighttpd/php.socket`
> 
> This is not a permanent change - any update or repair will revert this, but I would be interested to see if you still see the same issue.
> 
> My reasoning: there was some contention about changing the file of this path to live in `/tmp/`, but everything I read in the lighttpd docs used `/tmp` in the examples - so it seemed like a safe choice.
> 
> The default path when enabling fastcgi-php is `/run/lighttpd/php.socket`
> 
> Paging @gstrauss for any hints

updated both of my pi-hole nodes, so far no 503 error, should know within next 24hrs if the error happens again.

**Comment by linucksrox** [comment]
I upgraded to v5.15.2 today and had no issues, until about 30 minutes ago. It went back to a 503. Just to verify, I checked the socket config in 15-pihole-admin.conf and it points to `"socket" => "/run/lighttpd/pihole-php-fastcgi.socket"`

```
root@piholedns:~# ll /run/lighttpd
total 0
drwxr-x---  2 www-data www-data  100 Jan 24 01:59 ./
drwxr-xr-x 32 root     root     1060 Jan 24 02:36 ../
srwxr-xr-x  1 www-data www-data    0 Jan 23 14:12 php.socket-0=
srwxr-xr-x  1 www-data www-data    0 Jan 24 01:59 pihole-php-fastcgi.socket-0=
srwxr-xr-x  1 www-data www-data    0 Jan 24 01:45 pihole-php-fastcgi.socket-1=
```

I'm starting to think the problem is not what we thought it was.

**Comment by linucksrox** [comment]
And I want to add, this seems to be a service issue because a simple `sudo service lighttpd restart` resolves it, until it fails again. In other words, when the lighttpd service error logs claim it can't access the socket file, it's appears to be the lighttpd software having the issue, not actually a file or permission issue.

**Comment by gstrauss** [comment]
Basic troubleshooting: What changed on your system?  Which pi-hole version(s) worked?  Which pi-hole version(s) did not?

Did anything on Ubuntu OS change?  Did the lighttpd version change?  If neither of those were changed, then it is likely that the issue was recently introduced with something that did change.

When lighttpd is returning a 503 for your pi-hole request, lighttpd is reporting in the lighttpd error log that lighttpd believes that the backend is down, hence 503 Service Unavailable.  When that happens, is the PHP backend still running?  Is it eating CPU?  Have you tried killing the PHP backend?  Since lighttpd is configured to start the backend, lighttpd should detect that the backend exited and then lighttpd will restart the backend.  If you do that, do things start working again?  If so, then the next step would be to figure out why.

If you are familiar with `strace`, then taking an `strace` of the PHP (if it is still running) before killing the PHP might help reveal why the PHP is not accepting new connections.  An `strace` of lighttpd while send a request that gets 503 might also be useful if it a) fails immediately or b) times out.

My request for the timestamp on the socket file was a request for an `ls -l` when lighttpd was restarted *and* then again when the 503 started occurring so that we can detect if something removed and recreated the socket file.

Is there anything else in the lighttpd error log that might be useful besides the couple of lines shared by OP at the top?  You can increase log level of in lighttpd for additional trace if you set `fastcgi.debug = 1` right above `fastcgi.server` in lighttpd config file `pihole-admin.conf`.

pihole-admin.conf sets the global lighttpd error log, so please look here to find the lighttpd error log:
`server.errorlog := "/var/log/lighttpd/error-pihole.log"`
FYI: it might be more appropriate to set `server.errorlog` inside the `$HTTP["url"] =~ "^/admin/"` condition.  The ability to set multiple `server.errorlog` was a feature added in lighttpd 1.4.56, released over 2 years ago.

**Comment by gstrauss** [comment]
> And I want to add, this seems to be a service issue because a simple `sudo service lighttpd restart` resolves it, until it fails again. In other words, when the lighttpd service error logs claim it can't access the socket file, it's appears to be the lighttpd software having the issue, not actually a file or permission issue.

Actually, that indicates only that lighttpd is able to resolve the issue by being restarted, which involves lighttpd killing the PHP backend, recreating the socket file, and restarting the backend.  If you have not changed the version of lighttpd you are running, and this used to work with a previous version of pihole, then it is very unlikely that this is an issue with lighttpd.

**Comment by rdwebdesign** [comment]
@gstrauss 


> FYI: it might be more appropriate to set server.errorlog inside the $HTTP["url"] =~ "^/admin/" condition. The ability to set multiple server.errorlog was a feature added in lighttpd 1.4.56, released over 2 years ago.

We know that and we agree some versions are older and far from optimal, but we also know Debian 10 uses `lighttpd 1.4.53` and there's a lot of user using this OS.

The `server.errorlog` option was set there because we know there are users using older Operating Systems.

**Comment by rdwebdesign** [comment]
@linucksrox 

I'm not sure if this will help, but can you try one thing?

Please, edit `/etc/lighttpd/conf-available/15-pihole-admin.conf` and change the `min-proc` value to 1 and restart `lighttpd`.

**Comment by gstrauss** [comment]
That's a good idea, though misspelled.  Setting `"max-procs" => "1"` (not `min-proc` (misspelled) or `min-procs`) is a good idea for small embedded systems, or when the backend does not need multiple backend PHP processes, or when the backend must not have multiple PHP processes due to the backend not having proper locking of shared resources.

**Comment by rdwebdesign** [comment]
Actually, I think we should use:

```
"max-procs" => "1",
"min-procs" => "1",
```

Or completely remove the `min-procs`  option.

**Comment by linucksrox** [comment]
@gstrauss Regarding basic troubleshooting, the only changes I have made recently were upgrading pi-hole to the latest version, and adding the Uptime Kuma monitor right after that. I verified that there are no cron jobs running by root or my regular user account.

I guess lighttpd hasn't been updated, since you said the version I'm running is 3-4 years old, unless Ubuntu recently went from a very old version to a slightly less old version.

The only other changes I could say on this system are 1. Uptime Kuma now hits the admin page every 60 seconds and 2. regular apt updates. I don't read release notes for changes in apt updates, I just apply them regularly.

If it goes to a 503 error again, I will do my best to follow the troubleshooting steps you described and provide the output. But I'll ask again, do you want me to try updating to a newer version of lighttpd? I have no problems trying that. I also have no problems completely blowing this system away and using Docker, etc. instead where we know it "just works." But I thought the developers might be interested in debugging in case this is an issue that affects others and I'm happy to try to debug and get to the bottom of the issue.

Regarding the config change, my config currently includes:
```
"min-procs" => 0,
"max-procs" => 1,
```

So it's unclear what setting I'm being asked to change. This is a dedicated VM with 2GB RAM and 4 vCPUs, so not particularly resource constrained.

**Comment by rdwebdesign** [comment]
Please try:
```
"max-procs" => "1",
"min-procs" => "1",
```

**Comment by gstrauss** [comment]
Oh, looking in `pihole-admin.conf`, `"max-procs" => 1` is already set.

@linucksrox for troubleshooting, setting `"min-procs" => 1` is a good idea.

**Comment by rdwebdesign** [comment]
I think `lighttpd` is killing the socket when `min-procs=0`. The original config never had this option set.

**Comment by gstrauss** [comment]
> But I'll ask again, do you want me to try updating to a newer version of lighttpd?

Not for me.  If you think there is a bug in lighttpd, then please try a newer version of lighttpd.  However, I do not think this issue is with lighttpd code, since this used to work with the same version of lighttpd, but a prior version of pihole.

**Comment by linucksrox** [comment]
That makes sense. I updated the config to `min-procs=0` and restarted the service. Time to wait :)

**Comment by rdwebdesign** [comment]
@linucksrox 

Did you set the value to `0` or `1`?

**Comment by gstrauss** [comment]
@linucksrox please test with `"min-procs" => 1`, as @rdwebdesign noted, too.

@rdwebdesign I hope that you've picked up on the change the makes a difference.  That change would be my fault since I'm the one who proposed those recent changes.  Sorry.  

`"min-procs" => 0` works quite well on thousands of Turris routers, but Turris devices automatically update by default and run recent versions of lighttpd.

Do you know if anybody reported this 503 Service Unavailable issue running anything later than lighttpd 1.4.53 or lighttpd 1.4.55?

**Comment by rdwebdesign** [comment]
I'm not sure. Maybe we saw some issues from Debian 11 (`lighttpd 1.4.59`), but this needs confirmation.

**Comment by linucksrox** [comment]
My mistake, I typed the wrong thing here. I did in fact set the min-procs value to 1: `"min-procs" => 1`

**Comment by j0np** [comment]
> > Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` to `/run/lighttpd/php.socket`
> > This is not a permanent change - any update or repair will revert this, but I would be interested to see if you still see the same issue.
> > My reasoning: there was some contention about changing the file of this path to live in `/tmp/`, but everything I read in the lighttpd docs used `/tmp` in the examples - so it seemed like a safe choice.
> > The default path when enabling fastcgi-php is `/run/lighttpd/php.socket`
> > Paging @gstrauss for any hints
> 
> updated one of my pi-hole nodes to use /run/lighttpd/php.socket, s
> 
> > Ok let's try some advanced troubleshooting here, if you are still having this issue please try changing the php socket path in `/etc/lighttpd/conf-enabled/15-pihole-admin.conf` to `/run/lighttpd/php.socket`
> > This is not a permanent change - any update or repair will revert this, but I would be interested to see if you still see the same issue.
> > My reasoning: there was some contention about changing the file of this path to live in `/tmp/`, but everything I read in the lighttpd docs used `/tmp` in the examples - so it seemed like a safe choice.
> > The default path when enabling fastcgi-php is `/run/lighttpd/php.socket`
> > Paging @gstrauss for any hints
> 
> updated both of my pi-hole nodes, so far no 503 error, should know within next 24hrs if the error happens again.

Quick update, since the change yesterday, still no errors :)

**Comment by Android1338** [comment]
> Please try:
> 
> ```
> "max-procs" => "1",
> "min-procs" => "1",
> ```

It works on my 2 systems without problems after this adjustment, thank you :)

**Comment by PromoFaux** [comment]
@linucksrox - any change on your side?

**Comment by linucksrox** [comment]
Ok, over 48 hours with no issues (I haven't touched pihole or updated to the latest version yet just to make sure it wasn't getting restarted, etc.). I think you guys solved it, and thanks for all the help and responsiveness! If it goes to a 503 again, I'll be back ;)
