### ISSUE TITLE
Upgrading Raspbian from Buster to Bullseye leads to Error 403 (Forbidden) - Web admin panel 

### ISSUE THREAD

**Issue by jtrumpio** [pi-hole/pi-hole#5140]
### Versions

- Pi-hole:  v5.15
- AdminLTE:  v5.18.1
- FTL:  v5.20.1

### Platform

- OS and version:  Raspbian GNU/Linux 11 (bullseye)

- Platform:  Raspberry Pi armv7l

### Expected behavior

Uninstalling and reinstalling (or repairing) Pi-Hole should replace any missing lighttpd config files.  Config files appear to have gone missing during upgrade from buster to bullseye.

### Actual behavior / bug

lighttpd config files do not get copied, 403 Forbidden is displayed.  Copying configs from another working system fixes the issue.

### Steps to reproduce

1. Upgrade running system from Buster to Bullseye.
2. Reboot
3. Visit admin panel
4. Observe 403 Forbidden due to missing lighttpd config files.

## Debug Token

- URL:  https://tricorder.pi-hole.net/BuvNBcKz/

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
Please check if this is the same issue as described at https://github.com/pi-hole/pi-hole/issues/5131

**Comment by PromoFaux** [comment]
Quoting from the release notes:

> Automatic redirection to /admin will only happen if you browse via http://pi.hole. If you wish to browse via http://[IP Address], then you will need to ensure that you add /admin manually. In the past, a splash screen has been shown with a link to /admin, however this is now removed along with the now-defunct blockpage

The splash page was removed - it serves no purpose other than to say "click here to go to /admin". The solution is to type /admin after the IP address, update your bookmark, or use the address `pi.hole` instead of the IP address, which will automatically redirect to /admin.

**Comment by jtrumpio** [comment]
> Please check if this is the same issue as described at #5131

This is not the same issue.  I was receiving 403, not 503.  The lighttpd config files were missing.

**Comment by jtrumpio** [comment]
> Quoting from the release notes:
> 
> > Automatic redirection to /admin will only happen if you browse via http://pi.hole. If you wish to browse via http://[IP Address], then you will need to ensure that you add /admin manually. In the past, a splash screen has been shown with a link to /admin, however this is now removed along with the now-defunct blockpage
> 
> The splash page was removed - it serves no purpose other than to say "click here to go to /admin". The solution is to type /admin after the IP address, update your bookmark, or use the address `pi.hole` instead of the IP address, which will automatically redirect to /admin.

Hello,

403 was received at /admin as well.  The issue was not resolved until I replaced the lighttpd config files in /etc/lighttpd and created the following symbolic links in /etc/lighttpd/conf-enabled:

lrwxrwxrwx 1 root root   32 Jan 21 14:02 05-setenv.conf -> ../conf-available/05-setenv.conf
lrwxrwxrwx 1 root root   33 Jan 21 14:02 10-fastcgi.conf -> ../conf-available/10-fastcgi.conf
lrwxrwxrwx 1 root root   37 Jan 21 14:14 15-fastcgi-php.conf -> ../conf-available/15-fastcgi-php.conf
lrwxrwxrwx 1 root root   38 Jan 21 14:02 15-pihole-admin.conf -> ../conf-available/15-pihole-admin.conf
lrwxrwxrwx 1 root root   38 Jan 21 14:02 99-unconfigured.conf -> ../conf-available/99-unconfigured.conf

**Comment by PromoFaux** [comment]
As you did a full distribution upgrade, it is difficult to know what things change... the folks at Raspberry Pi always recommend you flash a new SD card with the latest OS rather than upgrade between versions for this reason.

That aside, I think that running `pihole -r` (to repair) after you upgraded from buster to bullseye would also have fixed things on pi-hole's side...

**Comment by jtrumpio** [comment]
Unfortunately pihole -r did not fix the issue.  I ran that several times, even after finally resorting to an apt-get purge on lighttpd and letting pihole -r reinstall the lighttpd dependency.

I would expect the -r or a clean install would copy the lighttpd config files correctly.

**Comment by PromoFaux** [comment]
Were you on the latest Pi-hole changes before you upgraded the OS?

**Comment by PromoFaux** [comment]
That all said...

I've just installed Pi-hole on a Debian 10 system - then done a full distribution upgrade to Debian 11, and the web interface is still operating correctly.

I suspect something went wrong in the process of upgrading Raspberry Pi OS 10 -> Raspberry Pi OS 11 here...

**Comment by jtrumpio** [comment]
It was on the latest pi-hole.

If you whack the configs at /etc/lighttpd and then do a pihole -r does it replace the configs?

**Comment by PromoFaux** [comment]
Ah, no, it wont. Because we only replace `lighttpd.conf` there is an existing one there with the line `FILE AUTOMATICALLY OVERWRITTEN BY PI-HOLE`:

https://github.com/pi-hole/pi-hole/blob/9048429bbbc002c851365d3ccef1c5923ef8845c/automated%20install/basic-install.sh#L1403-L1413

Changes were made in the latest version (hence the quote I posted above from release notes) to not clobber the default `lighttpd.conf` file that should be installed with `lighttpd` (not sure why this wasn't installed when you reinstalled `lighttpd`) The reasoning for this being that we should not enforce and overwrite the config on every update, rather we should allow those users that want to host more than just Pi-hole via `lighttpd` to do so.

On debian based OS, we then install our config into `/etc/lighttpd/conf-available` and activate it with `lighty-enable-mod`

https://github.com/pi-hole/pi-hole/blob/9048429bbbc002c851365d3ccef1c5923ef8845c/automated%20install/basic-install.sh#L1432-L1450

I still don't really know how all your config files ended up going missing - I've tried a couple of times now upgrading from 10 -> 11 and both times everything was still in place.

**Comment by jtrumpio** [comment]
So strange...  I have a few more pi's to update that are in a similar state - I'll see if I have similar results.

When doing the in-place upgrade I specifically chose to retain the lighttpd config files instead of replace them with the maintainer's version.

**Comment by PromoFaux** [comment]
If you have several to retry the process on - it might be worth choosing to replace the lighttpd config files and then seeing what effect that has.

**Comment by PromoFaux** [comment]
@ghtesting2020 - again, what you are seeing is expected without /admin. This issue is completely unrelated.

**Comment by SodaWithoutSparkles** [comment]
Could you please post result of `ls -lah /var/www/html/admin`? Just want a sanity check. BTW code blocks can be added by enclosing a paragraph with 3 backticks. 

````
```
Like this
```
````

**Comment by Peronia** [comment]
I have the same issue but I'm using Debian 11 (don't update from 10 to 11).
With Pi-hole v5.14.2, FTL v5.20, Web Interface v5.18 all is fine, admin and blocking works.
When I run `pihole -up` pihole successfully updated. Blocking works fine, admin says forbidden.

**Comment by Kopernikus1979** [comment]
Same problem here

**Comment by rdwebdesign** [comment]
@Kopernikus1979 

Do you see this error accessing the web interface using `http://<pihole_IP>/admin`?
Do you see the same error accessing `http://pi.hole/admin`?

**Comment by PromoFaux** [comment]
>UPDATE

>../admin/login.php can be accessed directly. Login works.

Per the release notes - yes.  

Everything from https://github.com/pi-hole/pi-hole/issues/5140#issuecomment-1399618905 onwards is expected and not related to the issue reported by the OP

**Comment by denetii** [comment]
I noticed this issue before I made this exact upgrade. so I was sure to backup the lighttpd config files. However, upon completing the OS upgrade, Pi-hole continued to work correctly and I never ran into this HTTP error. I was prompted to overwrite the config files for lighttpd during the upgrade, and I went with the default option (N, don't overwrite with the newer vendor-provided files). 

The versions of Pi-hole, FTL and the Admin panel on my system were all identical, so I'm not sure what would have produced a different result.
