### ISSUE TITLE
Fresh install Debian 11 Fails

### ISSUE THREAD

**Issue by TristanPFox** [pi-hole/pi-hole#5163]
I've tried this multiple times and it keeps failing. I'm trying to install on a Debian 11 LXC container on Proxmox.

Steps:
`apt update`
`apt upgrade -y`
`apt install curl`
`curl -sSL https://install.pi-hole.net | bash`
Then It asks me for some config options, I agree to all, then it starts the second part of install, then error occures

The error i keep getting is
`Job for systemd-resolved.service failed because the control process exited with error code.
See "system ctl status systemd-resolved.service" and "journalctl -xe" for details`
• The error seems to be "failed to start network name resolution"

And when I try to stop and then start the service. Same error. 

I've tried fresh installing this 4 times and is 100% repeatable. I'm available for screen sharing if needed. Only takes about 3 min to reproduce. Thanks

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
