### ISSUE TITLE
Says out of space | Only 34% Usage...

### ISSUE THREAD

**Issue by TristanPFox** [pi-hole/pi-hole#5164]
### Versions

- Pi-hole:  v5.14.2
- AdminLTE:  5.18
- FTL:  5.20

### Platform
- OS and version:  Debian 10
- Platform:  Proxmox LXC Container

### Expected behavior
• Log in to the web portal

• Set a new pass in the console

### Actual behavior / bug

• I try to login, and it just refreshes the login page when I use the correct login with no error message being shown. If I type it in wrong it says its wrong like expected.
• When I go to the console to try and reset the password, update, or do anything else. I throws an error saying `cannot create temp file for here-document: No space left on device` But I have plenty of space? Screenshow below of my `df -ah` result.

### Screenshots

![storage](https://user-images.githubusercontent.com/51061164/218164999-ac11607c-71ba-42dc-8f0e-792f949b438b.PNG)

### Additional context

Worked fine for a long time, when I ran into this in the past I used `apt clean` and `apt auto-clean` and that worked for a few weeks at a time. But now it seems to have completely bricked. I tried restoring a backup from a few days prior. Same issue. I tried clean installing and it wouldn't work either and threw the below error:
`Job for systemd-resolved.service failed because the control process exited with error code.
See "system ctl status systemd-resolved.service" and "journalctl -xe" for details`
• The error seems to be "failed to start network name resolution"
I tried fresh installing 4 times, 100% repeatable error. So I restored my back up. and back to square one...

**Comment by dschaper** [comment]
Is that screenshot of the proxmox host or the container? How are you accessing the terminal of the container, are you using `pct`?

**Comment by dschaper** [comment]
It doesn't look like there's any `/tmp` directory.

**Comment by TristanPFox** [comment]
> It doesn't look like there's any `/tmp` directory.

How do I fix this? Just mkdir tmp?

**Comment by dschaper** [comment]
I don't know, I don't use proxmox.

**Comment by TristanPFox** [comment]
> Is that screenshot of the proxmox host or the container? How are you accessing the terminal of the container, are you using `pct`?

That is a screenshot of the container. which is Debian 10. 

Here's what happens when I run ls, and try and make a file called tmp...
![Capture](https://user-images.githubusercontent.com/51061164/218286121-a89ffa26-4bb5-428e-b843-69dc531ec91d.PNG)

**Comment by TristanPFox** [comment]
If I try to mkdir /tmp
It says it already exists, when I go into it and ls, it's empty

**Comment by TristanPFox** [comment]
I don't mind fresh installing. I just encounter the issue I mentioned on the bottom half of the post

**Comment by dschaper** [comment]
If you are unable to make a directory in your home directory then indeed there are filesystem issues. May be space, may be lack of permissions, may be something else. `mkdir ~/tmp` or `/root/tmp` shouldn't touch anything other than the `/` partition.

I do know that running `pct enter` can cause problems, that's why I asked. 

The other issue you have is with `systemd-resolved` and that's not something we do or touch. That's the distro's native nameserver and can not be active when Pi-hole is active, they both need to listen on tcp/udp 53. 

So not being able to write to your home directory is not a Pi-hole issue directly, I don't know enough about proxomox to be able to help, I haven't used it in a few years. You could ask on our discourse forum at https://discourse.pi-hole.net or ask around at a proxomox support forum for the filesystem write issues.
