### ISSUE TITLE
DNS INTERFACE SETTINGS BUG

### ISSUE THREAD

**Issue by MrHumanRebel** [pi-hole/pi-hole#5180]
Every time I restart my server, I need to change from "Allow only local requests" to "Permit all origins" and then back again in order for PiVPN (Wireguard) to work with DNS name resolution.
![image](https://user-images.githubusercontent.com/80947401/219899688-e2f9bdcf-3655-4e37-9172-994cae66de46.png)
Previously it was working perfectly, this bug was probably introduced in the last 1-3 revisions. I noticed this behaviour after not having to restart the whole server for a few update cycles.

Thanks in advance.

Linuxmint latest
PI-HOLE [V5.15.5]
FTL [V5.21]
WEB INTERFACE [V5.18.4]

**Comment by rdwebdesign** [comment]
Please, generate a Debug Log and post here **only the Token**.

**Comment by MrHumanRebel** [comment]
https://tricorder.pi-hole.net/5uL5EyJ9/

**Comment by rdwebdesign** [comment]
Linux is not a supported OS, but the main problem is the OS `dnsmasq` is active and using port `53`, causing a conflicting with `pihole-FTL`.

You need to disable `dnsmasq`.

**Comment by MrHumanRebel** [comment]
I solved it with this workaround script at boot:

sleep 5
sudo -S <<< "PASSWD" pihole -a interface local
sleep 5
sudo -S <<< "PASSWD" pihole -a interface all

Hope it gets fixed soon, I had no problems with Pi-Hole until now, nothing has changed on my server since then, only Pi-Hole updates.

**Comment by jfb-pihole** [comment]
As was noted, Mint is not a supported distribution.

**Comment by dschaper** [comment]
Mint may not be supported but it's so close to what is supported that dismissing the issue purely because it's Mint is overkill.


> Hope it gets fixed soon
@MrHumanRebel Did you disable `dnsmasq` like was noted?

**Comment by yubiuser** [comment]
This sound like an issue with the the VPN interface not being ready when Pi-hole is already binding to the available interface. Please try if setting `DELAY_STARTUP=5` in `/etc/pihole/pihole-FTL.conf` solves the issue.

https://docs.pi-hole.net/ftldns/configfile/#delay_startup

**Comment by MrHumanRebel** [comment]
None of these fixed the probalem so I was forced to move to a docker instance. This morning the whole DNS resolution system was not working at all.

**Comment by qlyoung** [comment]
I have a similar issue. My pihole is part of a Tailnet (tailscale-administered wireguard mesh) and has a static IPv4, a DHCP-provisioned IPv4, and a Wireguard address on the VPN interface:

```
root@odroid:/home/qlyoung# ip addr
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    inet 192.168.0.3/24 scope global eth0
    inet 192.168.0.101/24 brd 192.168.0.255 scope global secondary noprefixroute eth0
3: tailscale0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1280 qdisc fq_codel state UNKNOWN group default qlen 500
    inet 100.93.144.53/32 scope global tailscale0
```


After each reboot, `pihole-FTL` was only bound to the statically assigned LAN address (`192.168.0.3`) and not to the DHCP or Tailscale v4s:

```
root@odroid:/home/qlyoung# netstat -tlnp | grep "pihole-FTL"
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:53            0.0.0.0:*               LISTEN      574/pihole-FTL
tcp        0      0 192.168.0.3:53          0.0.0.0:*               LISTEN      574/pihole-FTL
tcp        0      0 127.0.0.1:4711          0.0.0.0:*               LISTEN      574/pihole-FTL
tcp6       0      0 fe80::720b:76ca:738e:53 :::*                    LISTEN      574/pihole-FTL
tcp6       0      0 ::1:53                  :::*                    LISTEN      574/pihole-FTL
tcp6       0      0 fe80::d42f:4ae0:b80a:53 :::*                    LISTEN      574/pihole-FTL
tcp6       0      0 ::1:4711                :::*                    LISTEN      574/pihole-FTL
```

What I expect is that pihole-FTL be bound to port 53 on all 3 of the v4 addresses I mentioned. Performing a `systemctl restart pihole-FTL` does result in that situation:




I tried:
1. Setting `After=tailscaled.service` in `/etc/systemd/system/pihole-FTL.service`
2. Setting `DELAY_STARTUP=5` in `/etc/pihole/pihole-FTL.conf`
3. Setting `DELAY_STARTUP=10` in `/etc/pihole/pihole-FTL.conf`
4. Setting `DELAY_STARTUP=30` in `/etc/pihole/pihole-FTL.conf`

After each change, I rebooted the pihole.

Results:
1. Nothing changed
2. Nothing changed
3. Observed `pihole-FTL` now binding both static and DHCP IP
4. Observed `pihole-FTL` now binding static, DHCP and Tailscale IP

Thus I'm sticking with 4. However, I feel there should be a more elegant solution - perhaps along the lines of a systemd unit ordering that has the effect of making `pihole-FTL` wait until all interfaces are fully configured to start up, or patching `pihole-FTL` so that it notices interface changes and binds newly added addresses. The latter could be done by observing netlink messages, but is probably a lot of work to do right. Identifying a systemd dependency to produce the desired behavior seems like a good path forward.
