### ISSUE TITLE
Query search not always working

### ISSUE THREAD

**Issue by rube200** [pi-hole/pi-hole#5236]
### Versions
- Pi-hole:  5.15.5
- AdminLTE:  5.18.4
- FTL:  5.21

### Platform
- OS and version:  Debian 11
- Platform:  Raspberry Pi

### Expected behavior

_A clear and concise description of what you expected to happen._

### Explanation
I saw a domain in blocked list so i got to search for it(the domain is `cloclo59.cloud.mail.ru`).
When i query it in (/admin/queryads.php) both(partial and exact serach) found it:
![image](https://user-images.githubusercontent.com/20555316/224575379-62b0a1a9-ff5a-41a0-a200-4ae898ef32a0.png)
but when i try to search for (`cloclo` which is part of `cloclo59.cloud.mail.ru`) it doesnt found any match for both partial or exact match and the same goes for `cloud.mail.ru`.
![image](https://user-images.githubusercontent.com/20555316/224575433-78e44207-c9f1-4f7b-a87c-38c68c9d9dcf.png)
![image](https://user-images.githubusercontent.com/20555316/224575438-84a98eb8-9d8d-4ab1-a07b-f95526f60e7c.png)
![image](https://user-images.githubusercontent.com/20555316/224575451-bda6e3dd-bf36-4b8f-a046-efa77d40fca3.png)
![image](https://user-images.githubusercontent.com/20555316/224575459-6fa4c636-9fb6-48fe-987f-f53b55b61e08.png)

**Comment by SodaWithoutSparkles** [comment]
@yubiuser uh isnt this being investigated?

**Comment by yubiuser** [comment]
I looked into this and it's difficult to solve.
The relevant code part is here: https://github.com/pi-hole/pi-hole/blob/d885e92674e8d8d9a673b35ae706b2c49ea05840/advanced/Scripts/query.sh#L89-L92

When we scan the lists, we also check it the input sting is captured by a RegEx from one if the lists by **evaluating** the RegEx and match the input string against it. This way, we know `(\.|^)morginan\.com$` does match `morginan.com` but not `morginan` (which is the correct and expected result). However, what you want is to a **literal** comparison of (parts of) the input string with the RegEx. 

Technically, it's easy to solve, but we would need new buttons on the web interface and maybe a new option from the command line - because I'm not sure if such a literal search would fit into `partial match`or `exact match` properly.

**Comment by rdwebdesign** [comment]
This could be achieved using something like this (search the `$domain` in the regex):

```sh
echo "${lists}" | grep -i -F "${domain}"
```

But I think this will cause confusion, because not every possible "partial search" term will return the same regex as expected.

**Example:**
If you use this code and the original regex above (`cloclo[0-9]+.cloud.mail.ru`), you will find the regex if you search for `cloclo`, but there will be no match if you search for `cloclo59`.

**Comment by SodaWithoutSparkles** [comment]
How about adding sth like "try best to match something" match?

I found an answer for bash(?) here: https://stackoverflow.com/questions/23356796/gnu-regular-expression-for-partial-match

Or throw it into another language (e.g. Python) and let it return the result: https://stackoverflow.com/questions/36145045/partial-regex-matching

Or do is browser side with JS: https://stackoverflow.com/questions/22483214/regex-check-if-input-still-has-chances-to-become-matching/41580048#41580048

The JS one can only do matching from the start, like matching `cloclo96` would work but `mail` wont

**Comment by yubiuser** [comment]
I don't see this happening in any other language than `shell` (or maybe C if implemented directly within `FTL`) because it should work from command line as well (not all users install the web interface)
