### ISSUE TITLE
  Error, something went wrong! While executing INSERT OR IGNORE: attempt to write a readonly database Added 0 out of 1 domains

### ISSUE THREAD

**Issue by Yuhlabs** [pi-hole/pi-hole#5250]
### Versions

 Pi-hole version is v5.16.2 (Latest: v5.16.2)
  AdminLTE version is v5.19 (Latest: v5.19)
  FTL version is v5.22 (Latest: v5.22)

### Platform
- OS and version:  Raspberry Pi lite 64 bit 
- Platform:  Raspberry Pi 3 Model B V1.2

### Expected behavior

When I enter a domain it should blacklist 
### Actual behavior / bug
When entered it give the error (  Error, something went wrong! While executing INSERT OR IGNORE: attempt to write a readonly database Added 0 out of 1 domains)

### Steps to reproduce

1. Go to 'Domains'
2. Click on 'domain:'
3. Click add to blacklist

## Debug Token

- URL:  

### Screenshots

![Screenshot 2023-04-07 141055](https://user-images.githubusercontent.com/100239692/230657129-cabc1a7a-39c8-45d5-9a84-6a4e42fb677e.png)

### Additional context

Worked previously when tested with coolmathgames.com

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not provide debug tokens if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.

**Comment by Yuhlabs** [comment]
@dschaper after looking through the closed issues I cannot find a way to solve it could you please help?

**Comment by yubiuser** [comment]
Referencing from above

> Also, visit our [Discourse](https://discourse.pi-hole.net/) site for additional assistance.
