### ISSUE TITLE
Pi-hole loses internet, but I can connect to admin interface

### ISSUE THREAD

**Issue by pennywise134** [pi-hole/pi-hole#5256]
### Versions

- Pi-hole: v5.16.2
- AdminLTE: v5.19
- FTL: v5.22

### Platform
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

- Platform:  Raspberry Pi 4b 2GB

### Expected behavior

Internet Access

### Actual behavior / bug

No Internet Access

### Steps to reproduce

-install pi-hole with eth0 and static ip
-connect to pi-hole admin interface (working)
-use pi-hole as DNS server (for router or individual devices, both don't work)
-lose internet access
-pihole itself also has no internet access. cannot even ping gateway (modem)

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by pennywise134** [comment]
really strange issue as I'm able to access the pihole from my local network, however I can't even ping the gateway from the pi-hole

pi@raspberrypi:~ $ ip route | grep default
default via 192.168.2.1 dev eth0 src 192.168.2.222 metric 202
pi@raspberrypi:~ $ ping 192.168.2.1
PING 192.168.2.1 (192.168.2.1) 56(84) bytes of data.

--- 192.168.2.1 ping statistics ---
85 packets transmitted, 0 received, 100% packet loss, time 86014ms

**Comment by dschaper** [comment]
Because of the number of support requests and the very limited resources we have as a free open-source project run by volunteers, we will be closing all Issues that do not follow all instruction in the Issue Template and do not **provide debug tokens** if applicable. Thank you for your understanding.

Please search [open](https://github.com/pi-hole/pi-hole/issues) and [closed](https://github.com/pi-hole/pi-hole/issues?q=is:issue+is:closed) issues for others that may have your same question. Also, visit our [Discourse](https://discourse.pi-hole.net) site for additional assistance.
