### ISSUE TITLE
Own hostname entries are included in calculation of number of total blocked domains

### ISSUE THREAD

**Issue by ThinkPadNL** [pi-hole/pi-hole#527]
My */etc/pihole/gravity.list* contains two entries that are added automatically
192.168.4.12 adblock-vm
192.168.4.12 pi.hole

This is probably done so the pi-hole instance can also accessed by hostname (adblock-vm / pi.hole) instead of only by IP-address. Nice!

However, these are also included in the calculation on the dashboard ("Domains Being Blocked").
Not really a issue, but the calculation of the total domains blocked is not fair this way ;-) I noticed it when browsing the gravity.list (after i removed all the blocked ad domains). After removing all the domains that contain ads, the dashboard still indicated two blocked domains. When i removed the two lines with the hostname of the machine, the dashboard went to zero like i would expect.

**Proposed fix:**
I think the function '*CalcBlockedDomains()*' in *chronometer.sh* should contain some code to not include these lines with the own hostname in the calculation: 
https://github.com/pi-hole/pi-hole/blob/master/advanced/Scripts/chronometer.sh#L20

The lines seem to be added by function *gravity_hostFormat()* in *gravity.sh*:
https://github.com/pi-hole/pi-hole/blob/master/gravity.sh#L264

**Comment by PromoFaux** [comment]
Hey, thanks for the feedback!

>This is probably done so the pi-hole instance can also accessed by hostname (adblock-vm / pi.hole) instead of only by IP-address. Nice!

Also, if you ping a blocked domain from another client machine, the host name returned is whatever is at the top of `gravity.list` (Not sure why it's not the actual host name.. but there we go). We implemented adding the hostname and `pi.hole` (admittedly that came after) at the top of `gravity.list` so that a pinging a blocked domain (e.g `doubleclick.net`) didn't return a ping response from a dodgy looking domain (`0007ru.org`, or whatever was at the top)

What is displayed on the website is actually on the [Admin-LTE repo](https://github.com/pi-hole/adminLTE) in the PHP, it no longer relies on the JSON output of `chronometer.sh`. That said, both places could probably be updated to remove 2 domains from the calculation... though for all the difference it makes, nothing else uses that figure for calculations..

**Comment by ThinkPadNL** [comment]
For now i 'fixed' it by adding a '-2' to https://github.com/pi-hole/AdminLTE/blob/master/data.php#L10 between the last bracket and the ;

**Comment by PromoFaux** [comment]
Sure! See [this page on our wiki](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists) for useful tips on how to achieve that. 

The gist of it is:

```
cp /etc/pihole/adlists.default /etc/pihole/adlists.list
nano /etc/pihole/adlists.list
```

and then comment out all the lists. Even easier would just be `touch /etc/pihole/adlists.list` to create a blank file. 

After doing either of those above two options, just run `pihole -g` to update `gravity.list`

**Comment by PromoFaux** [comment]
As a pre-warning, if you end up with thousands of domains in your blacklist.txt, the web front end can be a little sluggish to load the list.

You can add larger/bulk hostnames to gravity.list by following something [like this](https://github.com/pi-hole/pi-hole/issues/494#issuecomment-217103007).

**Comment by ThinkPadNL** [comment]
Thanks, i ran the `touch /etc/pihole/adlists.list` and that seemed to work, because the `pihole -g` command was very fast this time.

I wasn't planning on adding thousands and thousands of hostnames, but if my blacklist becomes quite big, i will have a look at your link. 

Thanks!
