### ISSUE TITLE
Whitelist editor in the web interface

### ISSUE THREAD

**Issue by beukhof1** [pi-hole/pi-hole#53]
It would be nice and easy to have a whitelist editor on the web interface!

**Comment by DonLexos** [comment]
You would still need to run the gravity.sh script after you have added items to the whitelist I believe because from what I can tell it collects all lists (including the whitelist) and creates one master list that is actually used by dnsmasq.

I believe @jacobsalmela is already working on a more sophisticated admin panel that (I am guessing here) would have more features and statistics than the current one does.

**Comment by beukhof1** [comment]
Maybe when u hit save on the whitelist it also automaticly runs gravity.sh?

**Comment by DonLexos** [comment]
Well depending on how sophisticated you want it to be you could provide the option after the ability to save the whitelist (so box with the list, save underneath, and on the result page options to return to settings (maybe you want to do something else) or "apply all updates now and run gravity.sh").

Not sure if @jacobsalmela already has an idea of what kind of things he wants/needs/woulds/shoulds have in the interface. Right now it's all stats (and even there there are many things that can be added).

**Comment by jacobsalmela** [comment]
Believe it or not, I actually have a [whitelist script](https://github.com/jacobsalmela/pi-hole/blob/master/advanced/Scripts/whitelist.sh) but it's been a while since I updated it, so it probably doesn't work all that well.

I do plan to have more stats/graphs in the interface.  But first, I want to put things like update, whitelist/blacklist, restart, check service status, all from the interface.  Progress, as usual, is slow by today's standards since I have a full time job and do this in my free time.  But there are things in the works!

**Comment by jacobsalmela** [comment]
As a start, I am just adding a whitelist field on the left sidebar.  Eventually, this will turn into a full-fledged editor that lets you see what is whitelisted and sites you may want to.  But this should satisfice this highly-requested feature.
![pihole whitelist](https://cloud.githubusercontent.com/assets/3843505/11667134/92f8db40-9db5-11e5-9744-48b80dea574a.png)

**Comment by jacobsalmela** [comment]
I haven't forgotten about this one; [the editor looks pretty sweet](https://github.com/jacobsalmela/AdminLTE/pull/9).  I need to fix the bugs first though as they take priority.

**Comment by Mcat12** [comment]
This feature is now implemented in the devel branch of the [web interface](https://github.com/jacobsalmela/AdminLTE/tree/devel).

**Comment by PromoFaux** [comment]
@Mcat12 would you be annoyed if I changed the whitelist.txt content?

**Comment by Mcat12** [comment]
Changed how?

**Comment by PromoFaux** [comment]
Maybe don't worry about it for now. It's all half-thoughts.

**Comment by Mcat12** [comment]
The whitelist/blacklist editor is available via list.php?l=white or list.php?l=black, but the sudo issue with the web server needs to be fixed before they are put in the side bar.

**Comment by webbson** [comment]
One more thing that I would love from the web interface is the ability to edit the hosts file.

**Comment by Mcat12** [comment]
The Pi-hole's file or the client? That's basically what the whitelist/blacklist is doing.

**Comment by soehlert** [comment]
I think webbson is suggesting the piholes interface since they probably use it as I do...as an internal DNS server as well. So I can give my hosts inside my house domain names since dnsmasq is already running, why not? :)

**Comment by dschaper** [comment]
@soehlert @webbson Do you want the ability to edit the `/etc/hosts` file or are you interested in the avahi daemon functionality?

**Comment by soehlert** [comment]
I would like the ability to edit the hosts file.

**Comment by Mcat12** [comment]
Sounds like it could be possible.

**Comment by Mcat12** [comment]
This is next! https://github.com/pi-hole/AdminLTE/pull/88

**Comment by jacobsalmela** [comment]
Implemented in [2.7](https://github.com/pi-hole/pi-hole/wiki/Changelog#27---2016-06-11)
