### ISSUE TITLE
Pihole not redirecting to /pihole/index.html?

### ISSUE THREAD

**Issue by TimoVerbrugghe** [pi-hole/pi-hole#530]
##### Expected Behaviour:
When going to an ad domain address, pihole serves index.html webpage.

##### Actual Behaviour:
My apache server overwrites the redirect to my home page at my subdirectory /home

##### Steps to reproduce this issue:
Allright, not a normal setup here:

- Running Ubuntu 16.04, with an Apache webserver
- Changed the basic-install.sh script to modify dependencies to support php7.0 packages & to disable lighttpd install (remove dependency, remove the installation of lighttpd.conf)
- This apache webserver requires a password for every webpage
`<Location />
Authtype Basic
...
</Location>`
- **But made an exception** for the /pihole subdirectory (tested & works)
`<Location /pihole>
Satisfy any
Allow from all
</Location>` 
- I also have a custom home page in /var/www/html/home that I redirect to using a custom .htaccess file
`RedirectMatch ^/$ /home`

When I change the DNS address of one of my local clients, I suddenly get password forms when loading a webpage, since apache redirects to my home subdirectory & requires a password.

Does pihole/dnsmasq only redirect to the ip address, not directly to /pihole/index.html? Can I change this behaviour?

**Comment by PromoFaux** [comment]
The lighttpd [config file](https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf) has a rule which basically sets `/pihole/index.html` as a 404 page. 

Something like:

-  Page requests `http://naughtyadserver.com/images/ad.png`
-  Client PC queries Pi-Hole for the IP address of `naughtyadserver.com`
-  `naughtyadserver.com` is in `gravity.list` so Pi-Hole tells the Client PC it's own IP address instead of querying on the upstream DNS server.
-  Client PC now requests `http://PiHoleIpAddress/images/ad.png`
-  `lighttpd` does not have the requested file under `/images/ad.png` so returns a 404. Or in this case `/pihole/index.html`

**Comment by TimoVerbrugghe** [comment]
Thanks for the quick response! I changed my apache conf file and added:
`ErrorDocument 404 /pihole/index.html`

But that does not help... Apache still asks for password when I go to sites with ads.

<img width="432" alt="cnn" src="https://cloud.githubusercontent.com/assets/7707120/16078950/dc455ab2-3301-11e6-8ad3-650718abf6b1.PNG">

**Comment by PromoFaux** [comment]
Apologies for the slower response! I had typed out a reply but then got distracted by my job and promptly forgot :)

I'm not too hot on apache, but one of the other guys should be able to help here.. I know @Mcat12 has dealt with a similar issue before.. 

Pinging @pi-hole/gravity

**Comment by Zegnat** [comment]
I <i>think</i> (admittedly it has been a while since I used Basic Auth through Apache) the problem is that the browser is requesting `http://PiHoleIpAddress/images/ad.png` like @PromoFaux said and Apache is set to require authentication for requests to `/images/ad.png`. So it does that.

It does not matter that `/pihole` is whitelisted from this, because that is not what is being requested. The `ErrorDocument 404` directive only tells Apache what file to substitute when a different file is not found. It does not change the requested file location.

It is even possible that the advertiser makes a call to `/assets/background.png`. You might even have a file there. In that case it would never trigger the `ErrorDocument 404` and just try to load it.

One thing you can try is to make Apache only load your homepage for a specific domain request, through `VirtualHost`. That way a request for `naughtyadserver.com` from your Apache instance would never try to load files from your website directory.

**Comment by TimoVerbrugghe** [comment]
Well I "fixed" the issue by doing the following:
- I put all of my subdirectories in /var/www/html to a subdirectory called web
- I only protected the web subdirectory with a password

Now, I also needed to limit my SSL setup to this subdirectory (including disabling HSTS), because chrome was giving me SSL errors because the domain for my certificate obviously did not match the domain of the website I was accessing.

So issue is solved for now ;).
