### ISSUE TITLE
Unsollicited redirection to `/admin`

### ISSUE THREAD

**Issue by drupol** [pi-hole/pi-hole#5306]
Hello,

I'm running PiHole in a Docker container on a Raspberry Pi 400 running NixOS.

In overall, everything runs perfectly. I'm just opening this issue to see how I could fix this very minor issue which is bugging me out since the beginning.

The Docker instance of Docker expose the port `8093` which is the Pi Hole admin interface. So, when I go to `http://192.168.2.10:8093/admin`, I can login and use the web interface. I could also use the domain name `pi-hole.router.lan` since pinging `pi-hole.router.lan` resolve to `192.168.2.10` correctly.

Then, I added the Caddy service for a cool and easy reverse proxy that could bind the url `https://pi-hole.router.lan/` to `http://192.168.2.10:8093/admin`. The idea is to use a custom internal domain name and strip the `/admin` suffix. 

The definition of the reverse proxy is as follow ([see it online here](https://github.com/drupol/nixos-x260/blob/master/hosts/router/pi-hole.nix#L6-L12)):

```
    tls internal
    handle_path /* {
      rewrite * /admin{uri}
      reverse_proxy 127.0.0.1:8093
    }
```

This setup works well so far, however, sometimes I can make it fail.

To make it fail:

1. Open a new tab
2. Go to `https://pi-hole.router.lan/`
3. Enter the pi-hole password
4. Click on Log in
5. The pi-hole tries to redirect to `/admin` and it fails since the reverse proxy already removed `/admin`.

To make it work:

1. Open a new tab
2. Go to `https://pi-hole.router.lan/login.php`
3. Enter the pi-hole password
4. Click on Log in
5. The pi-hole redirect to `/index.php` successfully.

As you can see in step 2, the difference is subtle. 

At this point, I don't really know if the issue comes from my reverse proxy config or from lighttpd pi-hole's configuation.

Can you please tell me if you already had this issue and if you have found a fix?

Thanks.

### Versions
- Docker Tag [2023.05.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.05.2)
- Pi-hole [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1)
- FTL [v5.23](https://github.com/pi-hole/FTL/releases/v5.23)
- Web Interface [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1)

### Platform
- OS and version: Docker
- Platform: Raspberry Pi 400

### Expected behavior

It should not redirect the user to `/admin`

### Actual behavior / bug

It redirect the user to `/admin` upon login

### Steps to reproduce

1. Go to 'https://pi-hole.router.lan'
7. Type the password
8. Click on 'Log in'
9. See error

## Debug Token

- URL:  

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by rdwebdesign** [comment]
> It should not redirect the user to `/admin`

The `login.php` page redirects to `index.php`. The code doesn't add `/admin` to the URL:

https://github.com/pi-hole/AdminLTE/blob/3a11976ee8ecc50e2dd9efd76caad1ad41894dd5/login.php#L13-L17

Looks like the problem is related to proxy configuration.

**Comment by drupol** [comment]
I'm not sure because I can see that there are some redirections defined in `lighttpd` conf at: https://github.com/pi-hole/pi-hole/blob/master/advanced/pihole-admin.conf#L71

**Comment by rdwebdesign** [comment]
If you are using a docker image to run Pi-hole, there is no need to add extra configuration to redirect `http://192.168.2.10:8093` to `/admin`. You just need to add  the environment variable `FTLCONF_LOCAL_IPV4=192.168.2.10` and `lighttpd` will redirect to the correct URL.

Did you try to configure your proxy without the redirection to `/admin`?

**Comment by drupol** [comment]
> If you are using a docker image to run Pi-hole, there is no need to add extra configuration to redirect `http://192.168.2.10:8093` to `/admin`. You just need to add the environment variable `FTLCONF_LOCAL_IPV4=192.168.2.10` and `lighttpd` will redirect to the correct URL.
> 
> Did you try to configure your proxy without the redirection to `/admin`?

Yes, I'm well aware of that. The reason why I added a reverse proxy is to get rid of the suffix `/admin`, and it does it correctly.
The issue is that sometimes `lighttpd` redirect to `/admin` and sometimes not depending on the url I come from. See that in the two scenarios in the first message.

**Comment by dschaper** [comment]
Try using the `uri` directives instead of rewrite.

https://caddyserver.com/docs/caddyfile/directives/uri

**Comment by drupol** [comment]
I couldn't make it work actually, that's the reason why I left this issue open.

**Comment by drupol** [comment]
There's still no solution for that?

**Comment by yubiuser** [comment]
No. But solutions and pull requests are welcomed

**Comment by PromoFaux** [comment]
> Can you please tell me if you already had this issue and if you have found a fix?

I've never had this issue, but then I've never attempted to rewrite the URL to be something other than it is. I guess my question here is what are you trying to achieve?  Is having `/admin/` in the URL otherwise causing issues that removing it would solve?

If you're in the docker file, note here how there is an additional lighttpd config file created on startup to automatically redirect the base address to `/admin` (because we can be sure that inside this container we are the only web service running - then it only makes sense to redirect the requests to the admin directory

https://github.com/pi-hole/docker-pi-hole/blob/ca7b91186eecdaf235b0c2ef1858f4038ffd8cfc/src/s6/debian-root/usr/local/bin/bash_functions.sh#L383C17-L391

**Comment by drupol** [comment]
I couldn't make it work actually, that's the reason why I left this issue open, now going to close it.

**Comment by hakai** [comment]
A bit late to the party, but I had the same issue now with my first pihole installation. Maybe this can help whoever comes across this topic in the future.

What I found is: If you arrive at any page other than `admin/login.php` without being logged in, the webapp stores your current URI in a session variable, so it can redirect you after login. Since that happens inside the docker container, the URI it sees contains the `/admin` (which is added by the proxy to make the webapp work as usual). So you go to e.g. `/groups-clients.php` (or `/`), the proxy forwards to `/admin/groups-clients.php`, so after login the webapp tells the browser to go to `/admin/groups-clients.php` (which the proxy then forwards to `/admin/admin/groups-clients.php`). 

Fixing this in the Webapp in a clean way might be a bigger task, so here's a workaround: Configure your proxy to make a redirect of all `/admin/something` URIs back to `/something`. 

For nginx this could for example be achieved with `rewrite ^/admin(.*)$ $1 permanent;` in the server section. Other proxies will have similar directives.
