### ISSUE TITLE
Can you embed the Pi-hole Web-UI into an iframe?

### ISSUE THREAD

**Issue by TheWicklowWolf** [pi-hole/pi-hole#5335]
What i understood is that the code that prevents using iFrame is ""X-Frame-Options" => "DENY"" in /etc/lighttpd/lighttpd.conf
it needs to be "ALLOW" but...
/etc/lighttpd/lighttpd.conf does not have "X-Frame-Options" => "DENY"

**Comment by TheWicklowWolf** [comment]
This seems to work->

Changed:
`setenv.add-response-header = ( "X-Frame-Options" => "ALLOW")`

in
`/etc/lighttpd/conf-enabled/15-pihole-admin.conf`

**Comment by frakman1** [comment]
I tried this via your posted solution [here](https://discourse.pi-hole.net/t/can-you-embed-the-pi-hole-web-ui-into-an-iframe/63988/6) as I am using piHole within docker in Unraid and want to view it within Home Assistant.

I confirmed that the mapping works and the `20-pihole-external.conf` file exists in the container:

```
Container: 
/etc/lighttpd/conf-enabled/20-pihole-external.conf 

Host: 
/mnt/user/appdata/pihole/external.conf
```
It worked in that now I got the login page to display within the iFrame of HomeAssistant:

![image](https://github.com/pi-hole/pi-hole/assets/5826484/82924d30-88cf-477e-bf5e-7c515be3274e)

The problem is that it won't let me login. Everytime I enter the password, it re-loads the same login page and doesn't enter the main WebUI.

Am I missing something else?

**Comment by TheWicklowWolf** [comment]
> I tried this via your posted solution [here](https://discourse.pi-hole.net/t/can-you-embed-the-pi-hole-web-ui-into-an-iframe/63988/6) as I am using piHole within docker in Unraid and want to view it within Home Assistant.
> 
> I confirmed that the mapping works and the `20-pihole-external.conf` file exists in the container:
> 
> ```
> Container: 
> /etc/lighttpd/conf-enabled/20-pihole-external.conf 
> 
> Host: 
> /mnt/user/appdata/pihole/external.conf
> ```
> 
> It worked in that now I got the login page to display within the iFrame of HomeAssistant:
> 
> ![image](https://user-images.githubusercontent.com/5826484/278497423-82924d30-88cf-477e-bf5e-7c515be3274e.png)
> 
> The problem is that it won't let me login. Everytime I enter the password, it re-loads the same login page and doesn't enter the main WebUI.
> 
> Am I missing something else?

It could be a Home Assistant issue, never used it so can't comment
