### ISSUE TITLE
Pi-Hole only partially blocking ads on YouTube.

### ISSUE THREAD

**Issue by rafspeik** [pi-hole/pi-hole#534]
##### Expected Behaviour:
For Pi-Hole to block ads like it does everywhere else, so there's just white space where an ad would be.

##### Actual Behaviour:
The add 'box' is visible and there's an "unable to connect" error message inside it, as seen in the screenshot.
![capture](https://cloud.githubusercontent.com/assets/10629864/16167663/acc646bc-34ef-11e6-91be-991c4210970e.JPG)

Pi-Hole is working on both IPv4 and IPv6.

Any ideas what this could be?

**Comment by diginc** [comment]
I believe this is normal behavior for default pi installations when ad ad is served over HTTPS:// instead of HTTP://

There has been lots of discussion regarding improving HTTPS ad behavior but I think it boils down to the current tools pihole uses can't impersonate the secure ad servers' domains to generate a white page so it just drops the connection instead resulting in "Unable to Connect".  

Even if pihole did return a white page for HTTPS you'd still probably have a big white square in that same location.

**Comment by rafspeik** [comment]
OK, thank you! Would the best solution to this be simply installing a local ad blocker in the browser? Or is there anything else I can do

**Comment by PromoFaux** [comment]
I have uBlock running on my computer to mop up the stuff we can't get with pi-hole, It's not  perfect solution, but it works well!

**Comment by rafspeik** [comment]
OK, I'll check that out. Cheers!
