### ISSUE TITLE
Loading delay on iOS17 (PR block)

### ISSUE THREAD

**Issue by boehser-enkel** [pi-hole/pi-hole#5401]
### Versions

Docker Tag [2023.05.2](https://github.com/pi-hole/docker-pi-hole/releases/2023.05.2) Pi-hole [v5.17.1](https://github.com/pi-hole/pi-hole/releases/v5.17.1) FTL [v5.23](https://github.com/pi-hole/FTL/releases/v5.23) Web Interface [v5.20.1](https://github.com/pi-hole/AdminLTE/releases/v5.20.1) 

### Platform

- OS and version:  Ubuntu

- Platform:  Docker

### Expected behavior

Normal loading

### Actual behavior / bug

Sporadically delay on webpage loading (1-2 seconds) after iOS 17 update
BLOCK_ICLOUD_PR=false solves the issue
Private relay is not activated on end device

### Steps to reproduce

Update to iOS17 - surfing

## Debug Token

- URL:  W10PC21030

### Screenshots

_If applicable, add screenshots to help explain your problem._

### Additional context

_Add any other context about the problem here._

**Comment by yubiuser** [comment]
This is very likely due to changes on iOS 17. When `BLOCK_ICLOUD_PR=true` (which is the default) is enabled, two canary domains are blocked to signal iOS devices that private relay should not be used (as described in https://developer.apple.com/support/prepare-your-network-for-icloud-private-relay). 

As this issue did not occur for you on iOS16, Apple must have changed how they handle blocked responses to those domains. As we don't have more information than Apple released on that linked page, Pi-hole can't do anything about it.

**Comment by GitGramm** [comment]
I was faceing the same issue.
Solved by changing the settings for safari:

Go to Settings  > Safari, then turn any off the following: "Hide IP address"

BR
Der Liebe Opa;-)
