### ISSUE TITLE
Blocks domains even if the group is "open"

### ISSUE THREAD

**Issue by Kikketer** [pi-hole/pi-hole#5408]
### Versions

  Pi-hole version is v5.17.1 (Latest: v5.17.1)
  AdminLTE version is v5.20.1 (Latest: v5.20.1)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  

- Platform:  MacOS

### Expected behavior

Following the instructions on: https://docs.pi-hole.net/group_management/example/ I believe I should be able to create an "Open" group and have that group not be blocked on any domains.

### Actual behavior / bug

The domains are blocked even though they should be open and unblocked as part of the "not default" group.
![image](https://github.com/pi-hole/pi-hole/assets/958042/3912fc0f-0e93-4561-9182-aebeac3f171c)

This is Chrome with no ad blockers or any other sort.

"Disable blocking" allows these requests to go through just fine.

### Steps to reproduce

I create a group called "Open"
![image](https://github.com/pi-hole/pi-hole/assets/958042/c6d6c5c9-3f59-4b71-a1fe-c738ace0520e)

I then assign my target machine to that group (both Mac and Ip versions, I've tried both and one at a time):
![image](https://github.com/pi-hole/pi-hole/assets/958042/5d0b5d8e-cc05-448d-bb82-c3bc18958242)

I then have nothing different in the domains screen (I had tried whitelisting and adding that to the group but that didn't work either):
![image](https://github.com/pi-hole/pi-hole/assets/958042/e66c27d3-f86c-44a1-a4d0-786f1439bea6)

I then refresh the DNS on pihole:

```
pihole restartdns reload-lists
```

I also clear DNS cache on the laptop:

```
sudo killall -HUP mDNSResponder
```

## Debug Token

- URL:  https://tricorder.pi-hole.net/05InVpx5/

### Additional context

I'm attempting to make just my work machine hit these endpoints as that's part of may daily activities, but for the rest of the house I'd like these blocked.

**Comment by Bucking-Horn** [comment]
This is a router configuration issue.

Your debug log shows your router to distribute its own IP as local DNS server:
```
*** [ DIAGNOSING ]: Discovering active DHCP servers (takes 10 seconds)
   Scanning all your interfaces for DHCP servers
   
   * Received 300 bytes from wlan0:192.168.1.1
     Offered IP address: 192.168.1.71
     DHCP options:
      Message type: DHCPOFFER (2)
      dns-server: 192.168.1.1
      router: 192.168.1.1
```
To employ Pi-hole's client-specific filtering, the client that you want to be filtered has to use Pi-hole for DNS directly.

Currently, it seems you have configured your router to use Pi-hole as its upstream.
Your clients are not talking to Pi-hole for DNS, but to your router, which then forwards DNS requests it cannot answer itself to Pi-hole.

You'd have to configure your router to propagate Pi-hole as local DNS server, instead of having your router use Pi-hole as its upstream DNS server.
You'd have to consult your router's documentation for details on its configuration.

Alternatively, you may manually point your laptop to use Pi-hole.

As this isn't a bug, please note that these types observations should be raised over at  https://discourse.pi-hole.net, to help our development team focus on bugs and features.

In case you'd require further assistance with this, please head over there and open a new topic.

**Comment by Kikketer** [comment]
Thank you
Setting up the DNS server as upstream in the router is crazy easy and easy to understand.  Having it "propagate pi-hole as a local DNS server" sounds complicated and I'm not sure what to even google for it.

I'll likely just have this single machine point directly to Pi-Hole.
