### ISSUE TITLE
Pi-hole DNS needs to be restarted occasionally 

### ISSUE THREAD

**Issue by jamieburchell** [pi-hole/pi-hole#5426]
### Versions

  Pi-hole version is v5.17.2 (Latest: v5.17.2)
  web version is v5.20.2 (Latest: v5.20.2)
  FTL version is v5.23 (Latest: v5.23)

### Platform

- OS and version:  Raspbian GNU/Linux 11 (bullseye)

- Platform:  Raspberry Pi

### Expected behavior

DNS resolution and web interface stay up

### Actual behavior / bug

Occasionally all DNS resolution to Pi Hole fails and I am unable to access the web interface. Issuing `pihole restartdns` resolves the issue.

### Steps to reproduce

Cannot repro on demand

## Debug Token

- URL:  https://tricorder.pi-hole.net/5zrDJR9r/

**Comment by rdwebdesign** [comment]
I couldn't find anything on your debug log suggesting there is something wrong.

Is there something else running on the same machine?

**Comment by jamieburchell** [comment]
> I couldn't find anything on your debug log suggesting there is something wrong.
> 
> Is there something else running on the same machine?

Exactly, neither can I. When it was in an unresponsive state I SSH'd in to have a poke around and come up with nothing. The Pi Hole service was running, memory, CPU and load were fine, dmesg didn't say much. What can I check next time it happens?

It's this image https://homebridge.io/raspberry-pi-image so Homebridge is also running.

**Comment by rmbleeker** [comment]
> What can I check next time it happens?

Time synchronization. A Raspberry Pi has no Real Time Clock, so in order to keep accurate time it's completely reliant on NTP. If for some reason the clock on the Pi drifts this can result in weird behavior, especially when you've enabled DNSSEC. I speak from experience as I once spend several hours trying to figure out why my 2 Pi 3's with Pi-Hole and Unbound on them weren't resolving anything, only to find out that the time on both Pi's was off by several hours due to a mistake I made months earlier in the NTP configuration.

**Comment by jamieburchell** [comment]
I don't think that's my issue since the date and time is correct and the system hasn't been rebooted in ages. I'll check that it's still correct next time it happens though.

**Comment by AVerm** [comment]
I'm seeing an odd issue where DNS for my network (provided by the Pi-hole) keeps dropping every so often, leaving a message in the "Pi-hole diagnosis" tab relating to blocking after a maximum number of entries (150) is hit and leaving the Pi-hole reachable by local IP. Restarting the DNS resolver always fixes it. This leaves the network largely operational, I think due to the cache, though certain services like company VPNs will fail.

I'll gather more information the next time I see it, but I can try to get specific information if anyone requests some that would help.
