### ISSUE TITLE
lighttpd Placeholder page issue

### ISSUE THREAD

**Issue by suryaprakash251201** [pi-hole/pi-hole#5450]
### Versions

- Pi-hole:  v5.17.2
- AdminLTE:  v5.20.2
- FTL:  v5.23

### Platform

- OS and version: Ubuntu 22.04.3 LTS

- Platform:  VM

### Expected behavior

_A clear and concise description of what you expected to happen._

### Actual behavior / bug

_A clear and concise description of what the bug is._

### Steps to reproduce

1. i am installing fresh installation facing this issue ,trying solve but can't do because not solved

## Debug Token

- URL:  

### Screenshots
![Screenshot 2023-10-21 214230](https://github.com/pi-hole/pi-hole/assets/72648292/50667b9d-4b1c-4e69-a5b6-f5b93ffefd04)

_If applicable, add screenshots to help explain your problem._

### Additional context

unable to acees pi-hole help and give me solution or help me how to solve this problem

**Comment by tomwilsonhb** [comment]
How did you install Pi-hole?

**Comment by suryaprakash251201** [comment]
> How did you install Pi-hole?

Regular CURL METHOD

**Comment by rdwebdesign** [comment]
This issue doesn't provide a Debug Token and descriptions for "Expected behavior" and "Actual behavior / bug" sections. It only shows a screenshot with the expected page when the wrong path is used to access the web interface.

The web interface is in: http://pi.hole/admin (or `http://<piholeIP>/admin`)

Which URL are you using to access the web interface?

**Comment by suryaprakash251201** [comment]
thank you problem solved
