### ISSUE TITLE
Further feature request

### ISSUE THREAD

**Issue by stephenpperry** [pi-hole/pi-hole#547]
##### Expected Behaviour:

I'd like to have a way to easily subscribe to new add blocking lists via the web interface. I.e subscribe to other hosts files from the Internet. 

For example "someonewhocares.org" 

Being able to subscribe to live Web lists may mitigate the need for updates on the pi as these lists are already being updated. 
##

**Comment by dan019** [comment]
Currently there are only a few additional list  to choose from in /etc/pihole/adlists.default. They include:
- https://raw.githubusercontent.com/BreakingTheNews/BreakingTheNews.github.io/master/hosts
- http://securemecca.com/Downloads/hosts.txt
- https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/win10/spy.txt
- http://optimate.dl.sourceforge.net/project/adzhosts/HOSTS.txt
- http://adblock.mahakala.is/

Are you suggesting you'd like to see the option enable/disable them via the web interfaces. Because of parsing logic in scrapping hosts from a list, or certain list can be used to begin with.

**Comment by PromoFaux** [comment]
This is not a bad idea, to be fair, and certainly something we may be able to incorporate into the python re-write. Thanks for the suggestion.

And as @dan019 said, yeah, some of the lists (specifically those in the "Untested lists" section) may not work with pi-hole.

**Comment by jacobsalmela** [comment]
Closing. Closing this and [sending it into orbit](https://discourse.pi-hole.net/t/subscribe-to-block-lists-via-dashboard/560) so this feature is votable.
