### ISSUE TITLE
Reverse Lookup? 

### ISSUE THREAD

**Issue by rongten** [pi-hole/pi-hole#551]
Hello,

 not sure it is possible to do with the approach used by pi-hole, but would it be possible to pass reverse lookup queries in case a custom dns server used?
 
 I.e. setting a openwrt router as the custom dns, I would like to do a reverse lookup on an IP address to see the corresponding hostname in my home network.

 Or maybe I am holding it wrong? 

Regards

**Comment by dschaper** [comment]
We currently use `dnsmasq` as our DNS backend, so I'm not sure if that is possible. Are you looking to set up the `in-addr.arpa` domains so they return a FQDN from the PTR record request? Have you tried setting the name and address in the `/etc/hosts` file to check if you get a proper response?

We are doing a major overhaul of the code and one of the possibilities we are discussing is changing the daemon used for resolution. We'll have to see if there is the possibility to handle PTR's in a special case.

**Comment by rongten** [comment]
Hello,
 with openwrt (192.168.2.1) I get indeed a return from the in-addr.arpa domain, i.e.:
```
[xray@laptop ~]$ nslookup  192.168.2.8 192.168.2.1
Server:		192.168.2.1
Address:	192.168.2.1#53

8.2.168.192.in-addr.arpa	name = laptop.lan.

```
If I ask to pi-hole (192.168.2.9), I get no answer:

```
[xray@laptop ~]$ nslookup  192.168.2.8 
Server:		192.168.2.9
Address:	192.168.2.9#53

** server can't find 8.2.168.192.in-addr.arpa: NXDOMAIN

```

I just tried with latest pi-hole, set custom dns to the openwrt router (did not restart the pi however).

It is not a big deal, but it could be useful if in the house there are many devices.

Cheers

**Comment by dschaper** [comment]
I'll take a look at OpenWRT, it looks like the configuration there has the names of the local devices added in the reverse domain when they get their DHCP leases. I'll need to dig some more to see what the process is and if it's something we can do. It may not be, if it's tied in to the DHCP lease request,

**Comment by rongten** [comment]
Actually, it seems so, you are right.

I use static IP for a few devices and indeed for those you cannot use reverse lookup on openwrt (never did, since I know them by heart). 

I will see if it is possible configure correctly openwrt, otherwise obviously pi-hole cannot provide an answer.

**Comment by BiloxiGeek** [comment]
On 07/03/2016 06:19 AM, rongten wrote:
>
> Actually, it seems so, you are right.
>
> I use static IP for a few devices and indeed for those you cannot use 
> reverse lookup on openwrt (never did, since I know them by heart).
>
> I will see if it is possible configure correctly openwrt, otherwise 
> obviously pi-hole cannot provide an answer.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pi-hole/pi-hole/issues/551#issuecomment-230148254>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/APMRtZ3f3-XCbp4m3Yj6CnCUmhFR4uRAks5qR5rdgaJpZM4JC7eu>.
>
I use reserved IP addresses for everything on my home network.  I've 
added all the hostname/IP definitions to /etc/hosts on the pi-hole and I 
get valid reverse lookups. So I think if you make sure pi-hole knows how 
to resolve them (/etc/hosts) it should give a good response.


-- 
//-        Fixer of that which is broke        -//
//-        Home = sberg@mississippi.com        -//
//- Sinners can repent, but stupid is forever. -//

**Comment by dschaper** [comment]
It looks like there are two places you can set the DNS server on OpenWRT, I'm looking at the Material theme, and there is a place to edit the interface and set a custom DNS, and it looks like that one overrides everything for that interface. There's another place in the DHCP and DNS tab that lets you set forwarding DNS server addresses. If you set the DNS forwarder to the Pi-Hole address here it looks like it might work by looking up in its own dnsmasq process first and then forwarding names not internally known to the OpenWRT router out to the Pi-Hole. Need to test to check the name resolution routing, but that may be a way to get things to work for you.

**Comment by gshlomi** [comment]
I have (I think) the same configuration at my house:
OpenWRT as a custom DNS server for Pi-Hole
Pi-Hole as primary DNS, OpenWRT as secondary DNS server (in case Pi-Hole unavailable) - set using DHCP option 6.
Solved the Reverse Lookup problem by commenting "bogus-priv" in /etc/dnsmasq.d/01-pihole.conf, as found in https://forum.openwrt.org/viewtopic.php?pid=184521#p184521

Hope that helps

**Comment by rongten** [comment]
@gshlomi 
Definitely! Commented out, seems working fine, thank you! Never had the time to implement the other solution but this is so much simpler in my scenario!

**Comment by dschaper** [comment]
@gshlomi Do you have OpenWRT set to point back at itself as a secondary DNS server? That will cause a loop and will trigger all kinds of safety features in OpenWRT. It looks like you may have a solution in denying bogons, as that flag tells OpenWRT to accept addresses that it thinks it should be authoritative for but that are coming from an interface and not from the OpenWRT `dnsmasq` process. 

The usual caveats apply, only do this on a network that you are implicitly sure all proper security methods have been implemented. This would allow a rogue DNS server access to be able to redirect if there was one that was installed on your local network. And of course, have inbound DNS quries blocked from the WAN  at the firewall.

**Comment by gshlomi** [comment]
@dschaper OpenWRT uses google's DNS servers as the WANs DNS. Pi-Hole uses OpenWRT as its custom DNS server. The DHCP clients receive Pi-Hole as their primary server, and OpenWRT as their secondary.

**Comment by dschaper** [comment]
Try setting the OpenWRT WAN DNS to the Pi-hole address, the Pi-hole will automatically send lookups to Google (or your choice of upstreams) if it can not resolve the query. Then have OpenWRT hand out its own address as the DNS for DHCP. 

That flow would have the client query OpenWRT, which would then ask Pi-hole for the DNS information, both private and public. This setup would mean that you wouldn't need to have each client point to the Pi-hole, only the OpenWRT would point to the Pi-hole, and no other DNS servers. (This would prevent OpenWRT inadvertently querying Google when it shouldn't be, and letting in ad domains.) 

The goal is to have OpenWRT only ever query the Pi-hole and have no other DNS servers in its resolver  lists. Let the Pi-hole do that job, it's designed for that. 

Does that make sense, or does that confuse the issue?

**Comment by gshlomi** [comment]
The problem with this approach is that the Pi-Hole sees all queries as originating from OpenWRT, not the actual clients, so in a multiple clients environment it's a problem identifying if a specific site on a specific client was Holed.
Another issue is that if Pi-Hole is unavailable, OpenWRT has no DNS resolution.
My router has a UPS attached, the Pi doesn't.
The flow as I see it:
Client -> Pi-Hole ->(only if not known ad domain) OpenWRT -> GoogleDNS

**Comment by gshlomi** [comment]
p.s. - this way OpenWRT DNS doesn't cache known ad-domains at all, even if it's only the Pi-Hole IP

**Comment by dschaper** [comment]
Okay, that flow should work. Where you possibly would have issues is that if the client are given both the Pi-hole DNS IP and OpenWRT DNS IP and the OpenWRT uses Google as a secondary, then when your clients query the OpenWRT DNS and that resolver queries Google, then you will have leaks where ad domains will be injected into your network. 

Unless I am reading this wrong. If the Client only has Pi-hole as a resolver, and not the OpenWRT box, then you have some isolation for your Clients. Basically, any system other than the Pi-hole that has an upstream or secondary DNS has the potential to leak ad-domains in as part of the query responses.

**Comment by dschaper** [comment]
So you have the Pi-hole set up to use the OpenWRT box as the custom upstream? Just so I can get a better picture, can you post up the `pihole -d` results?

**Comment by dschaper** [comment]
And checking the bogon flag, it does appear that it is supposed to reply  NXDOMAIN to  RFC 1918 address requests. So I guess it's possible to run a rogue webserver and redirect, but if you had a user on net that would be capable of that, then there are other problems to attend to first.

**Comment by gshlomi** [comment]
@dschaper my results are at http://termbin.com/w5m0

**Comment by dschaper** [comment]
Thanks, so you did set the upstream for the Pi-hole to point to the OpenWRT install as the upstream resolver. Looks like with this configuration, the only way to do that is to disable rebind, or to allow for RFC 1918 address lookups without an NX response. Interesting concept and once that would need some more review to see what the actual flow is and what the modifications would need to be in order to allow for this with the least exposure.

**Comment by gshlomi** [comment]
http://termbin.com/xh8o

**Comment by dschaper** [comment]
That one seems to show an rDNS query for the 192.168.122.0/24 network?

**Comment by MichaelToborg** [comment]
If you wish to open the admin page then you can open the Web browser and insert the IP address 192.168.2.1. to see if it require the username and password. This is going to be the username and password to access the wireless router admin page. Each wireless router contains a default account information. So if you need to connect to the router settings page then insert [192.168.2.1](http://www.19216821ip.com/) in the URL bar of the Internet browser and hit go.

**Comment by macgeneral** [comment]
I'm probably in the wrong thread but would it be possible to show the reverse DNS name in the Webinterface for the forward destinations?

E.g. I use pi-hole alongside DNSCrypt and I've got 6 DNSCrypt proxies running for IPv4 and 2 for IPv6 and it would be nice if the Webinterface would show me the name I assigned in /etc/hosts instead of the local host IP (I use different localhost IPs for each proxy so I can see which one handles most requests etc).

> # DNSCrypt Proxies running on this machine
> 127.10.10.1	dk.dnscrypt.eu.dns
> 127.10.10.2	nl.dnscrypt.eu.dns
> 127.10.10.3	fr.4armed.com.dns
> 127.10.10.4	is.dnscrypt.is.dns
> 127.10.10.5	de.d0wn.biz.dns
> 127.10.10.6	de.cryptostorm.is.dns
> ::1		dknl.dnscrypt.eu.dns

![screen shot 2016-10-03 at 22 45 17](https://cloud.githubusercontent.com/assets/9381035/19053461/5f2e5bd0-89bb-11e6-9ad0-81291be170e8.jpg)

**Comment by p1r473** [comment]
This would be a very cool feature !

**Comment by PromoFaux** [comment]
I think it should be  possible! I'm away from my computer right now, but take a look at a function on data.php called `hasHostName`

We are soon to push some changes to the web admin so I'll try and remember to take a look at it then.

**Comment by PromoFaux** [comment]
@macgeneral @p1r473 

Like this? :)

![image](https://cloud.githubusercontent.com/assets/1998970/19072922/ee6a7dc8-8a2f-11e6-9606-4975059bd005.png)

**Comment by macgeneral** [comment]
Yes perfect :)

**Comment by PromoFaux** [comment]
Excellent, Have added it to this pull request https://github.com/pi-hole/AdminLTE/pull/149,

That branch is currently undergoing heavy testing, but as soon as it's ready we'll get it released!

**Comment by p1r473** [comment]
Cool thanks Adam!
Very useful for us dnscrypt users

@macgeneral when you added more than 2 dns servers, do you notice it
choosing a random one of the list? I noticed it doesn't always take mine
sequentially (only have 2 configured)
Does it do lowest latency first ?

**Comment by macgeneral** [comment]
@p1r473 dnsmasq polls all upstream servers periodically and selects the fastest one. In my screenshot you can see that each handles a different amount of request with the ones located in Germany handling the most of mine (which is where I live).

You can use the "all-servers" setting which makes dnsmasq send out each request to all of them (like a shotgun) taking the fastest reply as response, but it's considered bad practice because you create x-times the load for nothing. In practice I didn't feel a difference using the all-servers setting, hence I don't use the OpenDNS servers and most other DNSCrypt servers are slower than the big corporate ones ;)

But using more than one upstream server is a good choice for me in terms of reliability and speed (and privacy if you spread your requests on more different servers, but the ones I selected shouldn't log anything anyways)

**Comment by p1r473** [comment]
The tutorial I followed in the wiki only showed the setup for 2 servers.
Was adding a third the exact same ? Nothing special?

As well, I don't quite understand the difference between all-servers. You
are saying all-servers sends out a speed test to all DNS servers at every
DNS lookup, where without it it's just periodic in the background?

How do you set up all-servers? Just as a new line in the same file where I
declared my dnscrypt service ports ?

**Comment by macgeneral** [comment]
The all-servers dnsmasq setting will send all your DNS requests to all servers and will give you the result of the first server that replies. Which can make it faster for you but also puts unnecessary load on the servers. In my example if I type google.com in my address bar, my computer asks dnsmasq on the Pi for the IP of google.com - dnsmasq sends that request to all servers that you have configured with server=.... and will send the first result it get's back to my computer.

If you don't use that option it will pick one server and stick with it for a while, but still testing the others now and then and try to use the fastest server for your location etc. It will never use just the first defined server and fallback to the other one in case it fails.


For the additional DNSCrypt servers/proxies:
It's just a repetition of the tutorial steps involved creating the Systemd service to add more servers. I just changed the localhost IP instead of the port (so that Pi-hole shows a different forwarder for each DNSCrypt Proxy - else you will have just one localhost entry because it won't treat different ports as different servers).

`cat /etc/systemd/system/multi-user.target.wants/dnscrypt-proxy-backup_1.service
[Unit]
Description=DNSCrypt Proxy located in the Netherlands (DNSCrypt.eu NL)
After=network.target network-online.target

[Service]
Type=forking
Restart=always
RestartSec=5
PIDFile=/var/run/dnscrypt-server-dnscrypt_eu_nl.pid
ExecStart=/usr/local/sbin/dnscrypt-proxy \
  --resolver-name=dnscrypt.eu-nl \
  --daemonize \
  -u dnscrypt \
  -a 127.10.10.2:41 \
  -l /var/log/dnscrypt-server-dnscrypt_eu_nl.log \
  -p /var/run/dnscrypt-server-dnscrypt_eu_nl.pid \
  -E --edns-payload-size=4096

[Install]
WantedBy=multi-user.target`

The important part here is just the --resolver-name=..., the IP (-a 127.10.10.x:41) - you can theoretically use everything from 127.0.0.1 to 127.255.255.254, I left the port at 41 for each of them and just incremented the last number (and used 10.10. instead of 0.0. which would be most common). For the systemd service to work it's important that the path at -p /var/run/dnscrypt-server-dnscrypt_eu_nl.pid matches the one above at PIDFile=... and every dnscrypt server has a seperate log in my configuration (but you could propably share one or leave that option away so it would log to /var/log/messages / syslog).

**Comment by p1r473** [comment]
According to
http://ma.ttwagner.com/make-dns-fly-with-dnsmasq-all-servers/
It actually seems to be faster!

I want to try it out (just to test).
Do I just add
all-servers
to /etc/dnsmasq.d/01-pihole.conf?

**Comment by dschaper** [comment]
This is going way off topic for the issue. Can you take it to gitter or open a new issue for the conversation? We're hitting 3 or 4 different issues in this one thread and it's getting to be a little confusing as to what exactly is going on.

Thanks.

**Comment by p1r473** [comment]
Did this not make it into the latest build?

**Comment by dschaper** [comment]
Please clarify your question, what is the current situation, this thread is all over the place, and as such I'm going to close this. Please open a new thread, one thread per subject and please fill out the issues tracker form completely. I apologize that we have to do this, but this thread is to confusing to track at this point. Thank you for your understanding.
