### ISSUE TITLE
dnsmasq: failed to create listening socket for port 53: Address already in use

### ISSUE THREAD

**Issue by touhamii** [pi-hole/pi-hole#5554]
After installing a fresh MX Linux XFCE and updating everything, I 
1- installed pi-hole , restarted pc
2- changed my password for web interface and it didnt work until i manually go to Tools => Update Gravity, 
i expected pi-hole to just work after booting my PC without touching anything but this is not a big issue , after that i tested everything works 
3- However, the issue appeared after restarting the PC and attempting to "Update Gravity" ; it gave me the following error:
dnsmasq: failed to create listening socket for port 53: Address already in use
things i tried : 
1- restarted pc multiple times 
2- format my ssd again with fresh mx linux and fresh pi-hole but same exact issue

**Comment by touhamii** [comment]
thank you, i typed on terminal : 
sudo killall dnsmasq
and now after i Update Gravity it works 
i created a .sh file on my desktop : 

#!/bin/bash
/usr/bin/sudo /usr/bin/killall /usr/sbin/dnsmasq
pihole -g
i will try to find a way to auto start this on boot

**Comment by rdwebdesign** [comment]
Instead of killing `dnsmasq` after it starts (on every reboot), you should try to disable it (or uninstall it), so it will never start.

I'm not sure how to disable a service in your Operating System (I don't know if MX Linux uses `systemd`, `sysVinit` or a different service manager). You can probably find this information in MX Linux forums.

**Comment by touhamii** [comment]
i tried to unistall it didnt work , MX Linux is using SysV
