### ISSUE TITLE
can't be installed in rhel 9

### ISSUE THREAD

**Issue by userforsource** [pi-hole/pi-hole#5644]
I can't install pi hole in rhel 9 can you help

**Comment by rdwebdesign** [comment]
We need more information.

What happens when you try to install? 
Do you see any error messages or warnings?

**Comment by userforsource** [comment]
I got 2 error 1 selinux - enforced
2 Unsupported OS detected: redhat 9
Changes i made selinux permissible but 2nd error still present. Cent os and fedora is supported why not rhel most enterprises use rhel/oracle else ubuntu/debian.

**Comment by rdwebdesign** [comment]
Did you try to force the installation using the variable `PIHOLE_SKIP_OS_CHECK=true`?

```
curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true sudo -E bash
```

**Comment by userforsource** [comment]
![Screenshot_20240507-010744~2](https://github.com/pi-hole/pi-hole/assets/162728301/af9042b7-20a0-4432-a456-6bc97ee9aa2f)

Why this is needed why pihole does not support redhat a enterprise distro and for those who get this dostro for free or company provide this they will always use this instead of a free community distro so this should be supported also suse. Opensuse which are same kind of and nixos some of our server are using.

**Comment by rdwebdesign** [comment]
The correct way to install Pi-hole in an unsupported OS like Red Hat is adding the `PIHOLE_SKIP_OS_CHECK=true`. 

Also, SELINUX is not fully supported, but as the installer output says, you can add the variable `PIHOLE_SELINUX=true` to your command and Pi-hole will be installed.

---

> Why this is needed 

Because Red Hat is not a supported OS

> why pihole does not support redhat 

Because currently no one on our team is using Red Hat and as a free open-source project run by volunteers we have very limited time and resources to test on every different Operating System.

**Comment by userforsource** [comment]
If you want to test redhat is free for a developer account.

**Comment by bcambl** [comment]
@userforsource the reason selinux is not supported is due to the design of v5. Creating an selinux policy would require too much softening of selinux. If you currently require selinux enabled with a v5 install, please use containers. 
Feel free to try installing v6 beta as it plays much nicer with selinux enforcing. You will still need to use the two env vars to skip os and selinux checks.
Once v6 is ga, the selinux check in the installer can likely be removed.

**Comment by armonica17** [comment]
If someone wants to do this, just install. I got this to work. I'm not saying this is the only way or this is the way to do it. This is the way I did it. This is from my history file. If you are installing on a vm, you may want to snapshot it first. To error is human. To really mess something up good requires a computer. If you make a backup you probably won't need it.

Open firewall for 53 udp/tcp, 80,443 tcp

1) setenforce 0
2) Install pihole with lighttpd. After install, move to port 8080 if you want to run apache. Add proxy for /admin. Set your name server to localhost#5353 to use unbound.
3) install unbound and set to 5353
4) After all of this is running time to fix selinux.
setsebool -P httpd_can_network_connect 1
ausearch -c 'php-cgi' --raw | audit2allow -M my-phpcgi
semodule -X 300 -i my-phpcgi.pp
ausearch -c 'php-fpm' --raw | audit2allow -M my-phpfpm
semodule -X 300 -i my-phpfpm.pp
/sbin/restorecon -v /var/www/html/admin/scripts/pi-hole/php/
ausearch -c 'postdrop' --raw | audit2allow -M my-postdrop
semodule -X 300 -i my-postdrop.pp
ausearch -c 'unbound' --raw | audit2allow -M my-unbound
semodule -X 300 -i my-unbound.pp
5) Set setenforce 1

apache with ssl (do you use Let's Encrypt too?)
/etc/httpd/conf.d/ssl.conf, before SSL Protocol Adjustments:
   proxypreservehost on
    proxyrequests off
    proxypass /admin/ http://localhost:8080/admin/
    proxypassreverse /admin/ http://localhost:8080/admin/

The same patch will work in /etc/httpd/conf/httpd.conf. If you redirect to your ssl server, why put in there too?

Don't skip the unbound package part. If you do you're doing it wrong.
Everything working right? Delete your snapshot if you made one.
