### ISSUE TITLE
Three issues regarding installation (faulty 01-pihole.conf, missing dependencies, slow)

### ISSUE THREAD

**Issue by alice-margatroid** [pi-hole/pi-hole#567]
1) Still only workarounds for 16.04 LTS systems
**Fix:** had to run
` sudo apt-get install php-cgi php apache2`

2) DNS requests from clients in LAN are ignored.
**Fix:**
` sudo nano /etc/dnsmasq.d/01-pihole.conf`
change
` listen-address=127.0.0.1`
to
` listen-address=127.0.0.1, 10.0.0.9`
latter being the PC I'm currently on

3) Sites load slower if tracking scripts and ad images are loaded before actual content.
Possible fix `placeholder images / scripts` ??

It should be possible for skilled developers who made such a nice piece of software to at least address the first two issues with ease. On 16.04 servers the php5 dependencies will return an error. It should be possible to detect this error and automatically use the working php7 packages instead automatically.

The 2nd issue made the whole raspi ignore all DNS requests coming from my desktop. Durin installation I was never prompted that I had to manually add my clients. Colour me surprised I had to figure this out myself.

Kind greetings

**Comment by dschaper** [comment]
Thanks for the reports Alice, we may be able to add more case checking with a pull to the `/etc/lsb-release` to grab the release version. We'll need to take a look at that. (There is very active development going on with the web interface that may make this redundant, as some structure changes might let us drop some of those dependencies.)

Second point, need to really dig on that one, there shouldn't be a need to add another listen address, as the localhost notation should cause dnsmasq to listen on all available interfaces and not block.

Also need to look at site speeds and see what is causing the slow load, if it's a timeout issue, and rendering engine issue or some other cause somewhere in the chain. 

Lastly, Thanks!! for the compliment of calling us skilled developers. In all honesty, we are all just volunteers on this project, we all have other day jobs that pull us in different directions, (and to different continents, we are a global project) so we'll get to things when and as fast as we can. We do need the feedback from our users to help us out, but if things take a bit of time to implement, it's not because we're ignoring you, it's because we're IRL. (I personally just finished a 52 hour period with 4 hours of sleep from running from client to client putting out fires!)

**Comment by alice-margatroid** [comment]
Thank you for the fast reply, I am using https://wiki.ubuntu.com/ARM/RaspberryPi `ubuntu-16.04-preinstalled-server-armhf+raspi2.img.xz` as release for my raspi if it helps for testing.

Just adding about the third point: I noticed this, due to firefox showing this url preview in the bottom during page loads as well. I can see tracking networks like NuggAd slow page loading until they finally timeout. If I turn uBlock on again it loads fast. So the way pi-hole and uBlock handle blocked sites influences speed. I had hoped to drop certain addons in my browser thanks to pi-hole, but don't worry I still love it! At least I can block now ads in apps on my unrooted smartphone :)

**Comment by dschaper** [comment]
uBlock has the benefit of being an in-browser extension, so it can actually manipulate the html and change how the page is rendered. We don't have that ability, and to replicate that would require us to set up a proxy to grab the traffic and try to adjust the returns. Honestly the best solution for you may turn out to be using both the Pi-Hole and uBO together. We designed Pi-Hole to be able to work with any other ad blocking method.

And thanks for the pointer to Xenial on the 2, I didn't know there was an image out yet for that. (I'll see if I can get a chance to play with it at some time, just to see how the performance is but on my servers I've noticed that 16.04 has a really small memory footprint on the 32bit flavor. And the LTS 16.04.1 should be dropping next month or so, so you'll see a lot better support when all the 14.06 LTS images finally gain the ability to in-place upgrade to 16.04)

And the smartphone is the key feature we like :) 

Thanks for sharing your findings with us, it really does help us grow the project!
