### ISSUE TITLE
'playlists': collection of 'adlists' = 'groups'?

### ISSUE THREAD

**Issue by slynobody** [pi-hole/pi-hole#5691]
having problems to post on the pihole forum: is there a feature to bundle a selection of Adlists in form of a 'playlist' / collection concerning a specific topic?

could this be done through 'groups'?  and if yes: are this groups somehow export- / shareable – or is it even possible to import  groups and corresponding adlists from other people?

examples: f.e. OI-collection=collection of adlists for outsider intrusion, SM-collection: adlists for dealing with social media, PR-collection: adlists for dealing with porn-sites; PL: adlists for dealing with political-disinformation etc.)

**Comment by rdwebdesign** [comment]
> is there a feature to bundle a selection of Adlists in form of a 'playlist' / collection concerning a specific topic?

No.
You can add Adlists, but there is no "lists of adlists".

**Comment by slynobody** [comment]
thank you for your information. do you plan to implement such a feature 'lists of adlists' in the future? (could help usability-wise for beginners as well as for offering 'defaults' on specific topics (like f.e. in ublock))

**Comment by rdwebdesign** [comment]
Currently there are no plans to implement this kind of feature.

---

We receive a high number of requests, but as a free open-source project run by volunteers we have very limited resources.

Since you are suggesting a new feature, please we ask that you open your **Feature Requests** at our [Discourse Forum](https://discourse.pi-hole.net/c/feature-requests/8).

Thank you for your understanding.


**Pi-hole links:**
- Discourse Forum: https://discourse.pi-hole.net/
- Documentation: https://docs.pi-hole.net/
- Feature Requests: https://discourse.pi-hole.net/c/feature-requests/8
