### ISSUE TITLE
Do not identify OS by installed commands

### ISSUE THREAD

**Issue by diginc** [pi-hole/pi-hole#574]
##### Expected Behaviour:
If I installed RPM in debian, pi-hole's installer works.

##### Actual Behaviour:
I'm pretty sure I'd try to use the redhat os family installer because of the current install logic looking for `rpm` command.

##### Steps to reproduce this issue:
Install RPM on a debian based OS, run the install

I've confirmed in a docker:
```
docker run -it debian:latest bash
apt-get update
apt-get install -y rpm curl
command -v rpm && curl -L https://install.pi-hole.net | bash
```

Original comment in #573

Not 100% related to this but I was looking at the code around the changeset and saw you're using `if [ -x "$(command -v rpm)" ];then` followed by an `else if` for the same command against `apt-get`.

I'd say it's much more likely for RPM to be installed on a debian system for packaging RPMs or just rpm2cpio than apt-get to be installed on a redhat system leading to a potential bug.

I'd reverse the order of that `if` or just bite the bullet and start using some config management tools to help keep things more OS agnostic: https://docs.puppet.com/facter/3.0/core_facts.html#osfamily or https://docs.puppet.com/facter/3.0/core_facts.html#os

facter has a CLI interface that can be queried w/o using any puppet.

edit: salt core grains also has a decent python function to do a similar crazy check of many locations to be pretty sure what OS you're on https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1125

**Comment by dschaper** [comment]
I agree that it is more likely for a Debian system to have RHEL package management tools on it than for a RHEL box to have `apt` on it. I don't see it as being a case we'd run into with Pi-Hole also being installed on that environment, but if it can be alleviated with a flip of the logic then six of one. 

Now getting into config management may be something that the Python rewrite will help with, or maybe we do need to look to puppet/ansible/chef to help spinup. Of course all PR's are welcome and will be discussed and reviewed. Will check out `facter` to see what it would add to the current project or if that is a 3.0 type feature.

**Comment by bcambl** [comment]
I think it would be a good idea to flip the check for the time being.

**Comment by diginc** [comment]
Does this work in your systems @bcambl ?  my fake docker systems seem to like it: 

```
if [ -x "$(command -v rpm)" ] && [  -x "$(command -v dnf)" -o  -x "$(command -v yum)" ] ;then echo HIT ; fi
```

**Comment by diginc** [comment]
/etc/redhat-release existing more trustworthy than the `command -v rpm` too.

I only bring up configuration management because that is all this is re-inventing :)

Not that it isn't fun to do.  That is why there are so many CM solutions.

**Comment by dschaper** [comment]
Is `dnf` in epel-release for CentOS 6 yet or is it still build from source?

The config management really has only come up lately. When I first started volunteering with Jacob we only really were on Raspbian. It's only recently that things have taken off and other distros have become mainline and not edge cases. That being said, we're kind of nearing the end of `bash` usefulness and that's why were undergoing the rewrite from scratch. There may be some patch Python code to tide us over if it's truly necessary.  The level of popularity for the Pi-Hole is something I never thought I'd see. And the package is still done by all volunteers on spare time.

Documentation, now that's not fun to do, lol...

**Comment by bcambl** [comment]
```
[bcambl@redacted ~]$ if [ -x "$(command -v rpm)" ] && [  -x "$(command -v dnf)" -o  -x "$(command -v yum)" ] ;then echo HIT ; fi
HIT
[bcambl@redacted ~]$
```

The reason I chose to check the package manager over the release file was to keep it simple.
The release file is different between RHEL/CentOS/Fedora and we do not care about what specific version. 
Logic:
If it has `rpm` => good chance it is Fedora Family
Then check for `dnf` because it is the future.
else it is likely older and uses `yum`.

If we just check for apt-get first.. this edge case would be very small until a better installer is created.

**Comment by dschaper** [comment]
Safe to say that 22/6 is the earliest releases officially supported? I don't know of anything earlier than 22 on the Pi, but I'm not sure about CentOS. Off the Pi, is there a large base of installs that are earlier than 22/6? 

And I think what we can hope for is to minimize exposure to edge cases for now, and look to CM for the future since we can build that in from the start. May look to two different flavors, one for the Home User/Enthusiast on the Pi and another for a more Enterprise oriented user.

**Comment by bcambl** [comment]
[Fedora ARM](https://fedoraproject.org/wiki/Architectures/ARM) and [pidora](http://pidora.ca/) are the two most likely for ARM deployments.
CentOS 6 & 7 would mostly be server/virtual deployments...
Fedora 22 will be unsupported shortly so 23/24 is the current target for support.

**Comment by dschaper** [comment]
TY, just checked the team Slack and looks like Slackbot and I are the only two up right now. I'm sure the rest of the team will have thoughts and comments to add. (I'm currently sporting the Cone of Shame so I'm declining to do any merging for a bit, rough release day today.)

**Comment by dschaper** [comment]
Issue resolved and fixed in released code.
