### ISSUE TITLE
Pihole times out when doing a query all. Also stops all DNS queries while query all is stuck running.

### ISSUE THREAD

**Issue by gihub24** [pi-hole/pi-hole#5761]
Pihole times out when doing a query all.
Also **_stops all DNS queries_** while 'query all' is stuck running.
This has been a bug for a few month now.

http://pi.hole/admin/queries.php?all

### Versions

- Pi-hole:  5.18.3
- AdminLTE: Not shown with pihole -v
- Web version 5.21
- FTL:  4.25.2

### Platform
- Platform:  Raspberry Pi

### Expected behavior
Show the log within a minute

### Actual behavior / bug
Time out error, stops all DNS queries while query all is frozen

### Steps to reproduce

http://pi.hole/admin/queries.php?all

**Comment by rdwebdesign** [comment]
Please generate a debug log:

**Using the command line:**
- use `pihole -d` command.
- when asked to upload the log, answer <kbd>Y</kbd>.
- copy only the token and paste here.

**Using the web interface:**
- click on _**Tools > Generate Debug Log**_ menu.
- then mark the second checkbox to upload the log and click on the big button.
- when finished, copy only the token and paste here.

**Comment by rdwebdesign** [comment]
The debug log doesn't show information about the web interface or PHP errors because you are using `nginx` as the web server _(the log is not capable of showing web server logs when the installation is customized)_.

You need to look into nginx logs to find out what is the issue.

I can only guess what is happening, but this is probably an issue with PHP memory limit.
If you have a large number of queries, PHP will need more memory (and possibly more time) to generate the page.
If that's the issue, try to increase the memory limit in `php.ini`.

---

**Note:**

> AdminLTE: Not shown with pihole -v

Actually it is showing as: `Web version 5.21`. 
The web interface repository was renamed (from `adminlte` to `web`) almost a year ago: https://github.com/pi-hole/web/pull/2736.

**Comment by gihub24** [comment]
@rdwebdesign 
_php.ini_ Config was already set to limitless
memory_limit=-1

No info in nginx logs

This seems to be related:
High disk I/O prevents successful DNS resolution https://github.com/pi-hole/pi-hole/issues/5635
