### ISSUE TITLE
Blacklisting a url causes all blacklisted urls to be re-added to the gravity.list resulting in duplicates

### ISSUE THREAD

**Issue by roscom** [pi-hole/pi-hole#583]
##### Expected Behaviour:

Add one url to the blacklist, Domains Being Blocked should increment by 1
##### Actual Behaviour:

The existing entries in blacklist.txt are re-added to gravity.list together with the url to be black listed.
Domains Being Blocked increments by the number of entries in blacklist.txt
##### Steps to reproduce this issue:

Add a url to be blacklisted.
Observe the Domains Being Blocked increment by the number in blacklist.txt
##

**Comment by PromoFaux** [comment]
[Confirmed](https://youtu.be/zjP9isDbUKM)

I expect this is to do with the way white and blacklisting are handled.  Currently `pihole -b` will add the custom blacklisted domain to `gravity.list` I'm guessing the counting calculation is taking both the count of `gravity.list` and `blacklist.txt` into consideration. 

We might be able to get around this by having an additinal `blacklist.list` host file, so that `gravity.list` is not affected.

I've never been too pleased with the way I implemented the white/blacklists.. so it may be time for an overhaul! Although we are currently undergoing a rewrite in python.

Also interesting to note that the parser does not like domains with capital letters in them (hence the first failure in my video)

**Comment by PromoFaux** [comment]
Fixed with rework of blacklisting in 2.95
