### ISSUE TITLE
Issues in blacklist from sysctl.org

### ISSUE THREAD

**Issue by aureq** [pi-hole/pi-hole#632]
##### Expected Behaviour:
I should be able to access http://download.cdn.mozilla.net/pub/firefox/releases/48.0.1/update/win32/en-US/firefox-47.0.1-48.0.1.partial.mar

##### Actual Behaviour:
I'm being sent to my local pi-hole server

##### Steps to reproduce this issue:
Access the site through with pi-hole active

##### Notes ######
First, download.cdn.mozilla.net:
```
# dig @127.0.0.1 download.cdn.mozilla.net

[...]

;; ANSWER SECTION:
download.cdn.mozilla.net. 273   IN      CNAME   2-01-2967-001e.cdx.cedexis.net.
2-01-2967-001e.cdx.cedexis.net. 20 IN   CNAME   wildcard.cdn.mozilla.net.edgesuite.net.
wildcard.cdn.mozilla.net.edgesuite.net. 20870 IN CNAME a1284.g.akamai.net.
a1284.g.akamai.net.     60      IN      A       192.168.2.254
```
Everything resolves nicely up until `a1284.g.akamai.net`. After looking into the enabled lists, I found that `http://sysctl.org/cameleon/hosts` is blocking a whole bunch of Akamai CNAMES rather than blocking the real domain. This is causing issues for many sites that are using Akamai but not showing any ads through this CDN provider. In addition, this gives no visibility on which site is actually blocked.

I've contacted the list authors to determine if this is an intended behavior or a mistake. If intended, the pi-hole community should decide whether or not it's wise to enabe sysctl.org list by default.

Disabling the list fixes the issue.

**Comment by PromoFaux** [comment]
If you were to leave the list enabled, and just whitelist `a1284.g.akamai.net` (`pihole -w a1284.g.akamai.net`), does that fix the issue?

**Comment by aureq** [comment]
@PromoFaux Yes, that would work. However, there are multiple issues here

- Blocking a CDN provider (through CNAME resolution) may not be a great idea since there's no visibility on the origin.
- There's 193 entries for akamai.net alone
- Finding each occurrence (false positive) isn't that easy

**Comment by PromoFaux** [comment]
I see what you're saying, however I'd be hesitant to drop it as a default list. 

My reason being is that this list comprises of 21197 domains, and while there may be some false positives in there, it's probably better to manage those by whitelisting as and when problems arise.

e.g It also has 267 entries for various subdomains hosted on `popupad.net`. The only other list to mention `popupad.net` is the hosts-file list. If you were to remove the sysctl list, a website would still be able to load `ads1.popupad.net` because only `popupad.net` would be blocked (no wildcarding)

That said, the lists can be turned on and off by (creating and) editing `adlists.list`, so if any user does not want a particular list, then it can be easily disabled. (Note to @pi-hole/dashboard perhaps we can add something to the web-frontend to better manage this)

Side note, I wonder if `a1284.g.akamai.net` USED to host malware/trackers/ads, and has since been replaced?

**Comment by aureq** [comment]
So, I heard back from Philip (the list author) and he said the following (translated from French)

> Hi,
> Listing akamai doesn't seem to be a good idea.
>
> This list is an actual aggregate from the following list  `http://www.mvps.org/winhelp2002/hosts.txt`
>
> I added akamai to the exclusion list... I'll run the update script and the list should be updated in a few days.
>
> Best regards.

The list referred above by Philip is described here http://winhelp2002.mvps.org/hosts.htm

@PromoFaux I understand the benefits of this list, but there's a question where the pi-hole community should assess or not the potential risks. To me, not having Firefox updates in time is far more nefarious than having ads. The question then is to understand if the community is ready and willing to implement its own white list (ie: CDN CNAME records like akamai and cloudfront) to mitigate these risks?

**Comment by dschaper** [comment]
When a major issue such as Mahakala attempting to blacklist and entire TLD, then we have something that we need to look at. In that case we decided that the history of that particular list and its proclivity for overzealous blacklisting did indeed dictate removal from our default list. So far from what I understand, and please correct me if I am misunderstanding the situation, but one subdomain was inadvertently added via a CNAME record for a CDN. This does not warrant removal of the entire mvps.org list from the default configuration. If it happens again, or on a wider scale such that the entire CDN is blocked, we'll address that issue.

We provide you with the tools to configure your blocking how you would like. You can update the configuration to remove that list if you so choose, we provide the instructions for that. And thanks to your raising this as an issue, other users are also now aware of the situation and can adapt their installations to how they would like to solve the issue. We are very reticent to step in and alter configurations for users and remove that freeedom from them.

As for the issue at hand, with round robin DNS and a CDN it is very possible that the node has been removed from rotation already and that CNAME updated so that Mozilla and Akamai have solved the issue. That lists is not unique to Pi-hole and is used in a large number of blocking schemes and programs, I would be pretty confident in saying that they are aware of the blocklist and have taken their own steps to mitigate.

**Comment by aureq** [comment]
@dschaper Thanks for your answer and happy to read that you have a contingency plan. Cheers.
