### ISSUE TITLE
Feature Request: Ability to blacklist ads that got missed from browser

### ISSUE THREAD

**Issue by markdreyer** [pi-hole/pi-hole#633]
That would be nice to have a browser extension to report back ads that the pihole didn't catch. I love pihole and it catches most ads, but it would be nice to right click and block ads that come through. This is similar to the right click, block functionality of Ad Block Plus.
##

**Comment by dschaper** [comment]
That's a great idea and one that we've bounced around before. The issue that we come back to is how to handle the authorization of the request. For a family install, should one of the non-privileged users be able to modify the black and whitelist that everyone else uses? Or should only the people that are "authorized" be able to add and remove from the lists? In a single user environment, this isn't an issue, but when you have multiple users, then what do you think would be the best approach to the solution? 

Since this is a feature request, no need to go to the code level, just sharing some ideas of what and how is great!

**Comment by diginc** [comment]
When I was thinking about a browser extension (for python rewrite / api) I imagined the user could view some read only information (like recent blocks for their IP) through it and request access to edit the block/allow list, which an authorized admin would have to approve before the user could start making edits through the browser.  The request would show up in a queue on the admin web interface with machine name, IP, browser, etc. and an approve/deny button.

**Comment by dschaper** [comment]
I like that, was thinking of something that may allow for individual blocklists, but then that gets into the situation of determining who is requesting the changes, and if IP is specific enough, or stable enough to base off of. (This may be getting to something that goes beyond the typical home user.) Might be something that works with the database approach with Python, and something that can be handled with the API?

**Comment by jacobsalmela** [comment]
@markdreyer does #1057 work for this issue?

**Comment by jacobsalmela** [comment]
Request has gone stale.  Moving to discourse.pi-hole.net to make the feature votable.  It may be partially implemented with #1057.

https://discourse.pi-hole.net/t/ability-to-blacklist-ads-that-got-missed-from-browser/3144
