### ISSUE TITLE
Blacklisted Domains getting through

### ISSUE THREAD

**Issue by C4Wiz** [pi-hole/pi-hole#662]
##### Expected Behaviour:
blacklisted domain should redirect to blocked page

##### Actual Behaviour:
domain is displayed

##### Steps to reproduce this issue:
add adrunnr.com to blacklist, browse to http://adrunnr.com/?placement=401444&redirect, this page is displayed:
![screen shot 2016-09-05 at 7 20 12 am](https://cloud.githubusercontent.com/assets/3883521/18249065/4b16d1ba-7339-11e6-965f-c50b78200b29.png)

**Comment by Mcat12** [comment]
Remove `/var/www/html/index.lighttpd.html`. That's just the default placeholder page. If you try going to http://adrunner.com/test/123 for example, it should redirect to the block page. The reason the other one went to the placeholder is because everything after the `?` in the URL isn't used when finding the page (they're GET arguments).

**Comment by PromoFaux** [comment]
Just tested this myself, if you edit `/var/www/html/index.lighttpd.html` to only contain the word "test" then try that link again, you'll get the word "test" appear in your browser.

You can also verify this by trying to ping `adrunner.com` from your client device. You should get the IP of your pi-hole back.

**Comment by PromoFaux** [comment]
Interestingly, @Mcat12 http://adrunner.com/test/123 redirects to http://mycomputer.com/404.html

**Comment by C4Wiz** [comment]
the file was named index.lighttpd.orig, removed that now all is good... thank you
