### ISSUE TITLE
Whitelist Acceptable Ads

### ISSUE THREAD

**Issue by gabrielsadaka** [pi-hole/pi-hole#673]
I am a big fan of the Adblock Plus acceptable ads feature which allows certain ad networks which display unobtrusive ads to be whitelisted by default via this list here: https://easylist-downloads.adblockplus.org/exceptionrules.txt

However that follows the Adblock Plus format which is not supported in pi-hole. Is there a standard way of translating that into a format that pi-hole understands or even better could this be considered as a possible feature in the future?

**Comment by PromoFaux** [comment]
Hi there,

Check this [wiki entry](https://github.com/pi-hole/pi-hole/wiki/Customising-sources-for-ad-lists#how-to-parse-a-list-to-get-just-the-domain) for details on how to parse the list...

However, looking at that list, I'm not sure it's wise to do this automatically. It looks like the way the list is set up is to havea list of websites that are whitelisted for a particular ad domain. I.E Taboola Ads (See [Forum post about that here](https://adblockplus.org/forum/viewtopic.php?f=12&t=25991)). I'd even go as far as to question if that was indeed an acceptable ad... see the following two examples:

![image](https://cloud.githubusercontent.com/assets/1998970/18433955/4ae9b06e-78e2-11e6-83b4-7f02d8b3cd5a.png)

![image](https://cloud.githubusercontent.com/assets/1998970/18434037/bb05e250-78e2-11e6-9749-1050b0c6a0e2.png)

Because of the way Pi-Hole works, it's impossible to whitelist certain ads for certain sites, as we're blocking at a DNS level and have no idea of the originating site  that requested the DNS. I think it would be more effort than it's worth to try and auto parse this to get any kind of decent list of sites. Best bet is going to be to go through it manually, and decide whether or not you think that the ad domains they have chosen to be acceptable are in fact acceptable

**Comment by gabrielsadaka** [comment]
Thank you for your quick reply, I agree with your suggestions. I will just go through the list and pull out the particular domains I want to white-list.
