### ISSUE TITLE
pihole -up = command not found

### ISSUE THREAD

**Issue by TylonHH** [pi-hole/pi-hole#680]
##### Expected Behaviour:
Update without error

##### Actual Behaviour:
Update with error

##### Steps to reproduce this issue:
I run `pihole -up` and got this

>───────────────────────────────────────
> DietPi     | 23:13 | Mon 12/09/16
> ───────────────────────────────────────
> V130       | RPi 3 Model B (armv7l)
> ───────────────────────────────────────
> IP Address | 192.168.178.22
> ───────────────────────────────────────
>
>root@DietPi:~# pihole -up
>::: Fetching latest changes from Github...
>/usr/local/bin/pihole: line 58: git: command not found
>/usr/local/bin/pihole: line 59: /etc/.pihole/automated install/basic-install.sh: No such file or directory
>root@DietPi:~#

How can I solve this?

**Comment by Mcat12** [comment]
Please run `pihole -d` and post the output of `cat /etc/pihole/install.log`, thanks.

**Comment by TylonHH** [comment]
I only got
>No such file or directory
with both commands.
>/usr/local/bin/pihole: line 41: /opt/pihole/piholeDebug.sh: No such file or directory
I installed pihole via dietpi two days ago, and it's still running fine.

Btw `pihole -g` is working fine.

**Comment by Mcat12** [comment]
Ah, so you're using the DietPi version. That one's forked off of ours, and so it is supported by @Fourdee (maintainer of DietPi). I have a feeling that it wasn't modified to accommodate the changes between this version and his custom version.

**Comment by PromoFaux** [comment]
Yeah, last I checked it was on `2.8.x`, but fourdee can probably confirm that!

**Comment by TylonHH** [comment]
That is an different version? Sorry didn't knew that.
Maybe I'll set up new with rasbian and `bash`

**Comment by PromoFaux** [comment]
Yeah, I'm not sure how well it's advertised, but it has optimisations to work better with diet-pi.

You can also remove the diet pi version and reinstall the official version by running `curl -L https://install.pi-hole.net | bash` if you like, it should still work!

**Comment by TylonHH** [comment]
Done.

Quick question: where can I find the static IPv6 address (which I choose in setup)?

**Comment by PromoFaux** [comment]
It should be stored in `/etc/pihole/setupVars.conf`

**Comment by Fourdee** [comment]
#### The main differences with the DietPi fork of PiHole are:
- Not endorsed by PiHole.
- Because its a modified fork, supported by DietPi, not Pihole.
- Full non-interactive installation (minus the Static IP prompt, when PiHole is selected)
- Current version is ```2.9```
- Compatible with user web server choice. Users can choose Lighttpd/Nginx/Apache2: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L1784-L1828
- PiHole dash accessable via http://ip/pihole
- Not compatible with the official PiHole update system. We plan to roll this out via ```dietpi-update``` for existing installations to automatically update the forked PiHole.
- Smaller installation. We don't need git packages, and, we don't pull in all the PiHole scripts: https://github.com/Fourdee/DietPi/blob/testing/dietpi/dietpi-software#L3087-L3179
- ```https://install.pi-hole.net | bash``` Should work on a fresh DietPi installation. May have issues if user has Apache2/Nginx installed, not sure if the PiHole install script checks for this currently?
- ```/var/www/index.html``` contains "blocked by PiHole", rather than empty page.
- Allows for other users of the webserver (eg: Owncloud + PiHole installations). Its been a while since I last checked the official PiHole installation, so not sure if this has changed?
- Disabled update notifications in PiHole dashboard (not compatible).

PiHole has changed alot since I decided to do the fork. They have so many active developers (i'am jealous), fast progress :+1:.
So i'll take a step back next time we update the PiHole fork and rethink our DietPi installation. Maybe we can make it more compatible with the "official" installation.

**Comment by Mcat12** [comment]
Thanks!

**Comment by jacobsalmela** [comment]
Thank you!

**Comment by TylonHH** [comment]
Thanks for clarifying.
