### ISSUE TITLE
Backup old conf files before overwriting during upgrade

### ISSUE THREAD

**Issue by drwggm** [pi-hole/pi-hole#689]
I have update pi-hole a few times now, and every time any modifications to some of the related conf files (E.g., lighttpd) get overwritten. Supporting modified configurations can be tricky, but the update software should backup then overwrite or the user be given an option to. 
##### Expected

To backup or integrate changes to conf files an update overwrites. 
##### Actual Behaviour:

Simply overwrites the altered conf file. 
##### Steps to reproduce this issue:

Run' pihole -up 'after changing several of the related config files.  For example, I password protect the /admin dir in lighttpd.conf
##

**Comment by PromoFaux** [comment]
Hi there @drwggm, thanks for reporting.

We're actually going to look into providing password protection on the site as default, though we've all been quite busy outside of pi-hole recently (which is fun when it comes to catching up on issues...)

In an ideal world, the user should not need to touch any of the default configuration files, and I think the `lighttpd.conf` is the only case where you would need to, especially as we've not implemented a native solution yet. 

Though until we do implement it, and now that we've implemented a more graceful update method, perhaps we can try and be a bit more graceful with `lighttpd.conf`

**Comment by linuzer** [comment]
I also need this very desperately! 
To give you a reason why this is important: In a real world the PiHole almost never is the only service on a Raspi or BananaPi. In my case there runs also an owncloud-instance on the same lighttpd. Therefore I have to modify lighttpd.conf in order to exclude the owncloud-webpage from pihole - and I have to do this after every single update... Very annoying!

**Comment by stonedbovines** [comment]
I do something similar regarding password protection, but make use of the include_shell option to add the contents of a separate file. It still (currently) requires adjusting the lighttpd.conf file to add two lines, but it means that the actual authorisation details never get touched.

The auth details are in a file 'auth.conf' in the same directory as lighttd.conf and then the two lines that need adding to lighttp.conf (which could be made part of the template, as they don't affect anyone who doesn't want password protection) are:
1) add the `"mod_auth",` entry to the server.modules section
2) add a last line `include_shell "cat auth.conf 2>/dev/null"`

It uses include_shell, rather than just an include, so that it can deal with the non-existence of an auth.conf file.

**Comment by stonedbovines** [comment]
In fact, what I have just done is alter it to use a 'double redirection' in case I need to add multiple additional sections.

In lighttpd.conf the final line now reads
`include_shell "cat external.conf 2>/dev/null"`
and the new external.conf file contains the includes for everything else, eg
`include_shell "cat auth.conf 2>/dev/null"`

At the moment, I only require that one line but, now, I can add any additional requirements into external.conf and not have to change anything else about my upgrade process. Adding external conf (and mod_auth!) to the template(s) means pi-hole never needs to care about what else people are using lighttpd for.

**Comment by PromoFaux** [comment]
This. I like this.

So really, all we need to do is add `include_shell "cat external.conf 2>/dev/null"` to the end of `lighttpd.conf`, and then be good to go?

**Comment by stonedbovines** [comment]
Plus the mod_auth line, but yes

**Comment by PromoFaux** [comment]
Ah, yeah. Would you be able to make a Pull Request to the `development` branch to that effect, please?

**Comment by linuzer** [comment]
I cannot see how this helps to change the original line
`$HTTP["url"] =~ "^(?!/admin)/.*" {`
into the new line that I need:
`$HTTP["url"] !~ "^/(admin|owncloud)/.*" {`

**Comment by stonedbovines** [comment]
It doesn't attempt to do that, mostly because no-one can know what other uses people will be making of lighttpd.

What you _can_ do though is use a command in external.conf along the lines of (not real code)
`include_shell "change OLDLINE NEWLINE"` where 'change' is whatever your favourite tool is - perl, sed, awk, ...

**Comment by linuzer** [comment]
Sounds complicated to me, but probably because I have no idea how to do this...

But it would be nice if the pihole's lighttpd.conf could either be designed to co-exist without problem besides other websites, or at least a sample configuration shows how to include other websites like owncloud.

Either way, an update of pihole should not affect other websites on this lighttpd.

**Comment by linuzer** [comment]
Maybe the pihole could use a second IP-Adress on the network-interface which is bound exclusively to a "pihole"-virtual host on lighttpd. This way all traffic on that vhost could easily get dismissed, whereas all other websites sitting on the "normal" lighttpd are not affected.

That's just a raw idea. If this is possible at all, pihole should configure this during installation.

**Comment by PromoFaux** [comment]
The thing is, even using a second/virtual IP address, we still need to alter lighttpd.conf`....!

The great thing about @stonebovines suggestion is that it's completely agnostic. Any alterations the user wants to make to `lighttpd.conf` can be done in `external.conf` by calling a tool to do a find and replace. on the bits you need to change. That's how we get it to coexist.

**Comment by zandhaas** [comment]
Is there some kind of progress on this issue?
I for instance use a different server  port because the default 80 is already in use. And yes after every update I have to edit the lighttpd.conf file again to be able to access the PI-Hole web page.

**Comment by gstrauss** [comment]
FYI: Something which might make whatever solution is chosen a bit easier to implement:
lighttpd 1.4.40 and later support globbing include files, e.g. `include "conf.d/*.conf"`
https://redmine.lighttpd.net/issues/1221
(recommended lighttpd version is latest release: lighttpd 1.4.44)

**Comment by jacobsalmela** [comment]
@drwggm are you asking about _just_ the `lighttpd.conf` config file or others as well?  If it's just the `lighttpd` one, I think this will suffice: https://github.com/pi-hole/pi-hole/issues/704

If the scope is further, I'd like to move this over to discourse.pi-hole.net to make it votable
