### ISSUE TITLE
Pi-Hole not blocking ads on Android

### ISSUE THREAD

**Issue by cdb8457** [pi-hole/pi-hole#694]
##### Expected Behaviour:
Block Ads on Android

##### Actual Behaviour:

Ads not Blocked

##### Steps to reproduce this issue:

Did a clean wipe and new image and new install of Pi-hole. Not blocking ads on android.

**Comment by DonLexos** [comment]
I've had that problem once and turned out I was not connected to my WiFi (but on a 4G connection) and then ads are (of course) not blocked.

**Comment by TylonHH** [comment]
Please check with [Network Info UI](https://play.google.com/store/apps/details?id=aws.apps.networkInfoIi) under WiFi your DNS server. Is it your PiHole?

**Comment by cdb8457** [comment]
oh, ic, Well The app tell em its on 10.0.0.1 which is not the DNS I have my pi set to. How do I get the DNS set to my one the pi is using?

**Comment by TylonHH** [comment]
Client: Go to setting - WiFi - choose your WiFi - change  network - more option.
There you can setup up a static DNS.

What router are you using? It makes more sense to set the new DNS in your hole network.

**Comment by cdb8457** [comment]
R6300v2. I did set it to static, I woner why its not setting my mobile devices to that? Well I tried static on my phone, but the internet wont work.

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/18603685/b2b07fae-7c28-11e6-975f-3470ba75c9de.png)

**Comment by PromoFaux** [comment]
@cdb8457 [take a look at this guide to see if there is anything you missed](http://setuprouter.com/router/netgear/r6300v2/dns.htm)

**Comment by PromoFaux** [comment]
Although, what you have in that screenshot looks OK.

Could you please run `pihole -d` in an ssh session  on your pi, so we can take a look at your setup?

**Comment by TylonHH** [comment]
Just my two cents.
The screenshot is wrong. You don't have to set the IP in the DNS of your internet, rather in your network DNS. That are two different things

**Comment by TylonHH** [comment]
See also https://github.com/pi-hole/pi-hole/issues/149

**Comment by cdb8457** [comment]
http://termbin.com/d1el

**Comment by cdb8457** [comment]
I will try and set the DNS outside the IP range and see what happens.

**Comment by TylonHH** [comment]
I would suggest to the leave the PiHole in DHCP mode. And be sure that your netgear will give your Pi every time the same IP.

**Comment by cdb8457** [comment]
is there a guide on that? do i need to do a fresh install?

**Comment by TylonHH** [comment]
I guess you can set it somewhere in a file, but a dev has to tell you.
I red that netgear don't support an infernal DNS for local network.
I guess you have to setup every client ?!?!?

**Comment by Mcat12** [comment]
Your debug log shows that the ip address of the Pi-hole is 10.0.0.65, although the dns results return 10.0.0.2. Which IP address is correct? If it's the 10.0.0.2, then try setting that in the DNS settings on your router. Also, some routers hand out themselves as the DNS resolver, but internally forward to the ones you set. If you go to http://pi.hole/admin on your Android device, it will come up with the Pi-hole web interface if the DNS is correctly set. Also, on Android you may need to reboot the device (or wait for a long time) before the DNS cache is cleared. So if you go to pi.hole and it doesn't work, it will cache that result and still won't work until it clears it from cache.

**Comment by TylonHH** [comment]
If you're using chrome open 'chrome://net-internals/#dns' and clear the cache. You also have to reconnect to your WiFi to receive the new DNS.
I always check if this blocked 🚫 site is really blocked: https://a-ads.com

**Comment by Mcat12** [comment]
As an alternative to reconnecting to the network, you can run `ipconfig \flushdns` in the command prompt.

**Comment by TylonHH** [comment]
On Android?

**Comment by cdb8457** [comment]
I will check with this, when I get home.

**Comment by Mcat12** [comment]
On Windows. I assumed because of the chrome url that it wasn't Android, but checking now, it seems that Android does have that feature!

**Comment by cdb8457** [comment]
I did read somewhere I need to set the install at wan instead of ethernet. My question is the pi to directly connected to the router, should i have done the wan instead of the ethernet option in the UI?

**Comment by PromoFaux** [comment]
I'm not sure what's happened with your install... As @Mcat12 mentioned above, the IP address of pi-hole on your network is reported as `10.0.0.65`, but `dnsmasq` seems to think it's `10.0.0.2`

Did you change the IP address of the raspberry pi after you installed it?

**Comment by cdb8457** [comment]
No, when the ui came up for the the option to set the DNS server I changed it to 10.0.0.65

The UI wanted to give it 10.0.0.2.

Now, crazy question. I just noticed the pi is using wifi instead of using the Ethernet. It is plug into the router also. Would that mess with the actions of pi-hole.

**Comment by PromoFaux** [comment]
OK, I think there may be some confusion in play here... and your best bet is _probably_ going to be to start with a fresh SD card!

First off, decide if you want to connect with WIFI or with Ethernet. It's not going to make too much difference either way, but wired is always better if you're able to!

On the next screen, you are asked to select the protocols you wish to block over. By default this is just IPv4, but if your router is capable of IPv6, or even if you're just not sure, select IPv6 by arrowing down to it and pressing the space bar, before hitting enter to continue to the next screen.

The next screen is important. The installer will detect the current IP address of the Raspberry Pi (if you have not already set that, then it will be the one handed to it from your router) If you are happy with that IP address, go ahead and press yes, otherwise if you really want a different IP, choose no. **(*)**

_If you've pressed no, you have an oppurtunity to set the desired IP of your device. If you wish it to be 10.0.0.65, then this is where you add it. Don't forget the /24 at the end! The next screen will ask you for the default gateway, which is your router's IP. Confirm that the details are correct and hit enter to continue_

**(*. Actually a better way to do this would probably be to assign the IP to your raspberry pi through the router with a DHCP reservation, that way you can be sure that no other device will have that IP. Once you've done that, run the installer and choose yes at the IP address prompt.)**

The next screen asks you to select an _Upstream_ DNS provider. Choose one of the options, or if you have another you wish to use, enter it into Custom. DO NOT PUT YOUR PI's IP IN CUSTOM :)

And that's it for the install. Now you just need to make sure you set the DNS provider correctly in your router. You can follow the [guide I posted above](http://setuprouter.com/router/netgear/r6300v2/dns.htm) to make sure you're doing that correctly. This will ensure that any device that connects to your router will be told to point to your raspberry pi as a DNS server.

**Comment by cdb8457** [comment]
OK, I will let the router pick the IP and add it as a reserved so nothing else can have use of it. Do i put the /24 in my router dns?

**Comment by PromoFaux** [comment]
When you set the DNS server on the router, you don't need the /24.

**Comment by cdb8457** [comment]
![image](https://cloud.githubusercontent.com/assets/21016001/18621301/ade8aaea-7de6-11e6-86e4-0d2e71b135ae.png)

LOL why was this so hard, This looks like it should now! I just let the router pick it for me. Then I reserved the ip for the pi! I should be ready to go!

**Comment by TylonHH** [comment]
That's what I ment in the 15th post.
So this issue can be closed?

**Comment by PromoFaux** [comment]
We got there eventually! Glad it worked out for you. I'll close for now, but if you have any further issue, we can open again.

**Comment by patoessy** [comment]
A note to add, its important to tick ipv6 on pihole upstream dns. Ads on android devices will be blocked.
