### ISSUE TITLE
Saving Stats?

### ISSUE THREAD

**Issue by capsload** [pi-hole/pi-hole#721]
Hey guys,

its nice to clear the stats daily to save VPS resources,
but isnt there a way to save those daily stats in a seperate file?
The old methode is not working anymore as i saw in the code.

But it would be nice to have the daily/monthly or even yearly stats saved in a seperate file or page.
##

**Comment by andyforceno** [comment]
I made a script to do this, at least for the daily percentage stats. This script exports the total percentage to a text file, and then transfer it to an NTFS network drive on my server (since Chip, which runs Pihole, has no cifs.utils support).

    #! /bin/bash
    
    daily_stat=$(/opt/pihole/chronometer.sh -j | sed 's/,/\n/g' | tr -d '\}|\{"' | tail -1 | awk -F: '{ print $2 }')
    daily_date=$(date +%m-%-d-%y)

    echo "$daily_date	$daily_stat" >> /home/andy/adblock_stats.txt`

It would be nice to be able to save weekly, monthly, or yearly stats, though. It would be possible with a Bash script, but it would hardly be elegant.

**Comment by PromoFaux** [comment]
This will be easier to implement once [this](https://github.com/pi-hole/pi-hole/pull/731) pull is merged. Am thinking along the lines of user-configurable `x` number of days to store raw data for, with a daily summary saved beyond that. Or something.

**Comment by jacobsalmela** [comment]
Closing as discussion has migrated to discourse.pi-hole.net: https://discourse.pi-hole.net/t/long-term-statistics-for-pi-hole/1914
