### ISSUE TITLE
[WIP] Be able to update from the Web UI

### ISSUE THREAD

**Issue by DL6ER** [pi-hole/pi-hole#945]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 9

---
I compiled a component that can be used to update using the Web UI. It works nicely until it crashes because lighttpd is restarted
https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L1132-L1133
and
https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L743

If I disable the "restart", then the update finishes successful:
![screenshot at 2016-11-22 16-58-00](https://cloud.githubusercontent.com/assets/16748619/20560202/5426cda0-b178-11e6-920d-977ed6836e6a.png)

See also my PR on pi-hole/AdminLTE for the code of the web updater.

We have to discuss how to deal with this (not restart lighttpd, restart it later, or ...) best.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
Would an `if pidof lighttpd then kill -hup` type function called as the last step of install work for your solution?

**Comment by DL6ER** [comment]
@dschaper Does `lighttpd` reload its configuration when receiving SIGHUP? I know that this is what daemons commonly do, but I'm just not sure with `lightttpd`.

I just tried `killall -HUP lighttpd` and that seems to have worked.

**Comment by dschaper** [comment]
I was trying to find that out, and from what I've read so far `HUP` should signal a reload of configuration files. Haven't dug into the lighttpd man pages yet but I think that's a good possibility.

**Comment by DL6ER** [comment]
Okay, I just tested that and the connection to the web UI stays functional!

script:
```
echo "Before killall"
echo $(killall -HUP lighttpd)
echo "After killall"
exit
```

![screenshot at 2016-11-23 12-48-37](https://cloud.githubusercontent.com/assets/16748619/20560726/28c4260a-b17b-11e6-931f-4d5f302943e0.png)

**Comment by dschaper** [comment]
:+1:

**Comment by DL6ER** [comment]
@dschaper Following [Debian policy](https://www.debian.org/doc/debian-policy/ch-opersys.html#s-writing-init) I tried `reload` instead of `restart` but that seems to cut the connection as well. Also, I just found [this](https://github.com/vonSchlotzkow/systemd-gentoo-units/blob/master/sys-apps/systemd-units/files/services-server/lighttpd.service#L11). Not sure if it is still up-to-date.

**Comment by dschaper** [comment]
Yeah, we end up getting into an initscript tangle, sysv/systemd/upstart/supervisor, each one has a differing setup. I haven't found anything definitive either way as to SIGHUP yet.

**Comment by DL6ER** [comment]
It seems possible to temporarily interrupt the connection as long as we make sure that the command we call (in my case `service`) does not exit before it can actually restart `lighttd`.
```
echo "Before killall"
echo $(nohup service lighttpd restart &)
echo "After killall"
exit
```

![screenshot at 2016-11-23 13-22-01](https://cloud.githubusercontent.com/assets/16748619/20561638/d30ac124-b17f-11e6-9a61-a9615dc0e7f7.png)

**Comment by dschaper** [comment]
What about doing an actual restart but setting an autorefresh timer of like 15 seconds on the page, so that the page reloads after lighttpd has restarted?

**Comment by DL6ER** [comment]
I don't like forcing an actual restart. I was able to come up with this:

```
echo "Before killall"
echo $(nohup bash -c "service lighttpd restart" </dev/null &>/dev/null &)
echo "After killall"
exit
```

![screenshot at 2016-11-23 13-31-19](https://cloud.githubusercontent.com/assets/16748619/20561892/1fea6a7a-b181-11e6-8d98-db452952988f.png)

```
pi@raspberry:~# sudo tail -n 2 /var/log/lighttpd/error.log
2016-11-23 13:29:27: (server.c.1558) server stopped by UID = 0 PID = 1 
2016-11-23 13:29:28: (log.c.164) server started
```
Which actually indicates that the restart was successful.

**Comment by DL6ER** [comment]
```
echo "Before killall"
echo $(nohup bash -c "sleep 12; service lighttpd restart" </dev/null &>/dev/null &)
sleep 10
echo "After killall"
exit
```
Works just fine.

```
pi@raspberry:~# sudo tail -n 2 /var/log/lighttpd/error.log
2016-11-23 13:56:44: (server.c.1558) server stopped by UID = 0 PID = 1 
2016-11-23 13:56:45: (log.c.164) server started
```

**Comment by DL6ER** [comment]
A better possibility might be to start the update process completely separated from PHP in a nohub command. We could periodically display the output, which we redirect to a text file. Then, a restart of the web server would (temporarily) disable the output, but it would work again after the server in back online.

**Comment by DL6ER** [comment]
Okay, I tried for almost an hour but I was not able to really "disown" the update from `lighttpd`, i.e. as soon as it restarts, it kills the update script. Tried `daemon`, `setsid`, `nohub` and some more but wasn't successful. I always receive:
```
::: Starting lighttpd service...Signal 15 (TERM) caught by ps (procps-ng version 3.3.9).
ps:display.c:66: please report this bug
```

**Comment by dschaper** [comment]
Do you have the lighty angel monitoring script running?

**Comment by DL6ER** [comment]
Not sure what you mean by that. I'm not such into lighttpd to be honst... Do you have a reference for me?

**Comment by dschaper** [comment]
http://blog.lighttpd.net/articles/2007/09/02/there-is-an-angel-for-lighty/

**Comment by DL6ER** [comment]
Both of the links seem to be useless, how do I have to use it?

**Comment by dschaper** [comment]
Packaging says that there should be a control at `/usr/sbin/lighttpd-angel` for that. My Raspberry fell over again, I need to crawl back to the spot its in and hard restart it...

**Comment by DL6ER** [comment]
Indeed, there is something...
```
pi@raspberry:~# /usr/sbin/lighttpd-angel -h
lighttpd/1.4.35 (ssl) (Aug  6 2016 04:23:34) - a light and fast webserver
usage:
 -f <name>  filename of the config-file
 -m <name>  module directory (default: /usr/lib/lighttpd)
 -p         print the parsed config-file in internal form, and exit
 -t         test the config-file, and exit
 -D         don't go to background (default: go to background)
 -v         show version
 -V         show compile-time features
 -h         show this help

pi@raspberry:~# /usr/sbin/lighttpd-angel
2016-11-23 19:02:18: (server.c.617) No configuration available. Try using -f option.
lighttpd-angel.c.139: child (pid=14047) exited normally with exitcode: 255

pi@raspberry:~# sudo /usr/sbin/lighttpd-angel -f /etc/lighttpd/lighttpd.conf
2016-11-23 19:04:10: (network.c.409) can't bind to port:  80 Address already in use 
lighttpd-angel.c.139: child (pid=14079) exited normally with exitcode: 255
```

Not sure if this can help.

**Comment by dschaper** [comment]
Yeah, I think the original idea was to use the angel as the /etc/init.d/ script as a middle-manager and then you'd SIGHUP the angel to have it reload the configs and handle the `lighttpd` process restarts.

**Comment by DL6ER** [comment]
Not sure how to do this. lighttpd-angel isn't running, so I cannot send the SIGHUP to it. Also, i cannot start it as the port is already blocked. I'll wait if you find out how to use it properly :wink: 

```
root@pi:~# /usr/sbin/lighttpd-angel -f /etc/lighttpd/lighttpd.conf
2016-11-23 19:07:53: (network.c.409) can't bind to port:  80 Address already in use 
lighttpd-angel.c.139: child (pid=14134) exited normally with exitcode: 255

root@pi:~# service lighttpd stop

root@pi:~# /usr/sbin/lighttpd-angel -f /etc/lighttpd/lighttpd.conf
lighttpd-angel.c.139: child (pid=14230) exited normally with exitcode: 0

root@pi:~# ps aux | grep 'light'
www-data 14237  0.0  0.6  13296  2784 ?        S    19:09   0:00 /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf
```

**Comment by dschaper** [comment]
None of the init scripts source the angel, it's kind of just there for whatever historical reason. Though it may be nice to parse the configs for the debugger... But we can't be sure of the scripts existence on other distributions.

**Comment by DL6ER** [comment]
Another idea: Could we maybe live with not restarting it but asking the user to do it himself? If he does not know how to do it, he can simply restart the Pi (we could even have an option for restarting it on the Help Center page, I guess). If restarting is not an option for him (e.g. big server), then he surely knows how to do this via ssh, etc.

**Comment by DL6ER** [comment]
We would also have to make sure that apt-get would not update lighttpd, which would imply restarting it.

**Comment by dschaper** [comment]
What do we do for the other distributions?

**Comment by DL6ER** [comment]
Not sure how the other package managers work. Would have to look into this further. Also, I can only test on Debian based systems.

https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L104

**Comment by dschaper** [comment]
We have a full suite to test with, just about every major distro/OS (via Digital Ocean or Docker)

**Comment by dschaper** [comment]
Packaging, is basically either `apt` from Ubu/Deb or rpm's from the `yum`/`dnf` based installs.

**Comment by DL6ER** [comment]
We can prevent upgrading during dependency installation as follows (`apt-get` variant):

1. lighttpd is listed as a dependency [here](https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L95)

2. Before calling ` install_dependent_packages PIHOLE_DEPS[@]` [here](https://github.com/pi-hole/pi-hole/blob/development/automated%20install/basic-install.sh#L1116), we should call:
`sudo apt-mark hold lighttpd`

`man apt-mark`
> hold is used to mark a package as hold back, which will prevent the package from being automatically installed, upgraded or removed.
If I understand this correctly, then `hold` does not prevent that we want to install it _explicitly_ later on.

3. Later on, we can reverse this, so the user will be able to upgrade it himself:
`sudo apt-mark unhold lighttpd`

`man apt-mark`
> unhold is used to cancel a previously set hold on a package to allow all actions again.

For `yum`, I found that one can put a package in “hold” by adding a line with the directive exclude to the file `/etc/yum.conf`:
`exclude=package`
So for example you could use
`exclude=php*,lighttpd`
To exclude the package lighttpd and all php packages from being updated with the command `yum update`.

**Comment by DL6ER** [comment]
With disabled upgrade of the critical packages, where we can even pass a flag such that the upgrade/restart of the processes is only suppressed if we upgrade via the web UI if you like, the webupdater should work fine.

**Comment by DL6ER** [comment]
I implemented my thoughts from above in PR #946 . Please review them carefully and, in particular, test my experimental support of `yum`/`dnf` because this is completely untested!

**Comment by dschaper** [comment]
Why do we want to pin the release? What does this get us?

**Comment by DL6ER** [comment]
@pi-hole/dashboard 
Summary of private communication with dschaper: We are not able to prevent killing of the update process when `lighttpd` restarts as the `restart` script sends a `SIGKILL` around. That is quite an extreme measure and cannot be trapped by us.

There are basically two options for the web updater now:

1. We could detect if `lighttpd` would be upgraded by `apt-get` (or `yum`/`dnf`).
If yes: abort update and notify user that webupdate is currently not available and he has to do it via the terminal.
Otherwise, we don't restart `lighttpd` and recommend after the whole update to restart the Pi (or at least lighttpd manually for experienced users). We can offer a button to restart the Pi from the web UI so we don't have to force the reboot.

2. Don't implement this now. In the next re-write we might change the web server and/or have a pihole daemon available that can do the update detached from the web server.

**Comment by dschaper** [comment]
I concur. I think 1 may be a safe option as the `lighttpd` package should be updated very rarely. http://metadata.ftp-master.debian.org/changelogs/main/l/lighttpd/lighttpd_1.4.35-4+deb8u1_changelog shows one update in 2016, with 2014 being the previous release to that.

**Comment by WilliamStam** [comment]
couldnt you use ajax? so on the web interface once the user clicks "update" it fires off an ajax request to the backend to start the updating. when the request comes back it fires off another function with a setTimeout ajax request to a "is it alive" page. while this is going on the user gets a "pi-hole is updating please hold" if the request is unsucessful then call it again wait 10sec etc as soon as its successful then reload the current page. or am i missing something here?

**Comment by DL6ER** [comment]
I wasn't clear in my previous comment: It is not possible for us to restart `lighttpd` via **anything** that is triggered via the web UI. The problem is not that the connection is lost on restart of `lighttpd`. That could be solved by an ajax approach. However, the bad thing is that the restart script of lighttpd is also killed while it will restart. We tried a lot of different approaches, but none of them was able to produce a working `restart`: once `lighttpd` is stopped, it does not start afterwards.

**Comment by DL6ER** [comment]
The current status of the web based update process is: **Testing Required!**
I think that it is working, but I don't want it to be merged without proper testing.

**Comment by gstrauss** [comment]
@DL6ER:

lighttpd developer here.  I came across this pull request and have some questions about how lighttpd can improve reloading config/restarting services  (Yes, this is an area that could use some improvement in lighttpd).  First, some comments about the above posts:

If the restart script is sending SIGKILL, then that is quite unfriendly.

If the update script run by lighttpd is still attached to lighttpd process, then maybe I can help you with backgrounding and detaching (fork, setsid, fork) and redirecting stdin, stdout, and stderr so that script is not killed by SIGHUP or SIGPIPE if it writes to closed sockets or pipes.

Regarding the references to lighttpd-angel, here is one example of running lighttpd via lighttpd-angel:
https://github.com/pld-linux/lighttpd/blob/master/lighttpd.init
https://github.com/pld-linux/lighttpd/blob/master/systemd.patch

Now, I'll poke around a little bit more into this pull request, and if lighttpd can be modified to make this easier and more robust, let's see what we can do.  It would appear that deferring the restart of lighttpd might be a good thing to do in any case.  Cheers.

**Comment by DL6ER** [comment]
Sorry for not coming back to you earlier. 

> If the restart script is sending SIGKILL, then that is quite unfriendly.

I totally agree, but I'm not sure if we can really do anything against that because we have (at least) partially to rely on what the distributions the users have installed ship.

**Comment by gstrauss** [comment]
> I wasn't clear in my previous comment: It is not possible for us to restart lighttpd via anything that is triggered via the web UI. The problem is not that the connection is lost on restart of lighttpd. That could be solved by an ajax approach. However, the bad thing is that the restart script of lighttpd is also killed while it will restart. We tried a lot of different approaches, but none of them was able to produce a working restart: once lighttpd is stopped, it does not start afterwards.

I am still trying to understand the nuances of the issues described above.  If lighttpd is actively serving a page (e.g. as update commands are processed), then sending lighttpd SIGTERM results in ending the serving of the page.  A graceful shutdown of lighttpd via SIGINT involves finishing serving all existing connections before shutting down (and then a monitoring process can start lighttpd up again).  Maybe something is sending SIGKILL after timeout out waiting to shut down lighttpd, and if lighttpd is shutting down gracefully and is waiting for the currently running CGI script to finish?  It looks like Debian lighttpd.init for 'reload' which calls `start-stop-daemon ... --retry=TERM/60/KILL/5`

The ajax solution mentioned above to poll a log file would separate out this dependency.  Then, looking at the Debian lighttpd.init, restarting lighttpd with `restart`, which is not graceful, might be better than using `reload`.

Alternatively, you could have the script defer restarting lighttpd to the end, block SIGINT and SIGTERM in the script, finish sending the request (close stdout), and then trigger restart of lighttpd.  I think blocking SIGINT and SIGTERM in the shell script is the missing piece for successfully restarting lighttpd, which should be done at the end of the script, after finishing sending the CGI response.  Another possible solution: if atd is available, an `at` job might be a good solution to schedule restarting lighttpd at the end of the script, rather than triggering the lighttpd restart from the script.

As an aside, a HUP signal to lighttpd does not actually re-read the config or restart lighttpd. Historic lighttpd behavior when receiving a HUP signal is to merely re-open log files to allow for log rotation.  (Yes, this needs improvement, but as you might imagine, any changes in this behavior in lighttpd must be done very carefully.)

**Comment by DL6ER** [comment]
> The ajax solution mentioned above to poll a log file would separate out this dependency.

This is how we currently implemented our test version. In fact, we would not even need to restart `lighttpd` if we could instruct it to reload its config file.

We identified two possible scenarios which would prevent us from doing the webbased update:

- If the `lighttpd` config changes (we cannot restart it without loosing our updater)
- If the package manager would update `lighttpd` (I guess it would always restart it).

From our experiments it seems that `SIGKILL` is immediately sent to `lighttpd` without waiting for anything to time out. The update is already finished at this time, but `lighttpd` does never come back to live after being killed as the restarter is killed along.

P.S. Unfortunately, we cannot rely on `at` being available to let it handle the restart - already tried that.

**Comment by gstrauss** [comment]
> From our experiments it seems that SIGKILL is immediately sent to lighttpd without waiting for anything to time out. The update is already finished at this time, but lighttpd does never come back to live after being killed as the restarter is killed along.

Do you have any more details?  What platform(s) is this on?  Debian-based?  Redhat-based?  other?  I'd like to help with solution(s), but we need to track down from where the SIGKILL is coming.

In any case, here is some shell incantation to detach and background the call to gracefully restart lighttpd, reloading the config without interrupting the handling of existing connections.
```
    trap "" SIGHUP SIGINT SIGTERM
    setsid sh -c "nohup /etc/init.d/lighttpd reload < /dev/null >/dev/null 2>&1 &"
```
(It takes a few more steps to detach than it might minimally need to do so, but should definitely avoid the SIGKILL unless something is using killall with the string 'lighttpd')

(nohup is in coreutils package, setsid is in util-linux package)

**Comment by DL6ER** [comment]
We mainly target Raspbian (Debian Jessie) and this is also my test platform. Let me do some further tests and come back to you later. Thanks for your help! Much appreciated.

**Comment by DL6ER** [comment]
I tried your suggestion:

> setsid sh -c "nohup /etc/init.d/lighttpd reload < /dev/null >/dev/null 2>&1 &"

but I found that afterwards `lighttpd` is not running:
```
# service lighttpd status
● lighttpd.service - Lighttpd Daemon
   Loaded: loaded (/lib/systemd/system/lighttpd.service; enabled)
   Active: inactive (dead) since Mo 2017-01-23 11:18:29 CET; 23s ago
 Main PID: 21353 (code=exited, status=0/SUCCESS)
```

I'm going to try
```
setsid sh -c "nohup service lighttpd restart < /dev/null >/dev/null 2>&1 &"
```
in our code.

**Comment by gstrauss** [comment]
If restarting lighttpd at the end of your script, close stdout and then reload lighttpd config.  (The below closes stdin and stderr, too, just for good meaure.)
```
exec 0<&-
exec 1>&-
exec 2>&-
trap "" SIGHUP SIGINT SIGTERM
setsid sh -c "nohup service lighttpd reload </dev/null >/dev/null 2>&1 &"
```

If restarting lighttpd in the middle and you do not mind terminating all existing connections to lighttpd that are in currently in progress, then use `restart` instead of `reload`

**Comment by DL6ER** [comment]
Okay, thanks. That seems to work - however I realize that `lighttpd` needs almost two minutes to come back to `active` state on my testing machine. I wonder if that was also the case before and I just didn't wait long enough.

**Comment by gstrauss** [comment]
Glad to hear it works!

Two minutes sounds like a very long time, though would be possible to be even longer if lighttpd was in the middle of streaming a large response (think a movie) to a client, and lighttpd graceful shutdown waited until that request finished being processed.  Also, startup of lighttpd can be delayed by starting up a large number of backend fastcgi processes, but that is not likely for smaller devices.

Related to quicker restarts, I already have a patch ready for the next version of lighttpd (lighttpd 1.4.46) which closes keep-alive connections more quickly during a graceful shutdown, but `jessie` is still on lighttpd 1.4.35, and the keep-alive timeout is 5 seconds (default) unless changed in lighttpd.conf, so 5 seconds is nowhere near 2 minutes.

If you `/etc/init.d/lighttpd restart` instead of `reload` at the end of the script, does it still take 2 minutes?  (This sounds like something which might be useful to track down, though should probably be a separate issue from this page.  It would be useful to test with lighttpd 1.4.45.  Nightly builds of lighttpd for Debian `jessie` i386 and amd64 arches can be found at https://debian.lighttpd.net/lighttpd1.4/pool/main/l/lighttpd/)

**Comment by DL6ER** [comment]
My testing system (Raspbian) is on `armhf` but I might try to compile `lighttpd` from source at some point. Also, I'm not sure what causes the delay here. It seems like `lighttpd` exists correctly and then nothing is happening anymore for a long time (no `lighttpd` but a `service lighttpd reload` process with 0.0% CPU usage is there).

**Comment by gstrauss** [comment]
If you install the strace package, you can get a log of syscalls with their timings.
`setsid sh -c "nohup strace -f -ttt -o /dev/shm/lighttpd.strace service lighttpd reload </dev/null >/dev/null 2>&1 &"`
Or, you could temporarily modify /etc/init.d/lighttpd to touch a temporary file in /tmp with a descriptive-name before each step of `reload` so that you have an idea which step is taking so long by looking at the timestamps when each of those temp files was created.  (Then, manually remove those temp files.)  (You can't add print-like trace since output has been redirected to /dev/null)

**Comment by DL6ER** [comment]
After rebooting the Raspberry I can no longer observe this strange behavior. Since I haven't rebooted this machine for more than two months, who knows what might have gone wrong.

**Comment by gstrauss** [comment]
Well, if it comes up again, I'd be very interested in more information if you can collect some, and if the issue is present with latest lighttpd (lighttpd 1.4.45 at the moment).

For now, it sounds like you have a working solution to be able to update from the Web UI, including restarting lighttpd.  Right?

**Comment by DL6ER** [comment]
> For now, it sounds like you have a working solution to be able to update from the Web UI, including restarting lighttpd. Right?

Yeah, Thanks you very much. That seems to have done the trick:

https://github.com/pi-hole/pi-hole/blob/new/webupdater/automated%20install/basic-install.sh#L1225

**Comment by slambert** [comment]
Would love to see this implemented. I had an thought to gift pi's with pi-hole installed to less tech savvy friends, so having a gui based update for them would be key. Looking forward...

**Comment by gstrauss** [comment]
@DL6ER can this be closed since your note above? (Jan 23, 2017)
https://github.com/pi-hole/pi-hole/blob/new/webupdater/automated%20install/basic-install.sh#L1225

BTW, since lighttpd 1.4.46, lighttpd also supports a graceful restart with SIGUSR1.  See example in https://github.com/lighttpd/lighttpd1.4/blob/master/doc/systemd/lighttpd.service

**Comment by DL6ER** [comment]
Yes. We will look at implementing this with the new web interface that is currently in the works. It will turn away from `lighttpd` and PHP.

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/some-ideas/2356/2

**Comment by pralor** [comment]
This issue has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/feature-request-web-update/32143/5
