### ISSUE TITLE
Transparent squid installation

### ISSUE THREAD

**Issue by flow23** [pi-hole/pi-hole#947]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST]:**

It would be nice to have the chance to have a transparent squid option during install as well.
It should be managable to implement a minimal squid installation. If not needed it would be nice to have a "how to" implement a transparent squid installation for pihole.

**Comment by dschaper** [comment]
This would probably be better as a Feature Request on our discourse install. Since we really don't get involved with proxy traffic and only handle DNS, this is probably going to be out of scope for us currently. If there's more votes for the feature then we'll take a look, but on the Raspberry Pi, proxying traffic usually turns out to be a poor performer.

**Comment by dschaper** [comment]
Currently out of scope for this project.
