### ISSUE TITLE
Privacy breach

### ISSUE THREAD

**Issue by johnds123** [pi-hole/pi-hole#966]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- x[] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] The issue I am reporting can be *replicated*
- [x] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [x] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---

**[BUG | ISSUE] Expected Behaviour:**

The admin panel list ALL DNS queries this my be considered a breach of user's privacy.
This intensive logging should not be available be default if at all.
**[BUG | ISSUE] Actual Behaviour:**
Same as above

**[BUG | ISSUE] Steps to reproduce:**
Browse any sites and check the admin panel for recently DNS queries (left pane on main window)
-
-
-
-

**(Optional) Debug Log generated by `pihole -d`:**

`http://termbin.com/<something>`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by dschaper** [comment]
It should only be available to the installer of the Pi-hole application locally. No data leaves the Pi-hole unless you explicitly allow it (and that only happens when you run the debug command, you are provided with the directions of what information may be passed an where it is passed on to. You are given the option to not upload the debug log as well.)

We will be releasing an update soon that has the ability to password protect the web interface, and we have instructions on the Wiki how to turn off all logging and disable any use of the admin interface. 

I am not sure how this is a security or privacy breach?

**Comment by johnds123** [comment]
Well, to the pure everything is pure. But think about what would happen if one of your close relatives fires up a private/anonymous browser window believing that the traffic would be long forgotten when the window is closed. But it is not because the beautiful pi-hole made a complete record of each and every site visited. Say if it was you girlfriend visiting dating sites this way and you browsed through the history. Don't your think she would consider her privacy breached just a little bit?

**Comment by DL6ER** [comment]
No. Absolutely no!

I just opened up an "Incognito Window" in Chrome. If sche reads the text the browser shows her carefully, it should be clear to your girlfriend that she is **not invisible in incognito mode**.

![screenshot at 2016-12-07 12-15-21](https://cloud.githubusercontent.com/assets/16748619/20965656/0a45989c-bc77-11e6-8d04-4f116cc6bf86.png)

**Comment by johnds123** [comment]
Sure enough, but it doesn't mention anything about the nosy boyfriend's Raspberry PI luring on the private net.

**Comment by DL6ER** [comment]
Well, you surely don't expect the big browser companies to mention the possibility that there might be a custom DNS server in their network. This is somehow covered by "your employer" and "your internet service provider", since you are an active part of the internet service provider by providing a custom DNS server.

That is something you who has to make that clear to your girlfriend and everybody who uses your internet connection! You are right in the sense that you cannot expect them to know that the internet in your house is working differently than everywhere else. In their companies they may expect that there is something going on in the network which isn't transparent to the users. YOU have to make clear that something similar is going on in your network.

**Comment by johnds123** [comment]
Yes, I agree and I understand you feel strongly about your solution. But provided I install it and make my users use it,  it still puts me in an awkward position that I would rather not be in. During my professional life I have never felt it more intimidating than when I occasionally had to debug other people's e-mail problems. 
I think your idea is great and installing it was like a dream. Still I also believe it needs some refinements like making a less experienced sys admin know what paths he entering if he installs the software.
Let's close the discussion for now.

**Comment by DL6ER** [comment]
Please rest assured that we take your concerns seriously!

In the next release you will be able to disable logging very conveniently:
```bash
pi@raspberry:~ $ sudo pihole -l off
::: Flushing /var/log/pihole.log ...... done!
::: Logging has been disabled!
```

Since, however, most of the users don't consider the logs as privacy issue, we leave logging enabled by default.

**Comment by PromoFaux** [comment]
Just to add to this, the next admin interface release will have password protection available, too!

**Comment by paulkramme** [comment]
That are amazing news! Thanks! Even one of these alone is great!

**Comment by johnds123** [comment]
And please consider Letsencrypt for the connection.

**Comment by dschaper** [comment]
Let's Encrypt is currently out of scope for what we are doing, we are not currently getting into the SSL/TLS issue, that's a major undertaking to automate that process, and the users are better off installing that themselves. (LE requests the users email address and also requires the user to agree to their terms of conditions upon requesting a certificate, and that's not something we currently feel like we should be doing on behalf of the users. Self-signed certs are a possibility for a future option, but until we can find a way to pass the license agreement on to the users then LE would be beyond what we are capable of.)

**Comment by Mcat12** [comment]
Also, I don't think using LE would be that simple, since [they don't give certs to local domains](https://community.letsencrypt.org/t/certificates-for-hosts-on-private-networks/174).

**Comment by paulkramme** [comment]
IMHO it's simply beyond the projects scope. If we apply linux programming thinking to it, it's "better do one thing good than many things bad".

**Comment by DL6ER** [comment]
One last word to the general topic of SSL on your local network (i.e. Pi-Hole web UI nocht visible from the web): Whether you need encryption or not strongly depends on your local threat. If you have bad guys on your network, then you will need encryption. As has been mentioned by @Mcat12 LE is not an option here.

Self-signed certificates are also not an option because people will add exception rules in their browser for these certificates to remove the annoying warnings. But this demolishes the entire point of having certificates in the first place, specifically, hat not anybody can just make up a certificate and then have other computers believe that they're the right server. If you have the exception everyone else in the network can pretend that they are the *real* `pi.hole`, capture your traffic and fiddle with it. Everything about SSL/TLS really requires having trustworthy authorities which sign unique certificates.

Coming back to my initial point: If you are certain that you don't have bad guys in your network, then sending everything in the clear is just fine on your network. Of course, this also includes having a strong WiFi encryption with a strong password.

**Comment by DL6ER** [comment]
You will also be able to disable logging from the new `Settings` page.
![screenshot at 2016-12-15 15-31-24](https://cloud.githubusercontent.com/assets/16748619/21229272/5a5c8988-c2e1-11e6-981f-255cec61d03a.png)
