### ISSUE TITLE
Pihole started behaving strangely and activating/deactivating takes long (Admin panel won't open)

### ISSUE THREAD

**Issue by MaKin211** [pi-hole/pi-hole#971]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [X] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [X] 2

---
**[QUESTION]:**

I really love pihole and I'm using it for some weeks now without any trouble but today it started to behave strangely. It blocked some ads whilst others were not blocked so I decided to open the admin panel but it would not open. Using '''pihole disable''' would not disable it instantly but would take some minutes to really 'allow' ads again. I updated - didn't help. I uninstalled and reinstalled and the admin panel showed up again. Now I wanted to use Spotify which is blocked - sure, the whitelist entries were missing after the new installation. And now my admin panel won't open again...
In order to use Spotify I had to manually disable it with '''pihole disable''' but it took some minutes until I could use Spotify again. :(
Any idea what might have caused and still cause the issue?
After reinstalling pihole today I installed homebridge. And after the initial install of pihole some weeks ago the only thing I installed was a new version of Bluez and Pulseaudio. None of these changes anything with the network components or does it?
I'm really desperate as I'd like to avoid clean installing my Pi again as my home automations finally do as I want them to...
I'd really appreciate your help.

**[BUG | ISSUE] Expected Behaviour:**
Admin panel is reachable and enabling or disabling pihole works immediately without minute delays.

**[BUG | ISSUE] Actual Behaviour:**
Admin panel is not reachable and when enabling/disabling pihole it takes minutes for it to work.

**[BUG | ISSUE] Steps to reproduce:**

- open pihole admin panel (local ip)
- pihole enable/disable

**(Optional) Debug Log generated by `pihole -d`:**

token: tz3ebh780r

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by DL6ER** [comment]
Can you tell us what `uptime` says on your Pi?
An extraordinary high load could cause both the delays and the dysfunction of the web UI

If the values behind `load average` are large (larger than 1 on a RPi v 1 or larger than 4 on a modern Raspberry Pi v2 or v3) then you should check which processes are causing the high load using e.g. `top`.

You can also add pages to the whitelist via the `pihole` command (no need to use the we UI) using
`pihole -w domain1 [domain2 ...]`

**Comment by MaKin211** [comment]
Thanks for your response.

`13:01:30 up 21:24,  1 user,  load average: 1.00, 0.76, 0.78`

Same behaviour after rebooting. I thinks it has something to do with packages (dnsmasq?) that are change or overwritten when installing homebridge or something like that?

**Comment by DL6ER** [comment]
So the load doesn't seem to be your issue. I'm unfamiliar with `homebridge` but it doesn't seem to mess around with `dnsmasq`. Let's wait what the other say.

**Comment by Mcat12** [comment]
Make a debug log with `pihole -d`. When enabling/disabling the Pi-hole, clients will often not seem to have changed for a few minutes because of how Pi-hole and DNS works. Since Pi-hole acts as a DNS server, your clients send DNS requests to it. Once the clients get their answer, they cache it for a certain amount of time. This means that if a client has recently sent a DNS request for a blocked domain and got a blocked answer and then Pi-hole is disabled, the client will still use that blocked answer for as long as it decides it is still valid. Once the cache has expired or been flushed, it will ask Pi-hole again for the domain and will receive the correct answer. To quicker see the changes of enabling/disabling Pi-hole, it's recommended to flush the DNS cache on the client or restart it.

**Comment by MaKin211** [comment]
I did and posted the token.

Also used private mode. :/

**Comment by Mcat12** [comment]
It looks like lighttpd isn't working because it can't open the error log at `/var/log/lighttpd/error.log`. What permissions are on the file, if it exists?

**Comment by trinapicot** [comment]
If you uninstall pihole without uninstalling dependencies, the lighttpd configuration can get messed up for later pihole installs (see pull request #970). I suggest you uninstall pihole and choose to remove dependencies (lighttpd php-cgi and php-common). Then another fresh pihole install should result in a fresh lighttpd configuration and working admin page. And hope it doesn't affect your homebridge installation because I know nothing about that.

**Comment by MaKin211** [comment]
I just did that and the admin panel works again. I just hope that it was caused by some conflicts with another application and both will work in peace now. :)

Not sure whether to close this issue but I suppose that it really was not pihole related but caused by third party.

**Comment by Mcat12** [comment]
It was probably a Pi-hole-caused lighttpd issue. I'll close it since your issue is fixed.
