### ISSUE TITLE
Top Advert/Top Domain no longer load

### ISSUE THREAD

**Issue by Solaris17** [pi-hole/pi-hole#995]
**In raising this issue, I confirm the following (please check boxes, eg [X]) Failure to fill the template will close your issue:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] The issue I am reporting can be *replicated*
- [] The issue I'm reporting isn't a duplicate (see [FAQs](https://github.com/pi-hole/pi-hole/wiki/FAQs), [closed issues](https://github.com/pi-hole/pi-hole/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20), and [open issues](https://github.com/pi-hole/pi-hole/issues)).

**How familiar are you with the codebase?:**

- [] 1 (very unfamiliar)
- [] 2
- [] 3
- [] 4
- [X] 5
- [] 6
- [] 7
- [] 8
- [] 9
- [] 10 (very familiar)

---
**[FEATURE REQUEST | QUESTION | OTHER]:**

_{replace this section with your content or delete if not a FEATURE REQUEST/QUESTION/OTHER}_

**[BUG | ISSUE] Expected Behaviour:**

Expected entire GUI to load.

**[BUG | ISSUE] Actual Behaviour:**

After the first several days Top Advertizers and Top Domain info graphs stopped loading. Reboots did not fix the issue. Thinking it was a failed or slow memory card due to the amount of queries being processed I let it sit for several hours, However the charts still have the reticulating arrows with no data.

**[BUG | ISSUE] Steps to reproduce:**

- simply allow the PI to run for multiple days
- 12+ clients
- 10k+ DNS queries
- 1200+ blocked adverts

**(Optional) Debug Log generated by `pihole -d`:**

`6m1op8lnsl`

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

**Comment by Mcat12** [comment]
The problem is that your query log is too big for your Pi-hole to generate stats with before it times out (30 seconds). This is less of a problem on something more powerful than a Pi. We are working on improving performance and moving to a [database solution](https://github.com/pi-hole/AdminLTE/pull/149).

See issue #365

**Comment by Solaris17** [comment]
Awesome thank you! I wasn't sure if I should have used my PI 3 or PI 1. I use my Pi 3 for other projects. Would you happen to know if this is more a storage or CPU limitation?

**Comment by Tntdruid** [comment]
Works great, crazy fast on my poor pi now, at 40k+ DNS queries and still load fast 👍

**Comment by DL6ER** [comment]
> Would you happen to know if this is more a storage or CPU limitation? Maybe its a RAM limit?

It is definitely not a RAM issue. It is something that is a shared problem involving both the speed limitation of the SD card (we have to read the log file line by line) and the CPU power. The error comes about because the Pi kills the working PHP process after some fixed time-out since it things it has crashed (which is not the case).

**Comment by Solaris17** [comment]
Thanks for the advice. I went and bought some samsung evo select 32GB microSDs and threw one in. They replace some really old Adata cards from god knows when. Hopefully it can handle it now with the improved read speeds. Thanks so much!
